### ISSUE TITLE
Add Item in Visual Studio 2015 loses templates for .NET Core class library projects

### ISSUE THREAD

**Issue by petmat** [Azure/Azure-Functions#123] opened 2017-01-03 18:05 UTC
After I installed the Visual Studio Tools for Azure Functions from this address: https://aka.ms/azfunctiontools I noticed that in a .NET Core class library project when I added a new item (or new class) only templates visible were powershell and webpack config templates. The reason those were visible is probably because they came from extensions. Only .NET Core class libraries were missing the templates. I could add classes and other items in for example ASP.NET Core projects.

![image](https://cloud.githubusercontent.com/assets/3600035/21617621/8d3d1544-d1ef-11e6-9623-6794d466e72b.png)

So it seems installing the tools makes it difficult to add new classes and other items in a .NET Core class library project. I have Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3.

I tried several different .NET Core class library projects and they all had the same issue. I even tried to reset the VS templates, but it did not fix the problem. After uninstalling the Azure Functions tools all the item templates are visible again.

**Comment by maxpower720** [comment] 2017-01-07 03:42
I'm seeing the same issue on my machine. Thankfully, I found this issue as I just reinstalled and was unsure what the root cause was. I'm unaware of a workaround though I checked out the ASP.NET Core projects and those still have their templates in tact. Console and class libraries no longer have any templates (except for PowerShell)

**Comment by zigzag95** [comment] 2017-01-28 13:20
Same here,
I tried uninstalling Microsoft Azure App Service Tools 2.9.6 but the templates ars still missing.

**Comment by lindydonna** [comment] 2017-02-01 23:53
Try running `devenv /setup` from an **administrator** developer command prompt

**Comment by CharlesToniolo** [comment] 2017-02-13 12:59
Hi,

@lindydonna the command didn't solve the issue.

**Comment by lindydonna** [comment] 2017-02-13 20:32
@CharlesToniolo Thanks for providing the workaround!

**Comment by TomGroeneboer** [comment] 2017-02-14 08:27
Uhm @CharlesToniolo @lindydonna this breaks all the existing Azure tooling (publish, cloud explorer etc.). 

I have found the following files that needs to be removed; This is in the "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools Azure" folder.

- AzureFunctionsImages.imagemanifest
- Microsoft.VisualStudio.Web.WindowsAzure.AzureFunctions.dll
- Microsoft.VisualStudio.Web.WindowsAzure.AzureFunctions.pkgdef

The "Windows Azure Tools" does not need any change in my case.

**Comment by CharlesToniolo** [comment] 2017-02-14 17:53
@TomGroeneboer Great! I had to remove everything because I was in a hurry.

**Comment by lindydonna** [comment] 2017-02-14 19:02
@TomGroeneboer excellent point, thanks for providing your workaround.

**Comment by TomGroeneboer** [comment] 2017-02-14 19:06
@lindydonna I did run the uninstall for the Azure Functions and that didn't remove the files. So I would classify this as a bug in the uninstaller...

**Comment by lindydonna** [comment] 2017-02-14 19:14
@TomGroeneboer Agreed, I created https://github.com/Azure/Azure-Functions/issues/181, which will also document your workaround.

**Comment by jeanpaulsmit** [comment] 2017-02-16 13:10
I suppose it is a bug in the installer too?
As only the Powershell templates are left after installing the Azure Functions tools?

**Comment by martinstenhoff** [comment] 2017-04-20 06:36
Will there be a fix for this at some point? Not having access to the Item Templates for .Net core class libraries is really annoying.

**Comment by lindydonna** [comment] 2017-05-09 01:05
This particular version of the Functions tooling will not be maintained, and the new version will be based on class libraries. We'll also use a VSIX to install, which won't have this effect on other project types.

See [Azure Functions Tools Roadmap](https://blogs.msdn.microsoft.com/webdev/2017/04/14/azure-functions-tools-roadmap/) blog post

**Closed by lindydonna** 2017-05-09 01:05 UTC
Labels: bug, triaged, Visual Studio
