### ISSUE TITLE
Visual Studio Package Restore Doesn't Work

### ISSUE THREAD

**Issue by brianharwell** [Azure/Azure-Functions#185] opened 2017-02-20 02:02 UTC
I am trying to reference a nuget package and the restore in Visual Studio 2015 does not work. If I debug the function locally the packages are restored within the runtime environment but that doesn't help me at design time.

Here is my project.json...

`{
  "frameworks": {
    "net46":{
        "dependencies": {
            "WindowsAzure.Storage": "8.1.0"
        }
    }
  }
}
`

**Comment by lindydonna** [comment] 2017-02-23 20:03
This is by design, unfortunately. C# IntelliSense for scripting is limited at the moment. We are working on a feature that supports precompiled assemblies, which will solve this problem. I'm closing this issue as it's a duplicate of this feature request which is already in progress: https://feedback.azure.com/forums/355860-azure-functions/suggestions/17709979-visual-studio-tooling-for-precompiled-functions

**Closed by lindydonna** 2017-02-23 20:03 UTC
