### ISSUE TITLE
func.exe host start failing with "No job functions found. Try making your job classes and methods public."

### ISSUE THREAD

**Issue by Vaishnavims** [Azure/Azure-Functions#404] opened 2017-07-19 21:12 UTC
I used the Visual studio 2017 preview tooling support to create a function App which  is having one "TimerTrigger" function.

```
public static class Function1
    {
        [FunctionName("TimerTriggerCSharp")]
        public static void Run([TimerTrigger("0 */1 * * * *")]TimerInfo myTimer, TraceWriter log)
        {
            log.Info($"C# Timer trigger function executed at: {DateTime.Now}");
        }
    }
```
The function runs fine when starting the function app using Visual studio in debug as well as non debug mode.

But when I am trying to start the same function app using the Azure function Cli it fails with the following error:
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

Steps:
- I have build the solution using Visual studio and have downloaded the Azure functions CLI tools.
- Tried to run the Function app using the cli tool from the function app root directory

C:\Users\<name>\AppData\Local\Azure.Functions.Cli\1.0.0-beta.100\func.exe host start

The functionApp hosts starts but throws the error:

[7/19/2017 8:38:54 PM] Loaded custom extension: BotFrameworkConfiguration from ''
[7/19/2017 8:38:54 PM] Loaded custom extension: SendGridConfiguration from ''
[7/19/2017 8:38:54 PM] Host lock lease acquired by instance ID '000000000000000000000000FE82D73B'.
[7/19/2017 8:38:54 PM] Generating 0 job function(s)
[7/19/2017 8:38:54 PM] Starting Host (HostId=minint4tec5hd-1122794491, Version=1.0.11015.0, ProcessId=18672, Debug=False, Attempt=0)
[7/19/2017 8:38:54 PM] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

**Comment by lindydonna** [comment] 2017-07-24 21:52
You need to run it from the output folder, which is how the VS tooling launches the CLI. Make sure you're in the `bin\Debug\net461` directory.

**Comment by ewilsonambient** [comment] 2017-07-25 15:16
Likewise, I am having the opposite issue where I cannot debug my function app locally, but it does run on Azure.  I get the same error above in the console windows of the Azure function when running locally.  I have read that I need to call config.UserServiceBus() in the Main of my app, but function apps do not have a Main.  Everywhere I look, the code provided shows how to register but does not show where that is being done in a function app running locally.  Any pointers in the right direction would be greatly appreciated.

**Comment by AldoSaucedo** [comment] 2017-10-05 05:46
Hi @lindydonna,
I have the same problem @Vaishnavims has so I tried your solution but cannot see any func.exe in bin\Debug\net461 folder.

I'm using Visual Studio Community 2017
Steps to repro:
1. Create a new Azure Function project
2. Add a new Azure Function with
3. Click on Run button

And this is what I get:
[10/5/2017 5:42:07 AM] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

Any idea on what could be happening?

Thanks!

**Comment by PoisonousJohn** [comment] 2017-12-12 16:26
@AldoSaucedo if I got it right, you need to install Azure Functions Core Tools 2.0, so you will have func.exe in you PATH

**Comment by PoisonousJohn** [comment] 2017-12-12 16:33
@lindydonna, is it possible to build & run locally a precompiled project without VS tooling?

**Comment by androidand** [comment] 2018-05-31 11:02
For anyone trying this on a Mac (Azure Functions Core Tools 2.0), from your project folder, navigate to
/bin/Debug/netstandard2.0
func host start

Now the functions should be found. The tool should be able to find functions from anywhere within the project folder, at least from root.

**Comment by utrescu** [comment] 2018-07-23 09:47
Same workaround in Linux.

    cd ./bin/Debug/netstandard2.0
    TERM=xterm func host start

> Note: I need to put TERM because there are some problems with terminfo in Fedora (The terminfo database is invalid)

**Comment by whitehair30** [comment] 2019-02-06 09:59
I had a similar problem, and it was fixed when I ran visual studio in administrator mode

**Comment by AAATechGuy** [comment] 2019-06-15 00:01
If you debug/run from Visual Studio, somehow, even with latest Microsoft.NET.Sdk.Functions (v1.0.28), its not able to detect AzureFunctions in the project. I root caused the issue to Project properties > Debug > Working Directory is not set. Set it to the actual directory where binaries are found and your AzureFunctions becomes available for debug. 

![image](https://user-images.githubusercontent.com/3484074/59544356-f0226c00-8ec5-11e9-9fc3-eeeab5e9b5bf.png)

**Comment by fabiocav** [comment] 2019-07-15 22:38
Closing this issue as it has been reused a few times over the years. If you have a similar problem, please open a new issue for investigation.

**Closed by fabiocav** 2019-07-15 22:38 UTC
Labels: question
