### ISSUE TITLE
[UX] - Integration Blade not displaying correctly for a blob trigger 

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/Azure-Functions#1581] opened 2020-05-08 22:33 UTC
# Issue Title
Integration Blade not displaying correctly for a blob trigger 

## Description
A new blob triggered function in the integration tab without the direction specified is showing the blob binding as an output.

- Please provide a concise description of the issue
1. Create a function with a blob trigger 
2. Deploy the function app
3. Navigate to the Integration view 

The local tools seem to not set the direction property in the host.json so I'm not sure if this should be labeled a UX or VS tooling issue?

- Include Screenshots if possible
![image](https://user-images.githubusercontent.com/18233035/81454425-3d50a180-915a-11ea-9717-d0063dfa7eae.png)

![image](https://user-images.githubusercontent.com/18233035/81454020-1a71bd80-9159-11ea-9d2f-c8cc0bf9b0ed.png)

Function.json
```json
{
 "generatedBy": "Microsoft.NET.Sdk.Functions-3.0.7",
 "configurationSource": "attributes",
 "bindings": [
 {
 "type": "blobTrigger",
 "path": "imports/{name}",
 "name": "myBlob"
 }
 ],
 "disabled": false,
 "scriptFile": "../bin/xxxI.dll",
 "entryPoint": "xxxx.Function1.Run"
}

**Comment by btardif** [comment] 2020-05-09 21:27
this is a duplicate of #1528 so closing it. We are discussion option in the other bug.

**Closed by btardif** 2020-05-09 21:27 UTC
Labels: UX_Preview
