### ISSUE TITLE
[Visual Studio] Cannot publish multiple functions with the same name

### ISSUE THREAD

**Issue by BillRaymond** [Azure/Azure-Functions#280] opened 2017-05-12 00:14 UTC
I create a new Functions app with two functions and cannot publish them but receive errors and cannot publish. There are no resources whatsoever on Azure (no resource groups, storage accounts, etc.).

Repo steps: 

1. Create a new VS Azure Functions App (FunctionApp1).
2. Add two new Functions (Function1.cs, Function2.cs).
3. Publish the project.
4. Publish tool creates the same unique id for both functions.
5. Click "Create" (side note: maybe label the button "Publish"?)

The first dialog appears with the title "An error has occurred", with the following details:
System.Net.Http.HttpRequestException: {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/FunctionApp20170511045858Plan' at line '1' and column '3719' is defined multiple times in a template. Please see https://aka.ms/arm-template/#resources for usage details.'."}}
   at Microsoft.VisualStudio.Web.WindowsAzure.Provisioning.DeploymentManager.<ThrowOnUnexpectedStatusCode>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.HttpResponseExtensions.<DeserializeEntityJsonAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.ARMRootExtensions.<DeserializeEntityAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.EntityExtensions.<PutAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.WindowsAzure.Provisioning.DeploymentManager.<BeginDeployment>d__14.MoveNext()
<img width="388" alt="screen shot 2017-05-11 at 5 11 33 pm" src="https://cloud.githubusercontent.com/assets/15895828/25976970/f6e3c042-366c-11e7-831c-fac2348df9f4.png">

Click the _Close_ button and the second dialog appears with the title _An error has occurred_ with the following details (which are actually no details):
Template deployment failed. Deployment operation statuses:
<img width="384" alt="screen shot 2017-05-11 at 5 13 08 pm" src="https://cloud.githubusercontent.com/assets/15895828/25976990/203ee034-366d-11e7-9595-4b5d7f2987e7.png">

**Comment by lindydonna** [comment] 2017-05-18 00:06
I can't reproduce this. Based on your error, it sounds like the problem was when you tried to create a new Function App. Do you happen to know what parameters you used?  Are you able to reproduce the issue?

**Comment by BillRaymond** [comment] 2017-05-18 00:19
Hi @lindydonna Yes, I can reproduce it but it is intermittent. I can tell you that it happens when publishing the application for the very first time. In my case, I just created a project and added two functions without changing much more than the sample code's JSON response message from something like "Hello " + name to "Hey there " + name.

**Comment by lindydonna** [comment] 2017-06-08 20:40
Closing for now. Please open a new issue if you can repro.

**Closed by lindydonna** 2017-06-08 20:40 UTC
Labels: bug, Visual Studio
