### ISSUE TITLE
Not able to debug Azure Fuctions in Visual Studio

### ISSUE THREAD

**Issue by iamsunny** [Azure/Azure-Functions#110] opened 2016-12-17 05:33 UTC
----------------------------------------------------------------

VS Version: Visual Studio Enterprise 2015
			14.0.25431.01 Update 3

OS Version: Windows 8.1 Enterprise / 6.3.9600 Build 9600

----------------------------------------------------------------

Steps to Reproduce the issue:
---------------------------------
Download Microsoft Azure App Service Tools for Visual Studio from the link below:
https://aka.ms/azfunctiontools

Install Microsoft Azure App Service Tools for Visual Studio 
(Quit Visual Studio if running already. Or, it will ask you to quit.)

Start Visual Studio

New Project --> Cloud --> Azure Functions (preview)

Give a name to the  project --> Create

New Project is created with no function

Right click on Project in Solution Explorer
	-> Select "New Azure Function"
	-> Select your flavor of language and template.
	-> give it a name and hit Create

Function template is added.

Now hit F5 or Click "Start Debugging" under debug menu.

Popup comes - The Azure Function CLI tools are required to run this project. Would you like to download and install them now?

Another popup comes - 
The debug profile "{ProjectName}" is missing the path to the executable to debug.

and the debug stops.

**Comment by lindydonna** [comment] 2016-12-19 21:40
Did you successfully install the Azure Functions CLI tools?  You can check by going to the folder %USERPROFILE%\AppData\Local\Azure.Functions.Cli

If not, restart VS and do F5 again. You should get a prompt to install the tools.

**Comment by iamsunny** [comment] 2016-12-20 16:01
I tried it several times. The prompt comes up every time I restart VS. It runs for a minute long and then the error message shows up.
I also tried reinstalling Azure-Function-CLI multiple times. With and Without Admin privilege both. It is  working properly on command prompt.

**Comment by BaskarGovindaswamy** [comment] 2016-12-26 13:10
Hi,
i also face the same issue, Could you please give me the solution, Even i tried this through node.js command prompt --->  "npm i -g azure-functions-cli". But still didnt work for me,

**Comment by iamsunny** [comment] 2016-12-29 09:05
@lindydonna hi Donna. Any update on this bug?

**Comment by BaskarGovindaswamy** [comment] 2016-12-29 09:30
Hi Team,
it works now, it was network issue - In my organization internally they are blocking. when i reached home and tried with my Airtel dongle network connection and it was installed and i am able to debug the azure function.

But, the error message is not  a valid one. Please provide a valid message.

Thanks
Baskar.G

**Comment by svdoever** [comment] 2017-01-10 14:57
I'm having the same issue, on two different machines.

**Comment by lindydonna** [comment] 2017-01-10 23:55
@svdoever It sounds like the download of the CLI tools didn't complete. Do you see them installed in `%USERPROFILE%\AppData\Local\Azure.Functions.Cli`?

**Comment by lindydonna** [comment] 2017-01-12 00:13
@iamsunny It sounds like the tools didn't download. Do you see anything in %USERPROFILE%\AppData\Local\Azure.Functions.Cli?

**Comment by lindydonna** [comment] 2017-01-12 02:08
If you have problems downloading the tools through Visual Studio, you can unzip manually, just put it in the folder `%USERPROFILE%\AppData\Local\Azure.Functions.Cli\1.0.0-beta.9`.

You can download the beta 9 CLI drop from here: https://functionsbay.blob.core.windows.net/public/1.0.0.beta.9/Azure.Functions.Cli.zip

**Comment by iamsunny** [comment] 2017-01-13 11:02
@lindydonna thanks for replying. I tried extracting latest beta in mentioned folder and it worked this time.
Thumbs Up!

**Comment by iamsunny** [comment] 2017-01-13 11:03
@svdoever & @BaskarGovindaswamy : Please try the latest beta if still not resolved.

**Comment by waqar-haider-confiz** [comment] 2017-01-18 12:08
I am facing the same issue and have tried above solution. 
In my case, I can't see folder 'Azure.Functions.Cli' under '%USERPROFILE%\AppData\Local\' path.
I downloaded the zip and put at the path. But problem still persists. 

I have [Azure 2.9.6 .NET SDK](https://go.microsoft.com/fwlink/?LinkId=518003&clcid=0x409)  and [Visual Studio Tools for Azure Functions](https://aka.ms/azfunctiontools) installed at local.

**Comment by iamsunny** [comment] 2017-01-18 13:32
@waqar-haider-confiz did you try the latest beta:
https://functionsbay.blob.core.windows.net/public/1.0.0.beta.9/Azure.Functions.Cli.zip

You can try creating a folder there in case you don't find it.

**Comment by waqar-haider-confiz** [comment] 2017-01-18 14:08
I have tried it but not working for me.

**Comment by lindydonna** [comment] 2017-01-18 18:27
@waqar-haider-confiz Can you be more specific about your scenario and the workaround you tried?

**Comment by waqar-haider-confiz** [comment] 2017-01-19 06:16
Hey @lindydonna, 
 
I am using Windows 10. 
I want to start development of Azure Functions at local on my Visual Studio Enterprise 2015. For setup/installation, I followed this [link ](https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/). 
As mentioned in above tutorial link, I have **Azure 2.9.6 .NET SDK** and **Visual Studio Tools for Azure Functions** installed at local.

After installation of above components, I was able to create a project for Azure Functions in Visual Studio. I added new azure function in the project and executed it by pressing F5. 

Then,
{
_Popup comes -_ 
The Azure Function CLI tools are required to run this project. Would you like to download and install them now?

_Pressed 'Yes' button_

_Another popup comes -_
The debug profile "{ProjectName}" is missing the path to the executable to debug.

_and the debug stops._
}

I looked for folder 'Azure.Functions.Cli' at the path '%USERPROFILE%\AppData\Local' , but it was not there. 
As mentioned in your comment, to download Azure.Functions.Cli from that blob link. I downloaded and put the extracted folder named 'Azure.Functions.Cli' at the path '%USERPROFILE%\AppData\Local'. After that, I restarted the Visual Studio and hit the F5. 

Now, 
{
_Popup comes -_ 
The newer version (1.0.0-beta.9) of the Azure Functions CLI tools is available. Would you like to download and install them now?
 
_If I hit "No", Debugging stops._
_If I hit "Yes",_

_Another popup comes -_
Downloading version 1.0.0-beta.9 of the Azure Functions CLI tools. This may take a few minutes...

_After few minutes,_  

_Another popup comes -_
The debug profile "{ProjectName}" is missing the path to the executable to debug.

_and the debug stops._
}

**Comment by svdoever** [comment] 2017-01-19 06:45
I did exactly the same steps, on two machines, exact same behaviour... why is the manually installed click not picked up?



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Waqar Haider <notifications@github.com>
Datum: 19-01-17 07:16 (GMT+01:00)
Aan: Azure/Azure-Functions <Azure-Functions@noreply.github.com>
Cc: Serge van den Oever <Serge.van.den.Oever@macaw.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [Azure/Azure-Functions] Not able to debug Azure Fuctions in Visual Studio (#110)


Hey @lindydonna<https://github.com/lindydonna>,

I am using Windows 10.
I want to start development of Azure Functions at local on my Visual Studio Enterprise 2015. For setup/installation, I followed this link <https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/> .
As mentioned in above tutorial link, I have Azure 2.9.6 .NET SDK and Visual Studio Tools for Azure Functions installed at local.

After installation of above components, I was able to create a project for Azure Functions in Visual Studio. I added new azure function in the project and executed it by pressing F5.

Then,
{
Popup comes -
The Azure Function CLI tools are required to run this project. Would you like to download and install them now?

Pressed 'Yes' button

Another popup comes -
The debug profile "{ProjectName}" is missing the path to the executable to debug.

and the debug stops.
}

I looked for folder 'Azure.Functions.Cli' at the path '%USERPROFILE%\AppData\Local' , but it was not there.
As mentioned in your comment, to download Azure.Functions.Cli from that blob link. I downloaded and put the extracted folder named 'Azure.Functions.Cli' at the path '%USERPROFILE%\AppData\Local'. After that, I restarted the Visual Studio and hit the F5.

Now,
{
Popup comes -
The newer version (1.0.0-beta.9) of the Azure Functions CLI tools is available. Would you like to download and install them now?

If I hit "No", Debugging stops.
If I hit "Yes",

Another popup comes -
Downloading version 1.0.0-beta.9 of the Azure Functions CLI tools. This may take a few minutes...

After few minutes,

Another popup comes -
The debug profile "{ProjectName}" is missing the path to the executable to debug.

and the debug stops.
}

-

**Comment by lindydonna** [comment] 2017-01-19 18:22
Reopening the issue. 

@svdoever and @waqar-haider-confiz: can you provide the exact directory structure in your %USERPROFILE% folder?  I wonder if the problem is that you're off-by-one the layout.

**Comment by waqar-haider-confiz** [comment] 2017-01-23 04:39
Yeah sure, when I navigate to %USERPROFILE%, I see following files/directories.
-  AppData
- Contacts
- Desktop 
- Documents
- Downloads
- Favorites
- Links
- Music
- cont.

Inside AppData directory, following files/directories are there
- Local
- LocalLow
- Roaming

**Comment by lindydonna** [comment] 2017-01-23 19:44
@waqar-haider-confiz I should have been more specific. This is where my func.exe lives: `C:\Users\donnam\AppData\Local\Azure.Functions.Cli\1.0.0-beta.9\Func.exe`. Does your folder structure match that?

**Comment by waqar-haider-confiz** [comment] 2017-01-25 05:35
@lindydonna ,
The directory '1.0.0-beta.9' does not exist under '\AppData\Local\Azure.Functions.Cli\' path. 

I downloaded from the link you shared, it also does not contain the directory "1.0.0-beta.9". Pasting down the link from where I downloaded and put under my "Local" folder "https://functionsbay.blob.core.windows.net/public/1.0.0.beta.9/Azure.Functions.Cli.zip"

**Comment by lindydonna** [comment] 2017-01-27 23:27
@waqar-haider-confiz Yes, you need to manually create the folder `1.0.0-beta.9` and **unzip** the contents of Azure.Functions.Cli.zip as I mentioned in my earlier comment: https://github.com/Azure/Azure-Functions/issues/110#issuecomment-272055787

**Comment by DamianFlynn** [comment] 2017-02-14 16:22
I have also the same issues as reported in this thread - in AppData there is no folder for Azure.Functions.Cli, despite multiple times VS attempting to download and install. My guess is a timeout, as downloading the 26Mb package takes about 10 minutes on my internet connection. (No Joking - 6Mb pipe)

I have used NPM to get the current verision of the CLI, which has a lot of important fixes - 
**Azure Functions Cli (1.0.0-beta.91)
Function Runtime Version: 1.0.10726.0**

The zip linked above is for the older, build of *1.0.0-beta.9; *
I figured out that a tiny tweak would yield beta91
'https://functionsbay.blob.core.windows.net/public/1.0.0.beta.91/Azure.Functions.Cli.zip'

Once placed debugging is working.

**Comment by lindydonna** [comment] 2017-02-14 19:17
@DamianFlynn I wonder if we need to mirror the package on a CDN--right now it's in blob storage in West US. If you don't mind sharing, where are you located geographically?

**Comment by gabomgp** [comment] 2017-02-14 22:41
@lindydonna I'm in the same problem. When i'm trying to debug my Azure Funtion, a dialog with the message "Downloading version 1.0.0-beta.91 of the Azure CLI tools." and don't install anything. The numer 91 in version "1.0.0-beta.91" is extrange, is it ok?

**Comment by lindydonna** [comment] 2017-02-14 22:47
@gabomgp That is correct, we went from .9 to .91 because Visual Studio uses SemVer 1.0, which does a string comparison of everything after "beta". You can download the file from here: https://functionsbay.blob.core.windows.net/public/1.0.0.beta.91/Azure.Functions.Cli.zip

**Comment by lindydonna** [comment] 2017-02-14 23:08
@gabomgp @DamianFlynn @waqar-haider-confiz @svdoever: we've just switched over the URL that Visual Studio downloads from to use a download that is hosted on an Azure CDN. This will automatically geo-replicate, so folks should see much improved download performance.

**Comment by lindydonna** [comment] 2017-05-01 18:10
Closing this issue, as it appears to be network problem downloading the CLI.

**Closed by lindydonna** 2017-05-01 18:10 UTC
Labels: bug, Visual Studio

**Comment by priteshtechark** [comment] 2018-02-22 05:50
Run VS 2017 as an Administrator works for me.

**Comment by Mike-EEE** [comment] 2018-03-21 06:06
The zip provided above no longer exists... can someone please provide the latest?
