### ISSUE TITLE
Setting FUNCTIONS_EXTENSION_VERSION is not swapped

### ISSUE THREAD

**Issue by tjgalama** [Azure/Azure-Functions#925] opened 2018-08-31 10:38 UTC
When swapping two slots within a Functions App the value FUNCTIONS_EXTENSION_VERSION is not changed within the app settings.

Background: 
Currently we deploy our Functions App to a slot 'Deploy', start it up, swap with slot 'Production' and finally stop our Deploy slot. To make this work we changed app setting 'WEBSITE_CONTENTSHARE' a slot setting.

Further, our functions-app is using runtime V2 which currently is in preview. When setting 'FUNCTIONS_EXTENSION_VERSION' to value beta, the runtime is frequently updated with new (and great) releases. However, in the past our functions-app sometimes did not work anymore due to bugs in the new runtime (less-great). 

To eliminate this risk we want to test and deploy the functions-app with the setting 'FUNCTIONS_EXTENSION_VERSION' explicitly set to a specific (preferable latest) version.
Therefore we changed the app setting FUNCTIONS_EXTENSION_VERSION in the 'Deploy'-slot to a specific version. 
However, after swapping the Deploy- with the production-slot the FUNCTIONS_EXTENSION_VERSION value's did not appear to be swapped.

**Comment by davidebbo** [comment] 2018-08-31 17:08
If I understand correctly, you didn't make `FUNCTIONS_EXTENSION_VERSION` a slot setting, and still it behaved as if it were a slot setting when you swapped?

**Comment by tjgalama** [comment] 2018-09-03 08:03
Indeed. 'WEBSITE_CONTENTSHARE' was the only slot setting.

**Comment by davidebbo** [comment] 2018-09-04 00:32
@ruslany: it does indeed seem like `FUNCTIONS_EXTENSION_VERSION` is treated as a slot setting, even when it is not set up as one. What do you make of it?

**Comment by ruslany** [comment] 2018-09-04 16:58
Any app setting that ends with _EXTENSION_VERSION will be treated as slot setting. This behavior has been added a while ago prior to when we introduces capability for users to mark settings as slot settings.

**Comment by davidebbo** [comment] 2018-09-05 02:54
@ruslany I see, did not know that.

@tjgalama note that this won't be an issue after v2 goes GA (soon!), as both your slots will then have it set to `~2`.

**Comment by ColbyTresness** [comment] 2019-02-20 23:49
Closing as per above this is by design and not an issue anymore. Please reopen if necessary

**Closed by ColbyTresness** 2019-02-20 23:49 UTC

**Comment by johndowns** [comment] 2019-06-30 10:00
@ColbyTresness I think this may be more of a problem than it might seem.

I have a function app that uses deployment slots, and I want to try to minimise the downtime of the app during deployments. Additionally, it is deployed into an internal app service environment, so we are using 'run from package' to avoid using Kudu's deployment APIs. The way I've done that is to:

* Use an ARM template that:
   * Creates a function app.
   * Does NOT put any application configuration settings into the parent function app. This ensures that on the second deployment onwards, the parent function app's settings are left alone.
   * Creates a deployment slot.
   * DOES put application configuration settings into the deployment slot's configuration - including the `WEBSITE_RUN_FROM_PACKAGE` setting, and also sets the `FUNCTIONS_EXTENSION_VERSION` to `~2`.
* Uses PowerShell to initiate a swap.

Once the application has been deployed, the slot swap results in the parent function app configuration having the correct package URL. However, because of the behaviour mentioned in this issue, the runtime version defaults to `~1` instead of `~2`.

If I try to work around this by including the `FUNCTIONS_EXTENSION_VERSION` setting within the ARM template at the parent app level, then any other settings I've got on the app get erased because the whole settings array is overwritten. This breaks my whole deployment.

If the `FUNCTIONS_EXTENSION_VERSION` setting was treated as a normal setting instead of a slot sticky setting, then this wouldn't be a problem.

**Comment by tjgalama** [comment] 2019-07-01 07:56
The **work around** at this moment is to add a ARM-**condition** on the resource [type:Microsoft.Web/sites/config; name:MyFunctionApp/appsettings] in which you place settings like FUNCTIONS_EXTENSION_VERSION, FUNCTIONS_WORKER_RUNTIME, WEBSITE_CONTENTSHARE, 

Since the existence of a Functions app cannot be determined dynamically within the ARM template, you have to pass this via an ARM-parameter like 'isNew' (the existince of the function-app can be easily detemined dynamically outside the template e.g. using powershell, http, etc..) 

For more information about Functions App deployments via Swapping using ARM templates, I advice the article of Gary Lumsden: [Deploying Azure Function App with Deployment Slots using ARM Templates](https://nascent.blog/2017/05/31/azure-function-app-deployment-slots-arm-template/).

**Comment by ColbyTresness** [comment] 2019-07-01 16:20
@ahmedelnably for slots

**Comment by dgard1981** [comment] 2020-05-19 09:45
It would be helpful if 'Deployment slot setting' was checked for App Settings that do not follow slot swaps by design - this would at least give unsuspecting users a clue as to why their Function App is not working as expected after a slot swap.

**Comment by marcoNipo** [comment] 2020-08-06 10:07
We've been working around this issue by having the pipeline run some CLI commands to set the `FUNCTIONS_EXTENSION_VERSION` setting in the **production** slot. We do that only for the production slot, because specifying this as a _property_ in the staging slot of the app in the ARM template does the trick for the staging slot.  

So our template looks something like this:

```
{
            "type": "Microsoft.Web/sites",
            "apiVersion": "2018-11-01",
            "name": "your-app-name",
            "location": "[resourceGroup().location]",
            "kind": "functionapp",
            "properties": {
                "enabled": true,
                "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('hostingPlanName'))]",
                "httpsOnly": true,
                "scmType": "VSTSRM",
                "use32BitWorkerProcess": false
            },
            "dependsOn": [
                "[resourceId('Microsoft.Web/serverfarms', variables('hostingPlanName'))]",
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName'))]"
            ],
            "resources": [
                {
                    "apiVersion": "2018-11-01",
                    "name": "staging",
                    "type": "slots",
                    "tags": {
                        "displayName": "staging slot"
                    },
                    "location": "[resourceGroup().location]",
                    "dependsOn": [
                        "[resourceId('Microsoft.Web/Sites', parameters(your-app-name))]"
                    ],
                    "properties": {
                        "enabled": true,
                        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('hostingPlanName'))]",
                        "httpsOnly": true,
                        "scmType": "VSTSRM",
                        "use32BitWorkerProcess": false
                    },
                    "resources": [
                        {
                            "apiVersion": "2015-08-01",
                            "name": "appsettings",
                            "type": "config",
                            "dependsOn": [
                                "[resourceId('Microsoft.Web/sites', parameters(your-app-name))]",
                                "[resourceId('Microsoft.Web/sites/slots', parameters(your-app-name),'staging')]"
                            ],
                            "properties": {
                                "APPINSIGHTS_INSTRUMENTATIONKEY": "[reference(resourceId('microsoft.insights/components/', variables('appInsightsName')), '2015-05-01').InstrumentationKey]",
                                "AzureWebJobsDisableHomepage": true,
                                "FUNCTIONS_EXTENSION_VERSION": "[variables('functionsRuntimeVersion')]",
                                "FUNCTIONS_WORKER_RUNTIME": "[variables('functionsWorkerRuntime')]",
                                "WEBSITE_ENABLE_SYNC_UPDATE_SITE": "[variables('enableSyncUpdateSite')]",
                                "WEBSITE_RUN_FROM_PACKAGE": "[variables('runFromPackage')]"
                            }
                        }
                    ]
                }
```

We don't specify the setting for the production slot because otherwise the other settings will be wiped (for the staging slot, they will be applied when deploying the application).

It is too bad that the setting behaves as a slot setting, otherwise that would have been enough.  
We started using this workaround when we were still targeting v2 of the runtime: now we upgraded to v3 and I can confirm that it's still an issue, with the exact same behavior

**Comment by briandunnington** [comment] 2021-02-26 21:24
@ColbyTresness @ruslany  I know this is closed, but this behavior is both very confusing and a big roadblock for restart-free ARM deployments. There is no indication anywhere that this setting is treated in a special way. In fact, when you do a swap via the portal, the UI shows that the settings *will* be swapped to the new value, but it is silently ignored. 

If this is a system-level property, then it should not be set in the app settings configuration (like 32/64 bitness). Or if it is intended to let the user control it via app settings config, then it should be treated like any other config setting (like FUNCTIONS_WORKER_RUNTIME). With the current behavior, it is impossible to use a re-runnable ARM template to do deployments and then swap slots (without extra custom CLI/PowerShell commands that run outside of the ARM template).

![image](https://user-images.githubusercontent.com/1545776/109356196-3869f500-7835-11eb-8318-e761f300f993.png)

**Comment by briandunnington** [comment] 2021-03-01 19:30
Also pinging @fabiocav ^^^

**Comment by fabiocav** [comment] 2021-03-02 00:21
Pinging the appropriate folks both here as well as internally for follow up.

@ruslany @ehamai

**Comment by stephenwilson11** [comment] 2021-06-29 16:09
I do not understand why this is closed.

Currently as I understand it, my only option is to manually configure this on each environments production slot (which is a red flag for me). Why is it by design to not allow this configuration to flow through slots along with the release like everything else?

Please can someone explain?  @ruslany @ColbyTresness

**Comment by maartenkools** [comment] 2021-11-08 07:45
> 
> 
> You can set the following app setting WEBSITE_OVERRIDE_STICKY_EXTENSION_VERSIONS to prevent the FUNCTIONS_EXTENSION_VERSION from being sticky. See: https://docs.microsoft.com/en-us/azure/app-service/reference-app-settings?tabs=kudu%2Cdotnet#deployment-slots

I can't get this to work. Whenever I deploy infrastructure and artifacts, I set the settings on the staging slot, which are then swapped into production. Obviously the *_EXTENSION_VERSION settings aren't swapped. But what I'm trying to do is to set the WEBSITE_OVERRIDE_STICKY_EXTENSION_VERSIONS setting on the staging slot, which is then swapped into production for the first deployment. Now, for the second time the infrastructure and artifacts is deployed, this setting is again applied to the staging slot. At this point, both slots have this setting on '1'. However, the *_EXTENSION_VERSION settings still don't get swapped.

**Comment by jackbatzner** [comment] 2021-12-03 21:06
> 



> > You can set the following app setting WEBSITE_OVERRIDE_STICKY_EXTENSION_VERSIONS to prevent the FUNCTIONS_EXTENSION_VERSION from being sticky. See: https://docs.microsoft.com/en-us/azure/app-service/reference-app-settings?tabs=kudu%2Cdotnet#deployment-slots
> 
> @dolko-msft I can't get this to work. Whenever I deploy infrastructure and artifacts, I set the settings on the staging slot, which are then swapped into production. Obviously the *_EXTENSION_VERSION settings aren't swapped. But what I'm trying to do is to set the WEBSITE_OVERRIDE_STICKY_EXTENSION_VERSIONS setting on the staging slot, which is then swapped into production for the first deployment. Now, for the second time the infrastructure and artifacts is deployed, this setting is again applied to the staging slot. At this point, both slots have this setting on '1'. However, the *_EXTENSION_VERSION settings still don't get swapped.

I also cannot get this to work. I even attempted to set the slot as a deployment slot variable and that did not work

**Comment by davejclausen** [comment] 2024-10-17 14:52
@jackbatzner It seems you must set WEBSITE_OVERRIDE_STICKY_EXTENSION_VERSIONS to "0" (not "1") in order for FUNCTIONS_EXTENSION_VERSION to not be treated as sticky.
