### ISSUE TITLE
[Visual Studio] Event hub trigger not working with VS2017 functions tooling

### ISSUE THREAD

**Issue by IshaBatra** [Azure/Azure-Functions#528] opened 2017-10-06 05:24 UTC
Hi,

When I create Event Hub triggered functions using VS2017 functions tools I am getting following error when running function:

Function Error: Value cannot be null. Parameter name: receiverConnectionString

This my run method argument-

 public static void Run([EventHubTrigger("abc", Connection = "eventhub")]string[] myEventHubMessages, ExecutionContext exCtx, TraceWriter log)

My local.settings.json-
{
    "IsEncrypted": false,
  "Values": {
      "eventhub":"Endpoint=acbcdefgj",
    
  }
}

**Comment by justcla** [comment] 2017-10-06 06:01
The eventhub parameter is missing the leading double quote before "Endpoint=" in the local.settings.json

Try:
`{
  "IsEncrypted": false,
  "Values": {
    "eventhub":"Endpoint=acbcdefgj",
  }
}

**Comment by IshaBatra** [comment] 2017-10-06 06:45
That was a typo here..it is actually there in code. But still not working.

**Comment by sharpcoder28** [comment] 2017-10-06 13:26
For the C# tooling I had to upgrade to prerelease version because WebJobs.ServiceBus was locked to WebJobs 2.0, now it's 2.1.0-beta4

**Comment by Vesperpiano** [comment] 2017-10-14 16:36
Hi folks.  I think I'm having exactly the same issue.

Some background - I'm trying to get up and spinning with a simple IoT project as follows:
1. Raspberry Pi Running Windows 10 IoT;
2. Azure IoT Hub created, with my Raspberry Pi registered as an device for this IoT Hub though the Azure Portal;
3. Simple "background application" written in Visual Studio and deployed onto the Raspberry Pi that publishes messages to the Azure IoT Hub;
4. An Azure Function of type eventHubTrigger connected to the IoT Hub;
5. Messages received by the function will be parsed and written to Azure Table Storage;
6. PowerBI analytics on the Table Storage.

I've got it working as far as step 4 - where I've hit this problem.

Using VS2017 functions tooling to create "vanilla" Event Hub function as follows:

`using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Azure.WebJobs.ServiceBus;

namespace AzureFunctionProject
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([EventHubTrigger("**<EventHubCompatibleName>**", 
        Connection = "**<EventHubCompatibleEndpoint>**")]
        string myEventHubMessage,
        TraceWriter log)        
        {
            log.Info($"C# Event Hub trigger function processed a message: {myEventHubMessage}");
        }
    }
}`

In this case the <EventHubCompatibleName> and <EventHubCompatibleEndpoint> binding parameters are copied from the Azure Portal associated with the IoT hub that I've also spun up on Azure from:  <IoT Hub> / EndPoints / Events / Properties.

I've managed to build and deploy the function from Visual Studio successfully, however when I navigate to Function1 in the Azure Portal, a pink pop out box is displayed with the following red text:

> Error:
Function ($Function1) Error: Value cannot be null. Parameter name: receiverConnectionString. 
Session Id: ee8835a6c9964882926e643a1fe88a02
Timestamp: 2017-10-14T16:19:40.771Z

![error message from azure function](https://user-images.githubusercontent.com/11366447/31577405-a3d50230-b105-11e7-88f0-946c6d80945d.JPG)

I cannot find any documentation relating to "receiverConnectionString" online.

I'm running:
Microsoft Visual Studio Professional 2017 
Version 15.3.3
VisualStudio.15.Release/15.3.3+26730.12
Microsoft .NET Framework
Version 4.7.02046
WebJobs Tools v1.0.0   15.0.30923.0

Any ideas would be much appreciated.

**Comment by sharpcoder28** [comment] 2017-10-14 16:39
My issue was functionTimeout more than 10:00 in host.json.

**Comment by jeffhollan** [comment] 2017-10-28 16:07
@IshaBatra and @Vesperpiano are you still facing issues?  From above one big thing is if your C# Attribute mentiones connection `MyConnectionString` you have to make sure your `local.settings.json` file also has a `Values` for `MyConnectionString`.  I'm not sure what the constraints are for scope of the connectionString, but I know in my development I do a namespace-level connection string (the connection string doesn't end with `Entity-...`

Let me know - unable to repro on my end

**Comment by otryshko** [comment] 2017-10-31 10:00
@jeffhollan well, I'm facing this issue. my local.settings.json is
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;...",
    "AzureWebJobsDashboard": "",
    "EventHubConnection": "Endpoint=sb://..."
  }
}

    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([EventHubTrigger(
             "<my event hub name>" , 
            Connection = "EventHubConnection")]
        string myEventHubMessage, TraceWriter log)
        {
            log.Info($"C# Event Hub trigger function processed a message: {myEventHubMessage}");
        }
    }

**Comment by otryshko** [comment] 2017-10-31 10:30
Figured it out: originally I misconfigured the connection string, and got the "receiverConnectionString" error. I fixed the config but VS didn't change function.json on F5 and still complained about bad connection string. I had to clean the solution, and next time when I did F5 and function.json was (re)created, it had correct configuration values and it ran successfully.

**Comment by TheLever** [comment] 2018-03-22 09:52
I am still seeing this issue. Locally, things work fine, deployed it get the System.ArgumentNullException : Value cannot be null. Parameter name: receiverConnectionString. I removed the "generatedBy" property from the json file created by VS. Still, no love. Please advice how to proceed.

**Comment by jeffhollan** [comment] 2018-06-13 09:48
@TheLever @NucleoTech if working locally but not when published be sure to verify you have the value set as an Application Setting in the Azure Function after publishing.  The `local.settings.json` is your local version of all environment variables to use in development. After publishing this need to reflect in your **Application Settings** in Azure which has the environment variables.  We are tracking work items to automatically prompt and help guide users when settings exist locally but not in cloud when publishing (@cartermp as FYI who is helping track this).  Let me know if that resolves the issue or clears things up.

**Comment by NucleoTech** [comment] 2018-06-13 10:20
@jeffhollan I had similar issue (logged as #2915). But eventually I found out that when deploying from VS2017 the function.json in Azure did not contain correct bindings to the function entry point. When I corrected the bindings with Kudu, all was fine. It would however be great if the error messages could be more clear.

**Comment by jeffhollan** [comment] 2018-06-13 10:22
Hmm... you shouldn't have to touch Kudu for apps published from VS2017 as the binaries should be published as part of the app.

**Comment by NucleoTech** [comment] 2018-06-13 11:20
@jeffhollan The binaries are published fine but it seems the function.json not updated automatically to reflect the function parameter bindings. Not sure if it is supposed to?
In my FunctionApp setting runtime ~1 VS2017 project I am using NuGet packages:
Microsoft.NET.Sdk.Functions  (1.0.13)
Microsoft.Azure.WebJobs.ServiceBus (2.2.0)

See my other issue here: https://github.com/Azure/azure-functions-host/issues/2915

**Comment by jeffhollan** [comment] 2018-06-13 11:37
The `function.json` file is generated as part of the build step as part of the `Microsoft.NET.Sdk.Functions` package and should be published with the app. It is generated off of the Attributes included in the function method. What changes did you have to make to the function.json in Kudu?  The function.json included in the referenced issue appears to be valid from what I can see.

**Comment by NucleoTech** [comment] 2018-06-13 11:55
@jeffhollan 
Yes I see that the function.json is generated as part of the build step and then uploaded as part of the publish. Here is the function.json after publish:
`
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.13",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "eventHubTrigger",
      "path": "platformmanagementiothub",
      "consumerGroup": "hotpath",
      "connection": "PlatformManagementIotHub_events",
      "name": "myEventHubMessage"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/PlatformManagement.AzureFunctions.PlatformEventHandler.dll",
  "entryPoint": "Nucleo.GreatGuide.PlatformManagement.AzureFunctions.PlatformEventHandler.HandleDeviceEvent.Run"
}
`

and this is the function:
`
    [FunctionName("PlatformEventHandler")]
    public static void Run(
      [EventHubTrigger("platformmanagementiothub", Connection = "PlatformManagementIotHub_events", ConsumerGroup = "hotpath")]EventData myEventHubMessage,
      [Table("Lookups")] CloudTable lookupsTable,
      [Table("Platform")] CloudTable platformTable,
      [Table("IotEventErrorBin")] CloudTable iotEventErrorBinTable,
      [Table("RawEventErrorBin")] CloudTable rawEventErrorBinTable,
      [Table("RawEvent")] CloudTable rawEventTable,
      TraceWriter log)
    {
    }

`

**Comment by jeffhollan** [comment] 2018-06-13 12:03
So the function.jso above is being generated with the v1 .NET Framework path.  I can tell as the `path` parameter has been renamed to `eventHubName` in v2 .NET Core runtime.  I'm wondering if your issues may be coming from the fact of a version mismatch in the cloud environment (assuming you have function version set to "beta").  

If you look at the .csproj file in VS you should see both a target framework and function runtime version property.  It should be set to netstandard2.0 and v2 respectively I believe.  If you see net46 your local tools are likely building the function.json based on v1 rules

**Comment by NucleoTech** [comment] 2018-06-13 12:13
@jeffhollan 
In Azure, the runtime is Runtime version: 1.0.11820.0 (~1) 
My VS project has TargetFramework net471, but has no function runtime version property.

**Comment by njabulomp** [comment] 2018-06-13 13:00
Good day, I am facing the 'Value cannot be null.
 Parameter name: receiverConnectionString' issue, using application insights I am seeing the following for the exception settings.

```
Event time | 13/06/2018, 13:53:15 |  
-- | -- | --
Message | Error indexing method 'RouteFunction.Run' Value cannot be null.  Parameter name: receiverConnectionString |  
Exception type | System.ArgumentNullException |  
Failed method | Microsoft.Azure.WebJobs.ServiceBus.EventHubConfiguration.AddReceiver |  
SDK version | azurefunctions: 1.0.11820.0 |  
Client IP address | 0.0.0.0 |  
Sample rate | 1 |  
Device type | PC |  
Cloud role name | functionapp20180607122611 |  
Cloud role instance | eaa8a142a5904439e98660d4e1f397c697621338b527dee857aed3a11c7ece25 |  
Telemetry type | exception |  
Problem Id | System.ArgumentNullException at Microsoft.Azure.WebJobs.ServiceBus.EventHubConfiguration.AddReceiver |  
Assembly | Microsoft.Azure.WebJobs.ServiceBus, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 |  
Severity level | Error
```

I have been stuck on  this for a while, if someone could kindly point me in the right direction it would be much appreciated.

**Comment by jeffhollan** [comment] 2018-06-13 13:07
@NucleoTech the 471 means that it's targeting .NET Framework 4.7.1 which is great - our v1 runtime.  Just make sure the Azure Function in the cloud in Function Settings is set to ~1 and not "beta".  If it's set to beta (there's a corresponding application setting too) you have a runtime mismatch which could explain issues.

@njabulomp This is saying that you don't have an environment variable set for the Event Hubs connection string.  In your C# attribute you should have something like `Connection = "SomeEnvironmentVariableName"` - that would correspond to a value in `local.settings.json` locally that contains connection string.  In the cloud environment it means you need an Application Setting called `SomeEnvironmentVariableName` (in this case) where the value is the conneciton string.  If you don't have that application setting set you will get this error that it has a null connection string variable.

**Comment by njabulomp** [comment] 2018-06-13 13:17
@jeffhollan thank you for the reply.
 
The error I included is from when I've deployed the function to Azure, can you kindly explain how the local.settings.json file fits in. I was under the assumption that once deployed the local.settings.json file falls away and the 'Application Settings' from the portal takes precedence for the keys defined. Please correct me if I am mistaken.

**Comment by jeffhollan** [comment] 2018-06-13 13:19
You are correct.  So you need to make sure the name of the connection string you specified in your trigger attribute matches the name of an application setting for the function in Azure

**Comment by njabulomp** [comment] 2018-06-13 13:30
@jeffhollan, I am looking at the 'Application Settings' and have copied and pasted the keys and values from my local.settings.json file to the portal. I stopped and started the function and I am still receiving the 'Value cannot be null.
Parameter name: receiverConnectionString' issue.

**Comment by jeffhollan** [comment] 2018-06-13 13:33
May be related to similar problem as above.  The name of one of the properties has a breaking change between v1 and v2 so important that your config matches the right version in cloud.  That may be part of reason here.  In the local VS tools if using v1 (net471 in .csproj) make sure in the cloud you have the function setting to ~1.  If using v2 (netstandard2.0) make sure in cloud you have set to beta.  Also make sure you have the latest version of the Functions SDK in the function project (at time of this post is 1.0.13)

**Comment by njabulomp** [comment] 2018-06-13 13:42
@jeffhollan this is my function 'Run' definition 

```
[FunctionName("RouteFunction")]
public async static Task Run([EventHubTrigger("globill-azure-iot4eaf1", Connection = "EVENT_HUB_ROUTER_INPUT")]EventData[] myEventHubMessageInput, [EventHub("eph-message-eventhub", Connection = "EVENT_HUB_ROUTER_OUTPUT")]IAsyncCollector<String> output, TraceWriter log)
```
In the portal the key FUNCTIONS_EXTENSION_VERSION  value is ~1

I am using the full .Net framework v4.6.1. I have also included an image of the NuGet packages I am using in my project.

![capture](https://user-images.githubusercontent.com/39153433/41354825-3ff3e0ea-6f20-11e8-83ec-1b5bad2ef91d.PNG)

I feel like I am missing something trivial at this point but I don't know what it is.

**Comment by jeffhollan** [comment] 2018-06-13 13:44
Just make sure in Azure you have 2 application settings for the published app:

EVENT_HUB_ROUTER_INPUT
EVENT_HUB_ROUTER_OUTPUT

Both of those values should be connection strings to the Event Hubs namespace (not a connection string for an individual event hub inside a namespace)

**Comment by njabulomp** [comment] 2018-06-13 13:51
@jeffhollan if my 'EVENT_HUB_ROUTER_INPUT' setting is an IoT Hub instance, where would I find the connection strings for the underlying event hub namespace?

**Comment by jeffhollan** [comment] 2018-06-13 13:56
You'll want to open the IoT Hub in the portal, select **Endpoints**, and the **events** endpoint.  You should see **Event Hub-compatible endpoint** which is the event hubs connection string you need.

Also note that your event hub name (or path) likely isn't "eph-message-eventhub" if from IoT Hub.  I know by default the path is "messages/events" so you may need to update that part of the trigger as well.

**Comment by njabulomp** [comment] 2018-06-13 14:04
@jeffhollan the 'eph-message-eventhub' setting is for the output eventhub to send the results. I have it working locally from Visual Studio. Does this make a difference?

**Comment by jeffhollan** [comment] 2018-06-13 14:07
Yes apologies edited the comment above and meant to reference "globill-azure-iot4eaf1" - but yes if it works locally (triggers) it should work in cloud.  To simplify your life there is an azure function CLI command you can run to publish your local settings file to the cloud:

`func azure functionapp publish <FunctionAppName> --publish-settings-only` in the directory that has the local.settings.json file

**Comment by njabulomp** [comment] 2018-06-13 14:22
@jeffhollan , I've got a function working in Azure, I believe it was the IoT Hub endpoint connection string that could have been the culprit. I was chasing my own tail for a while there. Thank you so much for your assistance.

**Comment by NucleoTech** [comment] 2018-06-13 14:38
@jeffhollan Hello Jeff

![image](https://user-images.githubusercontent.com/6577720/41358211-34d96d30-6f28-11e8-99a0-d8a38b5bb18e.png)

**Comment by jeffhollan** [comment] 2018-06-13 14:47
Correct - I'm more interested in the Application Settings and the existence of these values:

EVENT_HUB_ROUTER_INPUT
EVENT_HUB_ROUTER_OUTPUT

**Comment by njabulomp** [comment] 2018-06-13 14:51
@jeffhollan, these application settings keys were always there, I believe it was the values that were incorrect specifically the EVENT_HUB_ROUTER_INPUT, I was switching between multiple IoT Hubs and most likely had the incorrect value for the IoT Hub event hub endpoint connection string. 

I've tested a couple times and the deployed function is doing what I need it to do.

**Comment by jeffhollan** [comment] 2018-06-13 14:53
Ah apologies @njabulomp glad you got it working - @NucleoTech may be having same issue but in this case it's PlatformManagementIotHub_events that appears to be the connection string setting name

**Comment by NucleoTech** [comment] 2018-06-13 15:01
@jeffhollan I had the same issue as @njabulomp but resolved it as per using the IOT hub endpoint compatible name as you explained to him. Took a while to figure out though.

However, my issue is rather that the function.json does not get generated correctly under runtime ~1. Maybe this should be in another issue#? When I edit the function.json in Kudu, everything works fine.

**Comment by jeffhollan** [comment] 2018-06-13 15:03
The one you pasted above appears to be valid for ~1 runtime that you are using. What changes do you have to make?

**Comment by NucleoTech** [comment] 2018-06-13 15:32
@jeffhollan In my post further up ( https://github.com/Azure/Azure-Functions/issues/528#issuecomment-396911465 ) you can see the generated function.json and the function declaration. Basically the bindings for all the additional parameters I added does not get generated. I need to then manually edit the function.json with KUDU to include the additional bindings. After I edit it, it looks like this

`      "bindings": [
    {
      "type": "eventHubTrigger",
      "path": "platformmanagementiothub",
      "consumerGroup": "hotpath",
      "connection": "PlatformManagementIotHub_events",
      "name": "myEventHubMessage"
    },
       {
       "type": "table",
       "name": "lookupsTable",
       "tableName": "Lookups",
       "take": 50,
       "connection": "my_STORAGE",
       "direction": "in"
       },
       {
       "type": "table",
       "name": "platformTable",
       "tableName": "Platform",
       "take": 50,
       "connection": "my_STORAGE",
       "direction": "in"
       },
       {
       "type": "table",
       "name": "iotEventErrorBinTable",
       "tableName": "IotEventErrorBin",
       "take": 50,
       "connection": ",my_STORAGE",
       "direction": "in"
       },
       {
       "type": "table",
       "name": "rawEventErrorBinTable",
       "tableName": "RawEventErrorBin",
       "take": 50,
       "connection": "my_STORAGE",
       "direction": "in"
       },
       {
       "type": "table",
       "name": "rawEventTable",
       "tableName": "RawEvent",
       "take": 50,
       "connection": "my_STORAGE",
       "direction": "in"
       },
       
       ],
`

**Comment by NucleoTech** [comment] 2018-06-13 15:33
@jeffhollan BTW Jeff is this the place to post feature requests as well?
Thanks

**Comment by jeffhollan** [comment] 2018-06-13 15:37
For C# functions input bindings can be discovered at runtime by the host process - so they don't appear or need to show up in function.json.  So the one from above should be valid. Potentially there is a bug in the attribute resolution at runtime, but that would likely be another issue (would be nice is you could do a repro in a new app and confirm it only works if you add input bindings to the VS published app).

You can create feature requests in this repo but easy for them to get buried under pile of other issues. I generally recommend adding votes to or creating items in [our uservoice page](https://feedback.azure.com/forums/355860-azure-functions) where it's a bit easier to have features bubble up

**Comment by NucleoTech** [comment] 2018-06-13 15:51
@jeffhollan  
Thanks for the UserVoice link. 
I will create a repro. I have another FunctionApp for testing purposes. How should I get the repro project to you?

**Comment by jeffhollan** [comment] 2018-06-13 15:55
If you want - I'd try again and if you still have the issue feel free to create another issue and include any source you can so I can try to get a repro as well. I have done similar patterns recently (input bindings + event hubs trigger) and it worked but always the possibility of new issues or bugs I haven't hit 👍

**Comment by NucleoTech** [comment] 2018-06-14 07:48
@jeffhollan I have created a small project to reproduce. Do I just attach it here?

**Comment by jeffhollan** [comment] 2018-06-14 09:10
Sure

**Comment by NucleoTech** [comment] 2018-06-14 10:03
@jeffhollan 
Here is the project. The function.json remains the same regardless of whether the CloudTable parameter is included or not

[FunctionBindingTest.zip](https://github.com/Azure/Azure-Functions/files/2101766/FunctionBindingTest.zip)

**Comment by jeffhollan** [comment] 2018-06-14 10:07
Correct. That's by design. See [this previous comment](https://github.com/Azure/Azure-Functions/issues/528#issuecomment-396983107)

**Comment by NucleoTech** [comment] 2018-06-14 11:09
@jeffhollan Hmm then we might be misunderstanding each other. You say that the generated function.json remains the same. This means that the binding to the additional CloudTable parameter does not happen. The function then fails because the parameter will be null. 

This is the reason why I have to manually alter the function.json in KUDU to add the additional binding.

**Comment by jeffhollan** [comment] 2018-06-14 11:15
We are misunderstanding each other.  [As documented](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#autogenerated-functionjson) for precompiled C# we don't use function.json for bindings, but a `configurationSource` for bindings.  So your CloudTable will still be bound - it does happen.  Also explained briefly in the 'what's new' section of [this blog post](https://blogs.msdn.microsoft.com/appserviceteam/2017/08/14/azure-functions-tools-released-for-visual-studio-2017-update-3/)

**Comment by NucleoTech** [comment] 2018-06-14 11:59
@jeffhollan Thanks, apologies for the misunderstanding. I am fairly new to Azure. I tested my test function and it bound fine without having to change the function.json. My question though is how does the binding know what storage account to use?

**Comment by jeffhollan** [comment] 2018-06-14 13:16
No worries understand - a lot at play with functions.  Attributes (like [Table()]) can be parsed by us even on your compiled code. So our process actually inspects your function code and pulls out the attributes and values when we load in your code and use that to bind to things like the Storage Account.

**Comment by ColbyTresness** [comment] 2019-03-13 21:22
Closing as I believe the conversation with Jeff resolved this.

**Closed by ColbyTresness** 2019-03-13 21:22 UTC
Labels: Visual Studio, pending-customer-response

**Comment by nskostas** [comment] 2019-08-21 11:19
Hi, 

I had the same issues where locally was running fine, but not in Azure when published.

For me the problem was that the connections strings from `local.settings.json`, weren't automatically published in Azure, with the default command.
You can update automatically the connections/parameters from 'local.settings.json' in the published Function using the following command.
`func azure functionapp publish functionnameonazure --publish-local-settings`

I hope this helps,
Cheers.
