### ISSUE TITLE
Azure function changed to Containers and Could not load file or assembly 'netstandard, Version=2.1.0.0'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/Azure-Functions#1730] opened 2020-09-21 07:49 UTC
This is a crazy issue I am experiencing.

I had this Azure Function App (.NET Core 3.1/Linux) which was running fine until today afternoon. A new code was pushed which triggered CI/CD and then the Function was failing to start with a message `Function host is not running`. When I checked it was showing `Could not load file or assembly 'netstandard, Version=2.1.0.0'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.`. Then I saw, it was using a container (Container settings is present).

The code being deployed is not containerized, and it was working all this time. I wasn't sure how the function app become containerized, I just deleted it and created a new function app (.NET Core 3.1/Linux/same settings as before name, storage account, app service plan). Did a fresh deploy, all was working.

![image](https://user-images.githubusercontent.com/5653381/93743088-77bb6680-fc43-11ea-901c-ec4a8a5fe5ce.png)

![image](https://user-images.githubusercontent.com/5653381/93742741-c61c3580-fc42-11ea-9220-e871d803c2c2.png)

After like 10 minutes, the function app switched back to container mode and it's not working anymore with the same error `Could not load file or assembly 'netstandard, Version=2.1.0.0'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.`. I am not expecting it to work because our code is not containerized. My issue is how is this Function App keeps getting switched to container mode?

![image](https://user-images.githubusercontent.com/5653381/93743037-5c505b80-fc43-11ea-8398-f86f84ba5b36.png)

This is crazy.

Please let me know the details you want to investigate. Prefer PM.

**Comment by davoodharun** [comment] 2020-11-18 13:06
I can reproduce this behavior. From my investigation I think this has something to do with the built in ADO task and how it operates. I noticed that when I deploy using the VS code extension, this behavior does not happen. I read into it a little more, and it looks like the VS code extension utilizes ZIP deploy with the RUN_FROM_PACKAGE setting: https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs-code?tabs=csharp#publish-to-azure

"When you deploy by using zip deploy, you can set your app to run from package. To run from package, set the WEBSITE_RUN_FROM_PACKAGE application setting value to 1. We recommend zip deployment. It yields faster loading times for your applications, and it's the default for VS Code, Visual Studio, and the Azure CLI."

However, in the built in ADO task, I do not see an option to select Zip deploy for Linux function apps as oppsed to WIndows based function apps:

Windows:
![image](https://user-images.githubusercontent.com/12518929/99534116-eb909b80-2974-11eb-9c12-f0ee0c82d902.png)

Linux:
![image](https://user-images.githubusercontent.com/12518929/99534144-f814f400-2974-11eb-9e0f-3f32fab8e5d7.png)

**Comment by davoodharun** [comment] 2020-11-18 19:38
this issue might help: https://github.com/microsoft/azure-pipelines-tasks/issues/13427

**Comment by v-bbalaiagar** [comment] 2021-04-20 11:02
Hi @jaliyaudagedara, Apologies for the delayed response, We would like to know if you are still facing the same issue

**Comment by jaliyaudagedara** [comment] 2021-04-20 18:06
@v-bbalaiagar,

I am sorry, this was like 7 months back. I think we can close the issue

**Comment by v-bbalaiagar** [comment] 2021-04-21 09:05
Hi @jaliyaudagedara, Closing this issue, Please feel free to reach back to us in case of any further queries related to this issue

**Closed by v-bbalaiagar** 2021-04-21 09:05 UTC
