### ISSUE TITLE
Azure Cosmos DB input binding not working when id is not found

### ISSUE THREAD

**Issue by stika1986** [Azure/Azure-Functions#1670] opened 2020-07-28 12:48 UTC
For https://docs.microsoft.com/en-us/learn/modules/chain-azure-functions-data-using-bindings on _Step 5 - Exercise - Read data with input bindings_ we are asked to create a Cosmos DB account, add some data to it and then create a function to find a bookmark.
Everything worked out well and was well documented but when we are asked to test with an id that exists and one that doesn't, the result of the id that doesn't exist is not what it should be, instead of receiving a _404 - No bookmarks found_ we are receiving a _500 - Internal Server Error_.
Looking at monitor the error we get is _Value cannot be null. (Parameter 'key')_

![image](https://user-images.githubusercontent.com/68903749/88667240-05158b00-d0d9-11ea-9987-bef423f9e4ce.png)

I eventually was able to fix it by changing the runtime version of the function from 3 to 2.
This made me not being able to continue to the next exercise because on the next exercise _Step 7 - Exercise - Write data with output bindings_ you aren't able to test the output properly.

Big kudos to [Arno Peters in SO](https://stackoverflow.com/a/63090435).

**Comment by vnextcoder** [comment] 2020-08-05 09:12
This is still valid today. I had to re-configure the Function engine to be ~2 to make it work and further add-bookmark function as well.

**Comment by v-bbalaiagar** [comment] 2021-04-22 09:19
Hi @stika1986, Apologies for the delayed response, We would like to know if you are still facing the same issue

**Comment by NicksCode** [comment] 2021-05-25 04:05
Yes as of 25th of May this issue still exists

**Comment by v-bbalaiagar** [comment] 2021-05-27 16:29
Hi @NicksCode, Thank you for the update, Shall try to reproduce this scenario and update you with findings.

**Comment by v-bbalaiagar** [comment] 2021-06-07 14:52
Hi @NicksCode / @stika1986 . This is a known issue and is being tracked in #1885 which is yet to be updated , but, as per design the partition key and id only accepts inputs as binding parameters like mentioned here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=csharp#http-trigger-look-up-id-from-query-string.

The code needs to look something like this : 
    {
      "name": "bookmark",
      "databaseName": "func-io-learn-db",
      "collectionName": "Bookmarks",
      "connectionStringSetting": "cosmosdb4455_DOCUMENTDB3",
      "id":"{id}",
      "partitionKey": "{id}",
      "direction": "in",
      "type": "cosmosDB"
    }

**Comment by v-bbalaiagar** [comment] 2021-06-11 09:49
Hi @stika1986, Closing this issue as the required information is provided, Please feel free to reach back to us in case of any further queries related to this issue.

**Closed by v-bbalaiagar** 2021-06-11 09:49 UTC

**Comment by brandonwoz** [comment] 2023-08-14 17:06
This is still an issue in v4.x. An internal service error occurs when the item is not found, not allowing the function to run and gracefully handling the not-found item. 

My configuration is correct (I believe) using v4.x API:

```
{
  "name": "bookmark",
  "databaseName": "func-io-learn-db",
  "containerName": "Bookmarks",
  "connection": "****",
  "id":"{id}",
  "partitionKey": "{id}",
  "direction": "in",
  "type": "cosmosDB"
}
```

Is the only solution still to role back to v2?

**Comment by mumurug-MSFT** [comment] 2023-08-16 13:27
@brandonwoz I have responded to your question in https://learn.microsoft.com/en-us/answers/questions/1345746/how-to-resolve-internal-service-error-with-cosmosd#answers. Unfortunately, I am unable to reproduce the issue at my end. If you still face the issue, please share the details requested in Q&A thread. We will investigate the issue further to find the cause.

**Comment by bronthulke** [comment] 2024-03-28 06:57
I am having this same issue myself now as I have just tried to Azure Cosmos DB extension version 3.0.9 to version 4.7.0.

An existing Azure Function that uses a `CosmosDBInput` binding throws a 500 error when the retrieval of data for the given SQL Query returns a 404.

In the past, it has happily just set that input variable to NULL, so that I could then handle that in my code.

As other have mentioned on the above link to the ticket on Learn, we are being forced to move to the 4.x version of the extension by August 31 2024, and yet this seems to be a widely experienced issue.

What solution would you recommend for this?
