### ISSUE TITLE
VS 2017 Tooling for Functions App is not working in Service Bus Queue based trigger

### ISSUE THREAD

**Issue by thuru** [Azure/Azure-Functions#478] opened 2017-09-03 13:26 UTC
I'm using VS 2017 Enterprise 15.3.3 with Azure Functions and Web Job Tools extension 15.0.30812.0.

There are some issues and observations.

I create the Azure Functions project and without adding any functions, I could update NuGet packages. This updates the package Microsoft.NET.Sdk.Functions 1.0.0 to 1.0.2. Then I add a Service Bus Queue Trigger function, which adds the below code. (I specified the parameter names in the dialog box)

```csharp
public static class TemperatureSpike
    {
        [FunctionName("TemperatureSpike")]
        public static void Run([ServiceBusTrigger("temperature", AccessRights.Manage, Connection = "TemperatureBus")]string myQueueItem, TraceWriter log)
        {
            log.Info($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
        }
    }
```

**Observation 1 :** VS automatically downgrades the package back 1.0.0 I have to again manually update the packages 1.0.2

I publish the app using VS. I browsed through the function.json in the portal. It doesn't have the direction parameter in the json. Without this I cannot switch to the standard view of the function.json in the portal.

```json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "TemperatureBus",
      "queueName": "temperature",
      "accessRights": "manage",
      "name": "myQueueItem"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\Test.dll",
  "entryPoint": "Test.Function1.Run"
}
```

**Observation 2:** The function.json still shows the version as Microsoft.NET.Sdk.Functions-1.0.0.0

**Observation 3** The bindings section does not have the 'direction' property. Unless I specify the 'direction' I cannot switch to the Standard Editor mode of the function.json in portal.

I configured the connection string in the Function App Settings.

Finally, **the trigger does not work.** I have tired different combinations of version with 1.0.0 as well but the triggers generated from the VS tooling is not working.

**Comment by thuru** [comment] 2017-09-06 13:33
Today I got an another update to the Tools - 15.0.30901.0 

In this my above observation 1 is solved as the project template refers the package Microsoft.NET.Sdk.Functions 1.0.2

But when i deploy the application to Azure the function.json still says it's 1.0.0.0
The only difference the header details in the bottom :)

Still the direction property is missing in the bindings section and without that we cannot switch to the standard view. And mainly the trigger **DOES NOT WORK**

**{
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "massroverservicebus_RootManageSharedAccessKey_SERVICEBUS",
      "queueName": "temperature",
      "accessRights": "Manage",
      "name": "myQueueItem"
    }
  ],
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "disabled": false,
  "scriptFile": "..\\bin\\FunctionApp1.dll",
  "entryPoint": "FunctionApp1.Function1.Run"
}**

**Comment by thucnguyen77** [comment] 2017-10-18 00:36
I am using Microsoft.NET.Sdk.Functions 1.0.6 and still facing the same issue. 

I am also unable to explicitly add the Microsoft.Azure.WebJobs.ServiceBus package due to the version conflict of Microsoft.Azure.WebJobs package.

Is anyone from development team keen to look at this issue?

**Comment by mlorbetske** [comment] 2017-11-07 00:42
@fabiocav could someone take a look please?

**Comment by WayneMcRae** [comment] 2017-11-08 10:23
I have a workaround to fix the issue with the broken function.json.  When using VS to publish an app function to Azure, the function.json omits the "direction" property.  For Service Bus Triggers (and other queue triggered functions), this breaks functionality.  Recently I discovered that Azure no longer allows me to change the published function to Read/Write, thus preventing me from fixing the function.json file in Azure.  I assume other people have the same issue.

There is another way to fix the file.
1) In Azure, open the App Service blade and Stop the function.
2) Open the Platform Features tab and start the App Service Tools, under the Development section.
3) Search the directory structure to locate the function.json file.  Mine is shown under the function name.
4) Edit the file to add the missing "direction": property.  The file will autosave.
5) Close the window and restart the app under the App Service blade.
6) When the function is started you can select it and see the modified function.json.
7) If this is the first time you've set up the app function you will need to set the service bus connections, etc.  There are plenty of tutorials to tell you how to do this in Azure.  I set the connection string under Application Settings, and then connected by app function to the Service Bus Queue using the Integrate tab.

Job done.

Hope this helps.  It took me quite a while to figure out how to fix the problem.  I hope it is useful for other people.

**Comment by hdsmachado** [comment] 2017-11-08 21:28
@WayneMcRae  You really put some hope in my tests, but unfortunately for me this workaround didn't work. =/  Thanks for sharing your way to fix the problem. 

I've already tried to replicate the function.json configuration that I have in another AzureFunction that I've created in Azure portal and this one works just fine. 

Does anyone know if there's a way that I could see/log "the errors"? I'm still shooting in the dark with this problem.

**Comment by FAlmeidaActionpoint** [comment] 2017-11-21 15:37
I had the same problem and I sorted out by changing manually the function.json and set the configurationSource to config:

{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-1.0.6",
  **"configurationSource": "config",**
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "eventHubConnectionString",
      "queueName": "alertqueue",
      "accessRights": "manage",
      "name": "myQueueItem",
      "direction": "in"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/FunctionApp.dll",
  "entryPoint": "FunctionApp.ServiceBusAlert.Run"
}

**Comment by katriendg** [comment] 2018-01-16 12:41
We're experiencing the same issue with the trigger for Service Bus Topic subscription, when using the VS2017 tools.
The generated function.json is never correct. Manually changing both the direction + configurationSource settings as described by @FAlmeidaActionpoint  and @WayneMcRae solve this. However this is not usable in real world as every time the function is published it will re-generate the wrong file and we need to manually correct it.

**Comment by hdsmachado** [comment] 2018-01-17 16:40
This workaround really works! Thanks @FAlmeidaActionpoint 

I hope that this issue could be solved soon, because every time that I need to change or publish any function I have to go and change every single "function.json"

**Comment by mhoeger** [comment] 2018-01-19 23:12
@katriendg @hdsmachado Could you check to make sure that you have defined the service bus connection string for the published version within the Azure portal? (Click on the function app name => Application settings). 

I think that the missing connection string _in the published version_ may be the root cause of the issue. Although changing configurationSource to "config" links the app to the connection string defined locally, it isn't the best solution (as I'm sure you all know too well). 

If you can confirm that this is the issue, we need to change the missing connection string error to have a more informative error message. Otherwise, I'll keep investigating!

![image](https://user-images.githubusercontent.com/8888531/35175671-a90f87a0-fd29-11e7-93e2-9aab14873cb6.png)
![image](https://user-images.githubusercontent.com/8888531/35175664-9bbc0b28-fd29-11e7-8a2a-b9456bc0f91a.png)

**Comment by Infoseeker** [comment] 2018-02-02 12:59
I am having similar issue. I have created all the app settings on the azure portal. No luck :-(. Had to manually edit function.json to get it working. (This gets hard to achieve automation  through continuous build and needs manual intervention).

**Comment by mhoeger** [comment] 2018-02-03 01:16
@Infoseeker There is a bug where the wrong function.json gets generated without a clean build before publish (#664). Could you try doing clean, then build, then publish?

If that doesn't work, would you mind sharing more details about what's going on? For example, the trigger type, exact error messages, and your function name so that we can investigate (you can also share it privately following these instructions: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by vinayakmali84** [comment] 2018-11-18 14:11
> We're experiencing the same issue with the trigger for Service Bus Topic subscription, when using the VS2017 tools.
> The generated function.json is never correct. Manually changing both the direction + configurationSource settings as described by @FAlmeidaActionpoint and @WayneMcRae solve this. However this is not usable in real world as every time the function is published it will re-generate the wrong file and we need to manually correct it.

It worked. Still this issue is not fixed in visual studio 17

**Comment by mhoeger** [comment] 2018-11-19 17:59
@vinayakmali84 - The fix should have been released in the tooling for Visual Studio a while ago but your tools may be out of date. Can you try making sure that your Azure Functions and Web Jobs Tools is updated?

**Comment by WayneMcRae** [comment] 2018-11-20 11:06
I'm running the latest release of Azure Functions and an up to date version of VS2017 Pro.  Still have this problem when I publish my functions to Azure.  I have to manually add "direction": "in" to function.json when I publish.

**Comment by vinayakmali84** [comment] 2018-11-20 18:13
> @vinayakmali84 - The fix should have been released in the tooling for Visual Studio a while ago but your tools may be out of date. Can you try making sure that your Azure Functions and Web Jobs Tools is updated?

I am using latest version on Visual Studio 2017 V: 15.9.1
I am using latest version of Azure Function, when I published app first time, it asked me to update it.  Still issue is not resolved. I need to do manual modification of "direction" in json

**Comment by jeffhollan** [comment] 2019-02-27 07:36
A few releases have gone out since this issue was created.  Does this still occur?

**Comment by WayneMcRae** [comment] 2019-02-27 09:14
It is still happening for me.  Azure Functions and Web Jobs Tools (15.10.2046.0; 17/10/2018) and Visual Studio 2017 (Version 15.9.7; VisualStudio.15.Release/15.9.7+28307.423; Microsoft .NET Framework; Version 4.7.03190)  My project is targeting .NET Core 2.2.  The project originally published the correct function.json.  None of the updates have fixed the issue.  I haven't tried it with VS 2019 yet.  2019 is still in RC and it's a little too early to trust with production code, in my opinion.

**Comment by mhoeger** [comment] 2019-02-27 22:28
@WayneMcRae - can you check the version of `Microsoft.NET.Sdk.Functions` in installed nuget packages? It should be >= [1.0.8](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.8).

![image](https://user-images.githubusercontent.com/8888531/53527445-d3d7fc00-3a9b-11e9-9b1a-62f173fa2517.png)

**Comment by WayneMcRae** [comment] 2019-02-28 09:03
Ah, that worked.  I was still using 1.0.7.  After upgrading to 1.0.25 it is working fine.  Thank you, Marie.  I really appreciate your help.

**Comment by mhoeger** [comment] 2019-02-28 23:47
No problem @WayneMcRae :) Glad your issue is resolved!!

Closing this issue - if anyone is still experiencing it, please check the version of `Microsoft.NET.Sdk.Functions` in installed nuget packages. It should be >= [1.0.8](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.8).

![image](https://user-images.githubusercontent.com/8888531/53527445-d3d7fc00-3a9b-11e9-9b1a-62f173fa2517.png)

**Comment by YalamanchiliBhavana** [comment] 2020-07-09 19:48
This issue is still happening for me with sdk version > 1.0.8. I am using  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.2" />. I am still facing this issue when the function is published through vscode

**Closed** 2020-07-09 20:03 UTC

**Comment by mhoeger** [comment] 2020-07-09 20:05
Hey @YalamanchiliBhavana - this is a fairly old issue and something different may be going on for your specific setup. Do you mind opening a new issue with more details? You can tag me in it too.
