### ISSUE TITLE
servicebus queue trigger function is not working after publishing it to azure

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/Azure-Functions#684] opened 2018-02-08 18:23 UTC
_From @almusawi on February 8, 2018 12:50_

Hi,

I have implemented an Azure function with service bus queue trigger, using visual studio 2017. the function works fine with VS, but after publish it to the azure. the function is not working.  it does not trigger at all.

any idea why this happen and how to fix that please?

Thanks

_Copied from original issue: Azure/azure-functions-vs-build-sdk#164_

**Comment by ahmelsayed** [comment] 2018-02-08 18:25
[Moved to this repo since the question is not related to the build task]

Hi @almusawi 
Did you publish it to azure through VS? Are the app settings set correctly on your app pointing to the correct Service Bus connection?

also can you share your app name, either directly or [indirectly](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by mhoeger** [comment] 2018-02-08 18:34
@almusawi - have you added the service bus connection string in the "App Settings" of your published version? Settings from local.settings.json are not automatically copied over by design (the idea is that local.settings.json likely contains keys/secrets like connection strings, and that shouldn't be automatically published). 

If that isn't the issue, can please share more details about your issue (for example, function app name - or if you don't feel comfortable sharing that publicly you can follow the steps [here](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately))

**Comment by almusawi** [comment] 2018-02-09 12:20
Hi @mhoeger @ahmelsayed, yes I have added them in the app settings, but seems to be it does not read them.

**Comment by almusawi** [comment] 2018-02-09 12:21
ok @mhoeger will fellow the steps to share it thank for both

**Comment by mhoeger** [comment] 2018-04-18 21:40
@almusawi - I'm closing this issue since it hasn't been active in a while, but please re-open it and @ me if you had other issues!

**Closed by mhoeger** 2018-04-18 21:40 UTC

**Comment by rabrahamOpti** [comment] 2018-05-25 19:22
@mhoeger I'm experiencing the same issue. In Visual Studio 2017, I 

* created an Azure Functions project
* initially selected "Empty" to create the project without triggers
* Selected a storage account under my Function App's resource group
* Added a "new item"
    * chose an Azure Function Service Bus Queue Trigger template
    * Set the Access rights to "Manage"
    * Set the Connection String to the primary connection string of my queue's Service Bus Namespace
    * Set the Queue Name to the queue I want the function to be triggered off of

Those steps set up a static class with a Run method whose signature I updated accept BrokeredMessage and ExecutionContext as arguments. It looks like this:

    
    public static void Run([ServiceBusTrigger("{My queue name}", AccessRights.Manage, Connection = "{Shared Access key}")]BrokeredMessage myQueueItem, TraceWriter log, ExecutionContext context)
    
I tested The function locally using a console application, as described [here](https://stackoverflow.com/a/45953267/1096596).  It worked as expected. I then published the project, and it published without issue, and when I looked at it in Azure Portal, the web interface says:
    
    Your app is currently in read-only mode because you have published a generated function.json.
    

Everything looks correct, but when I publish messages to the queue, they are stuck in an active state, and the function's monitor section indicates that the function has never run.

I'm afraid I can't get you an invocation id, because I can't seem to get it to run manually though the portal. I can email the information you're looking for to the email address listed on your github account though, if that would work.

**Comment by rabrahamOpti** [comment] 2018-05-29 18:01
For those that run into this in the near future, here's the issue: The configuration wizard windows generates the function code puts the raw connection string in the Connection Property, like so:

    public static void Run([ServiceBusTrigger("{My queue name}", AccessRights.Manage, Connection = "{Connection String}")]BrokeredMessage myQueueItem, TraceWriter log, ExecutionContext context)

The Connection value isn't meant to be a connection string, it's meant to be a Key in Application Settings, whose value is the connection string. In my version of Visual Studio and Azure SDK (which I'll list below), I had to do this manually. To do so, right click your project, select "Publish", and in the Publish screen, click "Manage Application Settings...". Enter a key value pair for your Service Bus Namespace connection string. Then update your function's signature to set the value of Connection to whatever you called the key.

**Comment by paulbatum** [comment] 2018-05-29 18:35
@rabrahamOpti You mentioned that the wizard puts the connection string straight into the Connection property, but I think it must be because you pasted your connection string into the wizard. Here is me doing the steps:

![image](https://user-images.githubusercontent.com/10663/40678011-2cb61ce8-6334-11e8-98b9-85fab864c17e.png)

This generates the following code:

```csharp

public static class Function1
{
    [FunctionName("Function1")]
    public static void Run([ServiceBusTrigger("myqueue", AccessRights.Manage, Connection = "MyServiceBusConnection")]string myQueueItem, TraceWriter log)
    {
        log.Info($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
    }
}
```

I think that the wizard is kind of confusing and needs to be improved, but to me it looks like its behaving as expected and this issue should stay closed. Let me know if I'm missing something.

**Comment by rabrahamOpti** [comment] 2018-05-29 19:17
@paulbatum Ah, you're right. However, I just went through these steps again, and noticed the wizard doesn't actually prompt you for a connection string. Further, when I click on the "Manage Application Settings..." link on the publish screen, the Connection String Setting key I put down doesn't appear there at all. So without performing this manual step, the function will fail when published.

I'm not sure if the Wizard not updating Application Settings constitutes a bug or a feature request, but I can create a feature request if you like.

**Comment by paulbatum** [comment] 2018-05-29 20:46
@rabrahamOpti I think its a feature request, so I'd file it separately (this repo is fine)

**Comment by rabrahamOpti** [comment] 2018-05-30 13:42
Here it is. Thanks!

https://github.com/Azure/Azure-Functions/issues/824

**Comment by rlmishra** [comment] 2019-04-14 00:38
This still doesn't work after deploy considering all the comments.

**Comment by mhoeger** [comment] 2019-04-15 17:59
@rlmishra - please open a new issue with your exact details. As a note, are you changing the Azure Service Bus connection string in the "App Settings" pane in the Azure Portal? And if so, please include your app name (either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)) when opening a new issue. Feel free to @ mention me

**Comment by rlmishra** [comment] 2019-04-15 23:20
It works. The problem was the AppSettings section of the Azure Function was missing some entries, although the same was published in local.json settings. My code was reading the settings through ConfigurationManager.AppSettings, which worked fine in Visual Studio, but after deploy it did not work, without giving any hint as to why? I redefined the same settings manually under AppSettings section of the Azure function after deploy, which fixed the issue.

**Comment by mhoeger** [comment] 2019-04-15 23:32
@rlmishra - per our [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#function-app-settings):

> Any settings you added in the local.settings.json must be also added to the function app in Azure. These settings are not uploaded automatically when you publish the project.

> The easiest way to upload the required settings to your function app in Azure is to use the Manage Application Settings... link that is displayed after you successfully publish your project.

Mainly, we don't want to encourage local connection strings and production connection strings to be the same because the local instance may conflict with the production instance (causing triggers to not be fired in either environment). Visual Studio has a good UI to manage local vs. production under "Manage Application Settings..."

**Comment by rlmishra** [comment] 2019-04-15 23:35
Okay, I will check it out.
