### ISSUE TITLE
Debugging Azure Functions on Apple Silicon M1 Fails to Start

### ISSUE THREAD

**Issue by ilushka85** [Azure/Azure-Functions#1780] opened 2020-11-19 01:35 UTC
When using Apple Silicon m1 Processor starting a debug session in Rider or Visual Studio for Mac hangs at the following console output:

Visual Studio for Mac:

Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

JetBrains Rider:

/Applications/Rider.app/Contents/lib/ReSharperHost/macos-x64/dotnet/dotnet exec /Applications/Rider.app/Contents/lib/ReSharperHost/JetBrains.Debugger.Worker.exe --mode=client --frontend-port=52885 --plugins=/Applications/Rider.app/Contents/plugins/rider-unity/dotnetDebuggerWorker

Loaded application domain 'DefaultDomain (id 1)'
Loaded Assembly '/Library/Application Support/AzureFunctions/System.Private.CoreLib.dll'
Loading module /Library/Application Support/AzureFunctions/System.Private.CoreLib.dll in application domain 1:DefaultDomain
Pdb file for assembly /Library/Application Support/AzureFunctions/System.Private.CoreLib.dll was not found or failed to read

Running without debugging works normally, but debugging is not currently possible because of this.

**Comment by anthonychu** [comment] 2020-11-19 08:35
Are you able to create and debug an ASP.NET Core app with VS for Mac? Just want to understand if the problem is specifically with debugging function apps.

**Comment by anthonychu** [comment] 2020-11-19 08:43
Closing in favor of https://github.com/Azure/azure-functions-core-tools/issues/2303

**Closed by anthonychu** 2020-11-19 08:43 UTC
