### ISSUE TITLE
Function (HttpTrigger-Java) Error: Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1

### ISSUE THREAD

**Issue by perdubug** [Azure/Azure-Functions#936] opened 2018-09-06 01:03 UTC
Env:
    Windows 10
    Visual Studio Code 1.26.1
    Azure Functions for Visual Studio Code (Preview) 0.10.0
    Language: Java

I deployed a simple 'Hello World' Azure Functions to Azure cloud. It was work fine until yesterday - I can not access my Azure Functions endpoint on Browser. So I login to Azure Portal and got below error message popup when clicking my Azure Functions:
__"Function (HttpTrigger-Java) Error: Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out.

Session Id: e7b3a4ed5cbc4586b539d7f6c2cad59f

Timestamp: 2018-09-06T00:48:23.990Z"_

I also tried the test page by going to Azure Function->HttpTrigger-Java. After clicking 'Run', I got below error message output:

**_**_2018-09-06T00:58:58  Welcome, you are now connected to log-streaming service.
2018-09-06T00:59:09.356 [Information] Executing 'Functions.HttpTrigger-Java' (Reason='This function was programmatically called via the host APIs.', Id=6d506a31-c66c-4cf0-a37b-df192b898ed3)
2018-09-06T00:59:09.393 [Error] Executed 'Functions.HttpTrigger-Java' (Failed, Id=6d506a31-c66c-4cf0-a37b-df192b898ed3)_**_**

Here's my extensions.csproj:
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<WarningsAsErrors></WarningsAsErrors>
	<DefaultItemExcludes>**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.0" />
  </ItemGroup>
</Project>

Anything I can do to make the Azure Function back to work? Thanks

**Comment by uzoltan** [comment] 2018-09-06 11:52
I have the same exact problem

**Comment by uzoltan** [comment] 2018-09-07 09:19
Problem persists even if I try to create a completely new Function App with the same code, using the latest azure.functions.java.library (1.0.0-beta-5).

**Comment by borgelo** [comment] 2018-09-10 10:58
I had the same problem. A colleague of mine pointed me here, that seems to fix the issue:
https://github.com/Azure/app-service-announcements/issues/112

**Comment by perdubug** [comment] 2018-09-19 14:49
@borgelo Thanks for your information. It seems the link you post is for old version. Now when I created a new Azure Functions project, the Azure Functions plugin version is higher than that.

**Comment by ColbyTresness** [comment] 2019-02-21 00:06
Closing, please see linked announcement.

**Closed by ColbyTresness** 2019-02-21 00:06 UTC

**Comment by paulyuk** [comment] 2023-03-04 19:28
The issue root cause and workaround may also be this.  https://github.com/Azure/azure-functions-core-tools/issues/3294
