### ISSUE TITLE
Cannot connect to CosmosDB from VS Code Azure Function

### ISSUE THREAD

**Issue by rmaziarka** [Azure/Azure-Functions#825] opened 2018-05-30 21:25 UTC
Hi Azure Functons team,

I created Azure Function (2.0v) from C# HTTP template . Then I added output binding to CosmosDB based on [CosmosDB docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb#output---example):

```csharp    public static class AddEvent

    {
        [FunctionName("AddEvent")]
        public static void Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]
                HttpRequest req, 
            [CosmosDB("SomeDatabase", "SomeCollection", Id = "id", 
            ConnectionStringSetting = "myCosmosDB", CreateIfNotExists = true)] 
                out dynamic document)
        {
            document = new { Text = "something", id = Guid.NewGuid() };
        }
    }
```
This is my local.settings.json. I based on values from CosmosDB emulator:
 ```json
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "AzureWebJobsDashboard": "",
        "myCosmosDB": "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
    }
}
```

Unfortunately, when I hit HTTP trigger I get:
`
System.Private.CoreLib: Exception while executing function: AddEvent. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'document'. Microsoft.Azure.DocumentDB.Core: The type initializer for 'Microsoft.Azure.Documents.UserAgentContainer' threw an exception. Object reference not set to an instance of an object.
`

What does this exception means? I cannot find any relevant information about it and it completely stops my local work. Function works well without CosmosDB attribute.

// sorry if this is not a correct place to put this issue

**Comment by arerlend** [comment] 2018-06-05 16:03
Same issue. @omusavi

**Comment by omusavi** [comment] 2018-06-05 16:08
Thanks @arerlend, yes I am hitting this as well:
azure-functions-core-tools@2.0.1-beta.28
.NET Core SDK 2.1.300

Not a VS Code only issue, it also occurs in a regular command line after doing:
```
dotnet build
cd bin\debug\netstandard2.0\
func host start
```

Note that the same exact repo works with VS2017 and running through the debugger there.

**Comment by ChristianWeyer** [comment] 2018-06-05 20:36
The exact same happens for me as well. Running beta28.
@fabiocav @ealsur

**Comment by fabiocav** [comment] 2018-06-06 21:09
The issue is understood and related to the native assets resolution changes in the latest release. Quickly putting a fix together to catch the current release train.

**Comment by jeffhollan** [comment] 2018-06-14 22:14
@fabiocav do you have status of this? Just wondering if we should move repos or if we can close. Thanks

**Comment by fabiocav** [comment] 2018-06-14 23:07
This should be resolved with the last release on NPM now (beta.29).

Closing as resolved, but please let me know if this issue continues to come up.

**Closed by fabiocav** 2018-06-14 23:07 UTC

**Comment by ealsur** [comment] 2018-06-15 12:14
I was able to solve it updating the Core CLI to beta.29 as @fabiocav mentioned, @arerlend @ChristianWeyer please update the CLI, it should solve it 😄

**Comment by ChristianWeyer** [comment] 2018-06-15 12:56
Yep - the error is gone. However, my CosmosDBTrigger is not fired (the same code works for v1).

**Comment by ealsur** [comment] 2018-06-15 13:51
@ChristianWeyer Are you running both functions in parallel? Or do you have another function (maybe already in Azure) using the same configuration (collectionname + leasecollectionname)? If so, that might be the issue. You can have multiple Functions listening to the same collection sharing the same lease collection if you use the `LeasePrefix` attribute.

**Comment by ChristianWeyer** [comment] 2018-06-15 18:14
True :-)
BTW: LeaseCollectionPrefix does not exist in the v2 package?

**Comment by brettsam** [comment] 2018-06-15 18:28
Yeah, they should. We must have missed that :-(

**Comment by fabiocav** [comment] 2018-06-15 18:29
@ealsur please! Those do need to be ported to `dev`, otherwise we'll have a gap there. 

I Created this to track https://github.com/Azure/azure-webjobs-sdk-extensions/issues/423

**Comment by ealsur** [comment] 2018-06-15 18:56
@fabiocav PR ready https://github.com/Azure/azure-webjobs-sdk-extensions/pull/424

**Comment by fabiocav** [comment] 2018-06-15 20:37
Thanks @ealsur ! That was quick! :)

**Comment by ChristianWeyer** [comment] 2018-06-17 19:19
Would any of you guys know when the merged code could show up in a release on Nuget @fabiocav @ealsur ?
