### ISSUE TITLE
ItemGroup None Update ignored in fsharp project msbuild

### ISSUE THREAD

**Issue by richardjharding** [Azure/Azure-Functions#1177] opened 2019-04-01 09:53 UTC
I'm not sure this is the correct repo so please point me in direction of correct repo if this is wrong the place to raise

I noticed an issue when attempting to build a functions v2 project with fsharp - I compared with an equivalent c# project and noticed a discrepancy. The issue is the behaviour of copying additional files such as host.json

with these lines
```
 <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
```
when I build the csharp project with ```dotnet build``` the 2 json files are copied as expected (whether they already exists or not in output folder) but when I execute the same build with fsharp project no files are copied

When I examined the build log with msbuild structured log viewer in the c# example the None item group was present but in the f# log it was not

When I change the f# example project to use Include rather than Update eg
```
<ItemGroup>
    <None Include="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup> 
```
it works as expected - this is with

.net sdk 2.2.105
in both cases
```<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />```
and 
```
Azure Functions Core Tools (2.4.498 Commit hash: 47cc64bd19eb8fa9bcbb1aaac88b217a9558617b)
Function Runtime Version: 2.0.12353.0
```

**Comment by estensen** [comment] 2020-03-03 12:03
This is still an issue! I spent quite a long time banding my head against the wall because the Cosmos bindings would not work. The F# template should generate correct config!

**Comment by Youenn-Bouglouan** [comment] 2020-04-06 13:06
I experienced this issue as well today, took me 2 hours to figure out what was going on. I initially thought it was related to the Azure Functions template as well, but it can be reproduced with a very simple .NET Core 3.1 console app (`<None Update="host.json">` works with csproj but not with fsproj).

Ideally there shouldn't be any difference at all between languages when it comes to those msbuild settings. @cartermp are you aware of this issue? Is there a better repo to submit this problem to?

Thanks!

**Comment by cartermp** [comment] 2020-04-09 18:45
Yeah, this isn't specific to F# or even visual studio tooling. I think there might be something wrong in the F# targets. I'll close this as a duplicate: https://github.com/dotnet/fsharp/issues/8914

**Closed by cartermp** 2020-04-09 18:45 UTC
