### ISSUE TITLE
The Debugging is not hitting the Breakpoint when Remote Debugging using Visual Studio 2017

### ISSUE THREAD

**Issue by TonyHenrique** [Azure/Azure-Functions#844] opened 2018-06-17 00:01 UTC
I published a Debug version of Azure Function (v2, C#, precompiled)

The Debugging is not hitting the Breakpoint when Remote Debugging
If I run locally, then Debugging works as expected.

It seems that I am unable to remote debug Azure Functions V2 C# precompiled, using Visual Studio, the debugging sessions starts, but the breakpoints does not hit

I noticed this message

> The current version of VS Remote Tools does not match this version of Visual Studio. If errors occur, try installing the matching version of VS Remote Tools.

I installed https://aka.ms/vs/15/release/RemoteTools.amd64ret.enu.exe  but still have this same problem.

I am using
 Azure Functions v2 Runtime version: 2.0.11857.0 (beta) and Visual Studio 2017 15.8.0 Preview 2.0

**Comment by cgillum** [comment] 2018-06-18 19:39
Have you checked the **Modules** window to see if your symbols are getting loaded?

Regarding the message you saw, it's possible the issue is related to your use of VS 2017 15.8.0, which is currently in preview, and thus we might not have the right server-side components installed. @safihamid do you know if the remote debugging bits we have today work with this prerelease version of VS?

**Comment by safihamid** [comment] 2018-06-18 22:34
I just tested this using 15.8.0 Preview 2.0 out of the box and everything worked fine for me. I didn't need to install any additional remote tools. I suggest you uninstall the remote tools package on your client and see if it works or not.

**Comment by TonyHenrique** [comment] 2018-06-18 23:39
After uninstalling Remote Tools
When I Attach Debugger, this appears

> System.Runtime.InteropServices.COMException (0x89710023): Unable to connect to the Microsoft Visual Studio Remote Debugger named 'webapius.azurewebsites.net'.  A conexão com o ponto de extremidade remoto foi encerrada.
> 
>    at Microsoft.VisualStudio.Debugger.Interop.Internal.IDebuggerInternal120.ConnectToServer(String szServerName, VsDebugRemoteConnectOptions[] pConnectOptions, CONNECT_REASON ConnectReason, Int32 fIncrementUsageCount, IDebugCoreServer3& ppServer)
>    at Microsoft.VisualStudio.Web.Azure.MicrosoftWeb.Operations.RemoteDiagnosticsSessionBase.ConnectToServer(String site, String user, String password)

**Comment by TonyHenrique** [comment] 2018-06-19 00:36
@cgillum I checked now the Modules 
My assembly WebAPI.dll has Symbols loaded.
![image](https://user-images.githubusercontent.com/6307623/41569095-9f59f5ce-733f-11e8-915e-79bf08bd0045.png)

**Comment by TonyHenrique** [comment] 2018-06-19 00:48
I don't know how, but now the debugging is worked again, that error window is not appearing anymore.
Breakpoint hits.
Then after a few attempts, breakpoint does not hit again.

**Comment by TonyHenrique** [comment] 2018-06-19 00:50
Another thing, sometimes when right click the Function on Azure and select Attach Debugger,
this error appears
Object reference not set to an instance of an object.
![image](https://user-images.githubusercontent.com/6307623/41569417-8ea7711e-7341-11e8-8fae-f8647bf0101c.png)

**Comment by jeromekol** [comment] 2018-07-20 08:21
I got the same problem and using Azure Functions and Web Tools 15.0.40617.0. I'm running my app on an app service plan and not even the modules are loaded from my function app.

**Comment by safihamid** [comment] 2018-07-23 17:00
@jeromekol There is a bug in VS Cloud Explorer for functions V2 that will be fixed soon. But when manually attaching make sure in the 'Attach to:' select button you pick 'Managed (CoreCLR) code.

![image](https://user-images.githubusercontent.com/1000764/43091530-2b4bf7dc-8e5f-11e8-9783-eb9bab56f501.png)

**Comment by jeromekol** [comment] 2018-07-24 07:36
thx @safihamid that worked for me!

**Closed** 2019-02-21 00:25 UTC

**Comment by StingyJack** [comment] 2019-02-22 18:56
This worked last week and does not work today. I get the same message in the output window -> Diagnostics Hub from both Server explorer and Cloud explorer.  @mathewc - can this be reopened?

**Comment by vjppaz** [comment] 2021-05-18 17:24
> @jeromekol There is a bug in VS Cloud Explorer for functions V2 that will be fixed soon. But when manually attaching make sure in the 'Attach to:' when clicking the 'Select...' button you pick 'Managed (CoreCLR) code'.
> 
> ![image](https://user-images.githubusercontent.com/1000764/43091530-2b4bf7dc-8e5f-11e8-9783-eb9bab56f501.png)

I am trying this step but i receive an invalid credential exception. what cred should i use? i tried my ms 365 account but it doesn't recognize it, i am the owner of the subscription.

**Comment by RDavis3000** [comment] 2024-05-18 21:57
> > @jeromekol There is a bug in VS Cloud Explorer for functions V2 that will be fixed soon. But when manually attaching make sure in the 'Attach to:' when clicking the 'Select...' button you pick 'Managed (CoreCLR) code'.
> > ![image](https://user-images.githubusercontent.com/1000764/43091530-2b4bf7dc-8e5f-11e8-9783-eb9bab56f501.png)
> 
> I am trying this step but i receive an invalid credential exception. what cred should i use? i tried my ms 365 account but it doesn't recognize it, i am the owner of the subscription.
I found these instructions helpful: 
https://turbo360.com/blog/remote-debugging-azure-functions-in-visual-studio-2022#:~:text=How%20to%20remote%20debug%20an%20HTTP%20trigger%20Azure,message%20to%20your%20HTTP%20trigger%20Azure%20Function%20

1. Download your Publish Profile
2. Open it in Notepad (or similar) and find the userName and userPWD fields
3. Use those in the credentials challenge

NB:// the userName will be in various formats in the file for different profile types, use the one which looks like  function-app-name\$function-app-name

**Comment by safihamid** [comment] 2024-05-20 15:01
By any chance you have Basic Auth disabled for your site?
