### ISSUE TITLE
Adding and removing a section in local.settings.json seems to break Azure Functions app targeting .NET 5

### ISSUE THREAD

**Issue by imsam67** [Azure/Azure-Functions#1938] opened 2021-06-22 22:01 UTC
This is the first time I'm creating an Azure Functions app targeting .NET 5. All my Azure Functions apps target Core 3.1 and never had this issue which is a very strange one and want to see if anyone else can replicate the issue.

I start a brand new Azure Functions app targeting .NET 5. Mine is a timer function but I don't think it matters what type of function it is.

I then add a value in my `local.settings.json` file:

```
    {
        "IsEncrypted": false,
        "Values": {
            "AzureWebJobsStorage": "MY_CONNECTION_STRING_FOR_AZURE_STORAGE",
            "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
            "MY_APP_ID": "1324"
          }
        }
    }
```
I modify the `Program.cs` to read this value:

```
var host = new HostBuilder()
   .ConfigureAppConfiguration(c =>
    {
            c.AddEnvironmentVariables();

             var config = c.Build();

             var id = config.GetValue<string>("MY_APP_ID");
     })
     .ConfigureFunctionsWorkerDefaults()
    .Build();
```

I then run the app and it seems to start up fine and looks like I'm able to read the value for `MY_APP_ID` just fine.

Then, I modify the `local.settings.json` file and add a section -- see below:

```
    {
        "IsEncrypted": false,
        "Values": {
            "AzureWebJobsStorage": "MY_CONNECTION_STRING_FOR_AZURE_STORAGE",
            "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
            "MY_APP_ID": "1324",
            "MyApp": {
                "MY_APP_ID": "1324"
            }
          }
        }
    }

```
When I try to run the app, I get the following error:
![Screenshot 2021-06-22 155521](https://user-images.githubusercontent.com/15844030/123005319-26c3d480-d373-11eb-803f-e6600ecc3816.png)

I then remove this section from my `local.settings.json` file and try running the app again and I get the same error. If I keep trying, I end up getting this error:
![Screenshot 2021-06-22 160753](https://user-images.githubusercontent.com/15844030/123005896-17915680-d374-11eb-8aa8-b9f95a389796.png)

It looks like, from this point on, there's nothing I can do to make this app run! If you noticed, I didn't change any code in my `Program.cs` file. Simply adding a section and removing it from `local.settings.json` file seems to render the app useless!

Any idea what's going on here?

**Comment by v-anvari** [comment] 2021-07-05 12:33
Hi @imsam67 , Thank you for your feedback! We will try to reproduce this further and update you with the findings.

**Comment by v-anvari** [comment] 2021-07-26 16:50
Hi @imsam67, This errors could be due to the configuration or the connection string used could be invalid. We would like to understand the startup file and the function details and do you have a timer trigger setup to run on startup. Are you debugging the startup code. Also, for .Net 5, if you have any break point setup in the startup code, then likely you may see these errors. If it is an out-of-process model, then these errors were fixed in the latest runtime.

**Comment by v-anvari** [comment] 2021-08-31 11:01
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue

**Closed by v-anvari** 2021-08-31 11:01 UTC
Labels: Needs: Author feedback
