### ISSUE TITLE
Is there any way to deploy a function to run in a Linux container/environment?

### ISSUE THREAD

**Issue by apengwin** [Azure/Azure-Functions#365] opened 2017-06-27 21:43 UTC

**Comment by ahmelsayed** [comment] 2017-06-27 21:48
Work is in progress https://github.com/Azure/Azure-Functions/issues/98#issuecomment-306361546

**Comment by apengwin** [comment] 2017-06-27 21:58
@ahmelsayed  Gotcha. Thanks!

**Comment by lindydonna** [comment] 2017-07-18 20:42
Closing as a duplicate of #98

**Closed by lindydonna** 2017-07-18 20:42 UTC
