### ISSUE TITLE
Azure Function Not Triggering by Event Hub in Consumption plan

### ISSUE THREAD

**Issue by navilwayne** [Azure/Azure-Functions#122] opened 2017-01-03 06:59 UTC
Hi Folks

- I have a Event Hub Trigger function app with consumption plan. It was working, when I open the portal in UI & continue to run for 3-4 hours , after that it automatically sleeps, when no request coming to event hub.
- Next day when request come again , it is not triggering, until I open portal.  I am facing the same issue for last 2 weeks
- In last,  I have to swap @from Consumption Plan to App Service Plan to run this.

When we can expect fix for Consumption Plan ????
@cgillum & @davidebbo 
Thanks.

**Comment by paulbatum** [comment] 2017-01-03 21:25
@navilwayne Does your connection string have an EntityPath? If so can you try removing it? We have a bug in our scale infrastructure that prevents us from reading the state of the event hub if there is an entity path present.

**Comment by navilwayne** [comment] 2017-01-04 17:06
Hi @paulbatum 
Yes, I have EntityPath in my connection string(EntityPath contains name of Event Hub)
Sample Endpoint=sb://xxxxxxxxx.servicebus.windows.net/;SharedAccessKeyName=xxxxxxx;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=;EntityPath=xxxxxxxxxxxx

**I am getting below  error if I removed entity path from connection string**  as suggested by you.
Microsoft.ServiceBus: The messaging entity 'Management operation failed. status-code: 404, status-description: The messaging entity 'sb://xxxxxxxxxxx.servicebus.windows.net/samples-workitems' could not be found..' could not be found. 
 
Session Id: c1c36cf02ce54fd89d26704d9cb57f22

 Please suggest.
Thanks.

**Comment by paulbatum** [comment] 2017-01-04 17:16
@navilwayne Did you enter the correct name of your event hub in the integrate section of the UI?

![image](https://cloud.githubusercontent.com/assets/10663/21651614/2c1011f8-d25e-11e6-91f9-177c38d2c271.png)

Alternatively if you are working from within VS or using the "advanced editor" the input binding in your  function.json should have the correct "path" property that corresponds to your event hub name:

    {
      "type": "eventHubTrigger",
      "name": "sensorEvent",
      "direction": "in",
      "connection": "EventHubsConnectionString",
      "path": "hub1",
      "consumerGroup": "$Default"
    },

**Comment by navilwayne** [comment] 2017-01-09 06:00
@paulbatum Yes It is working now. But this is finalised now that always we have to remove the entity path from connection string in event hub scenario or it is temporary fix.

In what another scenario's we have to do modification in connection string. For example in Blob or etc.

**Comment by paulbatum** [comment] 2017-01-12 18:20
@navilwayne glad to hear its working. Removing the entity path from the connection string is a temporary workaround until we fix a bug on our side. You shouldn't need to do this any other scenarios (that I'm aware of).

**Comment by sergsalo** [comment] 2017-02-01 22:18
I have the same problem - as soon as I close portal blade for function app, it stops receiving events. My connection string does not contain EntityPath. I have two Azure Functions in two different resource groups. One works and the other does not. Frustrating.

**Comment by davidebbo** [comment] 2017-02-02 00:06
@sergsalo Can you share your function app name (that's the **app** name, not function name!), either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by sergsalo** [comment] 2017-02-02 00:21
@davidebbo let me recreate it, because I started to use app service plan instead of consumption plan.

**Comment by davidebbo** [comment] 2017-02-02 00:23
Thanks. If it's a test site, then you may as well share the App Name directly, which is a bit easier.

**Comment by sergsalo** [comment] 2017-02-02 01:09
it seems like it is working after redeployment.

**Comment by davidebbo** [comment] 2017-02-02 01:12
Odd. Oh well, if you or anyone else run into this again, please give us the Function app name and we'll dig into it from our end. But as far as we know, the issue is now fixed.

**Comment by xelossan** [comment] 2017-02-17 09:21
Hi @davidebbo, I've got similar problem, but on App Service Plan (Standard S1). We've got function with Event Hub trigger, Always On is turned on in Application Settings. Everything worked fine for a couple of days, and then it stopped processing any event hub messages. After opening Function editor in portal and manually triggering the Function using Run button, it processed events and started working, but after a few hours it stopped again. The function app name is cx-in-functions.

**Comment by davidebbo** [comment] 2017-02-17 16:01
@xelossan the issue discussed here was very specific the the Consumption plan (I just clarified the title). Closing this one since we believe it is fully fixed.

Please open a separate one if you see thing in a Standard plan. Make sure to include the details we need for investigation, as discussed above (site name, function name, timeframe of incident, ...).

**Closed by davidebbo** 2017-02-17 16:01 UTC
Labels: bug

**Comment by sergsalo** [comment] 2017-03-08 07:23
@davidebbo It happens again. Consumption plan. Function name: ampbrokerhxc23nhsty2jk, appName: http://ampbrokerhxc23nhsty2jk.azurewebsites.net. 

The interval between data arrival is 5 minutes. Trigger: TriggerAzureMetrics. If I watch it - it works fine. If I leave portal - it stops working. consistent.

**Comment by davidebbo** [comment] 2017-03-08 20:55
@sergsalo I have a suspicion as to what might be going on: how are you editing your function files, and in particular function.json (which contains the triggers)? If you're doing it via App Service Editor, then it doesn't properly sync the triggers, which would explain this.

Try going to the Functions UI and clicking the Refresh button in the bottom left corner. That should get you fixed up.

**Comment by sergsalo** [comment] 2017-03-08 22:49
@davidebbo  apparently it is working now. We deploy function using ARM Template and powershell scripts to push code.  Is there API we can call to "refresh" after deploy?

**Comment by davidebbo** [comment] 2017-03-08 23:07
See [here](https://github.com/davidebbo/AzureWebsitesSamples/blob/3df2dd42025493c5a41a9fb3fb1f4c9eb0b4317a/PowerShell/HelperFunctions.ps1#L288-L291) for PowerShell / API example.

How exactly is your script pushing the code?

**Comment by sergsalo** [comment] 2017-03-08 23:16
We are pusing using Kudu API: 
Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method PUT -InFile $fileName -ContentType "multipart/form-data

**Comment by davidebbo** [comment] 2017-03-08 23:53
Ah yes, that would do it. Currently, the only deployment techniques that automatically do a sync are:

- Function Portal
- Git deployment via Kudu
- WebDeploy (e.g. VS publishing or VSTS)

I think if you integrate the PowerShell I gave you into your script, it will work reliably.

**Comment by sergsalo** [comment] 2017-03-09 00:05
cool, thank you so much for quick update!

**Comment by atinag** [comment] 2017-04-04 17:06
Will doing a restart of the app service do a Refresh or we need to explicitly do a Refresh?

**Comment by davidebbo** [comment] 2017-04-04 19:46
@atinag If you are indeed in this situation, you need to do a refresh.

**Comment by jtjk** [comment] 2017-05-05 04:30
@davidebbo, can you check our function app TrackerFunctionApp2 ?

**Comment by davidebbo** [comment] 2017-05-05 04:39
@jtjk can you also provide a sample UTC time where you expected your event hub function to get invoked and it didn't? I see you also have a timer function going every minute. Is that working?

**Comment by jtjk** [comment] 2017-05-05 04:42
@davidebbo 11:30 yesterday it was working. And it should be working all the time as we get 120 messages every hour now. 

Yesterday 11.30 we were getting millions of events and it was working until I closed portal.

**Comment by davidebbo** [comment] 2017-05-05 04:45
@jtjk So 11:30 UTC on may 3rd or 4th? Yesterday doesn't mean the same to everyone :)

**Comment by jtjk** [comment] 2017-05-05 04:47
Sorry, you must be in pacific time zone. 4th day I meant

**Comment by jtjk** [comment] 2017-05-05 04:49
@davidebbo forgot to tag

**Comment by davidebbo** [comment] 2017-05-05 04:55
I see abnormal things, but it looks like a completely different condition from anything above (which was fixed and has not been seen since). Can you open a separate issue? It's late here, so we'll try to get to it tomorrow (PST). Thanks!

**Comment by jtjk** [comment] 2017-05-05 06:35
I created issue https://github.com/Azure/Azure-Functions/issues/264 

Btw, how can I make a refresh. That button does not exist anymore or is it just my Safari that is not showing it?

**Comment by KZeronimo** [comment] 2018-02-21 20:08
@davidebbo we are seeing the event hub binding fail to trigger and we "wake" the function up by browsing the portal - we are using the newer kudo zipdeploy and VSTS deploy - any red flags here?

I can provide the function app resource via private message

**Comment by tohling** [comment] 2018-02-21 20:13
@KZeronimo, thank you for contacting us. Kindly open a new issue at https://github.com/Azure/azure-functions-host/issues and provide the information noted on https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately 

We will investigate promptly.  Thanks!

**Comment by shasdas** [comment] 2020-11-11 10:24
Function App shows unpredictable behaviors in triggering when I create and deploy IoT Hub Triggered function using Ansible.. Rest of the automation works fine..Azure Function is blocking us to become 100% automated .. very unfortunate!

**Comment by paulbatum** [comment] 2020-12-07 20:41
This issue is quite old and the underlying issue discovered at the time was fixed. Please file a new issue including the details outlined in our template if you are having problems.
