### ISSUE TITLE
Question: Azure Powershell Scripts in a Function

### ISSUE THREAD

**Issue by napalm684** [Azure/Azure-Functions#294] opened 2017-05-17 13:36 UTC
Random question, I know you can run powershell in an azure function.  Is it possible to run "azure powershell" scripts via an azure function to spin up/down infrastructure.  The question then becomes if it is possible how would one install azure powershell in the context of the azure function?  Thanks in advance, hopefully this hasn't already been asked as I couldn't find it (if it was).

**Comment by tohling** [comment] 2017-05-17 17:33
Yes, here's an SO thread that walks through how that is done.  http://stackoverflow.com/a/40883318/6465830

**Comment by napalm684** [comment] 2017-05-17 18:34
@tohling thank you for the response, it is my assumption that azure powershell is already installed for azure functions to utilize when you choose powershell as the function language?

**Comment by napalm684** [comment] 2017-05-17 19:10
Awesome thanks again!

**Comment by lindydonna** [comment] 2017-05-23 23:35
Closing issue as question was answered

**Closed by lindydonna** 2017-05-23 23:35 UTC
Labels: question

**Comment by Ilanak** [comment] 2018-01-01 13:13
@tohling  the suggested solution worked for me until last week.
Now the second import is falling:
Import-Module "D:\home\site\wwwroot\azuremodules\AzureRM.Resources.psd1" -Global;

In the Azure function itself the error message is not meaningful:
2018-01-01T13:08:40.672 Exception while executing function: Functions.extend-ownership. System.Management.Automation: Specified argument was out of the range of valid values.
Parameter name: i. System: Specified argument was out of the range of valid values.
Parameter name: i.

When trying to run the same imports in Kudo,  I get the following error:
The specified module 'AzureRM.Profile' with version '2.5.0' was not loaded because no valid module file was found in any module directory.
But on the second try to import the same module it works:
![image](https://user-images.githubusercontent.com/13463870/34467908-03c06bba-ef06-11e7-9602-fb976db5a9db.png)


Any Idea what caused this regression? and how can I fix it?

Thanks!

**Comment by mganeshphani** [comment] 2018-06-07 01:17
@tohling @napalm684 I went ahead and used this approach to import complete suite of Azure RM into Azure functions by updating $env:psmodulepath to include "D:\home\site\wwwroot\azuremodules" within azure function and reference base(azurerm) psd1 file to import... this approach seemed inevitable and simplest to use all the modules of AzureRM.
