### ISSUE TITLE
Cannot connect Python Azure Function with a Azure Redis Cache

### ISSUE THREAD

**Issue by xcsob** [Azure/Azure-Functions#1845] opened 2021-02-14 21:31 UTC
Hello, 
I'm trying to connect my Azure Functions with a Azure Redis Cache. 

The function is a TimerTrigger Azure Function written in Python and the Azure Redis Cache is on a Standard C0 Price tier. 

I'm using the official redis module in python. 

My version of Python is: 3.8.x. 

The error that I get is: 
` Error 110 connecting to xxxxx.redis.cache.windows.net:6380. Connection timed out.`

I get the error when I try to read a key from it, using: 
`r.get(key)`

Both the Azure Function and the Redis Cache are in West Europe Region. 

The Azure Functions works well on my local machine, while when I deploy it, it gives me the error above. 

Do you have any idea on how to solve this?

**Comment by balag0** [comment] 2021-02-15 03:34
What sku is the function app using? Is there any VNET involved? Does pinging the redis endpoint manually using Kudu work or is the connectivity issue intermittent?

**Comment by boscux** [comment] 2021-02-15 07:19
> What sku is the function app using? Is there any VNET involved? Does pinging the redis endpoint manually using Kudu work or is the connectivity issue intermittent?

How can I use Kudu? 
However I can connect to the Redis server with the following line of code: 
`r = redis.StrictRedis(host=myHostname, port=6380, password=myPassword, ssl=True)`

The problem is when I try to read a key using: 
`r.get(key)`

**Comment by balag0** [comment] 2021-02-15 07:28
You can access kudu using (not all skus have kudu support though)
https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=portal#kudu

Since the connectivity seems to be fine, is there a way for you to add some logging in redis to see if the get requests are even reaching there?

**Comment by boscux** [comment] 2021-02-15 07:44
> You can access kudu using (not all skus have kudu support though)
> https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=portal#kudu
> 
> Since the connectivity seems to be fine, is there a way for you to add some logging in redis to see if the get requests are even reaching there?

I don't think Redis allows you to add logs. 
Anyway I can see the request coming to Redis, as well as the connected clients.

**Comment by balag0** [comment] 2021-02-18 08:28
Thanks. Could you help understand why this is a functions issue since it looks like an application level failure on a dependent service. Is the same api working if you call it from outside a function app?

**Comment by v-anvari** [comment] 2021-06-14 12:22
Closing this issue as there is no further response, please feel free to reach back to us in case of any further queries related to this issue

**Closed by v-anvari** 2021-06-14 12:22 UTC
