### ISSUE TITLE
IoTHubTrigger function stops being triggered after a while

### ISSUE THREAD

**Issue by LevV** [Azure/Azure-Functions#1879] opened 2021-04-09 15:06 UTC
We have a C# function which processes telemetry messages at a rate of 120 messages per minute.
After a while - sometime after 15 minutes, sometimes after a couple of hours - the function stops being triggered, even though telemetry events continue hitting the hub.
Restarting the function app doesn't seem to help; the only way to get the function working again would be to add a new Consumer Group on the Hub, reference it in the function, and re-deploy it.
The typical execution graph looks like this (see attached).
The functionality doesn't seem to matter - we tried to do as little as log the number of incoming events and the problem still happens.
![Screen Shot 2021-04-09 at 11 03 53 AM](https://user-images.githubusercontent.com/9752426/114200881-a0772500-9923-11eb-9914-0aaa5f552b2e.png)

**Comment by v-bbalaiagar** [comment] 2021-04-13 16:59
Hi @LevV, Could you please provide us the invocation id to get the logs and check the cause.

**Comment by LevV** [comment] 2021-04-15 19:36
Hello @v-bbalaiagar, thanks for your prompt response. Per your request, I started logging the invocation ids and ran the function again. As you can see, the behavior is the same. Here are the invocation ids for the last couple of calls that were made:
d28126ba-98e3-4d8a-9e28-833b8bbfe82c
4bbbf5cb-bfcb-4c47-92ad-be5f22186b08
482ab61d-f035-4746-b344-73d255fac2f5
a2aada94-ce68-4db8-b3d1-2f9f16bfb4d0

I hope this helps! Looking forward to hear from you.

![Screen Shot 2021-04-15 at 3 35 48 PM](https://user-images.githubusercontent.com/9752426/114928176-4c2ae400-9e00-11eb-812d-208a667c6f76.png)

**Comment by v-bbalaiagar** [comment] 2021-04-20 10:21
Hi @LevV , We will be checking the backend logs to try and find any errors and update you with the findings shortly.

**Comment by v-bbalaiagar** [comment] 2021-04-22 12:25
Hi @LevV , We see that you are running with the default setting of logging sampling enabled for Application Insights.
If you are noticing that data is missing from your monitor logs, you may just need to adjust the sampling settings to fit your particular monitoring scenario. 
Go to App Service Editor to configure sampling. Please review [this guidance](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-sampling) 

When FUNCTIONS_WORKER_RUNTIME is configured to dotnet, function image LinuxFxVersion should be empty. Currently, we discards LinuxFxVersion and honors FUNCTIONS_WORKER_RUNTIME setting.The dotnet version is derived from FUNCTIONS_EXTENSION_VERSION and it is set to ~3.
Please go through the document here to check if your configuration is correct or not- https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=azurecli#automatic-and-manual-version-updates
  
Let us know if you are able to solve with this information.

**Comment by v-bbalaiagar** [comment] 2021-07-06 13:50
Hi @LevV , Closing this issue as the required information is provided, please feel free to re-open the issue with the latest invocation id, if at all you come across the issue in future.

**Closed by v-bbalaiagar** 2021-07-06 13:50 UTC
