### ISSUE TITLE
Long running Blob Triggered function successfully completes and then starts again for same blob

### ISSUE THREAD

**Issue by jon8884** [Azure/Azure-Functions#354] opened 2017-06-22 02:57 UTC
If you have a function that runs for a long period of time, it will trigger the blob in an infinite loop.   The function will successfully complete and then kick off again for the same blob.   As in this example there is a 10 minute delay, I'm seeing using an app service plan not the consumption model. 

Runs indefinitely in sequence:
 [FunctionName("My Function")]        
  public static void Run([BlobTrigger(....
{
     //do something
     thread.sleep(Convert.ToInt32(TimeSpan.FromMinutes(10));
}

Runs correctly once for the blob:
 [FunctionName("My Function")]        
  public static void Run([BlobTrigger(....
{
     //do something
}

**Comment by lindydonna** [comment] 2017-06-22 21:05
@brettsam Could you take a look?

**Comment by brettsam** [comment] 2017-06-22 21:11
It's this bug: https://github.com/Azure/azure-webjobs-sdk-script/issues/1600.

This has been fixed and will be in our next release. I'll update all of these linked issues when it goes out to everyone.

**Comment by brettsam** [comment] 2017-06-22 21:11
Closing this as a dupe of the other one.

**Closed by brettsam** 2017-06-22 21:11 UTC
