### ISSUE TITLE
Microsoft.WindowsAzure.Storage Version Mismatch

### ISSUE THREAD

**Issue by isaac2004** [Azure/Azure-Functions#821] opened 2018-05-24 16:28 UTC
I am building a v2 Azure Function locally and am seeing an odd issue when I debug the function. I am getting the following error when trying to do Azure Storage related tasks

> Exception while executing function: Function1. AzureMediaServicesDemo.Shared: Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file.

If I look at dependencies, WindowsAzure.Storage is version 9.1.1 referenced by Microsoft.NET Sdk.Functions

![image](https://user-images.githubusercontent.com/8878502/40498484-36e21126-5f4d-11e8-9868-e1e522b0c981.png)

However if I look at my loaded symbols, it looks like version 8.06.0.0 is being loaded

![image](https://user-images.githubusercontent.com/8878502/40498397-f36959cc-5f4c-11e8-9ac1-1b378b24d32e.png)

No idea why the newest beta of the CLI tools loads such an old version by default. Any ideas?

**Comment by mattchenderson** [comment] 2018-05-24 17:05
@ahmelsayed @fabiocav any ideas here on the CLI assembly loading?

**Comment by fabiocav** [comment] 2018-05-24 21:22
Yes. This is expected for now, until we finalize the work to decouple storage extensions from the WebJobs SDK (which is almost complete). In the meantime, Storage SDK assemblies are one of the few you're still expected to match the runtime version (which is 8.6.0). 

This restriction (like many of the other assembly version restrictions we had with other extensions) is a temporary issue and will be addressed in upcoming preview releases.

**Comment by isaac2004** [comment] 2018-06-18 14:17
@drphilgarner are you using v2 of functions? Here is a repo of it working

https://github.com/isaac2004/AzureMediaServicesDemo

**Comment by jeffhollan** [comment] 2018-06-26 00:00
Closing as by design for now - should be resolved when this issue is completed in the coming release

https://github.com/Azure/azure-webjobs-sdk/issues/1683

**Closed by jeffhollan** 2018-06-26 00:00 UTC

**Comment by fabiocav** [comment] 2018-06-26 00:03
The SDK update is complete, we're in the progress of adopting those changes into the runtime.
