### ISSUE TITLE
TimerTrigger fires when debugging from VS even if has "RunOnStartup = false"

### ISSUE THREAD

**Issue by Geims83** [Azure/Azure-Functions#949] opened 2018-09-14 07:04 UTC
As title.

VS 2017 15.8.4, Microsoft.NET.Sdk.Functions 1.0.21.

I notice that the timer object has IsPastDue = true and has past values for ScheduleStatus.Last, .LastUpdated and .Next.

**Comment by ColbyTresness** [comment] 2019-03-14 00:16
This actually isn't a VS issue, it's expected behavior when IsPastDue = true. Try setting that to false and let us know.

**Comment by ColbyTresness** [comment] 2019-06-11 00:46
Closing due to lack of customer response.

**Closed by ColbyTresness** 2019-06-11 00:46 UTC
