### ISSUE TITLE
Document use of [return: WebJobAttribute] with new VS Tooling for $return

### ISSUE THREAD

**Issue by NichUK** [Azure/Azure-Functions#326] opened 2017-06-05 16:02 UTC
None of the current documentation shows how to use the  [return: Attribute] form of WebJobs Attributes to cause the function.json file to be set up to use the $return form.
Since the new VS2017 tooling doesn't allow direct editing of the function.json file, this attribute form is important for any trigger except HttpTrigger.
If you want to write back a queue message or a blog, and especially if you want to use an async function, so cannot use an out parameter, this form is important, and should be documented.

**Comment by lindydonna** [comment] 2017-06-08 02:15
Duplicate of https://github.com/Azure/Azure-Functions/issues/321. The documentation should be published in the next few days.

In the meantime, here's an example:

```csharp
    [FunctionName("QueueOutput")]
    [return: Queue("myqueue-items")]
    public static string QueueOutput([HttpTrigger] dynamic input,  TraceWriter log)
    {
        log.Info($"C# function processed: {input.Text}");
        return input.Text;
    }
```

**Closed by lindydonna** 2017-06-08 02:15 UTC
