### ISSUE TITLE
Linux function app runtime creates wrong host-id for blob receipts when using blob trigger

### ISSUE THREAD

**Issue by altmnt** [Azure/Azure-Functions#1119] opened 2019-02-01 12:56 UTC
I am using azure functions for Linux with the blob trigger on Consumtion plan and with the runtime 2.x. After `func functionapp publish` host id is being changed. Also host id changes after some time passes. All blob receipts become invalid and all the blobs are queued again. That makes blob trigger unusable.

Some additional info can be found in my [stackoverflow](https://stackoverflow.com/questions/54458216/azure-functions-blob-trigger-use-same-receipts-for-different-host-names-and-ne) post.

**Comment by mathewc** [comment] 2019-02-02 01:12
Closing this as a dupe of https://github.com/Azure/azure-functions-core-tools/issues/1012. Let's just track this in one place :)

**Closed by mathewc** 2019-02-02 01:12 UTC
