### ISSUE TITLE
"A ScriptHost error has occurred" error on empty TimerTrigger Function

### ISSUE THREAD

**Issue by davidgouge** [Azure/Azure-Functions#139] opened 2017-01-12 11:09 UTC
Hi,

Visual Studio 2015 Update 3, Windows 10, CLI tools up to date.
Steps to reproduce:
New Azure Functions Project
Add New Azure Function
Select TimerTrigger
Click Create
Right click project, Debug, Start New Instance.

This is the result I get every time:

> Listening on http://localhost:7071/
> Hit CTRL-C to exit...
> Reading host configuration file 'C:\Users\***\OneDrive\Documents\Visual Studio 2015\Projects\FerFecksSake\TestingAgain\host.json'
> Generating 1 job function(s)
> Starting Host (HostId=*****-testingagain, Version=1.0.0.0, ProcessId=5240, Debug=True)
> Found the following functions:
> Host.Functions.TimerTriggerCSharp
> 
> A ScriptHost error has occurred
> Stopping Host

Other triggers such as HTTP and ServiceBus are working fine.

**Comment by skalinets** [comment] 2017-01-13 10:16
I am getting the same issue in command line with empty timer-trigger function

**Comment by slideep** [comment] 2017-01-17 13:37
Ditto, running locally getting the same (CLI tools 1.0.0-beta.9) and on Azure function is running and triggering happily.

**Comment by lindydonna** [comment] 2017-01-18 00:26
It looks like an issue with a bad error message (and documentation that needs to be improved). For all triggers except for HTTP, you need to set a value for AzureWebJobsStorage in appsettings.json. 

We'll make this more streamlined and less error-prone in the future. Here's a video demo that shows some of the manual steps: https://channel9.msdn.com/Shows/Tuesdays-With-Corey/Tuesdays-with-Corey-Coolness-of-Visual-Studio-Azure-Functions-Tools

**Comment by lindydonna** [comment] 2017-01-18 00:27
Possible duplicate of https://github.com/Azure/azure-functions-cli/issues/6

**Comment by slideep** [comment] 2017-01-18 11:50
That did the trick: for local development I added the key-value pairs for 'AzureWebJobsDashboard' & 'AzureWebJobsStorage' props and CLI host is running locally again like a charm.

**Comment by lindydonna** [comment] 2017-01-18 18:30
Closing as a duplicate of https://github.com/Azure/azure-functions-cli/issues/6

**Closed by lindydonna** 2017-01-18 18:30 UTC
Labels: CLI, duplicate

**Comment by vanhuynhnguyen2001140321** [comment] 2021-07-13 03:16
Hi , i have a problem with Host, i tried some ways, but the problem is not solved. I was created a sample project on Visual 2019 and run it, but there is a problem about Host as shown in the picture below. Please any one help me resolved this problem? Thanks.
![image](https://user-images.githubusercontent.com/38435142/125384612-622a4f80-e3c3-11eb-8fdf-ccc83024083d.png)
![image](https://user-images.githubusercontent.com/38435142/125384619-66566d00-e3c3-11eb-8547-4394277c6201.png)
