### ISSUE TITLE
EventHub - Functions inconsistently being triggered on receipt of message

### ISSUE THREAD

**Issue by darryncurranHP** [Azure/Azure-Functions#1640] opened 2020-06-24 10:43 UTC
I'm seeing the issue as defined here that was apparently fixed: https://github.com/Azure/Azure-Functions/issues/230
and is the same as seen here: https://github.com/Azure/Azure-Functions/issues/220 and https://github.com/Azure/Azure-Functions/issues/122

As part of a testing pipeline I'm bringing up an eventhub and functionapp using Terraform, and then POSTing a message to the eventhub during a validation step.
On receipt of an event to the EventHub, the functionapp is supposed to trigger, but as per the linked issue I'm not seeing this be the case 100% of the time.

I've seen sporadic failures, where I've verified the EventHub has received the message, but the functionapp hasn't triggered, and doesn't until I visit the blade in the portal.

FYI I'm also using a non default consumer group and running a consumption plan

**Comment by grik001** [comment] 2020-06-24 19:46
Hi Darry, by any chance are you experiencing delays or even data not being read from EH by your function. I am positive I am sending data to EH but my functions are not firing. I have tried redeploying, restarting and stopping but nothing seems to work. The works part is that I am not getting any errors.

**Comment by darryncurranHP** [comment] 2020-06-25 08:10
@grik001 Yeah that's exactly what I'm seeing but it's not consistent, and maybe only happens 10% of the time.

**Comment by shasdas** [comment] 2020-11-11 10:25
Function App shows unpredictable behaviors in triggering when I create and deploy IoT Hub Triggered function using Ansible.. Rest of the automation works fine..Azure Function is blocking us to become 100% automated .. very unfortunate!

**Comment by v-anvari** [comment] 2021-08-18 11:50
Hi @darryncurranHP , Apologies for the delayed response. Were you able find a solution? do let us know if the issue is still existing

**Comment by v-anvari** [comment] 2021-10-04 10:54
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue

**Closed by v-anvari** 2021-10-04 10:54 UTC
Labels: Needs: Author feedback
