### ISSUE TITLE
Azure Function V3 Local Testing

### ISSUE THREAD

**Issue by fleming-barry** [Azure/Azure-Functions#1695] opened 2020-08-20 17:17 UTC
I am trying to locally test service bus trigger. I keep getting the following error _System.Private.CoreLib: Exception while executing function: TestTransaction. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'message'. Microsoft.Azure.ServiceBus: Operation is not valid due to the current state of the object.

I am using Azure Functions V3 and .netcore 3.1
I am using the following DLLs
`Microsoft.Azure.Functions.Extensions Version=1.0.0
Microsoft.Azure.KeyVault Version=3.0.5
Microsoft.Azure.ServiceBus Version=4.1.3
Microsoft.Azure.Services.AppAuthentication Version=1.5.0
Microsoft.Azure.WebJobs.Extensions.ServiceBus Version=4.1.2
Microsoft.Azure.WebJobs.Host.Storage Version=4.0.1
Microsoft.Extensions.Configuration.Json Version=3.1.7
Microsoft.Extensions.Http Version=3.1.7
Microsoft.NET.Sdk.Functions Version=3.0.9
Microsoft.NETCore.Platforms Version=3.1.2
Swashbuckle.AspNetCore.AzureFunctions Version=2.0.5
`

I see the exception occurring around line 70. In the class Microsoft.Azure.WebJobs.Host.Bindings.BindingDataProvider.

**Comment by codebrane** [comment] 2021-04-28 08:16
still an issue.

System.Private.CoreLib: Exception while executing function: DLQTest. Microsoft.Azure.WebJobs.Host:
One or more errors occurred. (Exception binding parameter 'message') (Exception binding parameter 'messageReceiver').
Exception binding parameter 'message'. Microsoft.Azure.ServiceBus: Operation is not valid due to the current state of the object.

works with string instead of Message

**Comment by v-bbalaiagar** [comment] 2021-06-22 11:37
Hi @fleming-barry / @codebrane , Could you please provide us the repro steps to clone the issue and get the error.

**Comment by dnaren** [comment] 2021-07-12 14:08
Steps to reproduce:
1. Create a brand new Azure Functions project (netcoreapp3.1 & v3 runtime)
2. Add nuget - Microsoft.Azure.WebJobs.Extensions.ServiceBus v4.3
3. Add a ServiceBusTrigger function that binds Message parameter, like below
[FunctionName("SayHello")]
public async Task Run([ServiceBusTrigger("topicName", "subscription", Connection = "ConnectionName")] **Message queueItem**)
4. Run the function
5. HTTP POST a request to http://localhost:7071/admin/functions/SayHello with a request body as below
{
"input":"{\"message\":\"hello\"}"
}

Expected: The message should be picked up by the ServiceBus trigger function

Actual: Just as @fleming-barry posted above

**Comment by v-bbalaiagar** [comment] 2021-07-13 12:21
Hi @dnaren, Thank you for the repro steps, we will reproduce this issue and update as appropriate.

**Comment by codebrane** [comment] 2021-07-22 13:01
Using `Message message` instead of `string message` locally results in the following error with the above input:

`Exception binding parameter 'message'. Microsoft.Azure.ServiceBus: Operation is not valid due to the current state of the object.`

**Comment by v-bbalaiagar** [comment] 2021-08-24 10:37
Closing this issue as document issue is opened here - https://github.com/MicrosoftDocs/azure-docs/issues/80122

**Closed by v-bbalaiagar** 2021-08-24 10:37 UTC

**Comment by DannyvdSluijs** [comment] 2021-11-29 19:29
This issue exactly describes the challenge I'm running into. I'm trying to locally test a ServiceBus triggered function using the described `admin/functions` approach as described on https://docs.microsoft.com/en-us/azure/azure-functions/functions-manually-run-non-http 

Following the new issue cross-posted by @v-bbalaiagar it goes into the Azure Docs repo which was closed by @mike-urnun-msft as no documentation link was included. So there is no answer or resolution from the repository maintainers.

Trying to read more on the matter there is very little to find. The docs of Microsoft describe the message can either be: `string`, `byte[]`, A custom type, `BrokeredMessage` or a `MessageReceiver`. 
Where version 2.x and higher should use `Message` instead of `BrokeredMessage`
And for version 5.x and high it should use the `ServiceBusReceivedMessage` instead of the `Message`
See https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#usage to see the official docs.

Given that I'm using Masstransit as the message processor I need the `Message` type to pass it to the MassTransit receiver (See the [Masstransit Azure Function example](https://github.com/MassTransit/Sample-AzureFunction/blob/master/src/Sample.AzureFunction/SubmitOrderFunctions.cs#L24) src for details) and not any of th scalar values. From the official [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#message-metadata) I can see you can bind these to you function but in order to get the complete message the lines of code would increase and the first step would be to build an instance of the `Message` using the function arguments.

What I've tried to do is (and had no result so far):
- Simple JSON with a `message` key and string as value
- Simple JSON with an `input` key and string as value
- Complex JSON of a serialised object as the complete body
- Complex JSON of a serialised object as value to a `input` key

So I guess the question comes down to: How can we test a non-http azure function locally using the `Message` (or `ServiceBusReceivedMessage`) type. If it isn't possible that is sad but then it should be added to the docs to make this clearer for everyone.

Hope this provides a bit more info on the subject and results in an outcome in the near future
