### ISSUE TITLE
Route param is bound to custom payload type

### ISSUE THREAD

**Issue by Sti2nd** [Azure/Azure-Functions#1978] opened 2021-07-20 09:36 UTC
I am seeing some undocumented behaviour. I am doing a request `PUT /api/users/+4444444444` with payload

```json
{
   "userName": "Stian Jørgensrud"
}
```

I have a User class that looks like this

```c#
public class User {
    public string UserName { get; set; }
    public string UserId { get; set; }
}
```

and somehow, the route parameter finds its way into the User object 🤔 
![image](https://user-images.githubusercontent.com/6373430/126297966-6db01834-b65f-4701-b156-5bc4b3287832.png)

I swear I am not sending in the `userId` from Postman:
![image](https://user-images.githubusercontent.com/6373430/126298408-8bbc2a50-0b6e-4fb2-bae9-da47640dbb13.png)
![image](https://user-images.githubusercontent.com/6373430/126298635-2b76ce26-6baa-4e77-8ac8-67839d97ead6.png)

The only documentation I can find which is close to this behavior is [Using route parameters](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=csharp#using-route-parameters), but that is using JSON and using a template form I believe.

What is happening in my case?

```xml
<TargetFramework>netcoreapp3.1</TargetFramework>
<AzureFunctionsVersion>v3</AzureFunctionsVersion>
<LangVersion>Latest</LangVersion>
```

**Comment by v-anvari** [comment] 2021-07-20 15:58
Hi @Sti2nd , Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-anvari** [comment] 2021-07-26 10:12
Hi @Sti2nd , I tried to reproduce it normally by passing the userID in the route parameter. But, I am unable to reproduce your scenario exactly. Can you give me the repro steps and the code that you are using.

**Comment by Sti2nd** [comment] 2021-07-27 20:20
Hi @v-anvari ,
Here is a minimal code example in which I can reproduce: https://github.com/Sti2nd/Reproduce1978

```c#
[FunctionName("Function1")]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "users/{userId}")] User user,
    ILogger log)
{
    return new OkObjectResult(user);
}
```

The code simply takes in a User object and returns the same object. And even if one don't send in `userId` in the user object, `userId` magically appears in the returned object 😄

When I send the following request:
![image](https://user-images.githubusercontent.com/6373430/127221239-75374e29-463f-42bc-a354-3eb84a5a2e72.png)
I get the following user object back:

```json
{
    "userName": "Stian Jørgensrud",
    "userId": "4444444444"
}
```

Hopefully you can reproduce by checking out the repository. Just ask if there are any questions about my setup.

**Comment by v-anvari** [comment] 2021-08-03 13:14
Hi @Sti2nd , Apologies for the delayed response. I was able to reproduce the issue and I think the issue is here. 

Since you are mentioning userId in the user class. 

namespace Reproduce1978
{
    public class User
    {
        public string UserName { get; set; }
        public string UserId { get; set; }
    }
}

And when you return the User from the class like the below. The output is userName and UserID that you passing in the user class. 
![image](https://user-images.githubusercontent.com/66122429/128021101-c4c9c60a-9939-49fc-9d8b-b4a4e1f9a698.png)

If you remove UserId from the user class, The output will be only the UserName.
public class User
    {
        public string UserName { get; set; }
        //public string UserId { get; set; }
    }

![image](https://user-images.githubusercontent.com/66122429/128021399-c6d5ea54-1340-4300-8663-a1e9a8017570.png)

**Comment by Sti2nd** [comment] 2021-08-03 14:48
Glad that you could reproduce @v-anvari . That which you could reproduce should **not** be happening! 
This bug should preferably be fixed, or less preferably call it a feature and document it.

Either way, **something** needs to be done on your side. 
Removing the properties that clash with the route parameters (in this case `UserId`) is not a solution. It can be a [workaround](https://en.wikipedia.org/wiki/Workaround), and in that case we are working around a bug.

Since you have reproduced, we now know it is a bug in Azure Functions.

**Comment by v-bbalaiagar** [comment] 2021-08-12 16:57
Hi @Sti2nd, Apologies for the delayed response, This is expected behavior. The both of those properties you get hydrated form what is called binding data. so the way this works is that ultimately binding data will contain two properties, one named the username and another named user ID. Username comes from the body payload, the body content, and user ID comes from the route in this case, binding data is used to hydrate the Poco due to hydrate, so this currently by design.

**Comment by Sti2nd** [comment] 2021-08-12 18:11
Interesting! Can you point me to where in the documentation hydration is explained?

I couldn't understand from the current documentation that my route parameters can flow into my custom types.

**Comment by v-bbalaiagar** [comment] 2021-08-16 17:18
Hi @Sti2nd, It is not documented and this is the expected behavior.

Closing this issue as this is currently by design, please feel free to reach back to us in case of any further queries related to this issue.

**Closed by v-bbalaiagar** 2021-08-16 17:18 UTC
Labels: Needs: Author feedback
