### ISSUE TITLE
Azure Functions V3 won't run using .NET 5 on Visual Studio

### ISSUE THREAD

**Issue by o-k-a-y** [Azure/Azure-Functions#1883] opened 2021-04-15 14:06 UTC
# Error message:
```
System.UriFormatException: 'Invalid URI: The hostname could not be parsed'.
This exception was originally thrown at this call stack: Company.Function.Program.Main() in Program.cs
```

# Steps to reproduce:
1. Create .NET Azure Function using func cli or vscode extension
2. Run it in Visual Studio 2019
3. It will fail on host.run() saying it can't parse the URI

I tried running both with Azurite running on default ports, Azure Storage emulator, and not running either at all.

# Environment details:
Windows 10 newest release
Visual Studio 2019 Community newest release
- Azure Development workload installed

# Code used:
## Progam.cs
```cs
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Azure.Functions.Worker.Configuration;

namespace Company.Function
{
    public class Program
    {
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .Build();

            host.Run(); // exception thrown here
        }
    }
}
```
## QueueTriggerCSharp1.cs
```cs
using System;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;

namespace Company.Function
{
    public static class QueueTriggerCSharp1
    {
        [Function("QueueTriggerCSharp1")]
        public static void Run([QueueTrigger("myqueue-items", Connection = "LocalConnection")] string myQueueItem,
            FunctionContext context)
        {
            var logger = context.GetLogger("QueueTriggerCSharp1");
            logger.LogInformation($"C# Queue trigger function processed: {myQueueItem}");
        }
    }
}
```
## local.settings.json
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "LocalConnection": "UseDevelopmentStorage=true"
  }
}
```
## .csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by v-anvari** [comment] 2021-04-21 17:09
Hi @o-k-a-y , In the above scenario, you are using the local emulator for passing the queue message. If you are using the local emulator, then using "[AzureWebJobsStorage](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsstorage)" as a connection is the way. 

Missing value for AzureWebJobsStorage in local.settings.json. **This is required for all triggers other than HTTP**. You can run 'func azure functionapp fetch-app-settings <functionAppName>' or specify a connection string in [local.settings.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#local-settings-file).

If you are using version 5.x or higher of the extension, instead of a connection string, you can provide a reference to a configuration section which defines the connection. See [Connections](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#connections). 

I am using the Azure storage emulator, Visual studio and Func Cli to reproduce it. I reproduced the above scenario you have mentioned, and my function App ran successfully. 

     _public static void Run([QueueTrigger("myqueue-items", Connection = "AzureWebJobsStorage")]_ 

In your scenario, I dint find anywhere that you are parsing the URI. 

Using a "Service URI"

![image](https://user-images.githubusercontent.com/66122429/115592247-9cb6ab80-a2f0-11eb-9925-24976e63d91c.png)

**Comment by o-k-a-y** [comment] 2021-04-23 21:59
I am currently running locally, but using "AzureWebJobsStorage" as the connection string also fails. 

Can I ask what version of Visual Studio you're using and if you're using Azurite as the local storage emulator or something else?

**Comment by rbonestell** [comment] 2021-04-25 18:12
I'm experiencing identical symptoms, only using `ServiceBusTrigger` instead of `QueueTrigger`.

I have tried many solutions, and ultimately ended up completely removing the connection string from my local.settings.json file only to run into the _same_ issue still, after expecting it to throw an exception that it couldn't find the connection string.

My Azure function Run method:
```
[Function("ImporterWorkerFunction")]
public async void Run([ServiceBusTrigger("queueName", Connection = "ServiceBusConnectionString")] string queueItem, FunctionContext context)
```

Regardless of whether or not the following values exist in the local.settings.json file, I keep getting `System.UriFormatException: 'Invalid URI: The hostname could not be parsed'.` thrown from `host.Run()`.

Attempted setting names to use for the connection string:
- `AzureWebJobsServiceBus`
- `ServiceBusConnectionString`
- `AzureWebJobsServiceBusConnectionString`

The above options were derived from info found here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#configuration

> If the app setting name begins with "AzureWebJobs", you can specify only the remainder of the name. For example, if you set connection to "MyServiceBus", the Functions runtime looks for an app setting that is named "AzureWebJobsMyServiceBus". If you leave connection empty, the Functions runtime uses the default Service Bus connection string in the app setting that is named "AzureWebJobsServiceBus".

### Development environment info

Visual Studio: Visual Studio for Mac 8.9.7
OS: macOS 11.2.2

local.settings.json file:
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "AzureWebJobsServiceBusConnectionString": "Endpoint=sb://redacted.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=redacted"
  }
}
```

Project file:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<TargetFramework>net5.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<AzureFunctionsVersion>v3</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.5" />
		<PackageReference Include="CsvHelper" Version="27.0.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
		<PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
		<PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
	</ItemGroup>
	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="local.settings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
</Project>
```

**Comment by rbonestell** [comment] 2021-04-25 19:13
Shortly after my posting I found a resolution to my problem, perhaps this will work for you too @o-k-a-y!

I hadn't noticed there were pending Nuget package updates, so I checked and updated `Microsoft.Azure.Functions.Worker` to version 1.2.0 and the issue disappeared!

**Comment by v-anvari** [comment] 2021-04-26 07:19
Hi @o-k-a-y , I am using the visual studio version 19 and the cloud explorer as the local storage emulator. Can I know what are the packages you are using

**Comment by o-k-a-y** [comment] 2021-04-27 16:59
> Shortly after my posting I found a resolution to my problem, perhaps this will work for you too @o-k-a-y!
> 
> I hadn't noticed there were pending Nuget package updates, so I checked and updated `Microsoft.Azure.Functions.Worker` to version 1.2.0 and the issue disappeared!

I updated `Microsoft.Azure.Functions.Worker` to version 1.2.0 and `Microsoft.Azure.Functions.Worker.Sdk` to version 1.0.2 and now it's able to run

**Comment by v-anvari** [comment] 2021-04-27 17:10
Closing issue as resolved.

**Closed by v-anvari** 2021-04-27 17:10 UTC
Labels: Needs: Author feedback

**Comment by chandsalam1108** [comment] 2021-08-03 08:31
I'm getting following error. Please help.

**System.InvalidOperationException: 'The gRPC channel URI 'http://:0' could not be parsed.'**

Program.cs

`public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureServices(s =>
                {
                    s.AddPooledDbContextFactory<HealthCenterContext>(db => db.UseSqlServer(Environment.GetEnvironmentVariable("MRD_SqlConnectionString")));

                    s.AddSingleton<GraphQLAzureFunctionsExecutorProxyV12>();

                    s.AddGraphQLServer()
                    .AddQueryType<Query>()
                    .AddProjections()
                    .AddFiltering()
                    .AddSorting()
                    .ModifyRequestOptions(opt => opt.IncludeExceptionDetails = true);

                }).Build();

            host.Run(); //Error occurred here...
        }`

Project File:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>    
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.4.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="GraphQL.Server.Ui.Voyager" Version="4.4.1" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="11.3.0" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="11.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.7" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

Stack Trace:

   `at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.<>c.<AddGrpc>b__1_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 64
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at HealthCenterFx.Program.Main() in C:\PHCCWorks\NaraakomV2\HealthCenterFx\Program.cs:line 30`

VS 2019 Enterprise 16.10.4
.Net Version: 5.0.302
OS: Windows 10 64 bit

**Comment by v-anvari** [comment] 2021-08-03 10:31
Hi @chandsalam1108 , Please submit a new issue with all the required details in the form so that one of our engineering team could take up and work on it.

**Comment by chandsalam1108** [comment] 2021-08-03 10:35
Hi Anvari, Submitted a new issue # 2005. Thank you.

**Comment by wwjn** [comment] 2021-08-20 07:42
#2005

**Comment by tjmcdonough** [comment] 2021-11-07 10:13
For me, it was because I didn't have the Azure Toolkit for Rider installed. Install this as a plugin and you will be good to go.

**Comment by yeasin90** [comment] 2021-11-23 08:46
For my case, once I set the `IConfiguration` from `ConfigureAppConfiguration` middleware, the exception is gone

```
public static void Main()
{
    var host = new HostBuilder()
                    .ConfigureFunctionsWorkerDefaults()
                    .ConfigureAppConfiguration(config =>
                    {
                        config.SetBasePath(Directory.GetCurrentDirectory())
                            .AddJsonFile("AppSettings.json", false, true)
                            .AddJsonFile(
                                $"AppSettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json",
                                true)
                            .AddEnvironmentVariables();
                    })
                    .ConfigureServices(services =>
                    {
                        
                    })
                    .UseDefaultServiceProvider(options => options.ValidateScopes = false)
                    .Build();

            host.Run();
}
```

**Comment by kan-nan-k** [comment] 2022-03-07 09:12
I had a similar issue, my root cause was different, I did not install Azure development tools during initial setup, after installation it worked. Hope it helps someone. 

![image](https://user-images.githubusercontent.com/74256356/157001331-c05dee78-a7cd-4b45-bd7a-4230219255fa.png)

**Comment by jwoodall** [comment] 2022-05-03 15:50
Even though the Azure documentation says that the Azure tools are installed by default in Visual Studio, I found the same issue as kan-nan-k I had to use the installer to install Azure development module
