### ISSUE TITLE
How to start processing from a specific record using Cosmos DB trigger

### ISSUE THREAD

**Issue by baharedankoyuncu** [Azure/Azure-Functions#1889] opened 2021-04-29 09:25 UTC
Hi,

The Azure Functions Cosmos DB trigger has a property `StartFromBeginning` which enables us to control whether the change feed should start from the beginning.

However, what is the recommendation for cases where you don't want to start from the beginning but a certain point in time or from a certain record and forward?

I couldn't find any issues being tracked but is this in the pipeline or are there alternatives? Any recommendations would be appreciated.

FYI we are using Azure Functions running on .NET 5.

**Comment by v-anvari** [comment] 2021-05-03 16:56
Hi @baharedankoyuncu , There is no design as of now which can support this scenario, but flagging this to feature require for future support

**Comment by ealsur** [comment] 2021-05-03 17:10
@baharedankoyuncu There is only support for a certain point in time, it was added in https://github.com/Azure/azure-webjobs-sdk-extensions/pull/691

There is no support (and it's not possible because it is not supported by the backend) to specify a record.

**Comment by baharedankoyuncu** [comment] 2021-05-03 17:58
Hi @v-anvari  & @ealsur,

Thank you, I hadn't noticed that was available, couldn't seem to find anything in the docs about it https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?tabs=csharp#configuration.

This is at least a good alternative to `StartFromBeginning`.

Appreciate your help.

**Comment by v-anvari** [comment] 2021-05-04 13:08
Thank you @ealsur for confirming the support

Closing this issue as it is by design

**Closed** 2021-05-04 13:08 UTC
Labels: feature
