### ISSUE TITLE
Azure Function storage -

### ISSUE THREAD

**Issue by skorunka** [Azure/Azure-Functions#207] opened 2017-03-09 16:54 UTC
Can I share one Azure Storage Account with a two different Azure Function containers?

here I have two Azure Function containers:
![image](https://cloud.githubusercontent.com/assets/218913/23760774/9d983cf8-04e8-11e7-8999-72bdae287089.png)

And they share a one storage account:
![image](https://cloud.githubusercontent.com/assets/218913/23760803/b1631802-04e8-11e7-85ed-65ce1c163d12.png)

The functions inside the function containers are identical, except the configuration. One is for INT the other for QA. Currently I'm experiencing some issue where a TimeTriggered function is only execute in one container(INT) and not in the (QA). And i can also see the log of INT inside the QA function container.

Is it because of the sharing the  same storage account between the both containers?

**Comment by lindydonna** [comment] 2017-03-10 19:04
@skorunka You can share storage accounts between Function Apps, but if you use the same host ID, the timer will only trigger in one (by design). See https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger. 

We need to improve our documentation around this, I've created this issue to track: https://github.com/Azure/Azure-Functions/issues/209

**Comment by lindydonna** [comment] 2017-03-10 19:05
Closing this issue. Please reopen if changing the host ID doesn't fix the problem.

**Closed by lindydonna** 2017-03-10 19:05 UTC

**Comment by lindydonna** [comment] 2017-03-14 01:34
@skorunka: Could you provide information on why you were explicitly setting a host ID in host.json?  Is it because you used the Visual Studio tooling and the Azure Functions CLI?

The right pattern for your scenario is to not specify the host ID, as the Functions runtime will just use the site name as the host ID. Unfortunately, there's currently a limitation in the Functions CLI where it has to set the host ID in host.json. It's being tracked by this bug: https://github.com/Azure/azure-functions-cli/issues/86

**Comment by skorunka** [comment] 2017-03-16 09:17
@lindydonna yes, the VS has automatically generated and set the ID in host.json file. I did not know the ID needs to be different, now it makes sense. Thank you.

**Comment by GiuseppePiscopo** [comment] 2017-10-06 18:02
Hi all, sorry for diverting this (closed) issue. I could not find info about this elsewhere, so here we go:

can code from an Azure Function access that Storage account, specifically the Files Storage found within that. Also, more specifically, can code write+save a file in there?

[This tiny post](http://www.c-sharpcorner.com/article/explore-storage-account-of-azure-functions-file-share/) shows contents of that File share, with `data`, `LogFiles` and `site` folders, but pretty much that's it. It doesn't mention whether you can bind to that storage, and how.

Thanks

**Comment by lindydonna** [comment] 2017-10-06 18:08
@GiuseppePiscopo Please open a new issue in the future. Your wwwroot directory in Functions is actually your Azure files share. You don't need to do anything special to bind to it, just use regular file APIs.

**Comment by GiuseppePiscopo** [comment] 2017-10-06 19:05
Thanks for quick reply and for pointing that out. I was looking for a share which could be then mounted from another machine too.

Il giorno 6 Ott 2017 20:08, alle ore 20:08, Donna Malayeri <notifications@github.com> ha scritto:
