### ISSUE TITLE
How to Migrate from Consumption Plan to App Service Plan (and vice versa)

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#153] opened 2017-01-18 18:32 UTC
See main issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/1010

**Comment by lindydonna** [comment] 2017-01-19 21:31
I moved the original issue to this repo, closing as a duplicate of #155

**Closed by lindydonna** 2017-01-19 21:31 UTC
