### ISSUE TITLE
Function App is not running, why?

### ISSUE THREAD

**Issue by aymanhendawy** [Azure/Azure-Functions#578] opened 2017-11-05 11:56 UTC
After I keep getting those below error messages on my function app
URL
https://butterflyfnapp.azurewebsites.net
App Service plan / pricing tier
WestEuropePlan (Consumption)

Error:
We are not able to get the key swaggerdocumentationkey. Please check the runtime logs for any errors or try again later.
Session Id: 961d6b971f9b4b09be2132de359a6cdd
Timestamp: 2017-11-05T11:55:06.737Z

Error:
Host Error: Microsoft.Azure.WebJobs.Script: Host thresholds exceeded: [Connections].
Session Id: 961d6b971f9b4b09be2132de359a6cdd
Timestamp: 2017-11-05T11:55:08.537Z

I deleted it an created a new one with the same name 
URL
https://butteryflyfnapp.azurewebsites.net
App Service plan / pricing tier
butteryflyfnserviceplan (Standard)  -S2 standard -

but it's not being triggered, I don't know why? messages are received by my iothub, and delivered to Fns, but nothing happened.

Thanks

**Comment by aymanhendawy** [comment] 2017-11-05 13:54
keep getting bunch of error messages like,

Error:
We are not able to retrieve the runtime master key. Please try again later.
Session Id: f127ff3f5f414a4fa5acc1889edb2c05
Timestamp: 2017-11-05T13:53:02.553Z

**Comment by ahamfelt** [comment] 2017-11-06 12:53
+1 get the same massages here... restarting my function and it works for an hour or so but then the messages comes back.

**Comment by cgillum** [comment] 2017-11-06 23:55
The most important error message seems to be this one:

```
Host Error: Microsoft.Azure.WebJobs.Script: Host thresholds exceeded: [Connections].
```

See the discussion related to this here: https://stackoverflow.com/questions/47082856/azure-function-app-in-powershell-generating-host-threshold-exceeded-errors.

In summary, this error message means your function code is exceeding the network socket limit that is placed on a function app. It is not normal that anyone's code will hit this limit unless there is some kind of TCP connection leak. I would suggest looking through your code and checking to see whether all connection-related resources are being properly closed after use.

**Comment by ahamfelt** [comment] 2017-11-07 07:43
@cgillum has that limit changed or anything? 
My function app has been in production for around 6 months and this messages started coming in the past two days.

**Comment by cgillum** [comment] 2017-11-07 17:33
Yes, I believe this was changed as part of this release a few days ago: https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.11351. The underlying issue it was intended to fix is https://github.com/Azure/azure-webjobs-sdk-script/issues/1999.

@mathewc can probably comment further.

**Comment by aberthier** [comment] 2017-11-08 02:28
Hi There,

We ran into a similar issue and we might have solved it today.
In our case, the azure function is integrated to a queue and dispatches messages to a mongodb instance.
It seems that after the end of the execution, the functions keep the tcp connections open toward mongodb if they are not closed explicitly.

We did change our code to explicitly close the mongo connections and so far we did notice that the amount of connection on the mongodb monitoring is way lower and stable. No idea how to check the amount of tcp connections open on the Azure side.

We did log a premium support ticket with Azure and the only help we got was a suggestion to move to an app service plan for better troubleshooting (obviously with a way higher resource cost, bye 1M free executions).

Hope it helps

**Comment by ahamfelt** [comment] 2017-11-09 07:40
Maybe there's been an update again? 
My functions has been running with no errors for the past two days now (hopefully not jinx it now), and I didn't change anything about them.

**Comment by aymanhendawy** [comment] 2017-11-09 09:18
Still by function with s2 standard service plan throwing those errors,


0down votefavorite | My Azure Function App "butteryflyfnapp" URL https://butteryflyfnapp.azurewebsites.net App Service plan / pricing tier butteryflyfnserviceplan (Standard)Keep throwing the below errors, why?Error:We are not able to get the key swaggerdocumentationkey. Please check the runtime logs for any errors or try again later. Session Id: 1cd3f82f0430463c852c1ff04cfc094fTimestamp: 2017-11-09T08:59:19.954ZError:We are not able to retrieve the runtime master key. Please try again later. Session Id: 1cd3f82f0430463c852c1ff04cfc094fTimestamp: 2017-11-09T08:59:29.698ZAnd my function "Nodes_Current_State_Report_Fn_App" of "butteryflyfnapp" log output as following,<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD> <BODY><h2>Service Unavailable</h2> <hr><p>HTTP Error 503. The service is unavailable.</p> </BODY></HTML> <HTML><HEAD><TITLE>Service Unavailable</TITLE> <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD> <BODY><h2>Service Unavailable</h2> <hr><p>HTTP Error 503. The service is unavailable.</p> </BODY></HTML>
-- | --

**Comment by cgillum** [comment] 2017-11-09 19:15
@aymanhendawy I am noticing that your function app is failing with the following exception. You may be able to see this as well if you enable Application Insights integration:

```
System.InvalidOperationException : Host thresholds exceeded: [Connections]
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.IsHostHealthy(Boolean throwWhenUnhealthy) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 484
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.OnHostStarting() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 396
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 153
```

This means the functions host has detected a connection leak and has recycled your function app to restore it back into working behavior.  By chance is your function code making network calls and not closing connections?

**Comment by ahmelsayed** [comment] 2017-11-13 21:20
A fix for an issue that caused a similar error to be logged was pushed today to all regions. Can you restart your app and try again?. I'll close this issue, but feel free to reopen it if you're still broken 

/cc @mathewc @paulbatum

**Closed by ahmelsayed** 2017-11-13 21:20 UTC
