### ISSUE TITLE
Netcoreapp2.0 functions are not being detected by the runtime

### ISSUE THREAD

**Issue by mmisztal1980** [Azure/Azure-Functions#598] opened 2017-11-18 21:08 UTC
Using VS 2017 15.4.4 I've created a functions project.
I've changed it's framework type to **netcoreapp2.0** and added a QueueTriggered function.

![image](https://user-images.githubusercontent.com/1357057/32984766-0ea4c9f2-ccad-11e7-84e7-4150000d098d.png)

I've started the function project and noticed that the runtime failed to detect the function.
I've examined my solution and noticed that I seem to have a nuget restore error:

![image](https://user-images.githubusercontent.com/1357057/32984749-b1efedb8-ccac-11e7-946e-681047a6f40f.png)

Please advise whether its possible to work around this issue.
Please note that I'm having the same issue with Microsoft.Net.Sdk.Functions 1.0.5. 
The function project is unusable.

**Comment by mmisztal1980** [comment] 2017-11-20 23:19
Anyone?

**Comment by jeffhollan** [comment] 2017-11-21 06:36
The Nuget Restore error here likely [isn't the cause of your issues](https://stackoverflow.com/questions/47320863/azure-function-targeting-net-standard-showing-warning) but I'm not sure on if you can take a v1 Function Project and upgrade to v2 (netcoreapp2.0) just by updating target framework - believe their are differences in the project template as well.

Are you able to use the [new VS tools](https://blogs.msdn.microsoft.com/webdev/2017/11/15/improvements-to-azure-functions-in-visual-studio/) to create a netcoreapp2.0 function?

**Comment by mmisztal1980** [comment] 2017-11-21 12:16
I've installed VS 2017 15.5 preview, which is supposed to use the tooling that you've mentioned.
I've created a functions project, set it's target framework to **netcoreapp2.0**, added a queue-triggered function and added **Microsoft.CSharp** and **System.Runtime** packages, and this is what I've got:

![image](https://user-images.githubusercontent.com/1357057/33072036-29c98138-cebe-11e7-8235-e9a32f65f38a.png)

**Comment by mmisztal1980** [comment] 2017-11-21 14:48
@jeffhollan now that I think of it, I don't think the new 'create new project' dialog has let me pick anything else then a full .net framework - is that still intended?

**Comment by mmisztal1980** [comment] 2017-11-21 16:11
I've went through the install instructions again, and added the missing .vsix containing the WebJobs&Functions v2 tooling.

The project has been created with the new dialog. I've noticed that it contains a tag:
**<AzureFunctionsVersion>v2</AzureFunctionsVersion>** in the .csproj.

The project compiles and runs successfully, however its still displaying the nuget warning.

I take it it's coming with VS 2017 15.5 ? Do you have an ETA?

**Comment by jeffhollan** [comment] 2017-11-21 17:39
No ETA on the warning - @paulbatum or @mathewc do we plan to modify the `Microsoft.Azure.WebJobs.Extensions.Http` dependencies in regards to this warning around .netstandard2.0 support? I'm not even sure if it's a valid warning based - but don't know enough about .net standard

**Comment by paulbatum** [comment] 2017-11-22 01:26
In this particular case the warning is expected behavior in that one of our dependencies ([Microsoft.AspNet.WebApi.Client]( https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/5.2.2)) does not have .NET standard 2.0 as a TFM. However we know that in this case the warning is benign. Usually you can suppress these warnings in the project file and I'm looking at getting the template project file updated to included the suppression. Unfortunately I can't get this to work with transitive dependencies like this one. I'm following up with some internal contacts to try to find out if this is a bug in VS and if there is a workaround.

**Comment by jeffhollan** [comment] 2017-11-22 02:08
@justcla as well to help track

**Comment by paulbatum** [comment] 2017-11-22 03:10
I found the appropriate NuGet issue:
https://github.com/NuGet/Home/issues/5740

I'm not sure how to resolve this until that issue is fixed.

**Comment by jeffhollan** [comment] 2017-11-22 03:20
I think it's fair to close this issue here as track in Nuget - nothing actionable on our side as I see it

**Comment by fabiocav** [comment] 2017-11-22 03:36
Agreed. Closing this as the warning can be safely ignored (you can take one of the approaches described on the issue @paulbatum has linked to, if you want to suppress it) and will be addressed when suppression applies to transitive dependencies.

**Closed by fabiocav** 2017-11-22 03:36 UTC
