### ISSUE TITLE
Azure function with ActivityTrigger that accepts a value tuple does not work with cosmos db input binding with SQL Query

### ISSUE THREAD

**Issue by manojsubramani** [Azure/Azure-Functions#992] opened 2018-10-11 22:37 UTC
Hello Team,
I have an Activity Trigger Function app that receives value tuples as input. I'm trying to bind this to cosmos db input binding. Binding works fine if I bind to id, but fails when I bind to SQL Query (SqlQuery =  "SELECT * FROM c where c.Field3 = {data.Item1.Field1}). Is this the right way to bind when using a sql query? everything works fine when I bind id to "data.Item1.Field1".

I get this error when I bind to a sql query.
Exception while executing function: Function2_Hello <--- Exception binding parameter 'items' <--- Error while accessing 'Item1': property doesn't exist.

I use Function app V2.
Nuget packages I use

"Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.1" 
"Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.6.2" 
"Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.0" 
"Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0" 
"Microsoft.NET.Sdk.Functions" Version="1.0.22" 
"Newtonsoft.Json" Version="11.0.2" 
  
```
public static class Function2
    {
        [FunctionName("Function2")]
        public static async Task<List<string>> RunOrchestrator(
            [OrchestrationTrigger] DurableOrchestrationContext context)
        {
            var outputs = new List<string>();
            var typeA = new TypeA()
            {
                Id = new Guid("be57f7d0-c3bf-4f94-bca2-667f854f4289"),
                Field1 = new Guid("e4073c65-9a12-4a11-91cc-ed7cbbcfb656")
            };
            var typeB = new TypeB()
            {
                Id = new Guid("99c759be-51f6-46c2-807b-9ab3f6ae7479"),
                Field2 = new Guid("9372a3da-212c-4c55-9a57-63dca490afea"),

            };
            // Replace "hello" with the name of your Durable Activity Function.
            outputs.Add(await context.CallActivityAsync<string>("Function2_Hello", (typeA, typeB)));

            // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!"]
            return outputs;
        }

        [FunctionName("Function2_Hello")]
        public static void SayHello(
            [ActivityTrigger] (TypeA, TypeB) input,
            [CosmosDB(
                databaseName: "sometestdb",
                collectionName: "collection1",
                ConnectionStringSetting = "CosmosDBConnection",
                SqlQuery =  "SELECT * FROM c where c.Field3 = {data.Item1.Field1} ")]
                    IEnumerable<TypeC> items,
            ILogger log)
        {
            log.LogInformation($"Function2_Hello - {input.Item1.Field1.ToString()} and {input.Item2.Field2.ToString()}");
            
                    log.LogInformation(items.Count().ToString());

        }

        [FunctionName("Function2_HttpStart")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")]HttpRequestMessage req,
            [OrchestrationClient]DurableOrchestrationClient starter,
            ILogger log)
        {
            // Function input comes from the request content.
            string instanceId = await starter.StartNewAsync("Function2", null);

            log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

            return starter.CreateCheckStatusResponse(req, instanceId);
        }
    }
public class TypeA
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("Field1")]
        public Guid Field1 { get; set; }
    }

    public class TypeB
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("Field2")]
        public Guid Field2 { get; set; }
    }

    public class TypeC
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("Field3")]
        public Guid Field3 { get; set; }
    }
```

**Comment by jeffhollan** [comment] 2018-11-06 00:30
The `ActivityTrigger` must bind to type `DurableActivityContext`.  You can still pass in tuples, but you would need to format it closer [to this sample](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-bindings#passing-multiple-parameters)

**Comment by manojsubramani** [comment] 2018-11-06 02:16
Hi Jeff,
In order to make the function testable, I followed this example. 
https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-unit-testing#unit-testing-orchestrator-functions
I can confirm Activity Triggers works with POCO objects. 
What is not working is the binding to cosmos db when the POCO is a value tuple. 
Does this mean, Activity Trigger works with cosmos db bindings only if the input is DurableActivityContext?

**Comment by jeffhollan** [comment] 2018-11-06 02:59
You are correct and my bad - I expect though the valid binding types are likely limited to simple POCOs or types like strings.  I suspect tuples may not be supported.  I [don't see anything specified here](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-bindings#activity-triggers) so adding @cgillum in case he can confirm valid binding types

**Comment by cgillum** [comment] 2018-11-06 04:07
What if you replace "data" with "input" in your binding expression?  Something like the "BindToBlobViaParameterName" unit test in this code: https://github.com/Azure/azure-functions-durable-extension/blob/master/test/Common/TestActivities.cs.

**Comment by ColbyTresness** [comment] 2019-03-13 19:34
Anything else needed here @jeffhollan @cgillum ?

**Comment by Oceanswave** [comment] 2019-06-26 21:06
A google search on a similar issue lead me here -- can confirm if the [ActivityTrigger] function parameter name is 'data' it indeed gives the error. Changing the parameter name 'data' to another parameter name resolves it.

**Comment by ltouro** [comment] 2019-11-19 16:28
had the same problem as @Oceanswave. Naming your tuple as "data" causes the indexation error. I don't know if the problem is the same as the OP reported. Possible not. Will open another issue to track this.

**Comment by jeffhollan** [comment] 2019-11-20 15:16
Thanks @ltouro - I'm going to close this issue then and track your created issue (which I moved over to the Durable repo for now)

**Closed by jeffhollan** 2019-11-20 15:16 UTC
