### ISSUE TITLE
servicebusqueuetrigger

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#150] opened 2017-01-18 10:41 UTC
I`m trying to use ServiceBusQueueTrigger. After pasting the right connection string and setting the queue name, when I try to run it gives me the following error:

Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ServiceBusQueueTriggerCSharp'. Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string 'AzureWebJobsEndpoint=sb://[edited].servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=[edited]' is missing or empty.
Error indexing method 'Functions.ServiceBusQueueTriggerCSharp'
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
Job host started
The following 1 functions are in error:
ServiceBusQueueTriggerCSharp: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ServiceBusQueueTriggerCSharp'. Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string 'AzureWebJobsEndpoint=sb://[edited].servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=[edited]' is missing or empty.

Is there any step that I`m missing?

**Comment by thdotnet** [comment] 2017-01-18 10:48
It seems that this VS template is wrong. It creates the property on function.json, however, Azure Function Try to read from appsettings.json.

After I move the connection string to appsettings.json and just set the name of the property on function.json, it works.

function.json
```

{
  "disabled": false,
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "pedidos",
      "connection": "connection",
      "accessRights": "Manage"
    }
  ]
}

appsettings.json

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "AzureWebJobsDashboard": "",
    "connection": "Endpoint=s..."
  }
}

```
```

**Comment by fabiocav** [comment] 2017-01-18 18:10
This is the correct behavior. Secrets and all other sensitive information should be kept/managed as App Settings when running on Azure and are read from `appsettings.json` when running locally (CLI or VS).

Your `function.json` file will simply contain references to app settings names and load what is setup in the environment you're running on.

**Comment by thdotnet** [comment] 2017-01-18 19:42
@fabiocav Maybe you got it wrong. I'm using Azure Functions template from Azure .NET sdk 2.9.6. After I select the ServiceBusQueueTrigger template and set the right connection string / queue name through the window, what I was expecting was just press f5, and it should receive new messages. However, VS is not setting the connection string in the right place as I said. It's creating in the function.json and the error message given is not clear about that.

In my opinion, VS should set the connection string in the right place. Do not you think

**Comment by christopheranderson** [comment] 2017-01-18 21:08
+ @lindydonna 

Donna can explain more about the current behavior. We can probably capture that specific feedback in another issue.

**Comment by fabiocav** [comment] 2017-01-18 21:15
Yes, makes sense. Sorry, this wasn't clear to me at first.

@lindydonna reopening this for triage. The flow here is using the VS tooling, but the immediate action to ensure things are clearer may need to be against the Functions Templates (so we'd need an issue there) since that's where the resources come from. This is a more generalized issue, impacting the portal and other bindings as well, and does cause quite a bit of confusion (the resources in question here are `serviceBusTrigger_connection_help` and `serviceBusTrigger_connection_label`, but the other resources prompting for secrets need to be reviewed).

Long term, it would be nice to have the VS Tooling adding the secrets and names to the appropriate files (I recall seeing an issue for that, but can't find it right now).

**Comment by thdotnet** [comment] 2017-01-18 21:31
sorry @fabiocav  I should had explain with more details. Do you need print screens / videos to help reproduce that? Also, I have another feedback about it. Rather than just paste the connection string, and assuming that I have my VS connected with my Azure Subscription, why not let VS get the connection string directly to users?

**Comment by christopheranderson** [comment] 2017-01-18 21:35
I think we understand the issue now, @thdotnet, thanks for following up.

The issue is essentially that the VS tooling help you define your App Setting which will hold your secrets. It doesn't have an experience for setting those secrets for those App Settings. It should at least make that clearer, and potentially go a step further and make that experience easy from VS. @lindydonna should have some more clear opinions here, I think. She may have some questions on what your expected behavior is.

**Comment by thdotnet** [comment] 2017-01-18 21:52
Cool! Just ping in here if you guys need something else.

Cheers

**Comment by lindydonna** [comment] 2017-01-19 00:10
@thdotnet Yes, this is a limitation of the current VS tooling in that entering connection strings is extremely manual. I have not captured this as its own issue, but rather in a larger feature list for getting the VS tooling to release quality (rather than preview). Here's the issue where I've listed this: https://github.com/Azure/Azure-Functions/issues/148

If you have other feature requests, please add to that issue.

I'm closing this item as a duplicate.

**Closed by lindydonna** 2017-01-19 00:10 UTC

**Comment by lindydonna** [comment] 2017-01-19 00:13
Here's the issue to track the misleading label: https://github.com/Azure/Azure-Functions/issues/115

**Comment by DaveVoyles** [comment] 2017-08-01 23:09
I hate to re-open this, but I Think I have the same issue. I'll post my code below, as it's a throwaway app, I don't mind sharing the strings.

Running locally with the CLI, VS code, and node.

**appsettings.json (and local.appsettings.json is identical):**
```json {
  "IsEncrypted": true,
  "Values": {
    "AzureWebJobsStorage": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAATT+5AVOfWEubMtFAEo9LeQAAAAACAAAAAAAQZgAAAAEAACAAAACxOtLhQki40xKtm7Zqu95NkxKpRJ3LECC9cnoS1DMTUAAAAAAOgAAAAAIAACAAAACPSq0Q6Gp6odPitKXBWgj3vcJm/Lsyn0qxNI0FNAi9/rAAAAAPezOjVQ53E4SP1E9MZh6tsxdgQ4H66vklZvb4xBjF7Mi04Lp+cqg2GRa7VpW5P7Z42cGLVT9AHtIh0dov7khpXtZceZr5Wf1D732zq6P57aej977cF9YrbF9taPx4bDNtSNxEWpzKE12rDtoiKcsLLr2J29L/GQbluZTLnpiAzedINWKPJHiimkPEpmOjsxw8SqcDLIuyrch109rEKFZ+CIzza8HNsHWarXFFUQgLnEAAAABWMfA5Wdp3bxoJFZaa1SLQo1dnmWLFm3xV8SnQ6ysX7kA0lW/YqrQKdlrFQQvYH7D/Z9LuIDRfrA27huLkItgG",
    "functionsstorageacct_STORAGE": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAATT+5AVOfWEubMtFAEo9LeQAAAAACAAAAAAAQZgAAAAEAACAAAABqbQlH2szkCNDJvC8y4XHki+bJm57mB0Fvoc0nYHD+EwAAAAAOgAAAAAIAACAAAAB/qDcEFQ4LAEWhI3B/0J8Yq0yG6rUasdinnT7dj6IVh7AAAAA5dDpYWb26/QTpkHuADWc5dJRanYTdqLMyCcy/OfcDl9K8yMrdTRteHPNy6cLFL6hdMxie6orlkW05OIpXpaj19NqeyNblK/6zz4TMJN1Wh8Hv3Og8DmyHtjyP9Sc12tkBVXQGGXddohlQ5oRHpqAuP8POGHc5K1pumIKpykPqo96vFCQNiD6DSZLyZQaCjm+IsEp+g2vAHcDBIx0Opu4YpuzD8s/ddmdkGizgbrCyNkAAAAAYwJMjNau3tOeEmwSBvckmAyzzUOX3zGuSmk8dE1yET/sTZKZhkkhKyE89YndN/CwhXUU6uLMNGFRsUWMwHgxL",
    "AzureWebJobsDashboard": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAATT+5AVOfWEubMtFAEo9LeQAAAAACAAAAAAAQZgAAAAEAACAAAADvrqXQE+5bh1MRaasU719BHiF6PqirCsfIrih9yOHLMwAAAAAOgAAAAAIAACAAAADhGFv524kyRbPpV566FwugKV1r2T9nVnVwE539Xx8ZjbAAAACG1PWmJNfUQSsFXiqetUtM5kUw6XwkXfGUdboh40rfQSHRDgQ/A5r5YrsnSUUgi4DLmtZMjpUalwmhMLwHT23tbciJiDxgGCxlx2wujxuvOtmlpEUTc1ZV8rb1F93tP5GUviYswLsovEFEDi1Lbb2oGrdEraXIY2ac44Yt8Ndp9JDeWNdoN7VeknwOi9LPwOEBWvjm3NFL2jmgMcYwqBp7PCaq9GlALV0Us0sr6UapBkAAAAA4CufulBCVZY/4+/pZxVP6cp+LIV2VxDQP7JHAU+PX+cXF8wIlowM+GtXRgcDCrVUNB2kUQYlc8EmNSAqItyjm",
    "FUNCTIONS_EXTENSION_VERSION": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAATT+5AVOfWEubMtFAEo9LeQAAAAACAAAAAAAQZgAAAAEAACAAAADkeuwRkqrXB+AE3qxGNUQi+/KKoiVSYBkyGrPdeKqMxgAAAAAOgAAAAAIAACAAAACyQ5ikEpPgZEvMzVV7I6l3lMtTz+X7/qaY4Bwp+9XVbBAAAACjv+geDHKRlPbR7BHYa8qyQAAAAItIt68AxTRgAmMGzjFMBQcyBZK9wuTV0mV8iSjclLE9MW70BaCRE7p9g0wqXRa+UTgBfCQIV7wZUUaLW9gmRWU=",
    "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAATT+5AVOfWEubMtFAEo9LeQAAAAACAAAAAAAQZgAAAAEAACAAAACUNqJUPbkFU1M/dzr1W8vUiSb1AVHPwHaQIItrIjoqJAAAAAAOgAAAAAIAACAAAABO5FibPQ2U+QRDZm+hCN3T+1Tu/Nd22pRMGIBAcRZw8rAAAABmS1cKGent3707n+yAjg/kJ0Ts6Jldk2/w2De250f3z00a5MLWw/2LfQ5KPikyXIiaOTZi0eW8Kz2ZsLwQQ3yqSBQXZMr+6PaDYmTxSCUauUQ6MdosVbpcV/okLMNdux8ydUz/Nw9lMzRG0vmE1YX3GHuOyNnb+TrjfG2rTgZiSRLpbOil/yAORB6zBjpgb62IBujCYfFwos/ouJplOZiiQIk9ari2RYwycumV50jY40AAAAD/mZGvOq6r0vv0qudNL0zlz2SUaSDAqq3FPufRcCEAXrOW8n8rWWOTW2WWYMKxUHtdgit8bhm2LUj6naqRIZJu",
    "WEBSITE_CONTENTSHARE": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAATT+5AVOfWEubMtFAEo9LeQAAAAACAAAAAAAQZgAAAAEAACAAAABaFy6sW5/TciOEh3b6ZSJeg+jkzSVv2SdFw8Nin/peIgAAAAAOgAAAAAIAACAAAADlU1XjNES5gCaS/vLfoKidc74/fDsNMIvLqspL0fPtJSAAAADsZEJTLfuZx+kItQG9rKs4lNUHBMcFm78JOjvJyVNCQEAAAABAFmgQc4j4qI45DE8vK9vVolL36C+JBcw88gxrpxVcPNHhDgTCnQAoeMZW1guOyjaT4EOrM5Vx2zFSs1XuJLrC",
    "WEBSITE_NODE_DEFAULT_VERSION": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAATT+5AVOfWEubMtFAEo9LeQAAAAACAAAAAAAQZgAAAAEAACAAAAA8jRCI2jrOmKrOOgxLqXItkGWGKeKy2/vbZkFPvWsQ5QAAAAAOgAAAAAIAACAAAAAYys9xVr8gAsQrfkFC2DA2Am+HA2hF8rKqVVqTAzpeLxAAAACahCGlROPp2uTuu7xnQ8EKQAAAAKzhdsI2wGNMn5mEBBe+1Zot/mNnCkQiMH5B+g2p3zWWklwuzjwsFxC+ERaeA7YPehLuEfbokBA7qs+Ewk2BEBw=",
    "AZURE_STORAGE_ACCOUNT":"functionsstorageacct",
    "AZURE_STORAGE_ACCESS_KEY":"7msknqo7qOzSxhdh6THU5cwqXa1gr5rglDle0KEBowa3Kz0ZapefBN45uV59YyBeFIn1v1jqe/sqeWYoo2SfYQ==",
    "AZURE_STORAGE_CONNECTION_STRING" :"DefaultEndpointsProtocol=https;AccountName=functionsstorageacct;AccountKey=7msknqo7qOzSxhdh6THU5cwqXa1gr5rglDle0KEBowa3Kz0ZapefBN45uV59YyBeFIn1v1jqe/sqeWYoo2SfYQ==;BlobEndpoint=https://functionsstorageacct.blob.core.windows.net/;QueueEndpoint=https://functionsstorageacct.queue.core.windows.net/;TableEndpoint=https://functionsstorageacct.table.core.windows.net/;FileEndpoint=https://functionsstorageacct.file.core.windows.net/;"
  },
  "ConnectionStrings": {}
}
```


**MyBlobTriggerJS/function.json**


```json
{
  "disabled": false,
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "dumpster/{name}",
      "connection": "functionsstorageacct_STORAGE"
    }
  ]
}
```

**Index.js**

```javascript
var azure = require('azure-storage');

var storageAccountName = process.env.AZURE_STORAGE_ACCOUNT;
var connString         = process.env.AZURE_STORAGE_CONNECTION_STRING;
var accessKey          = process.env.AZURE_STORAGE_ACCESS_KEY;

module.exports = function (context, myBlob) {

    var blobService     = azure.createBlobService()
    blobService.listContainersSegmented(null, function(err, result) {
        if (err) {
            console.log("Couldn't list containers");
            console.error(err);
        } else {
            console.log('Successfully listed containers');
            console.log(result.entries);
            console.log(result.continuationToken);
        }
    });
    context.log("JavaScript blob trigger function processed blob \n Name:", context.bindingData.name, "\n Blob Size:", myBlob.length, "Bytes");
    context.done();
};  
```

**ERROR (and this appears 3x)**
```
A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.MyBlobTriggerJS'. Microsoft.Azure.WebJobs.Host: Microsoft Azure WebJobs SDK 'Storage' connection string is missing or empty. The Microsoft Azure Storage account connection string can be set in the following ways:
1. Set the connection string named 'AzureWebJobsStorage'.....
```

**Comment by christopheranderson** [comment] 2017-08-01 23:10
@ahmelsayed - can you look into this?

**Comment by ahmelsayed** [comment] 2017-08-01 23:15
@DaveVoyles you have `IsEncrypted` set to true, but you have an un-encrypted values in there for `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_CONNECTION_STRING`. What version of the CLI are you using? the current version should display a clear error message saying that decryption failed for these values.

**Comment by DaveVoyles** [comment] 2017-08-02 14:11
I am currently using:

```
Azure Functions Cli (1.0.0-beta.94)
Function Runtime Version: 1.0.10826.0
```

Oh OK, so I should change it to "encrypted" : "false" then, I suppose?

**Comment by ahmelsayed** [comment] 2017-08-02 15:49
update your tools version. this is the current version 

```
Azure Functions Core Tools (1.0.0-beta.100)
Function Runtime Version: 1.0.11015.0
```

also, you would need to remove the 2 un-encrypted settings first, run `func settings decrypt` then add them back again.

**Comment by DaveVoyles** [comment] 2017-08-02 17:52
Just updated. I realized why it wasn't at first. I was calling to update ```azure-functions-cli``` when I realized it was renamed to ```azure-functions-core-tools```. 

Now running 
```
Azure Functions Core Tools (1.0.0-beta.100)
Function Runtime Version: 1.0.11015.0
```

A new warning appears immediately (helpful): 
```
Warning: found both 'local.settings.json' and 'appsettings.json'. Ignoring 'appsettings.json'.
```

I ran ```func settings decrypt``` followed by ```func host start --debug vscode``` but have the same issueL

```
Listening on http://localhost:7071/
Hit CTRL-C to exit...
The host is taking longer than expected to start.
The host is taking longer than expected to start.
The host is taking longer than expected to start.
```

**Comment by ahmelsayed** [comment] 2017-08-03 16:32
Sorry I missed your comment. What do you get if you hit `http://localhost:7071` in the browser? also are you running in the root of your function app project? where `host.json` is ?

**Comment by DaveVoyles** [comment] 2017-08-03 17:00
Quite alright. I spun up a new node project with an HTTP trigger, taking the same blob code and it works flawlessly. That's why I'm genuinely curious about this one. I could probably just skip it for now, but think it may be a lower-level issue. 

In my new project:

**index.js**
``` javascript
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    } else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    var blobService     = azure.createBlobService();
       
        // List blobs
        blobService.listContainersSegmented(null, function(err, result) {
            if (err) {
                console.log("Couldn't list containers");
                console.error(err);
            } else {
                console.log('Successfully listed containers');
                console.log(result.entries);
                console.log(result.continuationToken);
            }
        });
    context.done();
};
```

**New project, function.json**
```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

**New project, local.settings.json**
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "AZURE_STORAGE_ACCOUNT":"functionsstorageacct",
    "AZURE_STORAGE_ACCESS_KEY":"7msknqo7qOzSxhdh6THU5cwqXa1gr5rglDle0KEBowa3Kz0ZapefBN45uV59YyBeFIn1v1jqe/sqeWYoo2SfYQ==",
    "AZURE_STORAGE_CONNECTION_STRING" :"DefaultEndpointsProtocol=https;AccountName=functionsstorageacct;AccountKey=7msknqo7qOzSxhdh6THU5cwqXa1gr5rglDle0KEBowa3Kz0ZapefBN45uV59YyBeFIn1v1jqe/sqeWYoo2SfYQ==;BlobEndpoint=https://functionsstorageacct.blob.core.windows.net/;QueueEndpoint=https://functionsstorageacct.queue.core.windows.net/;TableEndpoint=https://functionsstorageacct.table.core.windows.net/;FileEndpoint=https://functionsstorageacct.file.core.windows.net/;"
  }
}
```


Bu to answer your question, in the non-working project, if I navigate to ```http://localhost:7071``` while trying to run the function, it returns:
```
Function host is not running.
```

Host.json is located immediately outside of the folder with my function.
-My Functions
--BlobTwiggerTwoJS
-host.json
-local.settings.json

**Comment by ahmelsayed** [comment] 2017-08-03 17:42
That's really odd. Exactly the same code works fine for me. Does the folder path contain unicode characters by any chance?

if you go to `\Users\<userName>\AppData\Local\Temp\LogFiles\Application\Functions\Host`, there should be a log file there, does it contain anything interesting?

![2017-08-03_10-40-37](https://user-images.githubusercontent.com/645740/28935108-4259e184-7838-11e7-9ea3-7f415be87acd.gif)

**Comment by DaveVoyles** [comment] 2017-08-03 22:44
Woah. I've got my money's worth out of this thread just from this post alone.
1. I didn't know you could embed a .gif here
2. I didn't know I could use the Functions CLI **within** VS Code

The log is pretty large.  I tried posting it in Pastebin, but it is over the 512k limit. I tried attaching it (it is .txt) but for some reason GitHub doesn't accept it. 

I suppose we can just close this for now, and if I run into it in another project, I will post here again. Thanks for all of your assistance!

**Comment by ahmelsayed** [comment] 2017-08-03 23:19
you can also delete the logs then run again and see if something shows up.
