### ISSUE TITLE
Unable to start V3 Azure Function : Could not load file or assembly

### ISSUE THREAD

**Issue by StefH** [Azure/Azure-Functions#1518] opened 2020-03-06 10:00 UTC
# Function csproj:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.13.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
    <None Update="local.settings.development.json">
      <DependentUpon>local.settings.json</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

# Azure Function portal settings:
![image](https://user-images.githubusercontent.com/249938/76073328-bafd0300-5f99-11ea-8ea9-0feea2999f3a.png)

Unable to start Azure Function, error message in Azure Portal is:

> Error:
> 
> The function runtime is unable to start. My.FunctionApp: Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. . System.Private.CoreLib: Could not load the specified file. 

# Notes
Note that this is Azure Function is running on a Linux App Service plan.

**Comment by StefH** [comment] 2020-03-08 11:24
![image](https://user-images.githubusercontent.com/249938/76161872-b79f7e00-6137-11ea-8ba3-f6aafca6f048.png)

Example project:
https://github.com/StefH/AzureFunctionsV3

**Comment by tewleap** [comment] 2020-03-09 08:31
I am having the same issue, haven't found a solution yet.

**Comment by AlexanderRettkowski** [comment] 2020-03-15 14:58
I stumbled upon a similar issue and was able to solve it by setting the Microsoft.NET.Sdk.Functions dependency to 3.0.3. You might try that as well.
The issue might be linked to something like this one: https://github.com/Azure/azure-functions-host/issues/5747

**Comment by StefH** [comment] 2020-03-15 16:02
When using version 3.0.3 I get this error:
![image](https://user-images.githubusercontent.com/249938/76705061-91e91a80-66dd-11ea-887d-c4def81a849e.png)

## >>>
Note that I only get an error when running on a **Linux App Service**, when deploying the same code (3.0.3 or 3.0.5) on **Windows App Service**, it works fine.

**Comment by AlexanderRettkowski** [comment] 2020-03-16 15:28
Have you tried adding the necessary dependencies as PackageReferences manually? AddEnvironmentVariables() relies on 

- Microsoft.Extensions.Configuration.EnvironmentVariables
- Microsoft.Extensions.Configuration
- Microsoft.Extensions.Configuration.Abstractions
- Microsoft.Extensions.Primitives

I don't know that much about the runtime environments but I just did a few short experiments and fell upon the same issue as you when not adding those references. Depending on how you're loading the json files you might want to add

- Microsoft.Extensions.Configuration.FileExtensions
- Microsoft.Extensions.Configuration.Json

as well. I tested version 3.1.2 for all of them.

**Comment by brettsam** [comment] 2020-03-16 16:15
Trying to narrow down the issue -- what if you try using an earlier version of `Microsoft.Extensions.Logging.Console` -- does 3.1.1 work?

@AlexanderRettkowski -- does yours also only reproduce in Linux?

@StefH -- In your screenshot, it says you're using functions version ~3 yet running a v2 host, which seems broken. Is this a Linux Consumption app?

**Comment by StefH** [comment] 2020-03-16 17:29
@brettsam I'm nor running on V2 host (at least I think I am not..) Where did you see that I'm running at V2?

I did not yet try 'Microsoft.Extensions.Logging.Console - 3.1.1'

**Comment by brettsam** [comment] 2020-03-17 20:10
From your screenshot above -- it appears that you've got `~3` set, yet a v2 runtime is being used. 

Is this a Linux Consumption or App Service Plan? + @balag0 / @divyagandhii in case they've seen this in Linux apps.

![image](https://user-images.githubusercontent.com/1089915/76897161-75212400-6850-11ea-9765-1465fbe8634b.png)

**Comment by StefH** [comment] 2020-03-17 21:09
I see your point.

A function running on a Windows App Plan, I see this:
![image](https://user-images.githubusercontent.com/249938/76902065-7592dc80-689b-11ea-904e-5c81a91bf90a.png)

A function running on a Linux App Plan, I see indeed this:
![image](https://user-images.githubusercontent.com/249938/76902151-a5da7b00-689b-11ea-9e05-5a28c735c38e.png)

And the docker image which is used has this info:
`microsoft/azure-functions-dotnet-core2.0:2.0`
And logging:
```
2020-03-15 18:19:43.863 INFO  - Pulling image from Docker hub: microsoft/azure-functions-dotnet-core2.0:2.0
2020-03-15 18:19:45.029 INFO  - 2.0 Pulling from microsoft/azure-functions-dotnet-core2.0
2020-03-15 18:19:45.031 INFO  -  Digest: sha256:543d0a584daf8c4f9ff003c817da5a9e42c079e5526145470c350096fe29c1e9
2020-03-15 18:19:45.033 INFO  -  Status: Image is up to date for microsoft/azure-functions-dotnet-core2.0:2.0
2020-03-15 18:19:45.036 INFO  - Pull Image successful, Time taken: 0 Minutes and 1 Seconds
2020-03-15 18:19:45.048 INFO  - Starting container for site
2020-03-15 18:19:45.050 INFO  - docker run -d -p 9561:80 --name stef-function-app-linux-v3_0_21076afa -e WEBSITE_CORS_ALLOWED_ORIGINS=https://functions.azure.com,https://functions-staging.azure.com,https://functions-next.azure.com -e WEBSITE_CORS_SUPPORT_CREDENTIALS=False -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=true -e WEBSITE_SITE_NAME=stef-function-app-linux-v3 -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=stef-function-app-linux-v3.azurewebsites.net -e WEBSITE_INSTANCE_ID=31c0e435accff6d7fdc48c7918f57b1c0cbe27c6465fe990a7f0e8eeeac689f1 -e HTTP_LOGGING_ENABLED=1 microsoft/azure-functions-dotnet-core2.0:2.0  

2020-03-15 18:19:45.644 INFO  - Starting container for site
2020-03-15 18:19:45.646 INFO  - docker run -d -p 5815:8081 --name stef-function-app-linux-v3_0_21076afa_middleware -e WEBSITE_CORS_ALLOWED_ORIGINS=https://functions.azure.com,https://functions-staging.azure.com,https://functions-next.azure.com -e WEBSITE_CORS_SUPPORT_CREDENTIALS=False -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=true -e WEBSITE_SITE_NAME=stef-function-app-linux-v3 -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=stef-function-app-linux-v3.azurewebsites.net -e WEBSITE_INSTANCE_ID=31c0e435accff6d7fdc48c7918f57b1c0cbe27c6465fe990a7f0e8eeeac689f1 -e HTTP_LOGGING_ENABLED=1 appsvc/middleware:2001061754 /Host.ListenUrl=http://0.0.0.0:8081 /Host.DestinationHostUrl=http://172.16.10.2:80 /Host.UseFileLogging=true 

2020-03-15 18:19:46.336 INFO  - Initiating warmup request to container stef-function-app-linux-v3_0_21076afa for site stef-function-app-linux-v3
2020-03-15 18:19:50.892 INFO  - Container stef-function-app-linux-v3_0_21076afa for site stef-function-app-linux-v3 initialized successfully and is ready to serve requests.
2020-03-15 18:19:50.893 INFO  - Initiating warmup request to container stef-function-app-linux-v3_0_21076afa_middleware for site stef-function-app-linux-v3
2020-03-15 18:19:51.126 INFO  - Container stef-function-app-linux-v3_0_21076afa_middleware for site stef-function-app-linux-v3 initialized successfully and is ready to serve requests.
```

**Comment by balag0** [comment] 2020-03-17 22:17
@ankitkumarr This app has linux fx version set to DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0
Does Functions extension version override this or do we have update linux fx version to point to 3.0 images

**Comment by divyagandhii** [comment] 2020-03-18 17:21
This is a known issue - https://github.com/Azure/azure-functions-host/issues/5559 . The issue mentions only CLI client and we fixed it there but I think this issue needs to be fixed for portal and other clients as well.

**Comment by StefH** [comment] 2020-03-21 16:51
@brettsam & @balag0 :
I have a feeling that something has changed since the moment I created that Linux App Services based Azure Function (this is called `...v3`).

When using the new UI in Azure Portal, I see this for the old Function with these settings (an error is visible...):
![image](https://user-images.githubusercontent.com/249938/77231368-b55b0c00-6b9a-11ea-991a-23addad9073b.png)


However, I just created a new function (this is called `...v3a`), and this looks like:
![image](https://user-images.githubusercontent.com/249938/77231442-361a0800-6b9b-11ea-872c-119473399170.png)

**Note** that initially the stack settings where empty, but I manually changed these to this:
![image](https://user-images.githubusercontent.com/249938/77231456-4df18c00-6b9b-11ea-8730-d88676a4eb0c.png)

However after deploying (via Azure Pipelines, https://github.com/StefH/AzureFunctionsV3/blob/master/azure-pipelines.yml) the Function is broken again:
![image](https://user-images.githubusercontent.com/249938/77231611-6e6e1600-6b9c-11ea-97a9-d35883bd679c.png)

**Comment by StephenCleary** [comment] 2020-04-10 03:57
I believe I'm having the same issue. It looks like the `RemoveRuntimeDependencies` task (from assembly "$\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.5\tools\net46\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll") is waaaay too liberal about what files it likes to remove from the output directory.

- Microsoft.NET.Sdk.Functions 3.0.3 - works fine. `RemoveRuntimeDependencies` is not run at all.
- Microsoft.NET.Sdk.Functions 3.0.4 - `RemoveRuntimeDependencies` can cause `GenerateFunctionsExtensionsMetadata` to fail due to "could not load file or assembly".
- Microsoft.NET.Sdk.Functions 3.0.4 - `RemoveRuntimeDependencies` has been moved after `GenerateFunctionsExtensionsMetadata` so the build passes and the functions are found, but that doesn't help much because we still get "could not load file or assembly" at *runtime*.

**Comment by balag0** [comment] 2020-04-10 06:35
@StephenCleary Are you able to share your app name. Want to make sure if the app has the right config since it looks like there was some bug in the azure portal at some point.

**Comment by StephenCleary** [comment] 2020-04-10 11:13
@balag0 I'm running locally; it's not even published yet. Repro [here](https://github.com/StephenClearyExamples/AzureFunctionsAssemblyRepro).

**Comment by balag0** [comment] 2020-04-10 17:42
Thanks.

 @brettsam Looks like this is different from the other issue where the app had wrong image set.  Do you know of any known issues with Functions SDK 3.0.5?

**Comment by StephenCleary** [comment] 2020-04-10 18:38
Let me know if you want me to move my repro to a separate issue.

**Comment by StephenCleary** [comment] 2020-04-16 22:15
Still repros with 3.0.6.

**Comment by brettsam** [comment] 2020-04-17 19:45
@StephenCleary -- if you set `<_FunctionsSkipCleanOutput>false</_FunctionsSkipCleanOutput>` does that work? I agree that this we're too aggressive with trimming the output. I know we've got another issue tracking this -- I'll link it here as soon as I find it.

**Comment by brettsam** [comment] 2020-04-17 20:20
I'm going to use https://github.com/Azure/azure-functions-host/issues/5894 to track the cleaning fix for the SDK-side of things. 

@divyagandhii do you need this issue to track the things you mentioned above (https://github.com/Azure/Azure-Functions/issues/1518#issuecomment-600760175)? Or should we close this as all the issues are being tracked elsewhere.

**Comment by StephenCleary** [comment] 2020-04-17 20:42
@brettsam Yes, if I set `_FunctionsSkipCleanOutput` to `true` it does work; no more runtime exception.

**Comment by divyagandhii** [comment] 2020-04-18 00:46
@brettsam  No we will open issues in respective client repos. You can close this out.

**Comment by brettsam** [comment] 2020-04-20 14:56
Okay please make sure you link them here so we can keep a trail. Closing this out as we are tracking all the individual items elsewhwere

**Closed by brettsam** 2020-04-20 14:56 UTC

**Comment by ObsidianDelta** [comment] 2021-02-09 22:12
Make sure you are using the latest version of Azure Functions Core Tools (Make sure that your project file specifies V3)

```
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
```

Then downgrade any 5.0 dll's to 3.1.x

```
 <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.16.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.12" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="3.1.12" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="5.0.1" />
  </ItemGroup>

```

Then it should work!
