### ISSUE TITLE
Function app Huge I/O ~1 Million requests per day

### ISSUE THREAD

**Issue by vance** [Azure/Azure-Functions#48] opened 2016-10-25 16:49 UTC
I noticed my bill was about $20 fatter last month... upon investigation, it was from a storage account tied to a dynamic plan Function app. This app is not used in prod. However, it had a timed function that ran every five minutes or so as an experiment to help Azure resolve another issue. https://github.com/Azure/azure-webjobs-sdk-script/issues/298#issuecomment-244992601

I'm wondering if there is a bug in the Function App container, if it's writing 60k log entries every time there's a cold start, or if it's just doing that for no reason...

Anyway, it's writing about 60k files per minute. I terminated the app container. 

<img width="748" alt="screen shot 2016-10-24 at 8 51 09 pm" src="https://cloud.githubusercontent.com/assets/145471/19695422/117fe2c6-9a98-11e6-9e7d-ae58654bd69c.png">

**Comment by lindydonna** [comment] 2016-10-25 23:15
Can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?

**Comment by vance** [comment] 2016-10-26 02:41
I filed an actual support ticket, will update.

**Comment by lindydonna** [comment] 2016-11-01 03:50
Support is the right avenue for this, but let us know if there are opportunities for improving the billing experience. CC @dariagrigoriu

**Comment by lindydonna** [comment] 2016-11-21 17:34
Closing this issue since you opened a support ticket.

**Closed by lindydonna** 2016-11-21 17:34 UTC

**Comment by nandowalter** [comment] 2017-04-21 09:35
I've the same exact problem. I've a function with a timer trigger and thousend of unexpected write operation on storage account.
Did you found the cause for this?

**Comment by vance** [comment] 2017-04-23 01:27
this was never resolved from the support ticket.
