### ISSUE TITLE
Could not load file or assembly 'Amqp.Net, Version=2.1.0.0, Culture=neutral, PublicKeyToken=905a7b1e6458e0c3' or one of its dependencies. The system cannot find the file specified."

### ISSUE THREAD

**Issue by slanto** [Azure/Azure-Functions#904] opened 2018-08-03 07:41 UTC
Hello,
I'm using the following:

VS2017 15.7.5
Azure Functions and Web Jobs Tools: 15.0.40617.0
Azure runtime version: 1.0.11913.0

I have created function targeting Net461 that references Microsoft.NET.Sdk.Functions 1.0.14.
In this function I have a dependency to a custom .netstandard2.0 library that references the nuget package: AMQPNetLite.Core 2.1.3

When the function is running locally it is working fine but after publishing it to the Azure I will get the following exception:
"System.IO.FileNotFoundException : Could not load file or assembly 'Amqp.Net, Version=2.1.0.0, Culture=neutral, PublicKeyToken=905a7b1e6458e0c3' or one of its dependencies. The system cannot find the file specified."

I double checked that the Amqp.Net in 2.1.0.0 version is located in a bin directory on Azure. 

Do you have any ideas how to solve this?

Thanks in advance for you help

**Comment by slanto** [comment] 2018-08-03 10:45
In order to reproduce described issue, we have prepared sample project. You can find it here
https://github.com/marcin-chwedczuk-meow/azure-functions-amqp-problem

When it is run locally it is working fine. 
Log message from local execution shows correct behavior
```
[8/3/2018 9:25:55 AM] Host lock lease acquired by instance ID '0000000000000000000000009D6A848A'.
Debugger listening on [::]:5858
[8/3/2018 9:26:06 AM] Executing HTTP request: {
[8/3/2018 9:26:06 AM]   "requestId": "1695dd0b-0c2c-4e10-a814-ef5b44f19196",
[8/3/2018 9:26:06 AM]   "method": "GET",
[8/3/2018 9:26:06 AM]   "uri": "/api/Function1"
[8/3/2018 9:26:06 AM] }
[8/3/2018 9:26:06 AM] Function started (Id=996d8573-a6c7-4846-9f4f-1e5ae8e2c614)
[8/3/2018 9:26:06 AM] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=996d8573-a6c7-4846-9f4f-1e5ae8e2c614)
[8/3/2018 9:26:07 AM] ClassLibrary1, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
[8/3/2018 9:26:07 AM] netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[8/3/2018 9:26:07 AM] Amqp.Net, Version=2.1.0.0, Culture=neutral, PublicKeyToken=905a7b1e6458e0c3
[8/3/2018 9:26:07 AM] C# HTTP trigger function processed a request.
[8/3/2018 9:26:07 AM] Function completed (Success, Id=996d8573-a6c7-4846-9f4f-1e5ae8e2c614, Duration=325ms)
[8/3/2018 9:26:07 AM] Executed 'Function1' (Succeeded, Id=996d8573-a6c7-4846-9f4f-1e5ae8e2c614)
[8/3/2018 9:26:07 AM] Executed HTTP request: {
[8/3/2018 9:26:07 AM]   "requestId": "1695dd0b-0c2c-4e10-a814-ef5b44f19196",
[8/3/2018 9:26:07 AM]   "method": "GET",
[8/3/2018 9:26:07 AM]   "uri": "/api/Function1",
[8/3/2018 9:26:07 AM]   "authorizationLevel": "Anonymous",
[8/3/2018 9:26:07 AM]   "status": "BadRequest"
[8/3/2018 9:26:07 AM] }
```
Unfortunately, on Azure we encounter a problem with loading  Amqp.Net assembly. 
```
Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Dynamic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
ClassLibrary1, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Exception while executing function: Function1
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Function1 ---> System.IO.FileNotFoundException : Could not load file or assembly 'Amqp.Net, Version=2.1.0.0, Culture=neutral, PublicKeyToken=905a7b1e6458e0c3' or one of its dependencies. The system cannot find the file specified.
   at async FunctionApp1.Function1.HttpResponseMessage(HttpRequestMessage req,TraceWriter log)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at FunctionApp1.Function1.HttpResponseMessage(HttpRequestMessage req,TraceWriter log)
   at async FunctionApp1.Function1.Run(HttpRequestMessage req,TraceWriter log)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
```

Any help?

**Comment by marcin-chwedczuk-meow** [comment] 2018-08-03 11:44
As a clarification library that is used in this example is compatible with any net-standard 1.3 platform (source: http://azure.github.io/amqpnetlite/articles/installation.html).

**Comment by paulbatum** [comment] 2018-08-04 02:06
Thanks for the issue report. I just spent a few hours looking at this with @fabiocav and we have some theories but nothing 100% conclusive.

A couple of observations:
1. Your repro behaves the same for me as it you reported - it works fine when running using the local tools but it fails on Azure.
2. I can debug the failure locally on my machine, when I run our functions dev environment against this app. So the issue is not specific to Azure deployments per-se.
3. I can see that fusion is failing to load the assembly, and appears that the problem is strong naming related:

![image](https://user-images.githubusercontent.com/10663/43671435-e2be66d2-974e-11e8-9b27-60ee7c92e765.png)

```
System.IO.FileLoadException: 'Could not load file or assembly 'file:///D:\code\temp\azure-functions-amqp-problem\FunctionApp1\bin\Debug\net461\bin\Amqp.Net.dll' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)'
```
4. If I try to manually verify amqp.net.dll, I get an error:

```
C:\Windows\System32>sn -v "D:\code\temp\azure-functions-amqp-problem\FunctionApp1\bin\Release\net461\bin\Amqp.Net.dll"

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.
```

So we're assuming that this whole problem is related to the assembly identity and that if we retried with an amqp.net.dll assembly that did not have a signing problem, this scenario would work. But we dont have proof of that yet, and we're still not sure why it would be the case that this assembly would load perfectly fine in so many other contexts but fail within functions.

If you can, I suggest you try a few things:
1. building amqp.net.dll from the source and trying that
2. resigning the amqp.net.dll that comes from the nuget using something like strongnamer
3. following up with the azure amqp team about potential problems with their assembly identity (I'm also going to ask around to see if I can get someone to follow up on this).
4. testing on functions V2 (we made a great deal of changes to assembly loading)

Thats all we have right now. Let us know what you find.

**Comment by paulbatum** [comment] 2018-08-04 02:16
Forgot to mention, would be useful if you can confirm that you also get strong name verification failures when using sn.exe with amqp.net.dll.

**Comment by slanto** [comment] 2018-08-06 10:07
@paulbatum, @fabiocav, many thanks for your involvement in analyzing the issue. Your outcome is very useful. 
I checked  Amqp.Net.dll strong name verification and can confirm that it fails. I get the same error message. I have already informed Azure amqp team about it https://github.com/Azure/amqpnetlite/issues/292

**Comment by ColbyTresness** [comment] 2019-02-20 23:36
The referred issue has been closed and fixed, so I'm closing this. Please reopen if necessary.

**Closed by ColbyTresness** 2019-02-20 23:36 UTC
