### ISSUE TITLE
[Azure-CLI] az functionapp deployment source config-zip requests/sets invalid SAS Uri in WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by anthonychu** [Azure/Azure-Functions#1566] opened 2020-04-21 18:30 UTC
https://github.com/Azure/azure-cli/issues/13070

**Comment by miiitch** [comment] 2021-03-17 21:48
Hi, it's almost a year, and the issue is still here. When do planned to fix it? Do you have a workaround?
Regards,

**Comment by gzuber** [comment] 2021-04-20 00:43
Hi @miiitch -- really sorry for the delay here. This should be fixed with https://github.com/Azure/azure-cli/pull/17722, so I'm going to go ahead and close this. If you have any more trouble with this issue or the fix doesn't work as expected, please ping me directly and I'll see what we can do. Thanks!

**Closed by gzuber** 2021-04-20 00:43 UTC
Labels: P1, needs-investigation

**Comment by miiitch** [comment] 2021-04-26 11:47
Thanks!
