### ISSUE TITLE
netstandard2.1 support for Azure Functions V2

### ISSUE THREAD

**Issue by featuresnap** [Azure/Azure-Functions#1331] opened 2019-09-23 21:29 UTC
Hello, I am trying to determine if Azure Functions V2 supports referencing netstandard2.1 dependencies. If not, is there a timetable or plan to implement support for referencing netstandard2.1 dependencies? 

Use case: I am trying to reference a netstandard2.1 dependency (Microsoft.EntityFrameworkCore.Cosmos) and getting a strange build error. 

```
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes()
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryRun()
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Error generating functions metadata
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :
C:\Users\Me\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Metadata generation failed.

```

**Comment by bobbytreed** [comment] 2019-09-24 22:15
Me too!! I'm glad someone else brought this up.

**Comment by bbougot** [comment] 2019-09-30 07:44
I confirm the issue is even there with release 1.0.30-beta1.

**Comment by jamie-tillman** [comment] 2019-10-14 13:37
I'm developing in VS 2019, Azure Functions and Web Jobs Tools 16.3.285.24939 (per the VS "About" Dialog) and I'm getting this error as well when referencing a .NET standard project in the same solution.  Interestingly, the project was targeting .NET standard 2.0 at first, but the message insisted it couldn't find .NET standard 2.1.  Changing the project's target has no effect on the error message.

**Comment by fabiocav** [comment] 2019-10-15 18:48
Support for .NET Standard 2.1/.NET Core 3.0 will be in preview this month. The announcement was made here: https://github.com/Azure/app-service-announcements/issues/204
Please subscribe to be notified as we'll have updates on that very soon.

**Closed by fabiocav** 2019-10-15 18:48 UTC
Labels: documentation

**Comment by Costo** [comment] 2019-10-25 14:06
@fabiocav I think maybe you wanted to link to this announcement: https://github.com/Azure/app-service-announcements/issues/200

**Comment by paulbatum** [comment] 2019-11-08 20:15
So this error can still occur when using the V3 preview, tracked here:
https://github.com/Azure/azure-functions-core-tools/issues/1642
