### ISSUE TITLE
[UX][Feature Request] - Make Function app stack version editable in the Azure Portal

### ISSUE THREAD

**Issue by lgarciaarce-msft** [Azure/Azure-Functions#2359] opened 2023-03-29 13:24 UTC
Currently for Function Apps stack version is not **even visible in the Azure Portal.**

To simplify management operations and provide better visibility of the service, it would be great to be able to edit the stack version directly on the portal as it can currently be done for Web Apps (screenshot below)

![image](https://user-images.githubusercontent.com/125294802/228547250-ad30772d-58b5-4d16-ac89-8b0675dbd11f.png)

**Comment by btardif** [comment] 2023-04-06 20:50
@takyyon is working on this and can provide updates

**Comment by fkupchik** [comment] 2023-05-09 13:22
This is an obvious regression, because formerly it was visible and editable in Portal. Not sure why it's marked as feature request as it's a bug.

**Comment by takyyon** [comment] 2023-06-06 17:03
Hey @lgarciaarce-msft Closing this issue as our latest updates have been deployed, currently stack version updated for Windows function apps is supported for .Net Isolated, PowerShell and Java. Our team is working on enabling this for other stacks as well. (@pragnagopa @btardif as FYI for other stacks)

**Closed as completed by takyyon** 2023-06-06 17:03 UTC
Labels: UX_Preview
