### ISSUE TITLE
FUNCTIONS_EXTENSION_VERSION gets reset on initial deployment

### ISSUE THREAD

**Issue by blueelvis** [Azure/Azure-Functions#1585] opened 2020-05-11 07:05 UTC
Hi,

We have the tooling setup using ARM Templates and PowerShell scripts to Publish the contents to an Azure Function. The flow is as below -
1. When this is the first time deployment to an environment, the ARM template creates a default slot and a Function App. During this time, the App Settings are also published to the Slot.
2. The PowerShell script then goes and switches the slot with the production instance.
3. Once the slot swap is complete, deployment is completed.

The problem is that when this is the first time the deployment is happening, the `FUNCTIONS_EXTENSION_VERSION` gets reset to `~1` from `~3` as defined in our configuration. Please do note that all other settings remain as per the configuration except this. This causes the functions to stop loading. After the deployment completes, I have to manually go in and set this value to `~3` in the App Settings which fixes the issue. Subsequent deployments don't cause this issue. This only seems to be happening during the initial deployment.

Any idea what might be going on?

-Pranav

**Comment by viclin-msft** [comment] 2021-06-02 23:49
I am also seeing this, for not only `FUNCTIONS_EXTENSION_VERSION` but also `ApplicationInsightsAgent_EXTENSION_VERSION`. I did some testing, and it seems like the issue is that these two settings are treated as "sticky" to the deployment slot (as if *Deployment slot setting* is marked).

So, a workaround is to initially set the right value on both staging and production slots, e.g.

```powershell
az webapp config appsettings set --resource-group $rg --name $app --settings FUNCTIONS_EXTENSION_VERSION="~3" --output none
az webapp config appsettings set --resource-group $rg --name $app --settings FUNCTIONS_EXTENSION_VERSION="~3" --output none --slot Staging
```

**Comment by v-bbalaiagar** [comment] 2021-08-03 13:24
Hi @blueelvis, Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required.

**Comment by viclin-msft** [comment] 2021-08-04 21:59
@v-bbalaiagar see my theory and workaround above - I do believe this is a bug and should be fixed.

**Comment by v-bbalaiagar** [comment] 2021-08-05 07:49
Thank you for the update @viclin-msft 

@balag0 , Can you kindly look into this issue.

**Comment by balag0** [comment] 2021-09-07 00:39
By default _Extension_version settings are specific to each slot. Do you have WEBSITE_OVERRIDE_STICKY_EXTENSION_VERSIONS=1 by any chance?

Also make sure the arm template does not omit FUNCTIONS_EXTENSION_VERSION app setting. Leaving it out will set the setting to a default value ~1.

**Comment by viclin-msft** [comment] 2021-09-07 06:07
@balag0 I see, thanks for the pointer. Looking at [this documentation page](https://docs.microsoft.com/en-us/azure/app-service/reference-app-settings), the behavior isn't very clear even with this line:

> By default, the versions for site extensions are specific to each slot.

What does *versions for site extensions* include, anything ending with `_EXTENSION_VERSION`?

I still think this is a bug - some flag is not being set properly. *Deployment slot setting* should be checked in the UI to indicate stickiness:

![image](https://user-images.githubusercontent.com/67283638/132292433-7485df58-3609-4806-91b4-901fae926e99.png)

**Comment by balag0** [comment] 2021-09-07 06:40
>What does versions for site extensions include, anything ending with _EXTENSION_VERSION?

Correct


I think the confusion on the UI is because these settings are treated as a slot specific setting but are not actually slot specific settings. It could have been done this way possibly because other site extensions outside of functions dont really need a way to control stickiness of this setting. So controlling this behavior independently using a separate setting makes chances of other apps breaking accidentally.

**Comment by viclin-msft** [comment] 2021-09-08 15:50
Is there a good reason for making them separate settings when the functionality is the same?

I see three tasks to end confusion here:

1. Make all `*_EXTENSION_VERSION` marked as _Deployment slot setting_ on UI to match underlying behavior.
2. Update [documentation](https://github.com/MicrosoftDocs/azure-docs/blob/05e062aff6aca742a268b000bf2d0ab888696a31/articles/app-service/reference-app-settings.md) to indicate `*_EXTENSION_VERSION` is sticky (deployment slot setting) by default.
3. Specify in some doc page that `FUNCTIONS_EXTENSION_VERSION` will be set to `~1` when unset. Currently [this page](https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal) contradicts that:
    > By default, function apps are created in version 3.x of the runtime

**Comment by balag0** [comment] 2021-09-09 00:08
Good points
1. This needs changes in the backend and other places as well. UI is just displaying those checkboxes based on the response from the service. And making those changes in the backend could be a breaking change.
2. opened https://github.com/MicrosoftDocs/azure-docs/issues/80809
3. This looks like a bug. Will work on getting this fixed. (doc is correct)

**Comment by v-bbalaiagar** [comment] 2021-09-16 09:57
Hi @balag0, Can you please suggest if the label needs to be changed.

**Comment by balag0** [comment] 2021-09-16 19:29
I think we can close this issue.  We will follow up on the workitems we added in the respective repos. Thanks

**Closed by balag0** 2021-09-16 19:29 UTC
Labels: Needs: Author feedback
