### ISSUE TITLE
Azure Function v3: Route-Parameter overrides Request-Body

### ISSUE THREAD

**Issue by ChrWeinert** [Azure/Azure-Functions#1872] opened 2021-04-01 08:35 UTC
When using Azure Function v3, I run into some strange behaviour.

I have a custom Request-Type:
```csharp
public class MyRequest
{
   public Guid Id { get; set; }
   public string Name { get; set;}
}
```

My Azure Function likes something like:
```csharp
[FunctionName(nameof(MyRequestFunction))]
public async Task<IActionResult> UpdateRoleAsync(
[HttpTrigger(AuthorizationLevel.Function, HttpMethodNames.Put, Route = "someapi/{id}")]
            MyRequest input, Guid id)
{

}
```

I send a request to my function with "someapi/2cb0fce7-1588-42fc-9657-ad36f6be1f09" and the following body:
```json
{
  "id": "b8a29105-81da-41e6-bc9e-0f83138f754a",
  "name": "Testname"
}
```
During debuggung i noticed that the id from the route (2cb0fce7-1588-42fc-9657-ad36f6be1f09) was written to the id-property of the MyRequest instance and overwrites the original value (b8a29105-81da-41e6-bc9e-0f83138f754a).

If the name of the Route-Parameter is changed from id to myRouteResponseId everything works fine.

How can I prevent the auto-overwritting of Properties with the same name?

Thanks in advance!

**Comment by VektorPixel** [comment] 2021-04-01 08:40
I just discovered the same behavior in my project and I wonder if the mapping of route parameters to request properties is by design?

**Comment by v-bbalaiagar** [comment] 2021-04-22 09:45
Hi @ChrWeinert, Closing this issue as duplicate, Here is a [tracking issue](https://github.com/Azure/azure-functions-host/issues/7277) which is being addressed and worked upon on a similar scenario, Please find the space for further updates.

**Closed by v-bbalaiagar** 2021-04-22 09:45 UTC
