### ISSUE TITLE
Azure function Publish not creating Startup class entry in extensions.json

### ISSUE THREAD

**Issue by ssathasivan** [Azure/Azure-Functions#972] opened 2018-10-01 15:40 UTC
We are developing a set of  Azure functions for our new product. We are using dependency injection for our project following the strategy , mentioned in the following article 

https://blog.wille-zone.de/post/azure-functions-dependency-injection/

and registered the extension in Startup.cs

This is working fine in the local development environment. However when we tried to publish it azure , the azure functions runtime was not detecting the injected dependencies . We found a similiar problem in the following sctak over flow.com post

https://stackoverflow.com/questions/52123538/iextensionconfigprovider-not-initializing-or-binding-with-microsoft-azure-webjob

We made changes as per their recommendation in the accepted answer. As per this  

 "In C# the SDK 1.0.19 looks at build time for classes attributed with WebJobsStartup assembly attribute in the current function project or any dependency (ProjectReference or PackageReference) of the current project, and generates the corresponding extensions.json file."  

However we ran in to strange problem, When we do a release build , the startup class entry is created  in the extensions.json   

{
  "extensions":[
    { "name": "AzureStorage", "typeName":"Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"},
    { "name": "Startup", "typeName":"AAA.BBBB.Functions.Startup, AAA.BBB.Functions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"}
  ]
}

 however when we try to publish , the startup class entry is NOT created  in the extensions.json 
{
  "extensions":[
    { "name": "AzureStorage", "typeName":"Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
  ]
}

We are stumped and do not know what is the problem

We have created a issue for this in stackoverflow - [](https://stackoverflow.com/questions/52583637/azure-function-iextensionconfigprovider-startup-entry-not-coming-in-extension)

**Comment by BorisWilhelms** [comment] 2018-10-02 12:28
There is a workaround for this issues posted in a different thread: https://github.com/Azure/azure-functions-host/issues/3386#issuecomment-419565714

**Comment by fabiocav** [comment] 2018-10-03 16:41
Some of those issues are known limitations of the product at the moment. We are working on first class support for customer facing DI capabilities in Azure Functions, which will come with a full set of documentation, including services you can depend on and official guidance.

In the meantime, use of those undocumented patterns may be fragile in Azure Functions, which is something to be aware of. Updates on this will be landing very soon.

**Comment by gaikovoi** [comment] 2018-10-04 15:29
https://github.com/Azure/Azure-Functions/issues/928#issuecomment-427036687

**Comment by Joehannus** [comment] 2018-10-19 08:28
@fabiocav can you give an estimation on when the DI capabilities will be available in Azure Functions?

**Comment by DavidJFowler** [comment] 2018-11-15 14:38
> There is a workaround for this issues posted in a different thread: [Azure/azure-functions-host#3386 (comment)](https://github.com/Azure/azure-functions-host/issues/3386#issuecomment-419565714)

This workaround no longer works with Microsoft.NET.Sdk.Functions 1.0.24 and netcoreapp2.1 function apps.

**Comment by gaikovoi** [comment] 2018-11-21 17:00
https://github.com/Azure/azure-functions-host/issues/3386#issuecomment-440736419

**Comment by zmarty** [comment] 2018-12-05 23:06
@fabiocav Feel free to reach out to me by internal Microsoft chat and I can show you how it fails live. And we are not using anything fragile, just straight Azure Functions.

**Comment by fabiocav** [comment] 2018-12-06 18:12
Thank you for all the feedback here. The issue is well understood, but unfortunately, due to higher priority items (including design and implementation work on the official extensibility and DI model for Functions), it hasn't been addressed yet. We'll keep updating this as progress is made and will have this assigned to a sprint milestone when the work is assigned.

**Comment by jeffhollan** [comment] 2019-02-27 07:42
We're working on this now and work is being tracked here. I'm going to close this issue just so we don't have too many duplicate issues across repos.  Progress is being made though (was on a few emails about progress today 😄)

https://github.com/azure/azure-functions-host/issues/3736

**Closed by jeffhollan** 2019-02-27 07:42 UTC

**Comment by wtt235-bh** [comment] 2019-12-17 15:47
This appears to be an issue again now that V3 of the function runtime has been recently promoted out of preview.
