### ISSUE TITLE
VS2017 15.5.4: Publish Azure Function fails : The OutputPath property is not set for project 'XXXXXXXXXXXXX'. 

### ISSUE THREAD

**Issue by HamedSalameh** [Azure/Azure-Functions#665] opened 2018-01-22 14:36 UTC
Full error message: 
VS2017 15.5.4: **Publish Azure Function fails : The OutputPath property is not set for project 'XXXXXXXXXXXXX'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.** 

After upgrading to Visual Studio 2017 15.5.3, i am no longer able to publish to Azure Functions.
Upgraded again to 15.5.4 - same error.

Please note that I have verified that the output property is defined, but yet - the publish is failing.
on my old machine, which has VS2017 15.4.x is was working well.

MSBuild version 15.1.0.0

can you please assist?

**Comment by HamedSalameh** [comment] 2018-01-25 18:19
Hi Team

I've found a workaround for this, similar to the one recommended to use when first moved in V15.5.0 Preview2 : 
Update this line in `Properties\PublishProfiles\<ProfileName>.pubxml `(Remove the space in Any CPU).
(comment posted in issue #571 )

Thanks @vijayrkn - this is working for v15.5.4 as well.
@jeffhollan - FYI

**Comment by jeffhollan** [comment] 2018-02-06 13:56
Thanks @HamedSalameh - was able to repro and confirm this space was there and removing resolves.  Will notify the visual studio team for awareness

**Comment by pauloortins** [comment] 2018-05-15 14:12
Worked for me too. Nice catch @HamedSalameh!

**Comment by vijayrkn** [comment] 2018-05-15 17:53
@nickraphael @pauloortins -  This was an issue in the old version of the Functions tooling (https://github.com/Azure/Azure-Functions/issues/571) and has since been fixed. Are you running into this issue with the newer tooling. Can you please confirm the Functions tooling version from Tools -> Extensions and Updates -> Azure Functions and Web Jobs tools ?

**Comment by cartermp** [comment] 2018-05-15 23:31
@nickraphael That's definitely an older version. You should see an option to update the tools in VS. The latest version is 15.0.40502.0. If you install that, do you still see the issue?

**Comment by vijayrkn** [comment] 2018-05-16 00:56
Here is the link to the release notes with the version info - https://github.com/Azure/Azure-Functions/blob/master/VS-AzureTools-ReleaseNotes.md

**Comment by cartermp** [comment] 2018-06-26 15:35
Hey there @nickraphael were you able to install the latest version?

**Comment by itorian** [comment] 2019-01-21 06:54
I had same issue, but removing "Any CPU" white space didn't work (VS 15.8.9).
I noticed, "Password Required" on publish page (in VS), just re downloaded publish profile and used that to resolve the issue.

![image](https://user-images.githubusercontent.com/3646552/51457409-47893980-1d77-11e9-9a26-3e4549772aec.png)

**Comment by ColbyTresness** [comment] 2019-03-26 23:27
Password required is a separate issue that is fixed in VS19, and the previous issue is caused by using an old version, so I'm closing this.

**Closed by ColbyTresness** 2019-03-26 23:27 UTC
Labels: Visual Studio
