### ISSUE TITLE
Azure Function Consumption Plan goes to sleep only after 2 minutes of being idle

### ISSUE THREAD

**Issue by stergosjk** [Azure/Azure-Functions#1470] opened 2020-01-29 10:00 UTC
We have a consumption plan that hosts 5 azure functions. One of these functions is quite active... however we noticed via Application Insights that after only 2 minutes of being idle (not 20) it went to sleep and then took 40 seconds to warm up again. I thought this ONLY happened after 20 minutes of inactivity not 2.

**Comment by v-bbalaiagar** [comment] 2021-11-02 14:03
Hi @stergosjk, Apologies for the delayed response, the issue was somehow lost in the trace. Let us know if you are still facing the issues, if yes could you please provide us the invocation id of the error, region and time stamp during the error to get the logs and check the cause.

**Comment by v-bbalaiagar** [comment] 2021-11-30 15:02
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.

**Closed by v-bbalaiagar** 2021-11-30 15:02 UTC
