### ISSUE TITLE
The following 1 functions are in error: Can't figure out which ctor to call.

### ISSUE THREAD

**Issue by slideep** [Azure/Azure-Functions#277] opened 2017-05-11 12:39 UTC
Azure Functions CLI 1.0.0-beta.96
VS Community 2017 Preview Version 15.3 (26507.0-Preview)  Preview
VS2017 Tools for Azure Functions (Version 0.1)

Hey there,
Any idea why this function's signature with collector based `ServiceBus` attribute isn't generating a proper function for the host and isn't found? Am I missing something obvious here??

[11/05/2017 12.16.58] Generating 2 job function(s)
[11/05/2017 12.16.59] Starting Host (HostId=afterdark-1340788863, Version=1.0.10955.0, ProcessId=9512, Debug=False, Attempt=0)
[11/05/2017 12.16.59] Found the following functions:
[11/05/2017 12.16.59] Host.Functions.REDACTED
[11/05/2017 12.16.59] Host.Functions.REDACTED

```
[FunctionName("OperatingStatusTrigger")]
        public static async Task ProcessOperatingStatusAsync(
            [TimerTrigger("0 */1 * * * *")]TimerInfo operatingStatusTimer,
            [Table("OperatingStatus")]IQueryable<OperatingStatusEntity> operatingStatusBinding,
            [ServiceBus("fan-out-distributor", AccessRights.Manage, "MicrosoftServiceBusConnectionStringName")]IAsyncCollector<BrokeredMessage> notificationMessages)
        {
            // ..
        }
```

[11/05/2017 12.17.23] Job host started
[11/05/2017 12.17.23] The following 1 functions are in error:
[11/05/2017 12.17.23] OperatingStatusTrigger: Can't figure out which ctor to call.

**Comment by lindydonna** [comment] 2017-05-11 20:19
Could you post the contents of function.json from your bin folder?

**Comment by slideep** [comment] 2017-05-11 20:32
Sure thing, `AccessRights` param and `Connection` props were missing from the original comment but adding those didn't seem to change the situation from earlier today:

```
{
  "bindings": [
    {
      "type": "timerTrigger",
      "schedule": "0 */1 * * * *",
      "useMonitor": true,
      "runOnStartup": false,
      "direction": "in",
      "name": "operatingStatusTimer"
    },
    {
      "type": "table",
      "tableName": "OperatingStatus",
      "direction": "out",
      "name": "operatingStatusBinding"
    },
    {
      "type": "serviceBus",
      "queue": "fan-out-distributor",
      "connection": "MicrosoftServiceBusConnectionStringName",
      "entityType": "queue",
      "access": "manage",
      "direction": "out",
      "name": "notificationMessages"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\RedactedFunctions.dll",
  "entryPoint": "RedactedFunctions.OperatingStatusTrigger.ProcessOperatingStatusAsync"
}
```

**Comment by lindydonna** [comment] 2017-05-11 20:35
So the issue is that the function is not listed when it says what functions were found?  I'm a little confused because they are "redacted" in your original post.

**Comment by slideep** [comment] 2017-05-11 20:45
Host finds the other two functions just fine. 

```
[11/05/2017 20.38.29] Generating 2 job function(s)
[11/05/2017 20.38.30] Starting Host (HostId=afterdark-1340788863, Version=1.0.10955.0, ProcessId=21140, Debug=False, Attempt=0)
[11/05/2017 20.38.30] Found the following functions:
[11/05/2017 20.38.30] Host.Functions.FDPAutoForwarderTrigger
[11/05/2017 20.38.30] Host.Functions.FDPPurgeEventsDlqTrigger
[11/05/2017 20.38.30]
[11/05/2017 20.38.30] Executing HTTP request: {
[11/05/2017 20.38.30]   "requestId": "bcc96d47-ae69-4d78-a023-c5b5fc1242ae",
[11/05/2017 20.38.30]   "method": "GET",
[11/05/2017 20.38.30]   "uri": "/"
[11/05/2017 20.38.30] }
[11/05/2017 20.38.30] Executed HTTP request: {
[11/05/2017 20.38.30]   "requestId": "bcc96d47-ae69-4d78-a023-c5b5fc1242ae",
[11/05/2017 20.38.30]   "method": "GET",
[11/05/2017 20.38.30]   "uri": "/",
[11/05/2017 20.38.30]   "authorizationLevel": "Anonymous"
[11/05/2017 20.38.30] }
[11/05/2017 20.38.30] Response details: {
[11/05/2017 20.38.30]   "requestId": "bcc96d47-ae69-4d78-a023-c5b5fc1242ae",
[11/05/2017 20.38.30]   "status": "OK"
[11/05/2017 20.38.30] }
Debugger listening on [::]:5858
[11/05/2017 20.39.02] Executing 'Functions.FDPPurgeEventsDlqTrigger' (Reason='New ServiceBus message detected on 'somequeue/$DeadLetterQueue'.', Id=795faf5b-f669-4d6f-aa63-925fc9864ad5)
[11/05/2017 20.39.02] Job host started
[11/05/2017 20.39.02] Function started (Id=795faf5b-f669-4d6f-aa63-925fc9864ad5)
[11/05/2017 20.39.02] The following 1 functions are in error:
[11/05/2017 20.39.02] OperatingStatusTrigger: Can't figure out which ctor to call.
```

**Comment by lindydonna** [comment] 2017-05-11 20:52
@slideep Got it, it is probably a serialization problem with function.json. Looking at that output, it looks like it generated the wrong property for "queue", it should be "queueName" instead. Could you try manually changing it in function.json and see if that fixes it?

**Comment by slideep** [comment] 2017-05-11 21:08
That did the trick, I modified function.json after the job host started. The generated "queue" --> "queueName" and "access" --> "accessRights" (at least intellisense kicked in to suggest these). Now it finds all functions and gets triggered. Whole bunch of other exceptions but those are clear where they raise themselves. 👍

**Comment by lindydonna** [comment] 2017-05-11 21:09
Yes, I can repro it myself as well. I'm going to file a new issue in https://github.com/Azure/azure-functions-vs-build-sdk/

Thanks for the bug report!

**Comment by lindydonna** [comment] 2017-05-11 21:11
Closing in favor of https://github.com/Azure/azure-functions-vs-build-sdk/issues/40

**Closed by lindydonna** 2017-05-11 21:11 UTC
Labels: bug, Visual Studio

**Comment by slideep** [comment] 2017-05-11 21:13
Glad to help out, I'm gonna call it a night and continue tomorrow migrating other functions as well.
