### ISSUE TITLE
[Premium] Function App errors when storage account has VNET ACL

### ISSUE THREAD

**Issue by ishepherd** [Azure/Azure-Functions#1349] opened 2019-10-03 04:18 UTC
We want to add a VNET ACL to the storage account used by a function app

The networking page says this can be done, if you can wait 12 hours: https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options#restricting-your-storage-account-to-a-virtual-network, 

We've found it doesn't work. Gives access denied trying to access **D:\home\LogFiles\Application\Functions\Host**

Actually, the page I linked to above explains this error:

> There are some things that VNet Integration doesn't support including:
> Mounting a drive

Can this be fixed? We have a requirement to lock down all resources.

**Comment by ishepherd** [comment] 2019-10-10 02:48
paraphrasing off-thread with @alexkarcher-msft: This is supposed to work - if left alone long enough. The documentation point "doesn't support ... Mounting a drive" is unrelated.

I will see if I can repro the issue.

**Comment by ishepherd** [comment] 2019-10-15 23:10
@alexkarcher-msft I have a repro for this now.
UnauthorizedAccessExceptions for 16 hours and counting.

```
Access to the path 'D:\home\LogFiles\Application\Functions\Host' is denied. 

System.UnauthorizedAccessException:
   at System.IO.FileSystem.CreateDirectory (System.IO.FileSystem, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.Directory.CreateDirectory (System.IO.FileSystem, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.Abstractions.DirectoryWrapper.CreateDirectory (System.IO.Abstractions, Version=2.1.0.227, Culture=neutral, PublicKeyToken=96bf224d23c43e59)
   at Microsoft.Azure.WebJobs.Script.FileUtility.EnsureDirectoryExists (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script\Extensions\FileUtility.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 38)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeFileSystem (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 433)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.PreInitialize (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 425)
   at Microsoft.Azure.WebJobs.Script.ScriptHost+<InitializeAsync>d__80.MoveNext (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 256)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.ScriptHost+<StartAsyncCore>d__79.MoveNext (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 237)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__9.MoveNext (Microsoft.Extensions.Hosting, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService+<UnsynchronizedStartHostAsync>d__37.MoveNext (Microsoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 209)
```

![image](https://user-images.githubusercontent.com/3198421/66876247-e0926b80-effc-11e9-9c4f-885efbc195cf.png)

**Comment by ishepherd** [comment] 2019-10-15 23:11
Restarted the app to see if that helps.

**Comment by ishepherd** [comment] 2019-10-17 04:36
Off-thread with @alexkarcher-msft: The issue is understood and a fix is coming

Alex you might consider updating [the relevant doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options#restricting-your-storage-account-to-a-virtual-network) in the meantime - Cheers

**Comment by alexkarcher-msft** [comment] 2019-10-17 18:13
Good call out! I have a PR out to update the docs

https://github.com/MicrosoftDocs/azure-docs-pr/pull/92236

**Comment by ishepherd** [comment] 2019-10-30 00:44
@fabiocav you closed this, but @alexkarcher-msft is the fix still coming? How will we know when it's arrived?

**Comment by alexkarcher-msft** [comment] 2019-10-30 18:57
Ah, sorry. I confused this with a separate issue. We identified a workaround for this scenario, and need to fully document it.

It looks like you can connect to a secured storage account using run from package as a URL and that will allow your code to be stored in a VNET secured storage account 
https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enabling-functions-to-run-from-a-package

With that configuration you will need a separate storage account with just your code as a zip. Then, you should be able to secure your other account with VNET service endpoints. 

I haven't had a chance to test this configuration, but this is the current workaround we're tracking :)

**Comment by ishepherd** [comment] 2019-10-30 20:59
Thanks @alexkarcher-msft 

Good that there's a workaround but anything that compromises reliability is a no-go - Below re an incident we had on 2019-05-28, investigated by @FinVamp1. Also your link notes the impact on cold start performance which is not great either.

Will we be able to use `WEBSITE_RUN_FROM_PACKAGE = 1` and any guesses on ETA?

----

> For the 404 issue on the 28th of May three of the four workers assigned to the site ran into this pattern.
> 1) The worker is assigned.
> 2) It goes to download the Zip file from Storage for the application.
> 3) The Storage Account takes time to respond (up to 29 seconds on two of the instances.)
> 4) The Zip download fails.
> 5) A file called "FAILED TO DOWNLOAD ZIP FILE.txt" is created at D:\Home\Site\wwwroot
> 6) As we have no Host.json we create an empty one.
> 7) We cannot save this to disk as D:\Home\Site\wwwrot is still read only.
> 8) We send requests to this worker anyway and these return a 404.

**Comment by deyanp** [comment] 2020-05-06 12:12
@alexkarcher-msft , is it still not possible to secure the underlying storage account of a (Premium Plan) Function App with Vnet integration? 
How should I undrestand "wait 12h" - we cannot have a downtime for 12h if func app cannot connect to storage account ... 
Is WEBSITE_RUN_FROM_PACKAGE = 1 the only way how this can work? I understand it is not recommended due to cold start issues, or is it fine for Premium Plan Function Apps?

**Comment by jeffhollan** [comment] 2020-05-06 14:26
At this moment you shouldn’t need to wait for the VNet routes to establish when adding a service endpoint / private link service to call from your function. However, you still need some storage account that doesn’t have a VNet for the WEBSITE_CONTENTFILECONNECTIONSTRING app setting. That’s where your code is stored when doing general publish gestures (anything but run from package = some URL to a zip file). The feature to allow even that storage account to be behind a VNet via private link is checked in and rolling out in our next platform update. Likely about 2 months out.

**Comment by deyanp** [comment] 2020-05-07 06:16
@jeffhollan  this is great news, assuming I got it correctly - we will be finally able to network/firewall-secure (using service endpoints and vnet integration) the underlying storage account of a function app in 2 months!

**Comment by alexandrelimait** [comment] 2020-06-18 09:35
Any updates?
service endpoint for storage accounts and KeyVault really impact many customers.

**Comment by justinimel** [comment] 2020-09-01 04:40
Same Issue

**Comment by Carrie810** [comment] 2020-09-12 03:01
I got the same issue

**Comment by jeffhollan** [comment] 2020-09-12 03:17
Still coming - best ETA would be end of this year. We hit an issue with the deployment for the earlier ETA so doing a bit phased rollout later this year

**Comment by teamcitytest3** [comment] 2020-10-13 07:22
same issue

**Comment by fanasere** [comment] 2020-10-18 08:29
same issue

**Comment by jeffhollan** [comment] 2020-10-28 17:09
Heads up preview just went live for West Europe - let us know if you have any issues with this and hope to push it out globally in the coming weeks https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options#restrict-your-storage-account-to-a-virtual-network-preview

**Comment by JamesDLD** [comment] 2020-11-24 10:41
Same issue [here](https://github.com/JamesDLD/TagWithCreator/blob/master/environment/deploy.ps1#L28-L42), will follow this issue.

**Comment by VishalNagarAR** [comment] 2020-12-17 14:37
Thanks @jeffhollan for mentioning that link. I have my solution for West Europe and it did work.
Following changes were done in function appsettings to make it work.

WEBSITE_CONTENTOVERVNET = 1.
WEBSITE_VNET_ROUTE_ALL = 1.
WEBSITE_DNS_SERVER =168.63.129.16.

**Comment by knaidoo33** [comment] 2020-12-28 17:34
I have this issue as well. @jeffhollan, will the preview be available globally soon? I am in West US 2 and would like to try it.

**Comment by jeffhollan** [comment] 2021-02-05 00:09
Just updating - this is now GLOBAL, and generally available.

**Comment by Bunzab** [comment] 2021-02-17 19:29
> Just updating - this is now GLOBAL, and generally available.
Any ETA on when this will support Linux Plans please?

**Comment by blueelvis** [comment] 2021-02-28 17:59
@jeffhollan - I am still not able to get this working with a storage account secured by Private Endpoint. I did create a PV3 App Service plan (To ensure we are on the latest scale unit) and then scaled it to EP1 using ARM Template but I still keep on getting -
```
Access to the path 'C:\home\site\wwwroot' is denied.
System.Private.CoreLib: Access to the path 'C:\home\site\wwwroot\host.json' is denied.

```

I have the following App Settings in place -
```
- AzureWebJobsStorage
- WEBSITE_CONTENTAZUREFILECONNECTIONSTRING
- WEBSITE_CONTENTOVERVNET = 1
- WEBSITE_VNET_ROUTE_ALL = 1
```
Both `AzureWebJobsStorage` & `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` are backed by a Storage Account which is accessible only over a Private Endpoint.
Here is the support ticket # for reference - 2102280040000493

Thanks,
Pranav

**Comment by ketaanhshah** [comment] 2021-07-10 01:39
I am facing same issue  here with my STORAGE account in the SAME subnet as my Function App but still the same error and it seems @jeffhollan and other Microsoft folks have gone total sleep mode on this issue with no response for such a basic feature where the documentation lacks basic step by step guidance. Folks we are in field trying to use the product as designed and it is not working it would be great if you can provide some help. This is such a basic thing where the Function App (with Vnet/SubNet private end point enabled) with the STORAGE account within the same Vnet/Sub-net and still it doenst work. Can you please help? I know you have some priorities but a basic feature like this is not working and believe me there is no simple step by step documentation for this as well. Appreciate if you can provide some guidance as we are facing heat from customer for things not working.

**Comment by ketaanhshah** [comment] 2021-07-10 15:19
@blueelvis I am facing the same issue and I am not sure if your support ticket got any resolution? Can you please share if there was any resolution. I am facing exactly same issue as you are having and its now July 2021 and I have ensured the configuration have all those App settings as well. @jeffhollan any help on this please?

![image](https://user-images.githubusercontent.com/12475114/125167885-b7baee00-e170-11eb-9bde-3a1e122c424f.png)

**Comment by ketaanhshah** [comment] 2021-07-10 20:16
Resolved:  it seems that adding the "WEBSITE_RUN_FROM_PACKAGE" = 1 app settings to the Function App settings gets rid of that error.

**Comment by judedaryl** [comment] 2021-08-25 12:56
@ketaanhshah did you run into a 503 error on the scm? i get service unavailable the function app gets created

**Comment by victormendozalex** [comment] 2021-09-08 07:50
> @blueelvis I am facing the same issue and I am not sure if your support ticket got any resolution? Can you please share if there was any resolution. I am facing exactly same issue as you are having and its now July 2021 and I have ensured the configuration have all those App settings as well. @jeffhollan any help on this please?
> 
> ![image](https://user-images.githubusercontent.com/12475114/125167933-f9e42f80-e170-11eb-80a7-3a5d7b64ad86.png)

This helped me.

**Comment by ben-002** [comment] 2021-09-22 14:26
We are facing the same error in a function with a dedicated App service plan in production.  

We have a storage account that we secured and had no problems in the staging environments.  Our staging environments use a dedicated app service plan as well, but is not a premium: tier - Standard, size -S1 , capacity - 1. 
However, the above mentioned error appeared in production: tier - PremiumV2, size -P1v2 , capacity - 2.  

We had to revert the security changes in prod and now I'm trying to reproduce the problem in staging but it seems to be really tricky. I have not managed to reproduce the error even after scaling up the staging environment to a premium tier. Does anyone have any suggestions? I can't try the fixes from this thread until I am able to check if they fix the problem or not. And I can't do this in prod.

**Comment by apsi15** [comment] 2021-11-30 07:36
Same issue here. I am deploying both the function app and it's staging deployment slot through terraform using the Elastic Premium Linux. The deployment slot is working fine, but somehow the production slot is not able to reach the storage account. Disabling the vnet integration and network deny in the storage account bring the function back online. The settings are the same as @ketaanhshah posted. The NSG, Service Endpoints are configured correctly (tested it with SSH tcpping).
I feel like the CONTENTSHARE is not suitable for the scenario where the SA configured with deny rule, or at least not suitable for File Share, since the WebJobsStorage configuration is reachting the blobs behind a firewall.

**Comment by Nagipenugonda** [comment] 2021-12-13 01:41
Any updates on this issues? 

Run Azure/functions-action@v1
Using RBAC for authentication, GitHub Action will perform resource validation.
Successfully acquired site configs from function app!
Detected function app sku: Dedicated
Successfully acquired app settings from function app (RBAC)!
Detected function app language: Java
Will archive ./lastfunczip/target/azure-functions/cig-loy-tx-sprt into /home/runner/work/_temp/temp_web_package_880814317781418.zip as function app content
Will use https://<scmsite>/api/zipdeploy to deploy since RBAC Azure credential is detected.
Package deployment using ZIP Deploy initiated.
Error: Failed to deploy web package to App Service.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_880814317781418.zip as ZipDeploy content
Error:     Failed to deploy web package to App Service.
Internal Server Error (CODE: 500)
Error:       Error: Failed to deploy web package to App Service.
Internal Server Error (CODE: 500)
    at Kudu.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:175:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Deployment Failed!

when I allow all network to storage Github actions pipeline was working fine But I can't let my storage account open for PROD.

**Comment by CristianDorinFlorea** [comment] 2021-12-22 10:48
I'm facing the same issue. Any updates on this?

**Comment by Nagipenugonda** [comment] 2021-12-22 15:29
> I'm facing the same issue. Any updates on this?

 1 - Delete away WEBSITE_CONTENTSHARE, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING, VNETROUTEALL, DNS from your app settings if you're using dedicated service plan (premium)
Add this setting WEBSITE_CONTENTOVERVNET.

 2 - Under function app look for properties it will show you public IP.  Add that public ip under your storage account.

3 - Connect with Microsoft support they will check your resources health status.

**Comment by albernhagen** [comment] 2022-08-17 16:33
I'm also running into this exact same issue specifically for windows premium tier function apps.  Did anyone ever find a resolution?

**Comment by jjohnstonspm** [comment] 2022-08-18 15:21
Was there recently a change or regression here? I had it working for the last few weeks, then suddenly all of my functions were unable to access their storage accounts on a VNET for this reason. I've been unable to get them to communicate with the storage accounts short of turning on Public Access for All Networks.

**Comment by albernhagen** [comment] 2022-08-18 15:33
> Was there recently a change or regression here? I had it working for the last few weeks, then suddenly all of my functions were unable to access their storage accounts on a VNET for this reason. I've been unable to get them to communicate with the storage accounts short of turning on Public Access for All Networks on the Storage Account.

Maybe that explains why I lost so many hours to this using configuration that was supposed to work.  For what it's worth, I found a workaround by enabling service endpoints in the subnet.  I have both private endpoints and service endpoints setup for the azure storage account.  It's working in that deploys are succeeding and the function runs normally, but it's far from the preferred configuration.

**Comment by jjohnstonspm** [comment] 2022-08-18 17:59
That has not worked for me. Once the Azure Function launches (and presumably mounts its File System), it operates fine even if I make my Storage Account network access private, but if I restart the Function for any reason, it is dead again (even with Service Endpoints enabled).

**Comment by marcelovital** [comment] 2023-04-11 10:33
> > I'm facing the same issue. Any updates on this?
> 
> 1 - Delete away WEBSITE_CONTENTSHARE, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING, VNETROUTEALL, DNS from your app settings if you're using dedicated service plan (premium) Add this setting WEBSITE_CONTENTOVERVNET.
> 
> 2 - Under function app look for properties it will show you public IP. Add that public ip under your storage account.
> 
> 3 - Connect with Microsoft support they will check your resources health status.

`WEBSITE_CONTENTOVERVNET = 1` did the trick for me, while using an Elastic Premium EP1 tier for Azure Function and a Storage Account with restricted permissions. 

In a summary:
Make sure you have VNet integration configured in the Networking section of the Azure Function
Make sure that same subnet is allowed in the Networking section of the Storage Account
Add WEBSITE_CONTENTOVERVNET to your Azure Function configuration

**Comment by FinVamp1** [comment] 2023-04-18 16:13
Hi, thanks for all of the input on this thread. We've updated the docs to ensure that that the majority of scenarios that people see are covered. [How to Configure Azure Functions for a Vnet](https://learn.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to?tabs=portal) . I'll close this thread now.

**Closed by FinVamp1** 2023-04-18 16:13 UTC
Labels: premium-plan
