### ISSUE TITLE
Azure Function does not start

### ISSUE THREAD

**Issue by michelpf** [Azure/Azure-Functions#630] opened 2017-12-18 11:24 UTC
I created some functions which were running very well, but with no reason, stop working.
Tried to stop, start, restart and even create a new Azure Function instance/app. No success. I always got same error.

Just to isolated algorithms, I created a new function from template. The error log follows, as same as the other functions:

2017-12-18T11:16:57  Welcome, you are now connected to log-streaming service.
2017-12-18T11:17:14.199 Function started (Id=feb1af99-cc69-4585-b07d-ce2154979291)
2017-12-18T11:17:14.215 Executing 'Functions.SimpleTest' (Reason='This function was programmatically called via the host APIs.', Id=feb1af99-cc69-4585-b07d-ce2154979291)
2017-12-18T11:17:14.496 A ScriptHost error has occurred
2017-12-18T11:17:14.496 
**2017-12-18T11:17:14.543 Exception while executing function: Functions.SimpleTest. Microsoft.Azure.WebJobs.Script: .**
2017-12-18T11:17:14.199 Function started (Id=feb1af99-cc69-4585-b07d-ce2154979291)
2017-12-18T11:17:14.543 Exception while executing function: Functions.SimpleTest. Microsoft.Azure.WebJobs.Script: .
2017-12-18T11:17:14.652 Function completed (Failure, Id=feb1af99-cc69-4585-b07d-ce2154979291, Duration=453ms)

**Comment by kashimiz** [comment] 2017-12-18 22:25
Can you share the name of your Functions app with us? If you'd prefer to do so anonymously, [please follow the instructions here.](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately)

**Comment by michelpf** [comment] 2017-12-19 10:02
Hi, follow the infos:

2017-12-19T10:01:11.081 Id=85252614-364b-42a3-a441-5b9464e9322d
Central South US

**Comment by dariagrigoriu** [comment] 2019-02-15 00:53
Closing this due to lack of recent activity, please revisit if the issue is still relevant.

**Closed by dariagrigoriu** 2019-02-15 00:53 UTC

**Comment by michelpf** [comment] 2019-02-15 12:30
After the tests, I was able to install additional files of NLTK in current function folder:

`nltk.download('stopwords', download_dir='')`

Then, at the begining of my function (`__init__.py`):

```
import nltk
nltk.data.path.append("/")
```

Anyway, thanks all for supporting me.
