### ISSUE TITLE
[Visual Studio] What is the function of the "data" and "secrets" folders?

### ISSUE THREAD

**Issue by michaeldaw** [Azure/Azure-Functions#121] opened 2017-01-01 22:40 UTC
When using a Functions project in Visual Studio, the project automatically adds a "data" and "secrets" folder. They don't seem to do anything. Can future versions of the tooling leave this out?

**Comment by lindydonna** [comment] 2017-01-03 20:07
This is a duplicate of these bugs: https://github.com/Azure/azure-webjobs-sdk-script/issues/945 and https://github.com/Azure/azure-webjobs-sdk-script/issues/946

We haven't yet done a release with the fix, but you'll see the fix in version 0.10 of the CLI.

**Closed by lindydonna** 2017-01-03 20:07 UTC

**Comment by michaeldaw** [comment] 2017-01-03 20:08
Thanks for clarifying.
