### ISSUE TITLE
Unable to delete function

### ISSUE THREAD

**Issue by brettsam** [Azure/Azure-Functions#371] opened 2017-07-03 13:10 UTC
Spawned from: https://github.com/Azure/azure-webjobs-sdk-script/issues/1621#issuecomment-312445052

**Comment by brettsam** [comment] 2017-07-03 13:11
@spelltwister: Could you share your function app name -- either directly or indirectly? We can look at our logs to see what may be the problem.

**Comment by spelltwister** [comment] 2017-07-04 18:58
ghsprouts2

**Comment by brettsam** [comment] 2017-07-05 18:03
@spelltwister -- is your issue deleting the function itself or the entire app? Are you doing this via the portal?

**Comment by spelltwister** [comment] 2017-07-08 01:46
I just tried again and it deleted.  The function app with the above name would not delete the past weeks that I've tried.  Using the delete button in the portal with the function app blade open, it would appear in my alerts as "Deleting app ghsprouts..." and spin for few hours.  I tried this several times.  This time it promptly refreshed with the app deleted.

**Comment by lindydonna** [comment] 2017-07-18 20:44
Closing since the issue is now resolved.

**Closed by lindydonna** 2017-07-18 20:44 UTC

**Comment by ssashok10** [comment] 2018-05-31 21:36
I have the same issue. I am trying to delete a FunctionApp through portal and its spinning couple of hours already. I am not sure how long more I need to wait.
