### ISSUE TITLE
how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/Azure-Functions#465] opened 2017-08-29 15:58 UTC
hi,

am working with new azure functions in vs2017 release version.
am getting file not found errors.   my project setup is like this 
a. functionproj (4.6.1) -> uses -> dataserviceproj (netstandard1.3)  

But when i create new console app targeting 4.6.1 and add reference to dataserviceproj it works fine.

for now am using solution given here to do binding redirect using reflection.

https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/

please advise.

thanks

**Comment by tomkerkhove** [comment] 2017-08-30 14:29
Looks like duplicate of #387 which was closed unfortunately.
Are you using Newtonsoft.Json with a different version?

**Comment by krishnasingh1818** [comment] 2017-09-01 01:33
yes. external libs have different versions

**Comment by tomkerkhove** [comment] 2017-09-01 06:00
Then you'll have to follow the thread here: https://github.com/Azure/azure-webjobs-sdk-script/issues/992

**Comment by alexkarcher-msft** [comment] 2019-02-20 23:24
this has been fixed in Azure Functions v2, as per https://github.com/Azure/azure-functions-host/issues/992

**Closed by alexkarcher-msft** 2019-02-20 23:24 UTC
