### ISSUE TITLE
Can't disable an Azure function that has a hyphen in its name

### ISSUE THREAD

**Issue by m3talstorm** [Azure/Azure-Functions#1851] opened 2021-02-24 18:25 UTC
**From within the Azure Portal:**
- Create a function app (e.g `some-app` using App Service Plan)
- Create a function within the app with a hyphen in the name (e.g `some-app-function`)
- Navigate `Functions` > `some-app-function` and press the "Disable" button
- You will get an error in the top right of the portal "Failed to disable function" (error will be malformed)
- Look at the request/response it is doing, you will get:
`Message: "AppSetting with name 'AzureWebJobs.some-app-function.Disabled' is not allowed."`
- Navigate back to your Function app > `Configuration`
- Add a new application setting with a value the same as above `AzureWebJobs.some-app-function.Disabled`
- You will get the frontend validation message:
`App setting names can only contain letters, numbers (0-9), periods ("."), and underscores ("_")`

**Comment by balag0** [comment] 2021-02-24 20:09
Could you check if any of the other methods work for you - https://docs.microsoft.com/en-us/azure/azure-functions/disable-function

**Comment by v-anvari** [comment] 2021-04-26 08:02
Closing this issue as there is no response. Please feel free to reach back to us or re-open this issue in case of any queries.

**Comment by m3talstorm** [comment] 2021-04-26 14:21
The bug still stands

**Comment by v-anvari** [comment] 2021-04-26 14:33
Hi @m3talstorm , We have tried to replicate this issue but unable to reproduce it. Can you let us know if you have submitted a support request earlier? If not, can you create one, so that the support team can check the issues with your account. 
Do let us know if you find any trouble. 

Azure Portal > Help and support ? New support request

Thank you.

**Comment by m3talstorm** [comment] 2021-04-26 15:46
@v-anvari I have not created a support request, just this bug report.

Feel free to pass this on to the relevant team(s).

I highly doubt this would be an account-specific issue.

**Comment by v-anvari** [comment] 2021-04-26 15:49
Hi @m3talstorm , The support ticket is to be created through your portal, so please go ahead and create one from your account. We wouldn't be able to tell the issue if it is account specific.

**Comment by m3talstorm** [comment] 2021-04-26 16:12
@v-anvari I do not have permissions to create a support request within our client's subscription.

I have provided as much information as I can, I cannot take any further steps.

**Comment by v-anvari** [comment] 2021-04-26 16:14
Thank you for the update. 

@balag0 , Can you please suggest what could be done

**Comment by balag0** [comment] 2021-04-26 17:18
@v-anvari Was the app you tested with using Windows or Linux? If we haven't done it already, could we try with both to see if we can repro it?

**Comment by v-anvari** [comment] 2021-04-28 12:00
Hi @balag0 , I am able to repro this only in linux applications. The App settings do not allow few of the special characters for linux Apps.

### **Windows:**

![image](https://user-images.githubusercontent.com/66122429/116398628-a5096c00-a845-11eb-9e60-e37f427beef0.png)

![image](https://user-images.githubusercontent.com/66122429/116399098-2c56df80-a846-11eb-824a-4bfaf8d5995b.png)

**App settings for windows** :  ![image](https://user-images.githubusercontent.com/66122429/116399123-35e04780-a846-11eb-987f-5c594ef22f4b.png)


### **Linux :**
![image](https://user-images.githubusercontent.com/66122429/116399691-d171b800-a846-11eb-9c61-8b6e2fbaec43.png)

**App settings for Linux** ![image](https://user-images.githubusercontent.com/66122429/116399788-ed755980-a846-11eb-9734-3f7ff541d274.png)

**Comment by v-anvari** [comment] 2021-06-16 11:29
Hi @m3talstorm , This issue has been identified and is being investigated for fix. For now, this issue is by design for Linux and is being discussed on the fix.  

**Investigation incident** - https://portal.microsofticm.com/imp/v3/incidents/details/242098161/home

Closing this issue as further updates will be provided in the tracking incident, please feel free to reach back to us in case of any further queries related to this issue

**Closed by v-anvari** 2021-06-16 11:29 UTC

**Comment by scott-alvis** [comment] 2022-04-26 01:00
Why is this closed it still an open issue?

**Comment by ormu5** [comment] 2022-12-31 19:25
Interestingly, I deployed the following with terraform in my linux function app settings:

```
"AzureWebJobs.fetch-and-publish.Disabled" = "true",
"AzureWebJobs.subscribe-and-send.Disabled" = "false",
"AzureWebJobs.receive-and-insert.Disabled" = "false",
```
and it _succeeded_ in disabling 'fetch-and-publish'.

Follow-up az cli commands, though, led to a vague "Operation returned an invalid status 'Bad Request'" behind which was the subject error:

```
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"Code":"BadRequest","Message":"AppSetting with name 'AzureWebJobs.fetch-and-publish.Disabled' is not allowed.","Target":null,"Details":[{"Message":"AppSetting with name 'AzureWebJobs.fetch-and-publish.Disabled' is not allowed."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"04072","MessageTemplate":"AppSetting with name '{0}' is not allowed.","Parameters":["AzureWebJobs.fetch-and-publish.Disabled"],"Code":"BadRequest","Message":"AppSetting with name 'AzureWebJobs.fetch-and-publish.Disabled' is not allowed."}}],"Innererror":null}
```

**Comment by ssssssseb** [comment] 2023-09-11 10:22
Just ran into this issue as well. Please fix, Azure

**Comment by getstoopid** [comment] 2026-04-07 11:10
2026 and still an issue =/ Please fix it already!
