### ISSUE TITLE
Nuget restore failing with error "The user name or password is incorrect."

### ISSUE THREAD

**Issue by tohling** [Azure/Azure-Functions#590] opened 2017-11-14 22:41 UTC
During Nuget restore operations, customers are periodically seeing the error 

**"The user name and password is incorrect."**

**Comment by tohling** [comment] 2017-11-14 22:42
We are investigating this and will update the thread as soon as we have more information.

**Comment by paulbatum** [comment] 2017-11-14 23:14
Here is some sample log output when this error occurs:

```
2017-11-13T19:48:53.732 Installing WindowsAzure.Storage 7.2.1.
2017-11-13T19:48:53.794 Installing Microsoft.Bot.Builder 3.9.0.0.
2017-11-13T19:48:53.825 Installing Microsoft.Azure.DocumentDB 1.11.0.
2017-11-13T19:48:53.982 Installing Microsoft.Bot.Builder.History 3.0.6.
2017-11-13T19:49:13.403 The user name or password is incorrect.
2017-11-13T19:49:13.423 
2017-11-13T19:49:13.423 
2017-11-13T19:49:13.434 Packages restored.
2017-11-13T19:49:23.325 Function compilation error
```

**Comment by davidebbo** [comment] 2017-11-14 23:57
Though the scenario is quite different, https://github.com/projectkudu/kudu/issues/2622 likely has the same root cause.

**Comment by davidebbo** [comment] 2017-11-15 00:01
Also, from StackOverflow: https://stackoverflow.com/questions/47295401/azure-function-nuget-cache-restore-failing-with-the-user-name-or-password-is-in

**Comment by dersia** [comment] 2017-11-15 22:57
I just ran into the same issue. For me it came up while trying to add ```System.Runtime.Serialization.Formatters 4.0.0.0```

Once I realized that the version I was looking for instead was 4.0.1.0, I stopped getting that error.

@paulbatum maybe you can check the versions that you are trying to add, if they're available?

**Comment by davidebbo** [comment] 2017-11-15 23:13
@dersia that's odd, and I'm thinking this might be coincidental, and that this assembly version does not matter.

**Comment by barissaydag** [comment] 2017-11-16 01:26
For what it is worth, I want to confirm that I am getting the same error. 

> 2017-11-16T00:44:29.544 OK https://api.nuget.org/v3-flatcontainer/edjcase.jsonrpc.client/index.json 273ms
> 2017-11-16T00:44:29.544 GET https://api.nuget.org/v3-flatcontainer/edjcase.jsonrpc.client/1.3.1/edjcase.jsonrpc.client.1.3.1.nupkg
> 2017-11-16T00:44:29.786 OK https://api.nuget.org/v3-flatcontainer/edjcase.jsonrpc.client/1.3.1/edjcase.jsonrpc.client.1.3.1.nupkg 231ms
> 2017-11-16T00:44:29.848 GET https://api.nuget.org/v3-flatcontainer/edjcase.jsonrpc.core/index.json
> 2017-11-16T00:44:30.000 OK https://api.nuget.org/v3-flatcontainer/bouncycastle/1.8.1/bouncycastle.1.8.1.nupkg 956ms
> 2017-11-16T00:44:30.074 OK https://api.nuget.org/v3-flatcontainer/edjcase.jsonrpc.core/index.json 228ms
> 2017-11-16T00:44:30.090 GET https://api.nuget.org/v3-flatcontainer/edjcase.jsonrpc.core/1.3.1/edjcase.jsonrpc.core.1.3.1.nupkg
> 2017-11-16T00:44:30.143 OK https://api.nuget.org/v3-flatcontainer/edjcase.jsonrpc.core/1.3.1/edjcase.jsonrpc.core.1.3.1.nupkg 63ms
> 2017-11-16T00:44:30.268 Installing EdjCase.JsonRpc.Core 1.3.1.
> 2017-11-16T00:44:30.880 Installing EdjCase.JsonRpc.Client 1.3.1.
> 2017-11-16T00:44:31.425 Installing Nethereum.RLP 2.1.0.
> 2017-11-16T00:44:31.722 Installing BouncyCastle 1.8.1.
> 2017-11-16T00:44:31.894 Installing Nethereum.JsonRpc.Client 2.1.0.
> 2017-11-16T00:44:32.276 Installing Nethereum.JsonRpc.RpcClient 2.1.0.
> 2017-11-16T00:44:32.698 Installing Nethereum.KeyStore 2.1.0.
> 2017-11-16T00:44:33.120 Installing Nethereum.Signer 2.1.0.
> 2017-11-16T00:44:33.385 Installing Nethereum.ABI 2.1.0.
> 2017-11-16T00:44:33.656 Installing Nethereum.Util 2.1.0.
> 2017-11-16T00:44:34.140 Installing Nethereum.RPC 2.1.0.
> 2017-11-16T00:44:34.515 Installing Nethereum.Hex 2.1.0.
> 2017-11-16T00:44:34.817 Installing Nethereum.Contracts 2.1.0.
> 2017-11-16T00:44:35.161 Installing Nethereum.Web3 2.1.0.
**> 2017-11-16T00:44:36.177 The user name or password is incorrect.**
> 2017-11-16T00:44:36.196 
> 2017-11-16T00:44:36.196 
> 2017-11-16T00:44:36.196 Packages restored.
> 2017-11-16T00:44:36.302 Function compilation error
> 2017-11-16T00:44:36.302 run.csx(10,7): error CS0246: The type or namespace name 'Nethereum' could not be found (are you missing a using directive or an assembly reference?)
> 2017-11-16T00:44:36.302 run.csx(26,5): error CS0246: The type or namespace name 'Accounts' could not be found (are you missing a using directive or an assembly reference?)

**Comment by davidebbo** [comment] 2017-11-16 04:32
Can you all try setting an Azure App Setting named `WEBSITE_USE_PLACEHOLDER`, with value `0`? With suspect that it will solve the issue.

**Comment by barissaydag** [comment] 2017-11-16 04:52
I set the key.

First of all, everything is just very slow. Even switching between functions, it takes forever to show the code even. When I tried to run it, I received this error: 

We are not able to get the key swaggerdocumentationkey. Please check the runtime logs for any errors or try again later.
Session Id: b63ce6c50eed47ea976e541d71c62729

Timestamp: 2017-11-16T04:50:34.264Z

**Comment by davidebbo** [comment] 2017-11-16 04:55
@barissaydag That's likely a just result of the app restarting after setting the app setting. Try closing the app and coming back to it and it should be ok.

**Comment by barissaydag** [comment] 2017-11-16 04:59
Yup, you were right. 

OK, I don't see the "The user name or password is incorrect" error anymore. Also, project.lock.json is being created. I am testing more. But so far it seems like it solved the problem.

**Comment by davidebbo** [comment] 2017-11-16 05:05
@barissaydag thanks for confirming! Note that you will get a slower cold start as a result of not having that flag (which may or may not matter, depending on scenario). We are working on fixing the root issue, though we don't yet have a clear ETA.

**Comment by barissaydag** [comment] 2017-11-16 05:30
No problem, thanks for helping despite the late hour. I am looking forward to the permanent fix of the root cause.

**Comment by brandonchastain** [comment] 2017-11-21 22:10
+1

Encountered the same problem, and the workaround above fixed it. Thanks!

**Comment by paulbatum** [comment] 2017-11-21 22:28
Just a quick update - we have a fix for this issue and its in our next deployment train. Current ETA for full global deployment of the fix is 12/4. Feel free to ping me on this issue if I have not sent another update by then. 

Once the fix is deployed, its important that you remove the workaround (setting WEBSITE_USE_PLACEHOLDER to 0) so that your function app gets good cold start performance.

**Comment by richard-spice** [comment] 2017-12-11 19:49
Also encountered the same problem and am using the workaround.  Is there any new information on the deployment status of the fix?  Was this pushed on 12/5?

**Comment by paulbatum** [comment] 2017-12-11 19:56
@richard-spice The deployment completed a few a days ago. If you are still getting this error then I need to investigate. Can you give me a UTC timestamp and the region? That should be enough for me to track it down.

**Comment by richard-spice** [comment] 2017-12-11 19:59
Thanks for the quick feedback. We're not experiencing the error at this time, but I didn't want to remove the the workaround setting until I saw confirmation that the fix was deployed.  We will make the change in the upcoming days, and I'll report back with the information you requested if there is a problem.  Thanks!

**Comment by paulbatum** [comment] 2017-12-11 21:53
Just to make it clear for readers of this thread:

**Fix is deployed globally. We now recommend removing the WEBSITE_USE_PLACEHOLDER=0 setting to ensure your application gets better cold start performance.**

@richard-spice good to hear. Sorry for not updating the thread when the deployment completed.

**Comment by anhashia** [comment] 2017-12-13 01:45
Hi @paulbatum 
Tested with following **project.json** and it works fine now :-)
`
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.Azure.Devices": "1.5.0-preview-001"
      }
    }
  }
}
`

**Comment by jeffhollan** [comment] 2018-01-09 00:59
@paulbatum can we close this now?

**Closed** 2018-01-09 01:48 UTC
Labels: bug

**Comment by macbe** [comment] 2018-01-28 21:37
@paulbatum we seem to be encountering this again. We're running an .exe in a Function and getting "The user name or password is incorrect". The error goes away when we set WEBSITE_USE_PLACEHOLDER to 0. UTC 2018-01-28T20:22:28.453Z in Australia East.

**Comment by davidebbo** [comment] 2018-01-28 23:21
@macbe Can you share your function app name (that's the **app** name, not function name!), either directly or [indirectly](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately)? This will help us investigate. Thanks!

**Comment by macbe** [comment] 2018-01-29 00:47
@davidebbo "volparafunctionapp1"

**Comment by kranthikumarm** [comment] 2018-01-29 01:24
@macbe To help us debug the issue, would it be possible for you to put the app back in a state where the issue is repro-ing? (You'll have to remove the WEBSITE_USE_PLACEHOLDER setting and trigger this function.) If this app is business-critical, would it be possible for you to set up a repro function app?

**Comment by macbe** [comment] 2018-01-29 01:42
@kranthikumarm It isn't business-critical so we're happy to repro using that app. We've now removed the WEBSITE_USE_PLACEHOLDER setting and the issue is back.

**Comment by kranthikumarm** [comment] 2018-01-29 02:30
@macbe Thank you! Unfortunately, I need the issue to repro-ing while I'm on the machine to collect some traces. The traces are very high-volume, so I can't collect them for more than a couple of minutes. I see that the issue hasn't repro-d since 2018-01-29 01:36 UTC. Would it be possible for you trigger the function at, say, 2018-01-29 02:50 UTC? I will start tracing at that time, and hopefully, I can catch the repro.

**Comment by kranthikumarm** [comment] 2018-01-29 02:43
@macbe I forgot to add, please let me know if there's a different time that's better for you.

**Comment by macbe** [comment] 2018-01-29 03:06
Sorry I missed that one. How about in 24 minutes time at 2018-01-29 03:30 UTC?

**Comment by kranthikumarm** [comment] 2018-01-29 03:07
Sounds good. Thanks!

**Comment by kranthikumarm** [comment] 2018-01-29 04:04
@macbe I was able to capture the repro traces. We're analyzing them. Thanks again. Just to make sure I understand the situation correctly: This is an application that was working fine before yesterday, and it started failing, right?

**Comment by macbe** [comment] 2018-01-29 07:50
Correct. It was last run successfully on Friday NZ time. We noticed it had stopped working on Monday NZ time. No changes on our side.

**Comment by kranthikumarm** [comment] 2018-01-30 00:27
@macbe We've determined that the issue you're hitting occurs when you use the HOME_EXPANDED environment variable to construct the path of the EXE you're invoking. You should be able to workaround the issue by using "D:\home" instead of %HOME_EXPANDED%. We're continuing to investigate the root-cause underlying the regression.
