### ISSUE TITLE
Cannot create precompiled functions using VS tooling

### ISSUE THREAD

**Issue by JasonBSteele** [Azure/Azure-Functions#132] opened 2017-01-09 11:04 UTC
Having created a Function project and added a Function to it I want to add a class (.cs file) to replace the Run.csx file.

The Add New Item dialog does not show anything in it for me to select a Class so I am unable to add a Class to the project.

**Comment by lindydonna** [comment] 2017-01-10 00:09
To use a precompiled function, you need to create a separate class library project and add a build output step to reference from your Functions project. It's a bit involved, and we plan to have a blog post on this soon.

**Comment by JasonBSteele** [comment] 2017-01-10 12:09
Thanks lindydonna, however that doesn't appear to be what is being done in the example in the Wiki https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions.

There is only one project here with a .cs class file, and it works fine, no need to setup a build output step.

**Comment by lindydonna** [comment] 2017-01-11 02:08
@JasonBSteele Ah interesting, I didn't notice that in the sample. The problem is that that is a class library project, so you'd have to deploy manually (there's no publish in Visual Studio for a class library).

So, I think the real feature you want is project references: https://github.com/Azure/Azure-Functions/issues/90

**Comment by JasonBSteele** [comment] 2017-01-12 22:20
Hi @lindydonna,
It's a shame the precompiled Function scenario wasn't included in the VS tooling.
I have created a feedback post for this so other readers can vote for it if they also believe this is important: https://feedback.azure.com/forums/355860-azure-functions/suggestions/17709979-visual-studio-tooling-for-precompiled-functions

**Comment by lindydonna** [comment] 2017-01-12 22:57
Thanks for the creating the feedback item!

**Comment by lindydonna** [comment] 2017-05-09 01:08
The VS tooling will be based on precompiled assemblies. There's a lot more activity on https://github.com/Azure/Azure-Functions/issues/201, so I'm closing this issue in favor of that one.

**Closed by lindydonna** 2017-05-09 01:08 UTC
Labels: feature, triaged, Visual Studio
