### ISSUE TITLE
Function.json gets generated with duplicated/incorrect properties ?

### ISSUE THREAD

**Issue by armadillomx** [Azure/Azure-Functions#439] opened 2017-08-14 18:59 UTC
![image](https://user-images.githubusercontent.com/31016054/29286670-79d23dc8-80f8-11e7-85a4-5f51258a6ad6.png)
Steps to recreate:

    Create an Azure function project
    Create an Azure function with access rights set to Manage
    Publish the Azure functions using Visual Studio 2017 Preview with Azure Functions Tools
    Open Portal
    Go to the Azure function
    Open function.json

**Comment by mattchenderson** [comment] 2019-02-15 01:18
Believed to be a dupe of https://github.com/Azure/Azure-Functions/issues/446. Please reopen if there is still an issue.

**Closed by mattchenderson** 2019-02-15 01:18 UTC
