### ISSUE TITLE
No Record of unhandled failure in AZ function Monitor UI

### ISSUE THREAD

**Issue by chughesvf** [Azure/Azure-Functions#1939] opened 2021-06-23 16:08 UTC
After an un-handled exception there is no record of the invocation of the function inside its monitoring UI:

![image](https://user-images.githubusercontent.com/32402463/123131081-5af2d000-d41b-11eb-905c-457158040e17.png)

This was the report provided from a support case related to this:

I reviewed the logs that you provided for an invocation that didn’t complete due to the exception causing the process to exit unexpectedly in the middle of the executions. This is likely why you were it’s missing in Monitor tab the from the left pane and also missing in the Query telemetry data in the requests Schema. I was also able to reproduce the issue and confirm that the Process Id changed.

**Comment by v-anvari** [comment] 2021-07-05 12:31
Hi @chughesvf , Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-anvari** [comment] 2021-07-06 14:25
I was unable to reproduce this issue, can you give me the repro steps and can you share the function App name privately - https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately. This will help us go through the logs

**Comment by chughesvf** [comment] 2021-07-09 19:14
Hey Ansuri,

I worked for weeks with a Microsoft rep on this issue. They sent me here. This relates to the following Azure case: 2105190040002734 to which they were fully reproducing this issue.

**Comment by v-anvari** [comment] 2021-07-26 11:58
Hi @chughesvf , I am unable to retrieve the data from the support case. Can you give me the repro steps and can you share the function App name privately - https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately. This will help us breakdown the logs

**Comment by chughesvf** [comment] 2021-07-27 22:25
I can do you one better @v-anvari  and provide you some code. The first error occurs on line 19 and is caught. The second error occurs on line 13 ( attempting to assign the error object to a hashtable and convert it to json ). This second error will hang the function and eventually timeout after the default load balancer timeout.

This function's execution will never be recorded as failed in the function's monitor pane.

The last ID in my streamed logs was 22630beb-ae47-4a70-9612-9eea2641ad62

However the monitoring pane shows:
![image](https://user-images.githubusercontent.com/32402463/127235344-65a14946-a37c-4ddc-83bc-0084d5fdcc87.png)


```using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

try{

    import-module doesntexist -ErrorAction stop

}catch{
    Write-Warning "Failure in triggering script $"
    $reply = [PSCustomObject]@{
        Results = $_
        Status = 'Failed'
        InvocationId = $TriggerMetadata.InvocationId
        User = $test
        RequestBody = $Request
    }
    $result = ConvertTo-Json -Depth 20 -InputObject $reply
}
Write-Host "Sending response"

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = [HttpStatusCode]::OK
    Body = $result
})

**Comment by v-anvari** [comment] 2021-07-28 12:51
Hi @chughesvf , Can I have the Timestamp during the error and region in which you are running the App. This will help us go through the logs. Are you facing this behavior even now?

**Comment by chughesvf** [comment] 2021-07-28 13:07
@v-anvari  the logs in Azure insights are present. The logs in the monitoring pane of the function do not show failures when there is an uncaught exception like the one the script above will generate. This is misleading from a troubleshooting point of view. This was also reproduced by the MSFT engineer assigned to the Azure case and the product group suggested I create this as a feature request.

**Comment by v-anvari** [comment] 2021-07-28 15:38
Thank you for your feedback! We will investigate this further and update as appropriate

**Comment by v-anvari** [comment] 2021-08-31 10:57
Hi @chughesvf , I checked with the UX team, and they confirmed that its not a UX issue and it could be by design or a flaw. Apologies for the delay. I shall follow up with the product team to check if this can be included or fixed

**Comment by v-anvari** [comment] 2021-08-31 11:00
Can you tell me if you were expecting failed invocation calls, are these error seen in the Application insights. If they are unhandled exceptions, are you expecting them to be errors or are you ignoring them through the code.

**Comment by chughesvf** [comment] 2021-09-14 16:37
@v-anvari  These were unhanded exceptions that caused a delay in the Azure Function to reach the default timeout of the loadbalancer. We found them in application insights but they never appear under the individual function monitor screen leading us to believe the function was never called. 

When I worked with one of the Azure support folks we had to actually tweak the linked App Insight query in the monitor screen to even find it.

**Comment by v-anvari** [comment] 2021-10-04 10:22
@chughesvf , I have tagged you in the powershell worker where this issue is duplicated. Please follow up there for any further updates.

Closing this issue in this repo

**Closed by v-anvari** 2021-10-04 10:22 UTC
Labels: Needs: Author feedback

**Comment by chughesvf** [comment] 2021-10-04 18:31
https://github.com/Azure/Azure-Functions/issues/1939#issuecomment-887874742

See this link, has a snippet to exactly repro it. The unhandled exception occurs during convertto-json in the catch.

**Comment by v-anvari** [comment] 2021-10-05 12:13
The team is working on this issue here - https://github.com/Azure/azure-functions-powershell-worker/issues/687
Please update any information in the issue mentioned
