### ISSUE TITLE
Can not host local functions anymore: A scripHost error has occured

### ISSUE THREAD

**Issue by skorunka** [Azure/Azure-Functions#133] opened 2017-01-09 12:30 UTC
1. Create a new AzureFunction project and add a new TimeTrigger function
![image](https://cloud.githubusercontent.com/assets/218913/21766564/2a47a784-d667-11e6-846f-966b58fad86b.png)

2. Press F5
![image](https://cloud.githubusercontent.com/assets/218913/21766510/e1711900-d666-11e6-8684-cc95e8b33168.png)

Does not work with 1.0.0-beta.8 nor with 1.0.0-beta.9

What's wrong?

**Comment by lindydonna** [comment] 2017-01-10 00:08
We have a poor error message here, for timer triggers, you need to have a value for AzureWebJobsStorage in your appsettings.json file.

**Comment by lindydonna** [comment] 2017-01-11 01:51
@skorunka Could you try that and report back?

**Comment by skorunka** [comment] 2017-01-11 10:19
@lindydonna I have added it and this is how my appsettings.json file looks like:

{
	"IsEncrypted": false,
	"Values": {
		"AzureWebJobsServiceBus": "Endpoint=...",
		"AzureWebJobsDashboard": "",
		"AzureWebJobsStorage": ""
	}
}

Problem still occures. Any idea? Thank you.

**Comment by skorunka** [comment] 2017-01-11 10:31
Ok, I had to full in an AzureWebJobsStorage value. It can be found on Azure portal under a Storage the Functions are using: Storage/AccessKeys/"click ..." and "View Connection String"

![image](https://cloud.githubusercontent.com/assets/218913/21845065/03a96c60-d7e9-11e6-8b5e-1045fcdfe7dd.png)

What is the AzureWebJobsDashboard for and what value shout be in there?

**Comment by lindydonna** [comment] 2017-01-11 22:28
It should be the connection string for any Azure Storage account. Azure Functions uses a lot of queue storage internally, so in your remote function, the value for AzureWebJobsStorage is always set. When running locally, you need to specify it. We need to make the tooling more streamlined so you don't have to set it up manually like this!

Please check out this video for a walkthrough of how to get the connection string from Azure Storage explorer: https://regularitguy.com/2017/01/11/the-coolness-of-visual-studio-azure-functions-tools/

**Comment by lindydonna** [comment] 2017-01-11 22:31
Closing as a duplicate of https://github.com/Azure/azure-functions-cli/issues/6

**Closed by lindydonna** 2017-01-11 22:31 UTC
Labels: pending-customer-response
