### ISSUE TITLE
Azure function V3 - Twilio binding does not work

### ISSUE THREAD

**Issue by CodeFisher-02** [Azure/Azure-Functions#1612] opened 2020-06-01 14:09 UTC
[https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-twilio?tabs=csharp]

I am trying to create an azure function (v3) on .net Core 3.1 with TwilioSms Output binding. I referred to Microsoft official docs mentioned above

My function looks like 

``[FunctionName("QueueTwilio")]
public async static Task Run(
[QueueTrigger("sms-queue", Connection = "AzureWebJobsStorage")] JObject req,
[TwilioSms(AccountSidSetting = "TwilioAccountSid", AuthTokenSetting = "TwilioAuthToken")]
IAsyncCollector smsMessages,
ILogger log)
{
var message = new CreateMessageOptions(new PhoneNumber("+14xxxxxxxxx"))
{
Body = "Hello",
From = "+18xxxxxxxx"
};

                    await smsMessages.AddAsync(message);

    }
}``

I want the function to run asynchronously, which is why I do not want to use return value
like [return: TwilioSms(AccountSidSetting = "TwilioAccountSid", AuthTokenSetting = "TwilioAuthToken", From = "+1425XXXXXXX")]

I get an error

`Microsoft.Azure.WebJobs.Host: Exception binding parameter 'smsMessages'. Microsoft.Azure.WebJobs.Extensions.Twilio: Method not found: 'Void Twilio.Clients.TwilioRestClient..ctor(System.String, System.String, System.String, System.String, Twilio.Http.HttpClient)'.`

Libraries used :
Microsoft.Azure.WebJobs.Extensions.Twilio 3.0.0 ; Microsoft.NET.Sdk.Functions 3.0.3

**Comment by bcolebank** [comment] 2020-11-18 11:21
It appears the issue is with the referenced version of the Twilio package (5.6.3) that the WebJobs.Extensions.Twilio library is using.  Updating it to 5.49.0 removes the issue, but removes support for ProviderSid and MaxRate from the TwilioExtensionConfigProvider.CreateMessageOptions.

**Comment by v-bbalaiagar** [comment] 2021-07-13 13:35
Hi @CodeFisher-02, Apologies for the delayed response, the issue was somehow lost in the trace. Can you tell us if you are still facing this issue.

**Comment by v-bbalaiagar** [comment] 2021-07-27 12:10
Hi @CodeFisher-02, Closing this issue as resolved[ here](https://github.com/MicrosoftDocs/azure-docs/issues/56246), Please feel free to reach back to us in case of any further queries related to this issue.

**Closed by v-bbalaiagar** 2021-07-27 12:10 UTC
Labels: documentation
