### ISSUE TITLE
Does the timeout attribute not work for a function?

### ISSUE THREAD

**Issue by star286** [Azure/Azure-Functions#1900] opened 2021-05-19 04:32 UTC
I know we can set the time out for an azure function app by [setting functionTimeout in host.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout).

But now I want to set timeout per function in a function app. I see there is an attribute **timeout**(I found it in[ azure webjobs doc](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to#timeout-attribute)), we can set it at method level, like below:

```
[Timeout("00:00:20")]
public static void Run(Stream myBlob, string name, ILogger log)
{
    log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
    log.LogInformation("start up xxx............");
    for(int i=0;i<40;i++)
    {
        log.LogInformation("hello " + i.ToString());
        System.Threading.Thread.Sleep(30000);
    }
    log.LogInformation("the end............");
}
```

As you can see, I set the timeout attribute to 20s, and in the logic, the function will sleep for 30s. I think it should timeout after 20s. But it seems that the function ignores this attribute, it can work beyond 20s. Here is screenshot:

![timeout](https://user-images.githubusercontent.com/76468643/118756737-26c94400-b89e-11eb-831b-d67bd0b3c16e.JPG)

Is this the expected behavior? Or it's a bug?

**Comment by v-bbalaiagar** [comment] 2021-05-20 06:39
Hi @star286, Thank you for reaching out to us, checking internally on this issue.

**Comment by v-bbalaiagar** [comment] 2021-05-24 17:09
Hi @star286  , Thank you for your feedback, I was able to reproduce the scenario. Triaging this issue for further investigation.

//For the team for triage//

Function app name: fptimer1

Timestamp : 2021-05-24T12:11:29.646

Region : Central US

Expected result: It should timeout after 20s.

Actual result: But the function ignores timeout attribute, it can work beyond 20s.

**Repro steps:**

 1. I have created a new function app,

 2. Add a blob trigger function using portal.

![image](https://user-images.githubusercontent.com/74654421/119382188-541f5300-bcdf-11eb-89c9-ca6a7ae4513a.png)


**Output:**

Below is the live metric logs:

![image](https://user-images.githubusercontent.com/74654421/119382335-84ff8800-bcdf-11eb-99a7-86a4c248b901.png)

**Comment by star286** [comment] 2021-05-25 04:35
@v-bbalaiagar thanks for your update. Looking forward to new updates for this issue.

**Comment by BlackHole02** [comment] 2021-08-23 07:51
I have the same issue. This issue is still open.
Hi @v-bbalaiagar, is there any plan to fix this issue? I see there is no assignee for it.

**Comment by aleccaputo** [comment] 2021-08-31 13:44
Same issue here, would be especially for reporting tasks that may require a longer timeout than an api endpoint

**Comment by mathewc** [comment] 2021-09-15 17:48
For csx functions (and other languages other than precompiled .NET) the function level TimeoutAttribute doesn't apply. Currently you must specify the timeout at the host level via host.json, which will apply to all functions. It would be possible for us to allow a function.json level specification for this (similar to our host/function level support for retry), but we never have.

**Comment by v-bbalaiagar** [comment] 2021-11-02 12:50
Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue.

**Closed by v-bbalaiagar** 2021-11-02 12:50 UTC
Labels: bug

**Comment by aleccaputo** [comment] 2021-11-02 13:47
@v-bbalaiagar what's the "required information provided?". We are attempting to request a feature here for azure functions. Doesn't seem to be a resolution. Unless the resolution is "will not do".

**Comment by mathewc** [comment] 2021-11-03 18:30
@aleccaputo To be clear - the declarative metadata model for csx functions is host.json/function.json not code attributes. I.e. all binding attributes are specified via json metadata, not attributes. So this is by design.

**Comment by aleccaputo** [comment] 2021-11-03 19:28
@mathewc yup, totally understand that. I think this turned into "are attributes supposed to work" to "is it possible to set different timeout values for different functions", which you addressed in your prior comment as being something unsupported that could be supported in the future 👍
