### ISSUE TITLE
Deploying Event Subscription: Deployment has failed with the following error...

### ISSUE THREAD

**Issue by denyss-digiterre** [Azure/Azure-Functions#1007] opened 2018-10-25 14:29 UTC
Error:

> Deployment has failed with the following error: {"code":"Url validation","message":"The attempt to validate the provided endpoint https://xxx.azurewebsites.net/runtime/webhooks/EventGrid failed. For more details, visit https://aka.ms/esvalidation."}

Invalid link: https://aka.ms/esvalidation   ->   https://docs.microsoft.com/en-us/azure/event-grid/security-authentication

**Comment by soninaren** [comment] 2018-10-25 18:40
@denyss-digiterre Can you share the repro steps?

**Comment by denyss-digiterre** [comment] 2018-10-26 14:13
1. Create a storage event subscription to integrate a function with a dead letter storage and path/extension filters. Works (both creation and event flow).
2. Amend event subscription above to change retry config. Fails.

**Comment by ColbyTresness** [comment] 2018-11-02 23:13
Can you confirm that the function is created and shows up in the portal? And that you have the right version set between V1 and V2? The URLs change between versions.

**Comment by denyss-digiterre** [comment] 2018-11-05 09:16
@ColbyTresness Can you confirm that the link https://aka.ms/esvalidation is correct and points to the right article? Let's start with that.

**Comment by ColbyTresness** [comment] 2018-11-05 18:17
I can confirm that it redirects to the Event Grid Security and Auth page, the question is whether that's correct, which I can't tell as I need more information. The above looks like an event grid deployment error, not a Functions error, so I'm not really sure what's happening. Can you give us a more detailed repro?

**Comment by onlyutkarsh** [comment] 2018-12-16 12:06
@ColbyTresness I am having a similar issue when I am trying to create a webhook subscription via ARM template. 

Azure Function Runtime version: `2.0.12246.0 (~2)`
Function binding from function.json:
```json
"bindings": [
    {
      "type": "eventGridTrigger",
      "name": "eventGridEvent"
    }
  ]
```
ARM template to add the webook:

```json
{
            "name": "[concat(variables('topicName'), '/Microsoft.EventGrid/', parameters('eventGridSubscriptions')[copyIndex('eventGridSubscriptions')].subscriptionName)]",
            "copy": {
                "name": "eventGridSubscriptions",
                "count": "[length(parameters('eventGridSubscriptions'))]",
                "mode": "Parallel"
            },
            "type": "Microsoft.EventGrid/topics/providers/eventSubscriptions",
            "location": "[parameters('location')]",
            "apiVersion": "2018-01-01",
            "properties": {
                "destination": {
                    "endpointType": "WebHook",
                    "properties": {
                        "endpointUrl": "[concat('https://', parameters('eventGridSubscriptions')[copyIndex('eventGridSubscriptions')].functionAppName, '.azurewebsites.net/runtime/webhooks/EventGrid?functionName=', parameters('eventGridSubscriptions')[copyIndex('eventGridSubscriptions')].functionName, '?code=', listsecrets(resourceId(resourceGroup().name, 'Microsoft.Web/sites/functions', parameters('eventGridSubscriptions')[copyIndex('eventGridSubscriptions')].functionAppName, parameters('eventGridSubscriptions')[copyIndex('eventGridSubscriptions')].functionName),'2015-08-01').key)]"
                    }
                },
                "filter": {
                    "includedEventTypes": [
                        "[parameters('eventGridSubscriptions')[copyIndex('eventGridSubscriptions')].eventType]"
                    ]
                },
                "eventDeliverySchema": "EventGridSchema",
                "retryPolicy": {
                    "maxDeliveryAttempts": 10,
                    "eventTimeToLiveInMinutes": 1440
                }
            },
            "dependsOn": [
                "[resourceId('Microsoft.EventGrid/topics', variables('topicName'))]"
            ]
}
```
When I trigger the deployment I get the error
![image](https://user-images.githubusercontent.com/2685029/50053314-f4deb100-012a-11e9-85ce-acad7f08a075.png)

**Comment by ColbyTresness** [comment] 2018-12-17 20:36
@ahmelsayed can you help me triage this? Who's the best person to look into this?

**Comment by ahmelsayed** [comment] 2018-12-17 21:53
I think the problem is that the key used in calling `/runtime/webhooks/EventGrid`. The API call is getting 401 back, and from the ARM template above. I think the issue is that it's using the `listsecrets` API which doesn't work for v2 applications.

**Comment by onlyutkarsh** [comment] 2018-12-17 22:08
> I think the issue is that it's using the `listsecrets` API which doesn't work for v2 applications.

Thank you @ColbyTresness and @ahmelsayed - What options do we have? Cannot go back to v1 unfortunately and need a way to automate deployments.

**Comment by ahmelsayed** [comment] 2018-12-17 22:39
I was looking for a workaround. Try setting `AzureWebJobsSecretStorageType=files` in your app settings and deploy again. This will invalidate all your keys though, so keep that in mind.

**Comment by onlyutkarsh** [comment] 2018-12-17 23:02
> Try setting `AzureWebJobsSecretStorageType=files` in your app settings and deploy again

Had that key already to during my previous tries. Deployed the function app again now, still the same error :(

**Comment by ahmelsayed** [comment] 2018-12-19 20:51
@ColbyTresness we might need to follow up with @fabiocav once he's back. Looking at the [code](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs#L222), I think `/runtime/webhooks/EventGrid` should accept the function key, but I'm not 100% sure. The error I see coming back is 401 when making that API call. from the template it's being made using the function key.

**Comment by onlyutkarsh** [comment] 2018-12-19 22:11
@ahmelsayed When I click `Add Event Grid Subscription` link on the function (in portal) and then go to `Advanced Editor` I see a JSON (screenshot below - similar to what we use in ARM template to add the subscription). 

Couple of questions:

1. the code displayed here is function key or a different key for `/runtime/webhooks/EventGrid` endpoint? because the function key on the portal (UI) and this are different.
![image](https://user-images.githubusercontent.com/2685029/50250838-e79b1e00-03d9-11e9-8e6b-e8b156ece188.png)
2. I am seeing that this code is same for all the `eventgridtrigger` functions in the function app - is this by design?
3. If I take the URL generated in the advanced editor and add subscription it works all the time, but if we generate the URL using any other means be it ARM templates (using `listsecrets`) or Powershell and try to add it via UI, it fails. This makes me to believe the code here is not a function key, but I might be wrong.

Thanks!

**Comment by ColbyTresness** [comment] 2019-01-18 19:56
@fabiocav Can you help us look into this?

**Comment by markheath** [comment] 2019-01-25 12:50
I'm running into the same error message (`The attempt to validate the provided endpoint https://myfuncapp.azurewebsites.net/runtime/webhooks/EventGrid failed.`) trying to register an Azure Function with the Azure Functions CLI using the `az eventgrid event-subscription create` command.

I know that the endpoint URL I'm providing is correct, as I've been able to use Postman to send it a validation request and get the `validationCode` echoed back to me.

I'm also able to use the portal tooling to create the subscription pointing at my Azure Function successfully, but I can't automate creating it with the Azure CLI.

BTW the issue with the more details shortlink is that tools like VS code interpret the `.` at the end of the sentence as part of the URL.

**Comment by markheath** [comment] 2019-01-25 17:27
I finally got to the bottom of my issue - the endpoint URL had got corrupted because it contained a `&` character, so it needed to be escaped in my PowerShell script with `^^^&`. May not be the same issue that other people on this thread ran into, but hope this information helps someone.

**Comment by pragnagopa** [comment] 2019-04-25 19:38
@mathewc - Is this issue addressed by the ARM APIs feature?

**Comment by mathewc** [comment] 2019-06-20 18:05
Yes. Rather than using the old functions listsecrets API to get the key (which isn't the right key to use), you should use the new `api/sites/{name}[/slots/{slot}]/host/default/listkeys` API described in [this issue](https://github.com/Azure/azure-functions-host/issues/3994). The keys returned will include the EventGrid extension system key.

**Comment by mathewc** [comment] 2019-06-20 18:16
Closing this. If people are still having issues after trying the new APIs we can reopen.

**Closed by mathewc** 2019-06-20 18:16 UTC

**Comment by timlod** [comment] 2019-06-25 07:53
For reference, this ARM template will return the correct keys:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "functionApp": {"type": "string", "defaultValue": ""}
    },
    "variables": {
        "functionAppId": "[resourceId('Microsoft.Web/sites', parameters('functionApp'))]"
    },
    "resources": [
    ],
    "outputs": {
        "functionAppId": {
            "type": "string",
            "value": "[variables('functionAppId')]"
        },
        "functionkeys": {
            "type": "object",
            "value": "[listkeys(concat(variables('functionAppId'), '/host/default'), '2018-11-01')]"                                                                                }
    }
}
```

I suggest adding something like this somewhere as documentation - it took me a while to realise that this is how one could call the new ARM API inside a template, even though it is now obvious.
