### ISSUE TITLE
App settings with null values cause app keys to disappear

### ISSUE THREAD

**Issue by BelRarr** [Azure/Azure-Functions#1711] opened 2020-09-08 17:50 UTC
My team and I just noticed a very weird behaviour in Azure Functions. 

If we create an app setting with value null (let's say "ProxyUrl" or any other name), and then restart the function app, then the app keys will disappear. if we set any other value for that app setting and then restart the function app again, then the app keys will magically reappear.

Even weirder: if the app setting contains a dot in its name (e.g. "Endpoints.ProxyUrl"), then the issue isn't happening (i.e. the app keys don't disappear).

![image](https://user-images.githubusercontent.com/32443841/92510680-399d5c00-f1da-11ea-8084-453661dd6a82.png)

we're running a function app in .net core 3.1 LTS. If you need more infomation, I'd be glad to provide it.

Sincerely,

Tidjani Belmansour

**Comment by balag0** [comment] 2020-09-09 05:54
Could you check if you are seeing the same behaviour with Azure CLI as well. (in case this is a portal specific display behaviour)

https://docs.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest#az-functionapp-config-appsettings-list

**Comment by BelRarr** [comment] 2020-09-09 11:21
It’s apparently not a portal-specific issue as we are expecting it with ARM templates and with AzureRM cmdlets.

I’ll try later today the azure cli way and let you know.

Best regards,

Tidjani Belmansour, Ph.D. | Azure MVP
http://espacenuagic.com<http://espacenuagic.com/> | https://dev.to/tidjani | @tidjani_b<https://twitter.com/tidjani_b>

[X]

Le 9 sept. 2020 à 01:54, Bala G <notifications@github.com> a écrit :

﻿

Could you check if you are seeing the same behaviour with Azure CLI as well. (in case this is a portal specific display behaviour)

https://docs.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest#az-functionapp-config-appsettings-list

**Comment by BelRarr** [comment] 2020-09-09 16:21
Ok, this is really weird :

If I follow the repro steps I described in my previous comment, the function’s app key aren’t appearing. Now, As soon as I open Cloud Shell in the Azure Portal (only opening it, not typing a single command!), they appear again.

They also magically start appearing if I query them from Azure CLI or PowerShell commands from my local machine :

clear-host

az login

az account set --subscription 'Microsoft Azure Sponsorship'

$subscriptionId = '*************'
$resourceGroup = "webapp-rg"
$webAppName = "tidjanifunc123"
$resourceId = "/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Web/sites/$webAppName"

az rest --method post --uri "$resourceId/host/default/listKeys?api-version=2018-11-01"

[cid:image004.png@01D686A3.B8D1B270]

So, after all, it seems that it is a portal issue and possibly a runtime issue, because :

  1.  When querying the app keys using Azure CLI (for example) if they aren’t appearing in the portal, the query takes longer than the same query if these keys are appearing in the portal;
  2.  If the keys aren’t appearing, we experience issues : for example, no logs are sent to application insights.

I hope this helps narrow down the issue.

Best regards,

Tidjani Belmansour, Ph.D. | Azure MVP
http://espacenuagic.com<http://espacenuagic.com/> | https://dev.to/tidjani | @tidjani_b<https://twitter.com/tidjani_b>
[cid:image005.png@01D686A3.B8D1B270]

De : Bala G<mailto:notifications@github.com>
Envoyé le :9 septembre 2020 01:54
À : Azure/Azure-Functions<mailto:Azure-Functions@noreply.github.com>
Cc : Tidjani Belmansour<mailto:tidjani.belmansour@live.ca>; Author<mailto:author@noreply.github.com>
Objet :Re: [Azure/Azure-Functions] App settings with null values cause app keys to disappear (#1711)


Could you check if you are seeing the same behaviour with Azure CLI as well. (in case this is a portal specific display behaviour)

https://docs.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest#az-functionapp-config-appsettings-list

**Comment by BelRarr** [comment] 2020-09-09 18:24
Looks like the images aren't displaying since I responded from my email client. So I'm posting my comment below again:
=====

Ok, this is really weird :

If I follow the repro steps I described in my previous comment, the function’s app key aren’t appearing. Now, As soon as I open Cloud Shell in the Azure Portal (only opening it, not typing a single command!), they appear again.

They also magically start appearing if I query them from Azure CLI or PowerShell commands from my local machine :

``` powershell
clear-host

az login

az account set --subscription 'Microsoft Azure Sponsorship'

$subscriptionId = '*************'
$resourceGroup = "webapp-rg"
$webAppName = "tidjanifunc123"
$resourceId = "/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Web/sites/$webAppName"

az rest --method post --uri "$resourceId/host/default/listKeys?api-version=2018-11-01"
```

![image](https://user-images.githubusercontent.com/32443841/92638168-e265bd00-f2a7-11ea-8922-a385b4e3d4bc.png)


So, after all, it seems that it is a portal issue and possibly a runtime issue, because :

  1.  When querying the app keys using Azure CLI (for example) if they aren’t appearing in the portal, the query takes longer than the same query if these keys are appearing in the portal;
  2.  If the keys aren’t appearing, we experience issues : for example, no logs are sent to application insights.

I hope this helps narrow down the issue.

Best regards,

**Comment by balag0** [comment] 2020-09-09 22:00
Thanks. Since az cli returns the appsettings as expected the settings must be getting persisted correctly. 

I also don't understand the relation between how appsettings are displayed in portal and application insights logging. Also the screen shot is not related to appsettings. Could you provide more details on the actual issue you are seeing. Is it missing app insights logs?

**Comment by BelRarr** [comment] 2020-09-09 22:48
It’s not about app settings itself. The issue we’re facing is that when we define an app setting with a null value, the function app keys aren’t displayed and it seems that somehow this causes the logs not to be sent to application insights because, as soon as we set a non-null value for the app setting, the keys appear again and the logs are routed again to application insights.

I hope this is clearer now.

[X]

Le 9 sept. 2020 à 18:00, Bala G <notifications@github.com> a écrit :

﻿

Thanks. Since az cli returns the appsettings as expected the settings must be getting persisted correctly.

I also don't understand the relation between how appsettings are displayed in portal and application insights logging. Also the screen shot is not related to appsettings. Could you provide more details on the actual issue you are seeing. Is it missing app insights logs?

**Comment by balag0** [comment] 2020-09-10 00:47
Okay. The issue is basically missing logs in app insights. Please share timestamp, appname when you don't see the logs in app insights.

Also please check if sampling is enabled for the app
https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#applicationinsightssamplingsettings

**Comment by v-anvari** [comment] 2021-05-31 14:31
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue

**Closed by v-anvari** 2021-05-31 14:31 UTC
