### ISSUE TITLE
GetEnvironmentVariable with "temp" in key-name returns "D:\local\Temp"

### ISSUE THREAD

**Issue by dersia** [Azure/Azure-Functions#416] opened 2017-07-31 18:13 UTC
I just realized that whenever ```System.Environment.GetEnvironmentVariable``` is used with a key that starts with "temp" it returns ```D:\local\Temp```

I don't thing this is the desired behavior.

**Comment by christopheranderson** [comment] 2017-08-01 23:23
@davidebbo - can you confirm this is the behavior and what might be causing that behavior? That seems like a bug.

**Comment by davidebbo** [comment] 2017-08-02 00:55
I can't repro this. Here is my test code:

    log.Info("temp:" + System.Environment.GetEnvironmentVariable("temp"));
    log.Info("temp2:" + System.Environment.GetEnvironmentVariable("temp2"));

And the output is:

    2017-08-02T00:52:54.774 temp:D:\local\Temp
    2017-08-02T00:52:54.774 temp2:

@dersia if you have a repro, please provide some very specific code. Also, please test with my code to make sure you see the same as I see.

**Comment by dersia** [comment] 2017-08-02 08:24
Well for me it was GetEnvironmentVariable(“tempBlobStorageConnectionStrin”); but I also tried GetEnvironmentVariable(“tempAhdndjr”); random string, but I never tested with a digit after temp, though.

I'll check tomorrow and provide a repro.

**Comment by davidebbo** [comment] 2017-08-04 01:56
I couldn't repro with either of these two strings. Closing for now, but if you get a repro, please share the complete code.

**Comment by dersia** [comment] 2017-08-11 16:26
Sorry it took me a while to come back to this issue.

@davidebbo to reproduce it, I just created a new function with a manual trigger in the portal added the following key->value to the application settings ```tmpBlobStorageConnectionString```->```abc``` and this is the code for the run.csx:

```csharp
using System;

public static void Run(string input, TraceWriter log)
{
    log.Info($"{System.Environment.GetEnvironmentVariable("tmpBlobStorageConnectionString")}");
}
```

this is a screenshot from the portal:

![image](https://user-images.githubusercontent.com/1537958/29222356-feb15008-7e76-11e7-88d4-a725683c2169.png)

as you can see in the logs the return value for ```System.Environment.GetEnvironmentVariable("tmpBlobStorageConnectionString")``` is ```D:\local\Temp```

Let me know, if I can help with more details

**Comment by davidebbo** [comment] 2017-08-11 21:13
Thanks, I can repro now. This is quite strange! It is not Functions specific, and appears to be general behavior in App Service (e.g. same with Web Apps).

We will investigate further.

**Comment by davidebbo** [comment] 2017-08-11 22:22
The owning team confirmed that this is a bug, which apparently has already existed in App Service. The bug is now tracked, though it's not clear when it will be fixed.

Closing here since it is not directly Functions related. For now, it's best to just avoid this naming pattern.

**Closed by davidebbo** 2017-08-11 22:22 UTC
Labels: bug, needs-investigation

**Comment by nulltoken** [comment] 2017-10-10 14:05
@davidebbo Hey! I've just hit that bug as well, trying to retrieve the content from an environment variable named `TemporaryMapAccess`, running a .NET Core 2.0 website on top of App Services.

I understand this isn't Azure Functions related. However, would you know if there's a known issue tracking this. I'd be really willing to subscribe to it.

**Comment by davidebbo** [comment] 2017-10-10 14:52
@nulltoken there is an issue tracking that on the internal App Service system, though it doesn't look like it has been addressed. I can ping the owner again.

**Comment by nulltoken** [comment] 2017-10-10 16:20
@davidebbo 🙏 😍

**Comment by giorgos07** [comment] 2018-10-01 18:17
@davidebbo Hi I encountered the exact same problem with settings containing the string `TemplaterUrl`. Where is the proper place to track this so I can send my update?

Thanks

**Comment by phoude** [comment] 2018-11-13 20:02
We came across the same issue. We had an app settings starting with Temp and was returning d:\local\temp as raised above. We also encountered the same issue if the setting starts with Tmp. Very odd. No warning whatsoever about this "reserved" prefix. We have wasted some time before finding out.

**Comment by raxitr** [comment] 2018-11-29 13:05
I also ran into this issue where my variable name was "TemplateWorkspaceId". This was working fine till yesterday and started returning D:\local\Temp all of a sudden. 

I had to change the name to "SourceWorkspaceId" to get it working.

**Comment by kgoderis** [comment] 2019-01-07 16:24
+1. Issue still present

**Comment by AndrewNikolin** [comment] 2019-01-17 12:52
Can confirm, still an issue and affects our application hosted on Web Apps 
@davidebbo @christopheranderson can you guys update us on the issue status from your internal tracking? This exists almost for 2 years already

**Comment by davidebbo** [comment] 2019-01-17 16:04
@AndrewNikolin I'm no longer working on this, so I will let others comment. But note that this issue is general to App Service, and not specific to Functions, so this may not be the best place to track it.

**Comment by AndrewNikolin** [comment] 2019-01-17 19:47
@davidebbo Yea, I understand that this isn't the best place, but at least I can get some feedback here :) Personally, I've noticed this bug on the regular WebApp

**Comment by suwatch** [comment] 2019-01-31 17:42
FYI: we tracked this issue down and made a fix.   The fix will go live in March'19.   Apology for the delay.
