### ISSUE TITLE
Function.json gets generated with invalid AccessRights property

### ISSUE THREAD

**Issue by dnlmcv** [Azure/Azure-Functions#418] opened 2017-08-01 06:32 UTC
System: Windows 10, Visual Studio 2017 Preview

Description: I'm using Visual Studio for developing an Azure Functions project. I have some Azure Functions with the AccessRights set to Listen. When I publish the Function App to Azure, the function.json files are generated containing : "access": "listen" property, which is invalid. After each deploy I have to modify each azure function and set the "accessRights": "Listen" manually.

Steps to recreate:
1) Create an Azure function project
2) Create an Azure function with access rights set to listen
2) Publish the Azure functions using Visual Studio 2017 Preview with Azure Functions Tools
3) Open Portal
4) Go to the Azure function
5) Open function.json

Expected behavior: 
I expect to have the property "accessRights": "Listen"

Result:
The property "access": "listen" is set. 

Error message: Couldn't retrieve host keys.

Also there was another bug, but I think it was fixed. In the portal when I was setting the access rights to Listen, the function.json file was updated with the property: "accessRights": "Listen", but this value was invalid as well. I had to set "accessRights": "listen" and not use capital letters for getting the azure functions to work.

**Comment by lindydonna** [comment] 2017-08-14 22:08
@dnlmcv Is this a trigger?  Can you paste the generated contents of function.json?

**Comment by dnlmcv** [comment] 2017-08-16 07:36
@lindydonna  This is a service bus queue trigger. When I publish the function app from visual studio the function.json file looks like this : 

{
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "ServiceBusConnectionString",
      "queueName": "queue",
      **"access": "listen",**
      "direction": "in",
      "name": "input"      
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\Function.dll",
  "entryPoint": "Function..Run"
}

"access": "listen" value is invalid (received error is about failing to retrieve host keys for the azure functions.) so I need to open the portal and set again the access rights from the UI. After that the function.json file looks like this : 
{
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "ServiceBusConnectionString",
      "queueName": "queue",
      **"access": "listen",**
      "direction": "in",
      "name": "input",
      **"accessRights": "Listen"**      
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\Function.dll",
  "entryPoint": "Function..Run"
}

The UI adds accessRights value to the function.json file and this makes the azure function to run. One thing to note as well is that the value "Listen" is highlighted as a bad value, but if I change it manually to "listen" then the highlight disappears.

**Comment by darrenhull** [comment] 2017-10-19 14:10
System: Windows 10, Visual Studio 2017 Version 15.3.1, Azure Functions and web tools version 15.0.30923.0

I also have the same issue when creating a C# Azure Function from Visual studio. Here is the function.json generated:

{
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "CommandConsumerConnection",
      "topicName": "command",
      "subscriptionName": "CommandFunction",
      "access": "listen",
      "direction": "in",
      "name": "message"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\IoTHubFunctions.dll",
  "entryPoint": "IoTHubFunctions.CommandFunction.Run"
}

I then get the error: Error message: Couldn't retrieve host keys.

Looking at the function setting: Manage is selected for Access Rights. If I select Listen then function.json is modified to:

{
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "CommandConsumerConnection",
      "topicName": "command",
      "subscriptionName": "CommandFunction",
      "access": "listen",
      "direction": "in",
      "name": "message",
      "accessRights": "Listen"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\IoTHubFunctions.dll",
  "entryPoint": "IoTHubFunctions.CommandFunction.Run"
}

Do we have an update for this?

**Comment by mattchenderson** [comment] 2019-02-15 00:34
Is this still an issue using latest Functions tooling?

**Comment by mattchenderson** [comment] 2019-02-15 01:06
Actually, closing as dupe of https://github.com/Azure/Azure-Functions/issues/446

**Closed by mattchenderson** 2019-02-15 01:06 UTC
