### ISSUE TITLE
[UX] - In Portal create output binding overwrites connection string.

### ISSUE THREAD

**Issue by fasigpt** [Azure/Azure-Functions#1611] opened 2020-05-29 22:55 UTC
# Issue Title
If we need to need to create multiple output bindings to same EventHub Namespace and different EventHubs, the portal overwrites the older connection string. This happens when we use the same "SAS Policy" to setup a connection to EH.

## Description

![image](https://user-images.githubusercontent.com/11519211/83311479-3ac6f200-a1c4-11ea-98ff-0ac538a5460d.png)

In the above scrrenshot we are creating three output bindings to different EHs under same EH namespace. The first and the last bindings were created from the portal using the same SAS Policy

![image](https://user-images.githubusercontent.com/11519211/83311689-ce002780-a1c4-11ea-8047-ee30bcd17619.png)

Today, the name of the connection string depends on SAS policy. So the third output binding will overwrite the connection string which was initially created (in the app settings configuration.)

**Comment by btardif** [comment] 2020-06-08 19:52
@refortie can you take a look?

**Comment by refortie** [comment] 2020-06-08 19:55
That's currently the intended behavior. It looks like it isn't a good solution, I'll start a conversation internally to see how we want to handle it going forward

**Comment by btardif** [comment] 2020-06-18 20:17
@refortie  can you provide an update I think this is currently rolling out with our current deployment

**Comment by refortie** [comment] 2020-06-25 18:04
The fix for this should be in all regions tomorrow. Now if you attempt to create a duplicate, it will instead increment and create a new connection string

**Closed by refortie** 2020-06-25 18:04 UTC
Labels: UX_Preview
