### ISSUE TITLE
feature to trigger old events

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#410] opened 2017-07-26 23:25 UTC
I'm not sure if I should open this feature request in here, or if it belongs to another team, but here it goes...

Let's say that I have an application that uses queues to help me to decouple my services, and the initial development was not based on serverless approach. If I want to replace the part that consumes the messages in the queues with Azure Functions, only the new messages will be triggered, I'll need to code something else to dequeue messages and call the azure functions services.

It would be nice, if somehow I could "ask" azure functions to dequeue old messages as well. I know that it's not event based, but it's just one idea. Let me know your thoughts.

PS: not only with Queues, but with other bindings that this feature might suit too.

**Comment by christopheranderson** [comment] 2017-08-01 23:16
I'm not sure this would work for anything other than potentially Event Hubs. When you "dequeue" a storage queue, for instance, the message goes away (otherwise you'd end up with a bunch of messages you're paying for...). We do have some other requests for fine grained control over Event Hubs reader's start point.

I'm not sure this is feasible for us to do, just based on the way that queue services work. There is some fun magic that could be done if everyone logged their events to Event Hubs and used that as the source for events, but that's not likely. 

Closing this as won't fix for now. Reopen if you think there's something I'm missing.

**Closed by christopheranderson** 2017-08-01 23:16 UTC

**Comment by thdotnet** [comment] 2017-08-01 23:22
What trigger the Azure Function is when a new message gets into the queue right? What I was recommending is a way to trigger existing messages from the queue. Let's say that initially I was dequeueing messages using Worker Role, and I've decided to change it for Azure Functions. During the transition from one approach to the other, messages will remain in the queue, and somehow I'll need to process them. New messages will be trigger by Azure Functions...my idea was to "re-trigger" events (queues, blobs, etc...) to activate the azure function.

**Comment by christopheranderson** [comment] 2017-08-01 23:33
What triggers a Function is the queue reader reading a message on the queue. If some other reader has dequeued a message, it is no longer readable, thus we can't reread it - it's no longer there.

Generically, though, wouldn't you just simply stop the worker role and start the Function? In what scenarios would you want to rerun a queue message (or Blob, etc.) just based on the hosting model? 

There is the larger problem of there isn't currently a global event queue that Functions reads from that we'd just need to replay a log of. Each event source kinda does things differently. Services would need to keep a history log of previous messages/events, which is kind of sticky problem unless there is a central event store that everyone reads from, somehow. Even then, there are lots of problems. For instance, if you replayed a Blob trigger, but the blob had changed since the trigger, should you still run that Function, because you'll run again for the new trigger as well - the underlying data has changed. I'm not sure this is a thing which is possible to do unless the service has a change log (which services like CosmosDB does have, to be fair..., but not every service does. The services that do have it don't keep it around for super long periods of time, so this would also have a time bound).

I think the answer is that we could support this for triggers which have logs of events that can be replayed, like Event Hub, but we can't support this for things that disappear once processed like queues (by design).

**Comment by thdotnet** [comment] 2017-08-01 23:35
Got it. Thanks for the explanation.
