### ISSUE TITLE
AzureWebJobsScriptRoot variable is not defined on Azure Functions

### ISSUE THREAD

**Issue by PingPongSet** [Azure/Azure-Functions#1146] opened 2019-03-10 23:09 UTC
AzureWebJobsScriptRoot variable is not defined on Azure Functions. The code below returns no value.
`
System.Environment.GetEnvironmentVariables(EnvironmentVariableTarget.Process)["AzureWebJobsScriptRoot"];`

However,` %HOME%\site\wwwroot` will be returned based on below:

[AzureWebJobsScriptRoot](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsscriptroo)

> AzureWebJobsScriptRoot
> 
> The path to the root directory where the host.json file and function folders are located. In a function app, the default is %HOME%\site\wwwroot.
> Key 	Sample value
> AzureWebJobsScriptRoot 	%HOME%\site\wwwroot
> 

It returns correct value locally, not %HOME%\site\wwwroot

**Update**

Is this a bug with Azure Functions?

If so, what is an alternative solution?

Before the issue is fixed by Microsoft, can this variable, AzureWebJobsScriptRoot, be defined myself to "%HOME%\site\wwwroot" on Azure?

**Comment by ColbyTresness** [comment] 2019-03-13 17:28
@brettsam to take a look

**Comment by KetanChawda-MSFT** [comment] 2019-03-15 05:56
Possibly duplicate of this doc issue. https://github.com/MicrosoftDocs/azure-docs/issues/26761

**Comment by ColbyTresness** [comment] 2019-03-15 17:16
Yeah this is a dupe, leaving on other issue until a verdict is reached there as to whether there's anything to fix.

**Closed by ColbyTresness** 2019-03-15 17:16 UTC
