### ISSUE TITLE
Running with the debugger does not respect LocalHttpPort in local.settings.json

### ISSUE THREAD

**Issue by leftler** [Azure/Azure-Functions#584] opened 2017-11-10 16:36 UTC
1. Create a new function app
2. Update the NuGet package Microsoft.NET.Sdk.Functions to 1.0.6
3. Edit local.settings.json to be the following
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "AzureWebJobsDashboard": ""
  },
  "Host": {
    "LocalHttpPort": 7072,
    "CORS": "*"
  }
}
```
4. Add a simple HttpTrigger using the default template
5. Run function app.

In the console window you will see 

> [11/10/2017 4:32:33 PM] Reading host configuration file 'D:\Temp\ExampleApp\ExampleApp\bin\Debug\net461\host.json'
> [11/10/2017 4:32:34 PM] Host configuration file read:
> [11/10/2017 4:32:34 PM] {
> }
> Listening on http://localhost:7071/
> Hit CTRL-C to exit...
> [11/10/2017 4:32:34 PM] Loaded custom extension 'BotFrameworkConfiguration'
> [11/10/2017 4:32:34 PM] Loaded custom extension 'SendGridConfiguration'
> [11/10/2017 4:32:34 PM] Loaded custom extension 'EventGridExtensionConfig'
> [11/10/2017 4:32:34 PM] Generating 1 job function(s)
> [11/10/2017 4:32:34 PM] Starting Host (HostId=oshidevdw1012-332967204, Version=1.0.11351.0, ProcessId=8524, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
> [11/10/2017 4:32:34 PM] Found the following functions:
> [11/10/2017 4:32:34 PM] ExampleApp.Function1.Run
> [11/10/2017 4:32:34 PM]
> [11/10/2017 4:32:34 PM] Job host started
> [11/10/2017 4:32:35 PM] Executing HTTP request: {
> [11/10/2017 4:32:35 PM]   "requestId": null,
> [11/10/2017 4:32:35 PM]   "method": "GET",
> [11/10/2017 4:32:35 PM]   "uri": "/"
> [11/10/2017 4:32:35 PM] }
> [11/10/2017 4:32:35 PM] Executed HTTP request: {
> [11/10/2017 4:32:35 PM]   "requestId": "fd683b48-be98-4ee4-8be3-2a2c56a2b970",
> [11/10/2017 4:32:35 PM]   "method": "GET",
> [11/10/2017 4:32:35 PM]   "uri": "/",
> [11/10/2017 4:32:35 PM]   "authorizationLevel": "Anonymous"
> [11/10/2017 4:32:35 PM] }
> [11/10/2017 4:32:35 PM] Response details: {
> [11/10/2017 4:32:35 PM]   "requestId": "fd683b48-be98-4ee4-8be3-2a2c56a2b970",
> [11/10/2017 4:32:35 PM]   "status": "OK"
> [11/10/2017 4:32:35 PM] }
> 
> Http Functions:
> 
>         Function1: http://localhost:7071/api/Function1
> 
> Debugger listening on [::]:5858

You can see that the function is running on port 7071 and not on our custom 7072

If you start another function app with `"LocalHttpPort": 7073` set as the setting you will get the error message 

> HTTP could not register URL http://localhost:7071/. Another application has already registered this URL with HTTP.SYS.

Attached is a basic repo using the same steps listed above.
[ExampleApp.zip](https://github.com/Azure/Azure-Functions/files/1462010/ExampleApp.zip)

**Comment by ahmelsayed** [comment] 2017-11-10 17:04
can you see if this works for you

_from my reply on https://stackoverflow.com/a/44977350/3234163_

the command line takes precedence over the settings file, the problem is that VS passes an explicit port on the command line. 

work around is to go through `project -> properties -> Debug`, then under `Application arguments` take control of the args. you can type `host start --pause-on-error`


![pkhvf](https://user-images.githubusercontent.com/645740/32669646-137eaeec-c5f6-11e7-9882-f19dcad76324.gif)

**Comment by leftler** [comment] 2017-11-10 17:27
@ahmelsayed Thank you for the work around!

**Comment by ahmelsayed** [comment] 2017-11-10 17:30
Awesome! thank you for confirming. I'll close this issue then.

**Comment by leftler** [comment] 2017-11-10 17:31
@ahmelsayed I spoke too soon, the the problem still persist just with a different part. The debugging port is now in use. The second program to start fails with

> Error: listen EADDRINUSE :::5858
>     at Object.exports._errnoException (util.js:1020:11)
>     at exports._exceptionWithHostPort (util.js:1043:20)
>     at Agent.Server._listen2 (net.js:1258:14)
>     at listen (net.js:1294:10)
>     at net.js:1404:9
>     at _combinedTickCallback (internal/process/next_tick.js:83:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

Please reopen the ticket.

**Comment by ahmelsayed** [comment] 2017-11-10 17:35
you can change that port by specifying `--nodeDebugPort 5859`. We should expose all these settings to `local.settings.json` as well for more consistency. You can open an issue over here https://github.com/Azure/azure-functions-cli/issues for that.

**Comment by leftler** [comment] 2017-11-10 20:11
Setting the port fixed the issue, I have opened a issue on the cli repo (and helped someone who was having the same problem in their issue tracker too)

**Comment by Mike-EEE** [comment] 2018-03-21 05:26
OK I am confused here, please help me out.  Why have a setting for `LocalHttpPort` if it isn't used?

**Comment by Mike-EEE** [comment] 2018-03-21 05:32
Additionally, setting `host start --pause-on-error` results in the following exception:

`Microsoft.DotNet.Cli.Utils.CommandUnknownException: 'No executable found matching command "dotnet-host"'`

**Comment by ggailey777** [comment] 2018-03-22 17:45
@ahmelsayed can you address the issue that @Mike-EEE is reporting when trying to use the `host start --pause-on-error` workaround?

**Comment by pragnagopa** [comment] 2018-03-22 21:36
This is a known issue. Please see [here](https://stackoverflow.com/questions/44976890/how-to-run-azure-function-app-on-a-different-port-in-visual-studio/44977350#44977350) for the workaround

**Comment by pragnagopa** [comment] 2018-03-22 21:37
Apologies closed too soon.

**Comment by ahmelsayed** [comment] 2018-03-22 21:45
@Mike-EEE I'm assuming you're running v2? this issue was for v1. There are some differences in how VS loads things between the 2.

**Comment by Mike-EEE** [comment] 2018-03-23 05:36
Great!  I am not sure how I didn't see that post in all my searching.  That is exactly what I was looking for...thank you, team!  Please feel free to close this issue. :)

**Comment by ggailey777** [comment] 2018-03-23 16:54
Closing again per customer request.

**Closed by ggailey777** 2018-03-23 16:54 UTC

**Comment by ahmelsayed** [comment] 2018-04-13 17:57
@s-KaiNet  can you try running this command outside of visual studio and see if it works there?

```
%UserProfile%\AppData\Local\Azure.Functions.Cli\1.0.10\func.exe host start --port <yourPort> --useHttps
```

the first time you run this it needs to ask for elevation to register the urlacls with https.sys.

Alternatively you can also run 

```bash
netsh http show sslcert 0.0.0.0:<yourPort> #default 7071
```

You should see something like 

```
SSL Certificate bindings:
-------------------------

    IP:port                      : 0.0.0.0:7071
    Certificate Hash             : 1b85aea76b6202df2fef8dd3418c8e20cde24e39
    Application ID               : {02639d71-0935-35e8-9d1b-9dd1a2a34627}
    Certificate Store Name       : MY
    Verify Client Certificate Revocation : Enabled
    Verify Revocation Using Cached Client Certificate Only : Disabled
    Usage Check                  : Enabled
    Revocation Freshness Time    : 0
    URL Retrieval Timeout        : 0
    Ctl Identifier               : (null)
    Ctl Store Name               : (null)
    DS Mapper Usage              : Disabled
    Negotiate Client Certificate : Disabled
    Reject Connections           : Disabled
    Disable HTTP2                : Not Set
    Disable QUIC                 : Not Set
    Disable TLS1.3               : Not Set
    Disable OCSP Stapling        : Not Set
```

If you don't, you can run this internal CLI command yourself to register the cert with http.sys from an elevated cmd using 

```
func internal-use --actions 3 --port <yourPort> --protocol https
```

**Comment by ahmelsayed** [comment] 2018-04-13 18:01
You can see what this command [does here](https://github.com/Azure/azure-functions-core-tools/blob/958972c6bbc29b35ae7a32dc436a310cfa816905/src/Azure.Functions.Cli/Actions/InternalUseAction.cs#L83-L107)
```
func internal-use --actions 3 --port <yourPort> --protocol https
```

It generates a self-signed cert for localhost, adds it to your cert store then runs

```
netsh http add sslcert ipport=0.0.0.0:<yourPort> certhash=<the cert thumbprint>  certstorename=My appId=02639d71-0935-35e8-9d1b-9dd1a2a34627
```

**Comment by s-KaiNet** [comment] 2018-04-13 18:04
self-cert is the cause of the issue indeed. 
After investigating it deeply, I found that cli can't generate self-signed cert in my system and returns error:    

> Unable to cast COM object of type 'System.__ComObject' to interface type 'CERTENROLLLib.CX509PrivateKey'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{728AB362-217D-11DA-B2A4-000E7BBB2B09}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).   

I beleive I should create an issue in func-core cli repository...

**Comment by ahmelsayed** [comment] 2018-04-13 18:07
Can you please open an issue here https://github.com/Azure/azure-functions-core-tools/issues 
Also include your os version
