### ISSUE TITLE
Possible thread pool starvation detected

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/Azure-Functions#2054] opened 2021-09-24 09:16 UTC
> I would have created this under Discussions but it doesn't seem to work. I think categories are missing to be allowed to create a new discussion thread.

I'm starting to see the following warning in a log for a consumption-based function:

```
Possible thread pool starvation detected
```

I'm not sure why this problem occurs since my understanding of the consumption plan is that Azure Functions will scale the function to avoid problems like this.

The function is triggered by Azure Service bus and make a HTTP request for each message received from the bus. The HttpClient used to make the request is registered in a `Startup.cs` file:

```csharp
builder
    .Services
    .AddHttpClient("myclient", x =>
    {
        x.Timeout = TimeSpan.FromSeconds(30);
        x.DefaultRequestHeaders.ConnectionClose = true; // Keep-Alive = false
        x.DefaultRequestHeaders.AcceptEncoding.Clear();
        x.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));
        x.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("deflate"));
        x.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("identity"));
    })
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
    {
        SslProtocols = System.Security.Authentication.SslProtocols.None,
    });
```

Then, in my function I inject a `IHttpClientFactory` and use that to create the `HttpClient` in each invocation:

```csharp
public MyFunction(IHttpClientFactory httpClientFactory)
{
    this.httpClientFactory = httpClientFactory;
}

[FunctionName("MyFunction")]
public async Task Run([ServiceBusTrigger(...)]string mySbMsg, CancellationToken token)
{
    if (token.IsCancellationRequested) return;

    ...
    var httpClient = httpClientFactory.CreateClient("myclient");
    var request = new HttpRequestMessage();
    request.Method = HttpMethod.Get;
    request.RequestUri = ...;
    var response = await httpClient.SendAsync(request);
    ...
}
```

Any help here would be highly appreciated.

**Comment by v-anvari** [comment] 2021-09-27 13:34
Hi @ThomasArdal , Here is a document explaining the cause and possible solutions - https://github.com/microsoft/vs-threading/blob/main/doc/threadpool_starvation.md

Here is a blog explaining how to diagnose the issue - https://docs.microsoft.com/en-us/archive/blogs/vancem/diagnosing-net-core-threadpool-starvation-with-perfview-why-my-service-is-not-saturating-all-cores-or-seems-to-stall

Please let us know if you were still unable to resolve the error

**Comment by exhaler** [comment] 2021-09-27 14:39
I'm getting the same error as well

> 2021-09-27T14:23:53Z   [Verbose]   [HostMonitor] Worker status: ID=0a923147-f53b-4909-9483-3ed0aa018971, Latency=45351ms
> 2021-09-27T14:23:53Z   [Verbose]   [HostMonitor] Host process CPU stats (PID 5148): History=(95,93,92,91,93), AvgCpuLoad=92.8, MaxCpuLoad=95
> 2021-09-27T14:23:53Z   [Verbose]   [HostMonitor] Host process CPU stats (PID 3028): History=(3,0,1,2,1), AvgCpuLoad=1, MaxCpuLoad=3
> 2021-09-27T14:23:53Z   [Verbose]   [HostMonitor] Host aggregate CPU load 94
> 2021-09-27T14:23:53Z   [Warning]   [HostMonitor] Host CPU threshold exceeded (94 >= 80)
> 2021-09-27T14:23:53Z   [Warning]   Possible thread pool starvation detected.

My function is runing in Nodejs, this issue didn't appear couple of weeks ago

**Comment by ThomasArdal** [comment] 2021-09-28 11:37
Same here. I first noticed this in the log on Friday, September 17, 2021 07:14:51. Nothing changed around that time on my part.

**Comment by ThomasArdal** [comment] 2021-09-28 14:27
@exhaler Did you by any chance disable the health monitor in your `host.json` file?

**Comment by exhaler** [comment] 2021-09-28 14:31
Nope, the `host.json` hasn't changed

**Comment by v-anvari** [comment] 2021-09-28 15:19
Hi @ThomasArdal , Can we have the function invocation id, region name, and timestamp.

**Comment by ThomasArdal** [comment] 2021-09-28 17:48
I don't think I can provide an invocation id. At least an invocation id is not logged alongside the log message. I seems to come through Microsoft.Extensions.Logging but not as part of any invocation.

I have multiple instances of this logged. Here are a recent one:

Time: `2021-09-28T15:08:50.606136Z`
Region: `North Europe`

It's happening in West US, Brazil, etc. too. But only for consumption-based functions. None of my app service-based functions are logging this warning.

**Comment by v-anvari** [comment] 2021-09-30 09:51
Hi @ThomasArdal , Any invocation id would be sufficient, We require the invocation id to reach your App logs

**Comment by ThomasArdal** [comment] 2021-09-30 09:53
@v-anvari I see. Here's an invocation id from North Europe: 4dd84024-8b2b-4d0c-9fe2-328ea326d1cd

**Comment by v-anvari** [comment] 2021-09-30 09:55
Thank you for the information. We shall further investigate and update as appropriate

**Comment by v-anvari** [comment] 2021-10-07 16:42
Hi @ThomasArdal , I have gone through the logs, and I see that on 17 sep the instance picked up a new host version, to confirm if the issue is with the host version, can you pin the runtime[ 3.1.4](https://github.com/Azure/azure-functions-host/releases/tag/v3.1.4)  and let us know if you still see any issue. This will let us conclude if its because of the version.

Secondly, you can do a quick analysis by pulling the memory dump to check if any object is stuck in the pool which is causing any delays https://docs.microsoft.com/en-us/answers/questions/401671/how-to-capture-memory-dump-of-consumption-plan-fun.html

**Comment by ThomasArdal** [comment] 2021-10-07 18:32
Ah sorry. I think I found it here: https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal.

I have the same function app deployed to two different regions. I'll try to set `FUNCTIONS_EXTENSION_VERSION` to `~3` on one of them and `3.1.4` on the other one. And observe the logs from both apps to see if they both still produce the warning. Will let you know about my findings.

**Comment by v-anvari** [comment] 2021-10-11 13:07
@exhaler yes, when you use tilde "~", it should be using the latest version, Can you provide the invocation id, timestamp and region

**Comment by v-anvari** [comment] 2021-10-12 13:28
FYI  @pragnagopa

**Comment by exhaler** [comment] 2021-10-15 13:34
@ThomasArdal Ahh that means that your app is actually using `3.1.3.0` like the message says. I believe you can check this if you open the log stream the azure function version will show up

**Comment by ThomasArdal** [comment] 2021-10-15 13:37
@exhaler I'm afraid I don't have app insights enabled. But that sounds right and that is what the error on *Function runtime settings* says as well. I wonder why it is picking up `3.1.3.0` as "the latest version of the runtime". It's clearly not since there's a 3.2.x available too.

**Comment by ThomasArdal** [comment] 2021-10-15 13:46
@exhaler Could be. Just tried pinning to `3.1.3.0` and that also seems to work and the error is now a warning:

```
Your app is currently pinned to runtime version '3.1.3.0'. When this version is no longer supported your app will start using the latest version of the runtime, which could be a different major version and might contain breaking changes. It is advised to set that value to a specific major version (e.g. ~2) and you will get notified with newer versions for update.
```

🤷‍♂️

**Comment by ThomasArdal** [comment] 2021-10-20 07:53
@villevauhkonen-qoco I believe `3.1.3.0` is available in all regions but not sure. At least I only get a warning in the Azure portal when pinning to that version with a warning saying I will be upgraded once that version is no longer available.

**Comment by villevauhkonen-qoco** [comment] 2021-10-20 08:00
@ThomasArdal We have used now 3.1.4 and I can confirm that it's working properly, no alerts or high CPU. We are good with that for now, but of course ideal situation would be always use the most recent (stable) one. Anyways thanks for investigating and debugging this, so little information available of this one.

**Comment by villevauhkonen-qoco** [comment] 2021-10-20 08:10
@ThomasArdal I just checked and you are right. Seems that 3.1.4 defaults to 3.1.3. We use App Service Configuration FUNCTIONS_EXTENSION_VERSION to control this. 
![image](https://user-images.githubusercontent.com/53738266/138053648-015159ef-ea38-44a8-9092-8d0e3673aaec.png)

**Comment by ThomasArdal** [comment] 2021-10-20 08:12
Yep exactly. Using `FUNCTIONS_EXTENSION_VERSION` as well. Out of curiosity where is that screenshot taken from?

**Comment by liliankasem** [comment] 2021-11-03 20:32
It looks like pinning the version to 3.1.4 solved the original issue. Closing the issue.

**Comment by ThomasBleijendaal** [comment] 2021-11-03 23:04
So by pinning it to a 3.1.4 we can solve the warning? What if version 3.1.4. is no longer available?

**Comment by ThomasArdal** [comment] 2021-11-04 05:48
Agree. I don't think this issue is closed. If the proposed solution here is to just use the old version. As @ThomasBleijendaal points out, what should we do when `3.1.4` is no longer available and the issue is not fixed in the newest version? Create a new issue with exactly the same text and go through this entire thread again just to find out that there's no longer an old version that we can pin to.

**Comment by liliankasem** [comment] 2021-11-04 16:05
My bad! I think there was a misunderstanding on our side. We'll reopen and flag for investigation :)

**Comment by mathewc** [comment] 2021-11-10 00:57
This warning is logged by Functions host monitoring when it determines based on heuristics that the threadpool is unable to process tasks in a timely manner. This signal will influence scale out decisions in Consumption/Elastic SKUs, and is also used by the preview [Dynamic Concurrency](https://docs.microsoft.com/en-us/azure/azure-functions/functions-concurrency) feature which I understand isn't being used in this particular case.

It's a warning, not an error, so as long as your function app is running well for you, you can ignore it. It will operate in the background to influence scale decisions. The expectation is that for a healthy app that is scaled properly you shouldn't see this often. If you are seeing it often, it may mean that you need to throttle your work (e.g. ServiceBusTrigger MaxConcurrentCalls, etc.), and/or scale up/out if you're in a non Consumption/Elastic SKU.

**Comment by chtay1** [comment] 2021-11-10 01:32
> This warning is logged by Functions host monitoring when it determines based on heuristics that the threadpool is unable to process tasks in a timely manner. This signal will influence scale out decisions in Consumption/Elastic SKUs, and is also used by the preview [Dynamic Concurrency](https://docs.microsoft.com/en-us/azure/azure-functions/functions-concurrency) feature which I understand isn't being used in this particular case.
> 
> It's a warning, not an error, so as long as your function app is running well for you, you can ignore it. It will operate in the background to influence scale decisions. The expectation is that for a healthy app that is scaled properly you shouldn't see this often. If you are seeing it often, it may mean that you need to throttle your work (e.g. ServiceBusTrigger MaxConcurrentCalls, etc.), and/or scale up/out if you're in a non Consumption/Elastic SKU.

What we are seeing is that this is occurring in conjunction with high CPU usage, noted by a couple of others here also, like below from our logs.

message: [HostMonitor] Host CPU threshold exceeded (91 >= 80)
event props: aggregateCpuLoad=91, cpuThreshold=80, EventId_Id=327, EventId_Name=HostCpuThresholdExceeded, EventId=HostCpuThresholdExceeded

**Comment by ThomasBleijendaal** [comment] 2021-11-10 16:21
I get these messages while I my Azure Functions are hosted in a Elastic SKU Service Plan, and also on our acceptance environment which has almost no traffic or load.

**Comment by mathewc** [comment] 2021-11-10 16:26
@chtay1 Yes often when you're getting the high CPU warnings you'll also see these warnings. The monitor is working as intended in these cases - the host is under high load.

If you don't want to see the warnings in your log stream, you could filter them via log config in host.json: https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2.

**Comment by Bpflugrad** [comment] 2022-03-08 17:02
This problem is affecting my Azure Functions V4 (4.1.3.17473) regardless of load.
Here's a sample invocation Id def139d3-f33c-4d57-9fb3-e706580323e5, UTC timestamp 2022-03-07T22:20:06.472Z, region Central US.  This is hosted on an EP1: 1 App Service Plan.
We received 23 of these warnings between 2022-03-08T05:34:46.683Z and 2022-03-08T13:57:43.99Z when there was no load (this is a development deployment).
I also seem to observe the hosts stopping and starting more often than in Azure Functions V3.  We are in the process of migrating everything to .NET 6 and V4 to stay within LTS.  This is concerning for the stability of the applications though.

Is there any more information about this?

Yellow lines on the chart indicate approximate times between which the warnings occurred, not exhaustive.
![image](https://user-images.githubusercontent.com/26801962/157287410-7d7a152c-364c-41ea-bb9b-e010fdd13b7c.png)

**Comment by Bpflugrad** [comment] 2022-03-09 15:41
For anyone still running into this problem: Two of my applications were exhibiting it, which was pretty concerning.  Another bug with configuration values became apparent and was caused by [azure-functions-host issue 2015](https://github.com/Azure/azure-functions-host/issues/2015).  After setting `AzureFunctionsWebHost:hostId` to unique values under 32 characters on all deployment Slots, the Thread Pool Starvation warning ceased.

**Comment by JosefBackovsky** [comment] 2022-03-29 12:02
I am having same issue with V4 (4.1.3.17473) dotnet isolated process. I am not using deployment Slots (just production).

**Comment by BrunoJuchli** [comment] 2022-07-06 05:52
For us this warning has started to appear en masse yesterday 5th July 2022 from around 13:30 without us changing anything in code for the past few days.
![image](https://user-images.githubusercontent.com/2090172/177478002-7e0afaf3-69b8-4309-be4e-d2daf615d8f5.png)

It looks like to coincide with a restart of service (we didn't deploy).
![image](https://user-images.githubusercontent.com/2090172/177477893-71d5661f-4274-4331-80f2-c93b229adb44.png)

(From what I understand this spike happens on a restart; the functions are all timer triggered so after the temporary outage there's a peak where they are being caught up).

Azure region: Switzerland North
Example Function Operation ID:  9fa3ea18ca0dec577b86f071188055c5

**Comment by brandonh-msft** [comment] 2022-09-15 19:34
Seeing this today in Func V4.11 and a **Functions EP1 Premium** plan

![image](https://user-images.githubusercontent.com/20270743/190492991-b5758440-cec9-43d7-b421-b51ecb1bcc1d.png)

**Comment by durayakar** [comment] 2022-12-13 01:07
We see this on storage account queue triggered PowerShell 7.2 function app. 
The host is configured for 64 bit. 
The storage account queue has 4 messages in it. 

The plan is a P1V2. 
There is no other code/process  running at this time on this app plan.
This is the one and ONLY function app. 
The CPU hits %100 the moment the function is enabled. 

We use PaaS services to not to deal with underlying platform issues like this. 
Is ANY CUSTOMER using a simple storage queue trigger function app in production? 
How are they using this? 

Version is v4. The entire function code is below: 
```
# Input bindings are passed in via param block.
param($QueueItem, $TriggerMetadata)
# Write out the queue message and insertion time to the information log.
Write-Host "PowerShell queue trigger function processed work item: $QueueItem"
Write-Host "Queue item insertion time: $($TriggerMetadata.InsertionTime)"
```

host.json : 
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  },
  "managedDependency": {
    "enabled": true
  },
  "concurrency": {
    "dynamicConcurrencyEnabled": true,
    "snapshotPersistenceEnabled": true
  }
}
```

function.json :
```
{
  "bindings": [
    {
      "name": "QueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "adgroups-dev",
      "connection": "azdbdev_STORAGE"
    }
  ]
}
```

**Comment by aironi** [comment] 2023-03-09 09:39
Hi! We observe the same problem when running Java Function App is Elastic Premium 2 and host version 4. The warning could not be observed with function host 3.

Logs:

```
WARNING11:49:27.170 AM
[HostMonitor] Host CPU threshold exceeded (97 >= 80)

WARNING11:49:27.175 AM
Possible thread pool starvation detected.
```

Any updates or plans to fix this?

**Comment by liliankasem** [comment] 2023-03-09 23:45
Hey everyone, it'd like to reiterate what @mathewc previously commented about this issue:

> This warning is logged by Functions host monitoring when it determines based on heuristics that the threadpool is unable to process tasks in a timely manner. This signal will influence scale out decisions in Consumption/Elastic SKUs, and is also used by the preview [Dynamic Concurrency](https://docs.microsoft.com/en-us/azure/azure-functions/functions-concurrency) feature which I understand isn't being used in this particular case.
> 
> It's a warning, not an error, so as long as your function app is running well for you, **you can ignore it**. It will operate in the background to influence scale decisions. The expectation is that for a healthy app that is scaled properly you shouldn't see this often. If you are seeing it often, it may mean that you need to throttle your work (e.g. ServiceBusTrigger MaxConcurrentCalls, etc.), and/or scale up/out if you're in a non Consumption/Elastic SKU.

Additionally, the reason for this warning will vary from app to app because every application is unique and I'm concerned folks are not getting the support they need as more comments are added to this thread.

If this is something that is impacting your application and you don't understand why (i.e. how your code could be causing thread pool starvation and/or think there's a problem with the host/platform), please open a support ticket (or a new issue) so we can look into each individual application - this will make it easier for us to find issues and fix them.

**Closed by liliankasem** 2023-03-09 23:45 UTC

**Comment by chtay1** [comment] 2023-03-10 00:41
For what it's worth I believe our issue in the end was related to our application not the Azure Functions framework. Within our functions we were adding messages to service bus, sometimes in bulk, but we were not using best practices in terms of reuse of the ServiceBusClient and as such causing thread pool starvation and high CPU.

**Comment by aironi** [comment] 2023-03-15 08:59
Thank you for the update. In our case our application is performing parallel operations for several integrations (reactive streams) so I was a bit concerned whether our app was to blame here. It seems it is not.
