### ISSUE TITLE
Getting an intermittent 503 "unexpected error occured while fetching the AAD Token" when using MSICredential to access KeyVault and Blob Storage

### ISSUE THREAD

**Issue by jjgriff93** [Azure/Azure-Functions#1486] opened 2020-02-13 13:58 UTC
We are using MSI to access blob and KeyVault resources from our Azure Function, which is a Python Function running on a Linux Consumption plan.

The code is implemented like this for working with blob:
```
from azure.storage.blob import BlobClient, ContainerClient
from azure.identity import DefaultAzureCredential


# Get environment variables
cities_config_url = os.environ["CITIES_CONFIG_URL"]
blob_credential = DefaultAzureCredential() # Same behaviour if using ManagedIdentityCredential()

def create_blob_client(url):
    """Create blob client from URL to read/write blobs to Azure"""
    blob_client = BlobClient.from_blob_url(url, credential=blob_credential)
    return blob_client

polygon_blob_client = create_blob_client(cities_config_url)

    try:
        # Download polygon JSON blob from Azure Storage
        polygons_filestream = polygon_blob_client.download_blob() # << This is where an error occurs
```

And like this for working with KeyVault:
```
key_vault_uri = os.environ["KEY_VAULT"]
maps_endpoint = os.environ["AZURE_MAPS_ENDPOINT"]

def get_maps_subscription_key():
    """Retrieves Azure Maps key secret from Key Vault"""
    credential = ManagedIdentityCredential()
    client = SecretClient(vault_url=key_vault_uri, credential=credential)
    try:
        maps_key = client.get_secret("mapskey").value # << This is where other error occurs
        return maps_key
```

We've enabled MSI access on the Function and set up all the necessary permissions, and when deploying to the Function App it works initially for the first few runs; however then a 503 error crops up and persists across following runs until code is redeployed, where it works again for a few runs then fails.

It will either fail on the blob call first or the keyvault call, it seems random. The blob MSI failure is the following (notice that the IMDS endpoint unavailable exception causes an exception within the blod SDK handling, which I've raised with the blob team separately):
```
Exception: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\storage\blob\_download.py", line 366, in _initial_request
    **self._request_options
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\storage\blob\_generated\operations\_blob_operations.py", line 163, in download
    pipeline_response = self._client._pipeline.run(request, stream=True, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\core\pipeline\_base.py", line 208, in run   
    return first_node.send(pipeline_request)  # type: ignore
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\core\pipeline\_base.py", line 80, in send   
    response = self.next.send(request)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\core\pipeline\_base.py", line 80, in send   
    response = self.next.send(request)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\core\pipeline\_base.py", line 80, in send   
    response = self.next.send(request)
  [Previous line repeated 3 more times]
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\core\pipeline\_base.py", line 78, in send   
    _await_result(self._policy.on_request, request)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\core\pipeline\_base.py", line 47, in _await_result
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\core\pipeline\policies\_authentication.py", 
line 82, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\identity\_credentials\managed_identity.py", 
line 152, in get_token
    raise ClientAuthenticationError(message="IMDS endpoint unavailable")
azure.core.exceptions.ClientAuthenticationError: IMDS endpoint unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jamesgr\Desktop\TEAL\teal-ml\traffic-collection\__app__\SharedCode\blobutils.py", line 39, in get_polygonsJSON
    polygons_filestream = polygon_blob_client.download_blob()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\core\tracing\decorator.py", line 62, in wrapper_use_tracer
    return func(*args, **kwargs) # type: ignore
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\storage\blob\_blob_client.py", line 601, in 
download_blob
    return StorageStreamDownloader(**options)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\storage\blob\_download.py", line 316, in __init__
    self._response = self._initial_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\storage\blob\_download.py", line 385, in _initial_request
    if self._start_range is None and error.response.status_code == 416:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

And the KeyVault MSI failure is:
```
Could not get Key Vault secret
Traceback (most recent call last):
  File "/home/site/wwwroot/SharedCode/maputils.py", line 39, in get_maps_subscription_key
    maps_key = client.get_secret("mapskey").value
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator.py", line 71, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_client.py", line 71, in get_secret
    **kwargs
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_shared/_generated/v7_0/operations/_key_vault_client_operations.py", line 1621, in get_secret
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 208, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/policies/_retry.py", line 418, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 67, in send
    self._handle_challenge(request, challenge)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 91, in _handle_challenge
    access_token = self._credential.get_token(scope)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/managed_identity.py", line 204, in get_token
    token = self._request_app_service_token(scopes=scopes, resource=resource, secret=secret)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/managed_identity.py", line 214, in _request_app_service_token
    return self._client.request_token(scopes, method="GET", headers={"secret": secret}, params=params)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_authn_client.py", line 207, in request_token
    token = self._deserialize_and_cache_token(response=response, scopes=scopes, request_time=request_time)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_authn_client.py", line 104, in _deserialize_and_cache_token
    raise ClientAuthenticationError(message="Unexpected response '{}'".format(payload))
azure.core.exceptions.ClientAuthenticationError: Unexpected response '{'statusCode': 503, 'message': 'An unexpected error occured while fetching the AAD Token.', 'correlationId': '2dfc25e0-c062-4c74-be39-38d268a37cef'}'
```
 
Seems to be related to [Issue 1065](https://github.com/Azure/Azure-Functions/issues/1065). Happy to provide details of our function for further investigation

Thanks!

**Comment by jjgriff93** [comment] 2020-02-19 09:42
I have also tested the same code deployed to a Linux App Service Plan host (Basic tier) and this has resolved the 503 errors so it indeed appears that the issue is localised to the Linux consumption plan host

**Comment by fcstring31** [comment] 2020-03-19 16:07
Receiving the same error on a Node app in Linux consumption plan. It was intermittent until today - neither a fresh deploy or app restart are helping now.

**Comment by balag0** [comment] 2021-01-21 18:57
The fix for this issue is in progress. (Functions host version 3.0.15277)
The deployment is expected to complete in next few days. West US2 has been deployed so far. I will update this thread when deployment is complete. 

(You might have to restart the app once to get the latest functions host version if the app has been running continously)

**Comment by balag0** [comment] 2021-01-27 02:31
Fix has been deployed in all the regions. Please restart the app to make sure the app is running the latest version. Let us know if you are still seeing any issues.

**Comment by HoLengZai** [comment] 2021-02-10 11:17
Hi @balag0,
Seems to work but sometimes, after deploying a new version of my Azure Function. I still got the issue.
I have to restart my whole Function App, to get rid of this message.

please find some of my logs below. I confirmed that i used the version "3.0.15277" (West Europe)
```
"2021-02-10T11:11:24.242336264Z: [INFO]  [40m[32minfo[39m[22m[49m: Function.CDP_Ansible_HttpTrigger.User[0]
2021-02-10T11:11:24.242346264Z: [INFO]            'Server': 'Kestrel'
2021-02-10T11:11:24.243169069Z: [INFO]  [40m[32minfo[39m[22m[49m: Function.CDP_Ansible_HttpTrigger.User[0]
2021-02-10T11:11:24.243294070Z: [INFO]            'Transfer-Encoding': 'chunked'
2021-02-10T11:11:24.244022574Z: [INFO]  [40m[1m[33mwarn[39m[22m[49m: Function.CDP_Ansible_HttpTrigger.User[0]
2021-02-10T11:11:24.244031874Z: [INFO]        AppServiceCredential.get_token failed: (None) An unexpected error occured while fetching the AAD Token.
2021-02-10T11:11:24.244436477Z: [INFO]  [40m[1m[33mwarn[39m[22m[49m: Function.CDP_Ansible_HttpTrigger.User[0]
2021-02-10T11:11:24.244445577Z: [INFO]        ManagedIdentityCredential.get_token failed: (None) An unexpected error occured while fetching the AAD Token.
2021-02-10T11:11:24.244929680Z: [INFO]  [40m[1m[33mwarn[39m[22m[49m: Function.CDP_Ansible_HttpTrigger.User[0]
2021-02-10T11:11:24.244939580Z: [INFO]        DefaultAzureCredential.get_token failed: ManagedIdentityCredential raised unexpected error "(None) An unexpected error occured while fetching the AAD Token."
2021-02-10T11:11:24.245233982Z: [INFO]  [40m[1m[33mwarn[39m[22m[49m: Function.CDP_Ansible_HttpTrigger.User[0]
2021-02-10T11:11:24.245242982Z: [INFO]        DefaultAzureCredential failed to retrieve a token from the included credentials.
2021-02-10T11:11:24.245245982Z: [INFO]        Attempted credentials:
2021-02-10T11:11:24.245327482Z: [INFO]        	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2021-02-10T11:11:24.245335782Z: [INFO]        	ManagedIdentityCredential: (None) An unexpected error occured while fetching the AAD Token.
2021-02-10T11:11:24.293813477Z: [INFO]  [41m[30mfail[39m[22m[49m: Function.CDP_Ansible_HttpTrigger[3]
2021-02-10T11:11:24.293827977Z: [INFO]        Executed 'Functions.CDP_Ansible_HttpTrigger' (Failed, Id=e5f3280d-91d6-4843-9609-00228b68b1b9, Duration=6648ms)
2021-02-10T11:11:24.293944378Z: [INFO]  Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.CDP_Ansible_HttpTrigger
2021-02-10T11:11:24.293953878Z: [INFO]   ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
2021-02-10T11:11:24.293957578Z: [INFO]  Exception: ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
2021-02-10T11:11:24.294047579Z: [INFO]  Attempted credentials:
2021-02-10T11:11:24.294056479Z: [INFO]  	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2021-02-10T11:11:24.294060279Z: [INFO]  	ManagedIdentityCredential: (None) An unexpected error occured while fetching the AAD Token."
```

**Comment by balag0** [comment] 2021-02-11 21:57
@HoLengZai Looks like your app is not running on consumption plan. Could you open a separate issue as this issue is specific to consumption sku. (and tag me there)

Also closing this issue since the deployment is now complete and we have verified we don't see this issue anymore.

**Closed by balag0** 2021-02-11 21:57 UTC

**Comment by sa1sen** [comment] 2023-05-13 07:09
Hi @balag0 I have a similar issue as above. We are on latest Azure Function runtime running Linux Consumption. Multiple concurrent session are being invoked and it seem after a while ManagedIdentityCredential fails even though it works in the first ~5-10 mins. Outlined detailed issue on: https://github.com/Azure/azure-sdk-for-net/issues/36210

Created a new bug defect on: https://github.com/Azure/Azure-Functions/issues/2374

Thanks
