### ISSUE TITLE
Authorization Error for Azure Function in sealed Environment

### ISSUE THREAD

**Issue by ackermann81** [Azure/Azure-Functions#2329] opened 2023-01-23 08:59 UTC
Hi,
we are hosting software for our customer and has a sealed environment. Meaning all Azure Ressources are only available through private endpoints and can´t talk in or our of it network. 
We immplemented a Azure Function to trigger a transport from Blobservice of one storage account to Fileshare to another storage account. This works. But we hhave eseen issues in the LogAnalytics Errors fro the Function Host and also realize that the function is breaking of at some point. 

Its an Authorization issue but we cannot find out where or what as the info is not enough. Does anyone knows where i can search with the request id? From the callstack it seems something internal in AZure. 
Thhanks
Robert

Azure.RequestFailedException : This request is not authorized to perform this operation.
RequestId:e0e57144-8003-0058-3306-2fd585000000
Time:2023-01-23T08:39:06.8473569Z
Status: 403 (This request is not authorized to perform this operation.)
ErrorCode: AuthorizationFailure Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:e0e57144-8003-0058-3306-2fd585000000
Time:2023-01-23T08:39:06.8473569Z</Message></Error> Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: e0e57144-8003-0058-3306-2fd585000000
x-ms-error-code: AuthorizationFailure
Date: Mon, 23 Jan 2023 08:39:06 GMT
Content-Length: 246
Content-Type: application/xml    at async Azure.Storage.Queues.MessagesRestClient.EnqueueAsync(QueueMessage queueMessage,Nullable`1 visibilitytimeout,Nullable`1 messageTimeToLive,Nullable`1 timeout,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Azure.Storage.Queues.QueueClient.SendMessageInternal(BinaryData message,Nullable`1 visibilityTimeout,Nullable`1 timeToLive,Boolean async,CancellationToken cancellationToken,String operationName)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Azure.Storage.Queues.QueueClient.SendMessageAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Common.StorageQueueExtensions.AddMessageAndCreateIfNotExistsAsync(QueueClient queue,BinaryData body,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Queues.QueueProcessor.CopyMessageToPoisonQueueAsync(QueueMessage message,QueueClient poisonQueue,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Queues.QueueProcessor.HandlePoisonMessageAsync(QueueMessage message,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Queues.QueueProcessor.BeginProcessingMessageAsync(QueueMessage message,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Common.Listeners.QueueListener.ProcessMessageAsync(QueueMessage message,TimeSpan visibilityTimeout,CancellationToken cancellationToken)

**Comment by bhagyshricompany** [comment] 2023-01-23 09:01
Thanks for the update can you share the region appname,id etc

**Comment by ackermann81** [comment] 2023-01-23 09:04
Region: West Europe 
Whats the Appname id ?

**Comment by bhagyshricompany** [comment] 2023-01-23 09:07
functionid and appname

**Comment by ackermann81** [comment] 2023-01-23 09:21
One addition the error before this is:
Message has reached MaxDequeueCount of 5. Moving message to queue 'webjobs-blobtrigger-poison'.

We will try to create the queue. Maybe this is an issue that he cant create it.

**Comment by ackermann81** [comment] 2023-01-23 09:53
Also the Blobtrigger was done manually by json and not by the azure portal
appname: func-lpa-powershell-int-euw
functionname: Blob2Share_HSBC

**Comment by bhagyshricompany** [comment] 2023-01-23 10:32
please share the repro steps

**Comment by ackermann81** [comment] 2023-01-23 19:10
Hi, as the exception comes direct after  moving the message top webjobs-blobtrigger-poson we created the queue in the function storage account and the opne wherre the blobtrigger points to.

**Comment by ackermann81** [comment] 2023-01-23 21:03
Repro was:
- Create Powershell Function App with Storage Account as Base
- add Storage Account Link by Set-AZFunctionSetting
- add 'Az.Storage' = '5.*' to requirements.psd1 by  File Share on the func storage account
- Add Run.ps1 script and Blobtrigger in Function.json by File Share on the func storage account
- give contributor rights on source blob storage account and target fileshare storage account
- the function itself works but is disrupted due to unhandled exceptions restarting the function app host

function.json:
{
  "bindings": [
    {
      "name": "InputBlob",
      "path": "xxxx",
      "connection": "xxxx_STORAGE",
      "direction": "in",
      "type": "blobTrigger"
    }
  ]
}

run.ps1:
# Input bindings are passed in via param block.
param([byte[]] $InputBlob, $TriggerMetadata)

$ErrorActionPreference = "Stop"
Set-Content -Path out.txt -value $InputBlob -AsByteStream -Force
$contextFS = Get-AzStorageAccount -ResourceGroupName xx -Name xtarget
$contextBS = Get-AzStorageAccount -ResourceGroupName xx -Name xsource
Set-AzStorageFileContent -Context $contextFS.Context -ShareName 'xx' -Source out.txt -Path ('/xx/'+$TriggerMetadata.BlobTrigger.Split("/")[-1]) -Force
Remove-AzStorageBlob -Blob $TriggerMetadata.BlobTrigger.Split("/")[-1] -Container $TriggerMetadata.BlobTrigger.Split("/")[-2] -Context $contextBS.Context
Write-Host "PowerShell Blob trigger function Processed blob! Name: $($TriggerMetadata.BlobTrigger) Size: $($InputBlob.Length) bytes"

**Comment by bhagyshricompany** [comment] 2023-01-24 10:28
thanks will update you asap

**Comment by bhagyshricompany** [comment] 2023-01-24 18:16
As first error message 
It looks like the issue is with the Azure Storage Queue's MessagesRestClient and the error message suggests that the request is not authorized to perform the operation.

There are a few things you can check to troubleshoot this issue:

Verify that the Azure Storage account and the associated Azure Function app have the correct permissions to access the storage queue.
Check if the storage account and the associated Azure Function app are in the same Azure subscription and Azure Active Directory tenant.
You can also check the Azure Function app's identity and ensure that it has been granted the appropriate permissions to access the storage account.
Check the connection string and endpoint of storage account.
Check the service endpoint configuration of your VNet.
And Addition one error you mention for posion queue related
It looks like the error message is indicating that the message has reached the maximum dequeue count of 5 and is being moved to the poison queue 'webjobs-blobtrigger-poison'.

This typically means that the message has been dequeued and processed multiple times without being successfully processed, and is now being moved to a separate queue for further investigation.

It's possible that the issue is with the function that is processing the message, and it is causing it to fail. You should check the function's code and configuration to see if there is any issue that is causing it to fail.

Additionally, It could be that the poison queue is not created yet and the function is trying to move the message to it, so creating the poison queue could resolve the issue.

You can also check the Azure Monitor logs for more information on the error. The request ID you provided in your error message can be used to correlate the error message with the corresponding log entry in Azure Monitor.

**Comment by bhagyshricompany** [comment] 2023-01-31 10:02
No input  hope got you answer  am closing here if have question open new issue.
Thanks

**Comment by bhagyshricompany** [comment] 2023-01-31 10:03
No input hope got you answer am closing here if have question open new issue.
Thanks

**Closed** 2023-01-31 10:02 UTC
Labels: Needs: Author feedback

**Comment by arpanD93** [comment] 2023-12-06 08:42
@bhagyshricompany  we're also seeing same error. And it's not happening constantly, sometimes the functionapp is up and sometimes it's down. 

Message':'Message has reached MaxDequeueCount of 5. Moving message to queue webjobs-blobtrigger-poison.','category':'Microsoft.Azure.WebJobs.Host.Queues.QueueProcessor','hostVersion':'4.27.7.7','hostInstanceId':'065e5d1f-552f-498e-995f-73d9b26c6776','level':'Warning','levelId':3,'processId':24}",12/06/2023 08:33:58
2023-12-06T08:33:58.287195333Z MS_FUNCTION_AZURE_MONITOR_EVENT 3,FUNCTIONAPP.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,centralus,"{'appName':'FUNCTIONAPP','roleInstance':'638c3f4028214874bb1422f281053d75a28e137fcc4664bddc4c62c64dacf840','message':'Message has reached MaxDequeueCount of 5. Moving message to queue webjobs-blobtrigger-poison.','category':'Microsoft.Azure.WebJobs.Host.Queues.QueueProcessor','hostVersion':'4.27.7.7','hostInstanceId':'065e5d1f-552f-498e-995f-73d9b26c6776','level':'Warning','levelId':3,'processId':24}",12/06/2023 08:33:58
2023-12-06T08:33:58.294776490Z MS_FUNCTION_AZURE_MONITOR_EVENT 3,FUNCTIONAPP.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,centralus,"{'appName':'FUNCTIONAPP','roleInstance':'638c3f4028214874bb1422f281053d75a28e137fcc4664bddc4c62c64dacf840','message':'Message has reached MaxDequeueCount of 5. Moving message to queue webjobs-blobtrigger-poison.','category':'Microsoft.Azure.WebJobs.Host.Queues.QueueProcessor','hostVersion':'4.27.7.7','hostInstanceId':'065e5d1f-552f-498e-995f-73d9b26c6776','level':'Warning','levelId':3,'processId':24}",12/06/2023 08:33:58
2023-12-06T08:34:00.277809598Z MS_FUNCTION_AZURE_MONITOR_EVENT 2,FUNCTIONAPP.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,centralus,"{'appName':'FUNCTIONAPP','roleInstance':'638c3f4028214874bb1422f281053d75a28e137fcc4664bddc4c62c64dacf840','message':'An unhandled exception has occurred. Host is shutting down.
