### ISSUE TITLE
My function app is called every 10 seconds by ElasticScaleController

### ISSUE THREAD

**Issue by 0xced** [Azure/Azure-Functions#703] opened 2018-03-05 15:21 UTC
I recently created a new function app and I have noticed that it is called every 10 seconds.

Here are the streaming logs I see:

```
2018-03-05T15:04:55  Welcome, you are now connected to log-streaming service.
2018-03-05T15:05:02.111 [Info] Executing HTTP request: {
  "requestId": null,
  "method": "GET",
  "uri": "/"
}
2018-03-05T15:05:02.111 [Info] Executed HTTP request: {
  "requestId": "37d1629b-e0fb-4c79-978f-4b1aee9e6ea7",
  "method": "GET",
  "uri": "/",
  "authorizationLevel": "Anonymous"
}
2018-03-05T15:05:02.111 [Info] Response details: {
  "requestId": "37d1629b-e0fb-4c79-978f-4b1aee9e6ea7",
  "status": "NoContent"
}
2018-03-05T15:05:12.414 [Info] Executing HTTP request: {
  "requestId": null,
  "method": "GET",
  "uri": "/"
}
2018-03-05T15:05:12.414 [Info] Executed HTTP request: {
  "requestId": "6d2df424-5360-453c-a1ed-b5f4b865871e",
  "method": "GET",
  "uri": "/",
  "authorizationLevel": "Anonymous"
}
2018-03-05T15:05:12.414 [Info] Response details: {
  "requestId": "6d2df424-5360-453c-a1ed-b5f4b865871e",
  "status": "NoContent"
}
```

So I setup a proxy on `/` to go through a `DumpRequest` function that I wrote and I discovered that those requests are coming from IP address *10.0.128.19* with user agent *ElasticScaleController/70.0.8598.38*.

All these requests make my logs unreadable, so is there a way to disable these requests ?

I had created another function app under another account and I had never seen such requests, I wonder what's the difference between my old function app and this one.

**Comment by cgillum** [comment] 2018-03-05 18:31
These requests are intended to keep your function app alive when running in the consumption plan. You'll continue to see this as long as there are inputs to your function app that need to be processed (e.g. messages in a queue, event hub, etc.).

As for log spam, it's unfortunate, but the recommendation is to switch to Application Insights for your logging needs. That will make it much easier for you to filter these out. @mathewc or @brettsam is it possible to filter out the HTTP logs that get written when using the old file-based logging system?

**Comment by 0xced** [comment] 2018-03-05 20:05
> You'll continue to see this as long as there are inputs to your function app that need to be processed (e.g. messages in a queue, event hub, etc.).

The thing is, my function app is now idle for several hours (all queues are empty, no HTTP nor blob trigger for hours) and I keep seing these requests. I also tried to restart the function app, but I keep seeing these logs every 10 seconds.

Here is how to [identify my function app](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) for you to investigate: `2018-03-05T20:02:20.556 [Info] Function started (Id=ee818d59-48b0-4984-bb16-9c88f2aa3f52)` (West Europe)

**Comment by cgillum** [comment] 2018-03-05 20:15
Thanks for the additional info. Looks like you are running into a bug I fixed earlier this morning. :)

The problem is that you have a manualTrigger function configured in your function app. The scale controller mistakenly mis-categorizes manual triggers as function types that need to be constantly kept alive, and this is why you're getting constant pings.

You can resolve this by deleting or disabling the manualTrigger. In the next 4 weeks, my fix will go live and this behavior should stop happening. Sorry for the inconvenience!

**Comment by 0xced** [comment] 2018-03-05 23:57
> The problem is that you have a manualTrigger function configured in your function app.

Yes I do, I even submitted the pull request to [support manual triggers](https://github.com/Azure/azure-functions-vs-build-sdk/pull/140) for pre-compiled C# functions apps. 😉

Disabling the manual trigger functions indeed stopped this behavior.

Please keep us updated in this thread when your fix goes live.

**Comment by nevercast** [comment] 2018-06-09 23:06
I believe I'm seeing this issue in my Node.js function with only an `httpTrigger` binding. 
```
{
    "bindings": [{
      "authLevel" : "anonymous",
      "type"      : "httpTrigger",
      "direction" : "in",
      "name"      : "req",
      "route"     : "{*all}"
    }, {
      "type"      : "http",
      "direction" : "out",
      "name"      : "res"
    }]
  }
```

Analytics shows the request as
```
Incoming request: http://myfunctionapp/, headers: {   
    "connection": "Keep-Alive",   
    "host": "myfunctionapp",   
    "user-agent": "ElasticScaleController/74.0.8598.35",   
    "content-length": "0" 
}
```
I did not expect this keep alive activity as I would like my app to go to sleep (It is on a Consumption Plan)

**Comment by nevercast** [comment] 2018-08-03 01:52
@cgillum Can you please check this, these requests are spamming my Azure Functions to the point that they scale.

**Comment by cgillum** [comment] 2018-08-03 17:12
@nevercast You have an event hub trigger in your function app with new events available for processing during the times that I checked. Your function app needs to be kept awake to ensure those events will be processed. These pings will not be resulting in any scale operations.

I'm closing this issue since the original problem of manual triggers resulting in pings has been fixed.

**Closed by cgillum** 2018-08-03 17:12 UTC

**Comment by nevercast** [comment] 2018-08-04 01:05
I see, its hitting the http endpoint to keep alive the eventhub portion? Thanks for looking in to this.

**Comment by cgillum** [comment] 2018-08-06 17:18
Correct, it's hitting the built-in HTTP endpoint. There shouldn't be any side-effects of this. This ensures that all triggers, including your EventHub triggers, continue to run even if there is a process crash (because the HTTP pings will automatically restart the function app).

**Comment by nevercast** [comment] 2018-08-06 22:13
I have to handle this request myself though, it is not hitting a "built in" endpoint. As you can probably see, I've one project with 3 functions. One function takes items from the service bus and puts them in azure tables, the other two are http functions that pull data out of respective databases.

My `http` endpoint is being hit with the ElasticScaleController requests. Unfortunately these can take a while to respond since there is a large cold start on the `http` endpoint. It seems from my analytics tracing that if the scale requests take more than a few seconds to reply that the `http` endpoint scales up. Its hard to say for sure as I've not collected great data on this.

Either way, its not hitting a built-in HTTP endpoint, its instead hitting my node.js express endpoint with all its cold start glory.

**Comment by cgillum** [comment] 2018-08-06 23:47
Are you saying that your node.js function is being triggered by ElasticScaleController requests?

**Comment by nevercast** [comment] 2018-08-07 00:36
@cgillum That is precisely what I'm saying, unfortunately. I have code in production specifically to handle the ElasticScaleController requests, because they hit my http and if I don't process them they come up as failed requests.

**Comment by nevercast** [comment] 2018-08-07 00:37
@cgillum That is precisely what I'm saying, unfortunately. I have code in production specifically to handle the ElasticScaleController requests, because they hit my http and if I don't process them they come up as failed requests.
