### ISSUE TITLE
Service Bus output binding issue

### ISSUE THREAD

**Issue by bwwilliam** [Azure/Azure-Functions#442] opened 2017-08-16 00:46 UTC
Today, I updated my VS 2017 to version 15.3 (the latest). I also installed Azure functions extension (Visual Studio 2017 Tools for Azure Functions) and Microsoft.NET.Sdk.Functions -Version 1.0.0. 
Prior to the update, I was using the 15.3 preview and Microsoft Azure WebJobs Tools extension with Install-Package Microsoft.NET.Sdk.Functions alpha 6. My Azure functions worked fine with Service Bus binding as output.
After the update, the output binding stopped working.  
Error message: 
`Microsoft.Azure.WebJobs.Host: Error indexing method 'FunctionName'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'test' to type String&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).`

Can anyone please provide some help on this? 
Thanks.

**Comment by lindydonna** [comment] 2017-08-16 00:50
@bwwilliam Can you post your method definition and the contents of the generated function.json?

**Comment by bwwilliam** [comment] 2017-08-17 09:09
hi @lindydonna , please see the functions json below
`{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "httpTrigger",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "anonymous",
      "name": "req"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\FunctionApp1.dll",
  "entryPoint": "FunctionApp1.Function1.IACreate"
}`

Please also see the error message 
[17/08/2017 9:06:54 AM] The following 1 functions are in error:
[17/08/2017 9:06:54 AM] IACreate: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1.IACreate'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'test' to type String&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

**Comment by bwwilliam** [comment] 2017-08-17 09:09
Obviously, it is missing the output binding.

**Comment by lindydonna** [comment] 2017-08-18 01:02
@bwwilliam Can you post your method signature as well?

**Comment by bwwilliam** [comment] 2017-08-18 10:10
Hi @lindydonna 
Please see the signature of the Functions app below. 
[FunctionName("CreateApp")] public static HttpResponseMessage CreateApp([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]HttpRequestMessage req, [ServiceBus("writequeue", Connection = "AzureWebJobsServiceBus")] out string test, TraceWriter log)

**Comment by juchom** [comment] 2017-08-21 15:24
Same error with HttpBinding, worked fine before update to VS final 15.3 :

VS 2017 15.3 final
Azure Functions and Web Jobs Tools 15.0.30812.0

Error Message:

> [21/08/2017 15:20:29] A ScriptHost error has occurred
[21/08/2017 15:20:29] Microsoft.Azure.WebJobs.Host: Error indexing method 'PostEvent.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'req' to type HttpRequestMessage. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
[21/08/2017 15:20:29] Error indexing method 'PostEvent.Run'

Signature of my function:
`       
       [FunctionName("PostEvent")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]ClientEvents evt, HttpRequestMessage req, TraceWriter log)
        {
        }
`

Host.json
`
{
  "swagger": {
    "enabled": true
  }
}
`

**Comment by juchom** [comment] 2017-08-22 20:02
In my case it seems that direct binding to a POCO does not exist anymore.

Changing the signature and the reading the poco from the req did the job

`[FunctionName("PostEvent")] public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]HttpRequestMessage req, TraceWriter log) { }`

**Comment by hnanchahal** [comment] 2017-11-28 19:33
Is there an update to this issue? I modified the function.json manually to include the output binding and it works flawlessly but blows up if that is missing.

**Comment by mattchenderson** [comment] 2019-02-15 01:13
Closing as old / believed dupe of https://github.com/Azure/Azure-Functions/issues/446.

If this still is presenting an issue, please reopen.

**Closed by mattchenderson** 2019-02-15 01:13 UTC
