### ISSUE TITLE
Swagger Mixed Content Issue - http vs https

### ISSUE THREAD

**Issue by mikemassa84** [Azure/Azure-Functions#1933] opened 2021-06-15 13:37 UTC
The Swagger UI is not able to render when the Azure function is hosted on a dedicated Linux app service plan. Attempting to load the UI renders this error message:

![image](https://user-images.githubusercontent.com/14846033/122061752-6bb89b80-cdb4-11eb-9347-833a2c62135e.png)

You can also see this error here:
https://openapitestl.azurewebsites.net/api/swagger/ui

I've used the following library to decorate my function to generate the swagger.json:
**Microsoft.Azure.WebJobs.Extensions.OpenApi - v0.7.2-preview**

I tested the following function in these environments:

- Windows Consumption Plan - Success
- Linux Consumption Plan - Success
- **Linux Hosted Plan (P1v2) - Failure**

I used the Function1 template that is created by Visual Studio (2019) when picking the Http trigger with OpenAPI option.

```
public static class Function1
{
	[FunctionName("Function1")]
	[OpenApiOperation(operationId: "Run", tags: new[] { "name" })]
	[OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
	[OpenApiParameter(name: "name", In = ParameterLocation.Query, Required = true, Type = typeof(string), Description = "The **Name** parameter")]
	[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(string), Description = "The OK response")]
	public static async Task<IActionResult> Run(
		[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
		ILogger log)
	{
		log.LogInformation("C# HTTP trigger function processed a request.");

		string name = req.Query["name"];

		string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
		dynamic data = JsonConvert.DeserializeObject(requestBody);
		name = name ?? data?.name;

		string responseMessage = string.IsNullOrEmpty(name)
			? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
			: $"Hello, {name}. This HTTP triggered function executed successfully.";

		return new OkObjectResult(responseMessage);
	}
}
```

The issue was originally reported here:
https://github.com/Azure/azure-functions-openapi-extension/issues/77#issuecomment-861051941

**Comment by v-anvari** [comment] 2021-06-15 15:11
Hi @mikemassa84 , Thank you for your feedback, checking internally for the supportability. I shall update the information as appropriate

**Comment by v-anvari** [comment] 2021-06-22 11:11
Hi @mikemassa84 , I have checked internally on this issue, and the team wants to understand the issue further in details. Can you give is the template that you have used in visual studio, also, please provide the repro steps for us to reproduce this issue.

**Comment by mikemassa84** [comment] 2021-06-29 14:04
@v-anvari 

1. Create a new Function App in Azure
    1. Publish as Code
    2. Runtime stack .NET
    3. Version 3.1
    4. Region North Central US
    5. OS - Linux
    6. Plan - App Service Plan, P1v2
2. Create a new Azure Functions Project in Visual Studio 2019
    1. Create a new Function class using the Http trigger with OpenAPI option
    2. 
![image](https://user-images.githubusercontent.com/14846033/123811225-acd2a480-d8b8-11eb-8939-c44f535da7b1.png)
3. Publish the new function to your Azure Function App
4. Attempt to load the swagger UI page - `/api/swagger/ui`

**Comment by v-anvari** [comment] 2021-06-29 14:35
Hi @mikemassa84 , Thank you for the details, we shall reproduce this issue and update the findings

**Comment by v-anvari** [comment] 2021-07-05 10:05
Hi @mikemassa84 , I was unable to reproduce the issue exactly, below are the findings.

Azure Functions OpenAPI Extension- 1.0.0 

When I debug the App, I get  RenderSwaggerUI: [GET] http://localhost:7071/api/swagger/ui , I try to load this URl and the execution is successful

[2021-07-05T09:46:30.138Z] Executing 'Functions.RenderSwaggerDocument' (Reason='This function was programmatically called via the host APIs.', Id=54cf07b3-2f46-45f7-9da1-2745be7c2340)
[2021-07-05T09:46:30.150Z] swagger.json was requested.
[2021-07-05T09:46:30.386Z] Executed 'Functions.RenderSwaggerDocument' (Succeeded, Id=54cf07b3-2f46-45f7-9da1-2745be7c2340, Duration=258ms)

When I load the page - http://localhost:7071/api/swagger/ui

I get the below test environment in the swagger ui page 

![image](https://user-images.githubusercontent.com/66122429/124454568-43660080-dda6-11eb-9fde-1987c022678e.png)

When I load the following URL in the browser: https://functionapp120210705144152.azurewebsites.net/api/swagger.json

I get the below output:

`{
  "swagger": "2.0",
  "info": {
    "title": "Azure Functions OpenAPI Extension",
    "version": "1.0.0"
  },
  "host": "functionapp120210705144152.azurewebsites.net",
  "basePath": "/api",
  "schemes": [
    "http"
  ],
  "paths": {
    "/Function1": {
      "get": {
        "tags": [
          "name"
        ],
        "operationId": "Run",
        "produces": [
          "text/plain"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "description": "The **Name** parameter",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "The OK response",
            "schema": {
              "type": "string"
            }
          }
        },
        "security": [
          {
            "function_key": [ ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "function_key": {
      "type": "apiKey",
      "name": "code",
      "in": "query"
    }
  }
}`

**Comment by mikemassa84** [comment] 2021-07-06 13:28
Hi @v-anvari, in your example, if you hit the following URL in the browser, you will see the problem:

https://functionapp120210705144152.azurewebsites.net/api/swagger/ui

**Comment by v-anvari** [comment] 2021-07-06 14:09
Hi @mikemassa84 , Thank you for the details, Checking internally if we can hit the URL directly.

**Comment by v-anvari** [comment] 2021-07-26 16:43
Hi @justinyoo, Could you please check this issue with the OpenAPI

**Comment by Oceanswave** [comment] 2021-07-28 21:36
Running into this exact issue as well

**Comment by v-anvari** [comment] 2021-07-29 13:20
Thankyou for the information @Oceanswave . 

@mikemassa84 , Could you please try the above method

**Comment by mikemassa84** [comment] 2021-07-29 14:11
@Oceanswave Thanks for the tip! I didn't want to implement the entire IOpenApiConfigurationOptions, but was able to accomplish the same thing by setting an App Configuration setting named `OpenApi__HostNames` to `https://openapitestl.azurewebsites.net/api`.

![image](https://user-images.githubusercontent.com/14846033/127506860-5f10451c-da82-44d0-b791-ba63f57f6f4b.png)


@v-anvari This work around does work, but do you know why it is only required on a Linux hosted app service plan?

**Comment by v-anvari** [comment] 2021-08-31 11:05
Hi @mikemassa84 , This could be better answered by the open API team - https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#OpenAPI-Metadata-Configuration.  I was unable to collect an answer for you. Apologies. Closing this issue here as this issue is related to open Api

**Closed by v-anvari** 2021-08-31 11:05 UTC
Labels: Needs: Attention :wave:
