### ISSUE TITLE
Monitor tab contains only stale invocations / not updating

### ISSUE THREAD

**Issue by npiasecki** [Azure/Azure-Functions#259] opened 2017-04-21 22:00 UTC
I have 4 different function apps hosting precompiled functions on consumption plans. The Monitor tab for all functions displays invocations, but they're all stale. I can see the invocation data if I browse in Azure Storage Explorer. And logging on the "Function Name" tab (used to be called the "Develop" tab, I think) is showing current invocations. It's just everything in the Monitor tab is stale, for all function apps. Any ideas what could be causing this? A recent invocation that I should be seeing in the Monitor tab but am not is ce0ddbd1-6b61-4ce1-9c91-da810b9e0eaa; the region is East US.

**Comment by maucaro** [comment] 2017-04-22 21:51
I am seeing the same, also in East US, on a regular (non-consumption) app service plan.

**Comment by flagbug** [comment] 2017-04-30 10:49
Seeing the same here

**Comment by atinag** [comment] 2017-05-01 05:31
Yup, same here

**Comment by tohling** [comment] 2017-05-01 06:04
This is a known issue and should be fixed soon.  Kindly refer to thread [here](https://social.msdn.microsoft.com/Forums/azure/en-US/394ef8a7-3f17-47c5-8443-17723c9a856e/invocation-logs-not-updating-in-portal?forum=AzureFunctions).

**Comment by sjwaight** [comment] 2017-05-10 05:22
I noted that @davidebbo mentioned this was fixed on the linked thread. Just putting up here that I'm still seeing this behaviour in AU East, so am not sure if the patch has rolled out yet (I assume not).

**Comment by davidebbo** [comment] 2017-05-10 05:42
@sjwaight to please make sure you have `FUNCTIONS_EXTENSION_VERSION` set to `~1`, and restart your App to make sure it binds to the latest runtime.

**Comment by sjwaight** [comment] 2017-05-12 05:50
There is still something weird happening - invocations do not show up immediately. Runtime is set to ~1 - these are compiled C# Functions with App Insights enabled. Invocation shows in the log window, but not under the Monitor tab.

**Comment by davidebbo** [comment] 2017-05-12 17:02
@sjwaight can you clarify what you mean by 'invocations do not show up immediately'? After how long do they show up?

**Comment by sjwaight** [comment] 2017-06-01 12:53
I actually have issues here - I have a timer-triggered Function that runs every 20 seconds. It is not doing much work, but logs invocations to App Insights fine. The monitor tab for this Function shows the last invocation as 15 days ago, which is incorrect. Some Function invocation logs are blank. Extension version is: 1.0.10947.

A test build of the same Functions running ~1 in a different Plan are also displaying incorrect invocation information.

Happy to supply more details via DM / email.

**Comment by paulbatum** [comment] 2017-06-01 20:09
@sjwaight  Do you happen to have a host ID specified in your host.json? This might have been inserted for you if you used an earlier version of the functions core tools (or VS tooling). There is a known bug  https://github.com/Azure/azure-webjobs-sdk-script/issues/1474 where if its explicitly set then your monitor page won't work correctly.

**Comment by sjwaight** [comment] 2017-06-01 21:09
The host.json that is deployed into my App Services does have a single entry ("id") which I assume is this. You're saying that this file should be empty (i.e. just {}) and this issue will go away?

**Comment by paulbatum** [comment] 2017-06-01 21:41
@sjwaight yes its quite likely that if you remove the id property you'll find your monitor UI starts working again. If not let me know, because it means we have a different bug to track down :)

**Comment by sjwaight** [comment] 2017-06-07 11:43
Confirmed that removing the host ID fixed this in my Function App. Additionally, removing it also helped the Function App local runtime actually run the Function App on debug from Visual Studio which is something it stopped doing some time ago.

**Closed** 2018-11-06 01:03 UTC
Labels: bug, triaged
