### ISSUE TITLE
Unable to see Azure Functions template on VS 2019 16.10.4

### ISSUE THREAD

**Issue by chandsalam1108** [Azure/Azure-Functions#2006] opened 2021-08-03 10:38 UTC
I'm unable to see Azure Functions template on VS 2019 Enterprise after updating from 16.9.3 to 16.10.4.

**Comment by v-anvari** [comment] 2021-08-03 12:06
Hi @chandsalam1108 , I am able to add the Azure function template 

![image](https://user-images.githubusercontent.com/66122429/128012414-71bfc7dc-0067-4122-a299-c5e0c6b35aec.png)

![image](https://user-images.githubusercontent.com/66122429/128011999-bf939a25-4aa8-4b37-bca2-492b9197f3db.png)

Can you try once after you restart you system or update once again, since there could be any breaks in between. If it still doesn't work, please report a problem in visual studio.

![image](https://user-images.githubusercontent.com/66122429/128012135-647f832e-d63b-4781-8f34-442c5bd1e60d.png)

Closing this issue here, since this is not reproducible. Please feel free to reach out to us

**Closed by v-anvari** 2021-08-03 12:06 UTC
