### ISSUE TITLE
[Premium]

### ISSUE THREAD

**Issue by sudhirbabu1979** [Azure/Azure-Functions#1809] opened 2020-12-26 20:31 UTC
Hi ,while I am creating the new Azure functions using Azure portal .I am not able to see the option to create new storage account.As per the microsoft document mention the option to create the storage account while creating the Azure functions.please find the attachment for your reference.[
![microsoftdocument](https://user-images.githubusercontent.com/46627761/103158752-41006980-47b9-11eb-87a4-3d68ea896b4d.png)
](url)

**Comment by jedjohan** [comment] 2020-12-26 20:55
What happens when you click "Create New" ?
![image](https://user-images.githubusercontent.com/10931607/103159054-08ff2380-47c5-11eb-8660-836439a7e09c.png)

**Comment by sudhirbabu1979** [comment] 2020-12-26 21:13
Hi Johan, thanks for responding.i don't see any option to create new storage account while creating the Azure function where as in the microsoft document it is mentioned option to create the new storage account .the screeshot which I had attached is from Microsoft document.

**Comment by jedjohan** [comment] 2020-12-26 21:23
Ahh, ok sorry. Was a bit obvious I guess:) Then I don't really have any tips. Just tried creating a FA and looks ok from here:

![image](https://user-images.githubusercontent.com/10931607/103159363-de16ce80-47c8-11eb-828b-23ae75603633.png)

**Comment by v-anvari** [comment] 2021-06-14 15:50
Hi @sudhirbabu1979 , Apologies for the delayed response. Thank you for reaching out to us. We are unable to reproduce the issue, since it is related to your specific subscription, we suggest you to open a support ticket. We are able to see the Create New button for storage account. 

![image](https://user-images.githubusercontent.com/66122429/121920982-33827000-cd56-11eb-9126-38016fa731da.png)

Path: Azure portal> Menu> help and support

Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue

**Closed by v-anvari** 2021-06-14 15:50 UTC
Labels: premium-plan
