### ISSUE TITLE
Getting error: "We are not able to retrieve the keys for function "

### ISSUE THREAD

**Issue by atrauzzi** [Azure/Azure-Functions#226] opened 2017-03-25 07:34 UTC
![image](https://cloud.githubusercontent.com/assets/115199/24320447/91986636-1103-11e7-8dc9-8ebdad64a298.png)

This error seems misleading as it's showing up right next to my loaded function.  Not sure what to do here.

**Comment by lindydonna** [comment] 2017-03-27 19:42
CC @ahmelsayed

**Comment by marcelvandendungen** [comment] 2017-03-27 22:02
Have the same issue with a new Function app.

**Comment by csharpgirl13** [comment] 2017-03-27 23:09
I have the same problem with brand new functions. I'm not able also to create a new key.
![azure_key_issue](https://cloud.githubusercontent.com/assets/25597704/24381903/c955d1b6-1307-11e7-8d78-a655caf6dafc.JPG)

**Comment by csharpgirl13** [comment] 2017-03-27 23:56
This actually happened when I published my new function to the azure portal from Visual Studio 2015. Before I created my functions on the portal manually. So, if I'm creating brand new Function App I'm not experiencing the same issue there.

**Comment by lindydonna** [comment] 2017-03-28 00:01
@marcelvandendungen Can you share your Function **App** name?

**Comment by marcelvandendungen** [comment] 2017-03-28 15:13
Sure, the function app was called KeyvaultMonitor. I deleted the app and recreated it. Seems to work now.

**Comment by atrauzzi** [comment] 2017-03-28 15:20
I haven't changed mine at all, it's called `atrauzzi-blog`

**Comment by sergsalo** [comment] 2017-03-28 20:59
I see the same error for function that worked just fine before

**Comment by atrauzzi** [comment] 2017-04-02 01:49
@lindydonna - Still experiencing this issue.

**Comment by Diavolita** [comment] 2017-04-03 15:16
Having the same issue as well, been days now...

**Comment by ahmelsayed** [comment] 2017-04-03 17:58
@atrauzzi, @csharpgirl13, for your issue here is a tracking bug on the functions runtime repo https://github.com/Azure/azure-webjobs-sdk-script/issues/1352

@sergsalo I was not able to find your function app, would you mind sharing the name?

@Diavolita what is your function app name?

**Comment by Diavolita** [comment] 2017-04-04 19:01
Hello @ahmelsayed -- thanks for the message. Have a look at:

PBNFunctionApp2  and
NeelandsDecompressionFunctions  seems to have come back online today but the issue was happening since 03/31/2017.

I was creating a bunch of others hoping to work around it but I am still having this issue even with newly created ones as well... very intermittently.

Thanks!

**Comment by mamaso** [comment] 2017-04-04 21:48
Have any of you set the 'functions' array property in `host.json` at the root of your app?

@atrauzzi in particular, I notice that your AddAuthor function is not listed in 'functions', which means it will not be loaded by the runtime. If you remove the 'functions' array we will attempt to load all functions.

**Comment by atrauzzi** [comment] 2017-04-04 23:45
Going to give that a shot!  Shouldn't take too long to see if it works thanks to @davidebbo helping me out with my deployment issues. 😄

**Comment by atrauzzi** [comment] 2017-04-05 00:07
![image](https://cloud.githubusercontent.com/assets/115199/24684215/f267d492-1969-11e7-9c92-addffe9e19c7.png)

I think it worked!

**Comment by atrauzzi** [comment] 2017-04-05 00:22
Spoke too soon.  Now getting:

```
2017-04-05T00:18:15.969 Exception while executing function: Functions.AddAuthor. Microsoft.Azure.WebJobs.Script: Thread was being aborted.
```

Will open another ticket.  The adventure continues.

**Comment by ArunAdPushup** [comment] 2017-04-05 12:12
I am also facing the same issue, along with this one - 
> Host Error: Microsoft.WindowsAzure.Storage: Unable to connect to the remote server. System: Unable to connect to the remote server. System: An attempt was made to access a socket in a way forbidden by its access permissions.
Session Id: b9c833859fa144848e7647813fcbd0a3
Timestamp: 2017-04-05T12:10:18.961Z

![screen shot 2017-04-05 at 5 39 45 pm](https://cloud.githubusercontent.com/assets/20511680/24704891/26dba042-1a27-11e7-8d4a-872008a9235d.png)

**Comment by davidebbo** [comment] 2017-04-05 16:39
@ArunAdPushup it seems your issue is different, and relates to reaching a socket limit. Things to try:

- Are you properly closing outgoing connections?
- Can you reuse connections between calls?
- You can also reduce concurrency on the host by setting queues.batchSize to a lower value (e.g. 8) in you [host.json](https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json).

**Comment by ArunAdPushup** [comment] 2017-04-06 09:12
It was working properly earlier, I've been facing this issue since yesterday. I think it has something to do with the ``Function`` and ``Host`` keys that are set automatically when you create a new azure function. I noticed that in my case, these values were missing, no sure how. 

![screen shot 2017-04-06 at 1 54 58 pm](https://cloud.githubusercontent.com/assets/20511680/24746552/1ea5ec56-1ad7-11e7-9ad6-99e8f1e1394c.png)

**Comment by isamllr** [comment] 2017-04-11 10:48
Hello
Same issue on a brand new function.

**Comment by MurrayFoxcroft** [comment] 2017-04-17 20:53
Seeing the same for me. I created a consumption plan in Azure, then deployed my function to it from VS2015.

**Comment by nishantsinha-5** [comment] 2017-04-20 12:53
Have the same issue with a new Function app. 
![image](https://cloud.githubusercontent.com/assets/4038289/25231689/4e9c2370-25c8-11e7-942d-4b8ca3f08fc5.png)

**Comment by ahmelsayed** [comment] 2017-04-20 16:33
share your function app name or session id.

**Comment by AartiDalvi10** [comment] 2017-04-21 05:48
I am also facing the same issue. Also I have observed Function Keys is not present neither i am able to add it

![image](https://cloud.githubusercontent.com/assets/27818108/25264356/eaf49daa-2655-11e7-928d-f20c1b7e47b9.png)

**Comment by ahmelsayed** [comment] 2017-04-21 18:18
@AartiDalvi10 You've specified in your host.json that only 1 function should be loaded, so all other functions are not loaded and the portal is unable to get keys for these functions.

**Comment by AartiDalvi10** [comment] 2017-04-24 07:11
Yes It worked for me now....I made changes in host.json file of my function app by removing function attribute using "https://<yourfunctionappname>.scm.azurewebsites.net/dev/wwwroot/host.json" and restarted the function app. 
Thanks ahmelsayed

**Comment by ahmelsayed** [comment] 2017-04-25 17:03
@AartiDalvi10 I'm just curious, why did you have that setting to begin with? I know it's a valid runtime setting, but the UI doesn't handle it at the moment. I'm trying to understand your use case for it.

**Comment by arntmo** [comment] 2017-04-27 10:27
Any solution to this issue? I have the same problem. But the functions are working (but I get the error message)

**Comment by ahmelsayed** [comment] 2017-04-27 17:13
@arntmo can you share your session id or function app name?

**Comment by Schaemelhout** [comment] 2017-05-05 07:38
I am facing the same issue for a couple of days now...
Session id `5896b6dc6fcb471c8d2c6d826b2087e6`

**Comment by GitRik** [comment] 2017-05-09 10:54
Same issue here with functions that run smooth for the last months
session id = ec2d3a7738b04c1bb83908ecbe3f6a0e

**Comment by ctaggart** [comment] 2017-05-09 12:36
I just went to create a new function after a couple of months and I'm seeing this error.
```
Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: c01b686e0ea04d18abcbf198c12325e3

Timestamp: 2017-05-09T12:28:49.678Z
```

My existing host.json is:
``` json
{
    "id": "3f4963dff32f4085bbd173c79516e1ab",
    "queues": {
      "maxDequeueCount": 1
    },
    "tracing": {
      "consoleLevel": "verbose",
      "fileLoggingMode": "always"
    }
}
```

**Comment by ebashmakov** [comment] 2017-05-09 15:27
I'm having the same error in different Function Apps.

```
Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: 120747a95fbb4139ba9ea9d9c6b22491

Timestamp: 2017-05-09T15:25:07.368Z
```

**Comment by erikadanis81** [comment] 2017-05-09 15:49
I am having the exact same issues to functions that used to work up until last night

Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: 76f2e9e6ad53409bb33b015ba0c9c557

Timestamp: 2017-05-09T15:44:29.923Z

**Comment by davidebbo** [comment] 2017-05-09 16:35
Ok, so I think we know why there is a new wave of these errors. There are two possibilities:

1. You are on the beta. At this point, the beta is no longer usable, and you need to switch the app setting back to ~1. Sorry for the poor communication on this. We just updated the [blog post](https://blogs.msdn.microsoft.com/appserviceteam/2017/04/06/azure-functions-application-insights/). Not that AppInsights is now fully available in the released bits
2. If you're not on the beta and are still seeing this, try Stopping and then Starting your Function App

**Comment by ebashmakov** [comment] 2017-05-09 16:46
@davidebbo I've switched to `~1` and everything seems to be working. Thanks!

**Comment by pwiebe** [comment] 2017-05-09 17:46
I'm seeing the same issue.  Not on beta.  Tried stopping and starting my Function App.  Still persists. Am running the Functions runtime as specified here https://github.com/Azure/azure-webjobs-sdk-script/wiki/Deploying-the-Functions-runtime-as-a-private-site-extension.

**Comment by ahmelsayed** [comment] 2017-05-09 17:49
@pwiebe  are you running the latest changes for the runtime? In particular this commit https://github.com/Azure/azure-webjobs-sdk-script/commit/6008a50b878e8698ad3a5d436567be78a2890e50

**Comment by davidebbo** [comment] 2017-05-09 17:52
@pwiebe note that using a private site extension is by nature unsupported. Once you move to that mode, you are responsible for keeping it updated as the product evolves. Just merge the latest bits and redeploy, and you'll be ok.

**Comment by pwiebe** [comment] 2017-05-09 18:31
Was running an older version.  Now works.  Thanks!

**Comment by willwhite1** [comment] 2017-05-11 17:49
I am running everything default and am seeing this error come and go. Was fine this morning and now seeing it again.

**Comment by willwhite1** [comment] 2017-05-11 17:54
My issue was caused by setting 'newBatchThreshold' to 0 in host.json. Running locally via visual studio revealed the underlying exception.

**Comment by davidebbo** [comment] 2017-05-12 19:59
The primary issue that was causing a bunch of these recently has been addressed by a portal change.

If you see errors that look like this is the future, the root cause will likely be different, so please open a separate issue.

**Closed by davidebbo** 2017-05-12 19:59 UTC
Labels: improvement, triaged

**Comment by apedzko** [comment] 2017-05-24 09:46
I'm seeing the same error on a function created automatically by VS build

Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: 329be7bdfdc74ea3b7e65d4de70186a4

Timestamp: 2017-05-24T09:45:56.727Z

**Comment by ahmelsayed** [comment] 2017-05-24 19:11
@apedzko  are you seeing any other errors related to not having a `AzureWebJobsStorage` defined?

**Comment by apedzko** [comment] 2017-05-25 07:45
I have this setting defined. I'm not sure how but i managed to fix the
issue by doing one of the 3 things:

1. I had removed everything from host.json file - kudu was saying that it
was incorrect - maybe some encoding issue.
2. I had fixed encoding on run.csx file in source control from unicode to
utf8 and redeployed the function.
3. I had disabled sessions on the servicebus queue to which the function
was bound to.

Thanks,
Alex.

2017-05-24 22:11 GMT+03:00 Ahmed ElSayed <notifications@github.com>:

**Comment by jtmott** [comment] 2017-05-25 14:59
I'm getting a combination of the "We are not able to retrieve the runtime master key.." and the error shown below suddenly on a function that was previously working without issue.  It's really unusual though, as when I deploy, I can see that a few iterations of the trigger execute without issue and are logged, but then it just stops working and shows the error messages.  I have tried restarting and recreating the function:

```
**Error:**
We are not able to retrieve secrets file for [functioname]. Please try again later.
Session Id: 95d3bb79b74e48eb97a457865a825579
Timestamp: 2017-05-25T14:54:22.860Z
```

**Comment by ahmelsayed** [comment] 2017-05-25 18:30
@jtmott there appear to have been a stale DNS entry that was directing traffic into the wrong end point for your function app. That has been resolved. can you please give it another try?

**Comment by jtmott** [comment] 2017-05-25 19:42
Thanks for the feedback @ahmedelnably, the function is running as expected now.

**Comment by jtmott** [comment] 2017-05-26 15:06
@ahmedelnably The function ran fine for a day, but after creating a new function I'm once again receiving the following errors.  The new function was created using the Service Bus Queueu Trigger template in the portal, and no modifications have been made:

> Error:
> 
> We are not able to retrieve the keys for function EHFreshLocWorkerPrimary. This can happen if the runtime is not able to load your function. Check other function errors.
> Session Id: 6c08ca00507d42ad91ccd042b08d1ca4
> 
> Timestamp: 2017-05-26T15:04:52.701Z

> Error:
> 
> The function runtime is unable to start. Please check the runtime logs for any errors or try again later.
> Session Id: 6c08ca00507d42ad91ccd042b08d1ca4
> 
> Timestamp: 2017-05-26T15:01:27.411Z

**Comment by ahmedelnably** [comment] 2017-05-26 15:44
Mentioning the right @ahmelsayed  :)

**Comment by guitarrapc** [comment] 2017-06-12 04:10
I met same issue right after deploy new function "We are not able to retrieve the runtime master key. Please try again later. "

**Comment by ahmelsayed** [comment] 2017-06-12 16:50
@guitarrapc please share your function app name or session id.

**Comment by tenkatim** [comment] 2017-06-12 19:24
Same issue. 4 different functions deployed to the same app service plan show Availability as "Not applicable". One of function also receives the following error.

![screen shot 2017-06-12 at 22 18 28](https://user-images.githubusercontent.com/2536540/27051160-c5e33bf2-4fbd-11e7-8de4-2accbcdb3cf3.png)

**Comment by ahmelsayed** [comment] 2017-06-12 19:34
@tenkatim share the text of the error message so I can copy the session id

**Comment by tenkatim** [comment] 2017-06-12 19:38
@ahmelsayed 

Session Id: 30fc539eb27a4b199f49a3c3666b1e80
Timestamp: 2017-06-12T19:34:01.860Z

**Comment by ahmelsayed** [comment] 2017-06-12 20:23
@tenkatim your issue was setting `maxDequeueCount` to something less than 1. We need to improve that error case.

**Comment by mamoorkhan** [comment] 2017-06-13 12:01
deleted the fucntion app, then recreated with the same name, now I am getting the following error
`We are unable to access your function keys. If the error persists, please contact support.
Session Id: a7d008dbb61c4079b9ce9540410f8507

Timestamp: 2017-06-13T11:56:54.929Z`

**Comment by ahmelsayed** [comment] 2017-06-13 17:12
@mamoorkhan can you try again now? 
When you deleted your function app and recreated it with the same name, the IP of the new app end point was different, but DNS cache hasn't updated yet, so we were talking to the wrong IP for your app.

**Comment by mamoorkhan** [comment] 2017-06-14 08:14
@ahmelsayed thank you, yeah it works fine now.

**Comment by benmccallum** [comment] 2017-07-31 23:09
I'm getting this error message. I've got auto-deployment from GitHub setup, so I've potentially pushed something that caused it all to fall over so here's what I've been up to. 

I've been trying to do is add in/out bindings to an existing function I created on local machine. Seems that a {functionname}/function.json folder was created in Azure so I pulled that down locally, adjusted the file with my new bindings, moved {functionname}.cs into {functionname} directory with function.json and pushed that up. Then I started getting the issue.

> Error:
> We are unable to access your function keys. If the error persists, please contact support.
> Session Id: b427296b224d4517974dac462d4600c9
> Timestamp: 2017-07-31T23:02:51.244Z

**Comment by niravbhalodiya** [comment] 2017-08-11 07:17
Hi,

I am getting below error since last 2 days. Any Idea. How to diagnose this .. where to look for the diagnostincs log or error log in azure functions ?

Error:

We are not able to retrieve the keys for function CampaignJobHandler. This can happen if the runtime is not able to load your function. Check other function errors.
Session Id: 14b8420b52bb4a87a65881277fb33c10

Timestamp: 2017-08-11T06:09:51.506Z

**Comment by ahmelsayed** [comment] 2017-08-11 18:09
@niravbhalodiya I'm a bit confused looking at the logs for that session. Do you have a function called `CampaignJobHandler`? I can't find a function with that name, yet the logs show that we are failing to get the keys for the non-existing function, which makes sense. I just can't seem to find out why we are trying to get the keys for a function that doesn't exist. 

@benmccallum sorry for the late reply I somehow missed notification for your reply. 
Are you still seeing these errors? The error in the screenshot happens if you re-generate your storage keys without updating the app settings for the function app. Can you check the app settings and make sure the storage connection strings there are valid?

**Comment by benmccallum** [comment] 2017-08-13 17:38
Hi @ahmelsayed , No worries. You're 100% correct. I realised myself that I'd done just that. Is it possible to handle this scenario (which wouldn't be awfully common I know but would help those who do) and show an error in the portal to the effect of "Could not connect to storage, please check your app settings." or something similar? Something for the backlog perhaps. Thanks :)

**Comment by niravbhalodiya** [comment] 2017-08-17 06:23
@ahmelsayed .. Thanks for your response. I have deleted that whole functionapp as it was not behaving as expected and created new one with the same functions.

**Comment by shankarmaha** [comment] 2017-08-24 09:40
Hi, my function name is mhl-ft-commonHelper-eu-n-test-fn. I have deleted the function several times and recreated again from both Visual studio and VSTS. Keep getting the same error 



Error:

We are not able to retrieve the runtime master key. Please try again later.

Session Id: e0a98edbd2894849926ba8f0e0c2726f

Timestamp: 2017-08-24T09:34:50.518Z

**Comment by ahmelsayed** [comment] 2017-08-24 16:17
/cc @fabiocav 

looks like another case of this

```
System.Security.Cryptography.CryptographicException : The payload was invalid.
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext,UInt32 cbCiphertext,Byte* pbAdditionalAuthenticatedData,UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext,ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData,Boolean allowOperationsOnRevokedKeys,UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData,Boolean ignoreRevocationErrors,Boolean& requiresMigration,Boolean& wasRevoked)
   at Microsoft.Azure.WebJobs.Script.WebHost.DataProtectionKeyValueConverter.Unprotect(Key key) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Security\DataProtectionKeyValueConverter.cs : 43
   at Microsoft.Azure.WebJobs.Script.WebHost.DataProtectionKeyValueConverter.ReadValue(Key key) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Security\DataProtectionKeyValueConverter.cs : 30
   at Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.ReadHostSecrets(HostSecrets hostSecrets) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Security\SecretManager.cs : 383
   at async Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.GetHostSecretsAsync() at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Security\SecretManager.cs : 83
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsSdkExtensionHookProvider.GetOrCreateExtensionKey(String extensionName) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebHooks\WebJobsSdkExtensionHookProvider.cs : 71
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsSdkExtensionHookProvider.GetExtensionWebHookRoute(String extensionName) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebHooks\WebJobsSdkExtensionHookProvider.cs : 64
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsSdkExtensionHookProvider.GetUrl(IExtensionConfigProvider extension) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebHooks\WebJobsSdkExtensionHookProvider.cs : 49
   at Microsoft.Azure.WebJobs.Host.Config.ExtensionConfigContext.GetWebhookHandler()
   at Microsoft.Azure.WebJobs.Extensions.EventGrid.EventGridExtensionConfig.Initialize(ExtensionConfigContext context)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.InvokeExtensionConfigProviders(ExtensionConfigContext context)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.CreateStaticServices(JobHostConfiguration config)
   at Microsoft.Azure.WebJobs.JobHost.PopulateStaticServices()
   at Microsoft.Azure.WebJobs.Script.Utility.CreateMetadataProvider(JobHost host) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 362
   at Microsoft.Azure.WebJobs.Script.ScriptHost.LoadCustomExtensions() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 673
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 507
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment,IScriptEventManager eventManager,ScriptHostConfiguration scriptConfig,ScriptSettingsManager settingsManager) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 937
```


@fabiocav's workaround:

> can you delete (or rename) the host.json file in d:\home\data\Functions\secrets\ and retry? This will force the runtime to re-create those secrets for that environment. Keep in mind that this would also change your master and default keys.

**Comment by ahmelsayed** [comment] 2017-08-24 18:04
I'm locking this thread. Please open a different thread if you see the same issue including your session id and time stamp.
