### ISSUE TITLE
Service Bus Trigger - direction attribute missing in function.json generated from VS 2017

### ISSUE THREAD

**Issue by jasho** [Azure/Azure-Functions#742] opened 2018-03-30 11:10 UTC
I'm experiencing an issue when working with Service Bus Triggers and publishing from VS 2017. The function I'm using is defined as:
```csharp
[FunctionName("TestSensor")]
public static void Run([ServiceBusTrigger("uplink_testsensor", AccessRights.Listen, Connection = "test-demo-bus-uplink_ListenAccessKey_SERVICEBUS")]string message, TraceWriter log)
```

The resulting function.json file is missing the "direction" attribute, so after publishing to Azure, the function doesn't get triggered and the "Integrate" tab only displays the "Advanced editor" aka the content of the function.json file. After adding "direction" : "in" to the bindings directly in Azure it starts working fine. This is however annoying as I need to edit it manually after each publish.

The generated bindings are as follows:
```javascript
"bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "test-demo-bus-uplink_ListenAccessKey_SERVICEBUS",
      "queueName": "uplink_testsensor",
      "accessRights": "listen",
      "name": "message"
    }
  ],
```

The tools used are:
- Visual Studio 2017 v 15.6.4
- Azure Functions and Web Job Tools v 15.0.40322.0

**Comment by ConnorMcMahon** [comment] 2018-04-02 16:41
It looks like this doesn't happen in the portal. @justcla, can you take a look at this?

**Comment by paulbatum** [comment] 2018-04-02 18:38
@ConnorMcMahon I doubt this is an issue on the VS side. If there's a bug here it would either be in the metadata generator or the functions host.

@jasho is this using functions V1 or V2? Can you paste your PackageReference entries from your csproj?

**Comment by jasho** [comment] 2018-04-04 08:12
@paulbatum I'm using the functions V1 (from what I understand V2 is still in beta and I can't use that for a customer). The package references are:
<PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="2.1.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.9" />

**Comment by jasho** [comment] 2018-04-05 15:38
I've tried to update everything. So the version of Visual Studio I'm using now is 15.6.5.
And the package references are:
```xml
<PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="2.2.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.13" />
```
However the issue with the publish still persists.

**Comment by paulbatum** [comment] 2018-04-05 17:53
OK I just ran through all of this myself. I made a new function app locally, got the same packages that you have, confirmed that my service bus triggered function was successfully triggered when running locally, then deployed to azure and checked the same thing. Everything worked fine. 

My function.json is the same as yours (no direction setting). As far as I know, the presence/absence of that setting should not impact how your app runs because you generated your function.json from VS and it SHOULD contain a line that says `  "configurationSource": "attributes"`.

Can you give me information about the app you have that is not being triggered. Here's the info I need:

```
- Timestamp:
- Function App version (1.0 or 2.0-beta):
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:
```
If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**Comment by ColbyTresness** [comment] 2018-12-04 18:46
Closing due to lack of customer response (can reopen if necessary)

**Closed by ColbyTresness** 2018-12-04 18:46 UTC

**Comment by YalamanchiliBhavana** [comment] 2020-07-09 16:02
I am having the same issue. Direction attribute is not being set to the bindings and the service bus function doesn't trigger. i am using the below package for the service bus and function version is v2

<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="3.0.3" />
