### ISSUE TITLE
WEBSITES_ENABLE_APP_SERVICE_STORAGE is overriding AzureWebJobsScriptRoot variable

### ISSUE THREAD

**Issue by lb5tr** [Azure/Azure-Functions#1507] opened 2020-02-27 16:47 UTC
I have a scenario when I need a fair chunk of local disk storage (~40GB per function call) to extract and convert certain data from one system and pass it to the other.

I need to use docker images as I'm bringing various tools with my code.

Docker generally caps out at 10GB of internal container storage so I need to use external volumes. 

From what I understand `WEBSITES_ENABLE_APP_SERVICE_STORAGE` set to `true` will cause the runtime to mount my app service plan volume into `/home/site/wwwroot` which is great - default 250GB is enough for me but then I need to move my code someplace else by setting `AzureWebJobsScriptRoot` to for example `/app`. This generally works _unless_ `WEBSITES_ENABLE_APP_SERVICE_STORAGE` is set to `true` which seems to be forcing runtime to run out of `/home/site/wwwroot` regardless of `AzureWebJobsScriptRoot` value.

Is there a way to force runtime to launch code from `AzureWebJobsScriptRoot` while keeping `WEBSITES_ENABLE_APP_SERVICE_STORAGE` set to true?

**Comment by przemos** [comment] 2020-12-09 18:28
Indeed, I can confirm that behaviour. It is problematic since you would like to run your processes on a given host instance rather from than the shared space. Shared storage for running compute creates potential clash while deploying new version of the application or scaling up the number of instances long with the container - for NodeJS I am doing rsync between files.

**Comment by v-bbalaiagar** [comment] 2021-09-28 14:51
Hi @lb5tr, Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required. I shall follow with the right team members to resolve this issue. The issue was somehow lost in the trace.

**Comment by v-bbalaiagar** [comment] 2021-11-19 14:21
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue.

**Closed by v-bbalaiagar** 2021-11-19 14:21 UTC
