### ISSUE TITLE
[Visual Studio] Can't create Functions project - no template could be found

### ISSUE THREAD

**Issue by Loreno10** [Azure/Azure-Functions#399] opened 2017-07-18 11:35 UTC
I just installed latest Preview of Visual Studio 2017 15.3 (Preview 4) and Azure Functions Tools form Marketplace.
When I try to create a new Functions project I get the following error: "No template could be found with the group identity 'Microsoft.Azure Functions.ProjectTemplates'".

It's a fresh installation, I only installed Functions Tools, nothing more. 

My OS: Windows 7 x64

**Comment by lindydonna** [comment] 2017-07-18 18:45
@vijayrkn Could you take a look?

**Comment by vijayrkn** [comment] 2017-07-18 19:09
@Loreno10 
Can you try File -> New Project -> ASP.NET Core Web Application -> Empty -> Ok
& then try creating a new Functions project to see if it fixes the issue?

**Comment by Loreno10** [comment] 2017-07-19 06:54
@vijayrkn I tried that, nothing changed.
Also, I noticed, that in project type window (when creating new project) AzureFunctions project doesn't display 'lightning' icon, like in the examples. It's a different icon:
![image](https://user-images.githubusercontent.com/10273406/28354366-e8e055cc-6c5f-11e7-8b6b-2cb702905782.png)

**Comment by SharvariHDesai** [comment] 2017-08-03 19:02
Is there any update on this?

**Comment by vijayrkn** [comment] 2017-08-03 20:33
Can you please try installing the latest version from here - https://marketplace.visualstudio.com/items?itemName=AndrewBHall-MSFT.AzureFunctionToolsforVisualStudio2017

Also please make sure you have the following 

- Install Visual Studio 2017 (version 15.3) Preview (it will not work with any earlier versions of Visual Studio) 
- Install either the ASP.NET and web development workload  or Azure development workload

**Comment by krishnasingh1818** [comment] 2017-08-04 18:14
am having same issue. solutions suggested didnt work. any one got it fixed ?

**Comment by krishnasingh1818** [comment] 2017-08-11 17:23
i figured out a work around.
1.  create function .csproj file manual using below content
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>
```
2. save this file as myfunction.csproj.  
3. right click solution and choose add existing project and choose project created in step 2 
4.  now u can start working on this by adding references and function code.

**Comment by krishnasingh1818** [comment] 2017-08-14 23:32
other solution is during installation manually check the component **install .net 4.7 framework** it will be under asp.net or cloud anyone of them.  i got lightning yellow sign and it works fine now

**Comment by girirajanprabu** [comment] 2017-09-05 13:59
I am getting the same error. 

I installed the tools as a user with administrator permission. surprisingly that user has the correct Azure Function Icon; where as the development user doesn't. this issue doesn't happen with the admin user; When a dev user launches VS 2017 and trying to create a Azure Function project; this error pops up.

Any resolution ?

**Comment by lindydonna** [comment] 2017-09-05 20:25
@girirajanprabu It's possible that you need to update the tools. See the note under this screenshot: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio#prerequisites

**Comment by abdielivanquintero** [comment] 2017-09-20 16:29
Thanks @lindydonna , that worked for me!

**Comment by yogeshrain** [comment] 2017-09-28 06:34
It worked for me after deploying 4.7 Development tools.

**Comment by girirajanprabu** [comment] 2017-09-29 08:19
After some trial and error, it worked.

 I did the following

1. Granted my user temporary admin access.
2. Launched VS2017 as administrator
3. Installed latest version of tools
4. Revoked admin access
5. Launched VS2017 normally and things started to work as expected. 

I suspect the issue is around having enough permissions in my development box. Even though the tools installation says it is completed; it doesn't. Hence when I launch it as administrator it has enough permission to download and install without any issue.

**Comment by dotnetninja10** [comment] 2017-10-08 14:22
Any news on this? I have just installed fresh VS 2017 15.3, and updated tools (Azure Fuctions). Still Empty icon and same error "..no template could found.."

**Comment by lindydonna** [comment] 2017-10-12 02:17
See note at the end of this section: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio#prerequisites

**Comment by dhmorrison** [comment] 2019-01-29 07:01
I'm a bit late to this game.  I have all the latest installed, yet no "function" template to be found.  Is there an update on this issue?
Thanks,
David

**Comment by ColbyTresness** [comment] 2019-03-14 18:43
This issue was moved to Azure/azure-functions-vs-build-sdk#293

**Comment by ColbyTresness** [comment] 2019-03-14 18:51
Reverting move, tracking here.

**Comment by ColbyTresness** [comment] 2019-03-14 22:42
This should be fixed now. @dhmorrison please follow this if you're still having issues https://github.com/Azure/azure-functions-tooling-feed/wiki/Fixing-Azure-Function-Core-Tools-download-issues-for-Visual-Studio

**Closed by ColbyTresness** 2019-03-14 22:42 UTC
Labels: Visual Studio, bug
