### ISSUE TITLE
[Visual Studio] "HTTP could not register URL http://+:7010/. Your process does not have access rights to this namespace"

### ISSUE THREAD

**Issue by peder** [Azure/Azure-Functions#87] opened 2016-12-01 22:06 UTC
Sorry for the crummy screenshot, I had to use the Screen2Gif recorder to capture this error since it appears/disappears too quickly to catch. Looks like debugging an Azure Function fails immediately after prompting for admin privileges with `"HTTP could not register URL http://+:7010/. Your process does not have access rights to this namespace"`

![image](https://cloud.githubusercontent.com/assets/1018574/20814564/d3af070a-b7df-11e6-8c78-7b22068c1cf2.png)

This is with a basic HTTP function without any code customizations:

![image](https://cloud.githubusercontent.com/assets/1018574/20814616/17dccf52-b7e0-11e6-8e19-f050ede5ed1f.png)

**Comment by lindydonna** [comment] 2016-12-01 22:13
It looks like a problem listening on that port. Can you try installing the Azure Functions CLI and seeing if you get the same error?  There are instructions here: https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/

If you run `func host start` and get the same error, try passing a different port, via `func host start -p 7072`

**Comment by peder** [comment] 2016-12-01 22:13
Is that configurable from Studio in any way?

**Comment by peder** [comment] 2016-12-01 22:20
`func host start` works just fine, with whatever port, so long as my shell was run as an **administrator**. Even though a non-admin shell will prompt to elevate privileges, that apparently doesn't help--the shell needs to be run as an admin.

On that same note, Visual Studio will work with Azure Functions so long as it's opened as an admin.

**Comment by lindydonna** [comment] 2016-12-01 22:37
@peder No, you can't currently configure the port, but this is a good feature for the final version.

What version of Windows are you running on?  We haven't seen this admin prompt in our environment--what I do see the first time is a firewall warning.

**Comment by lindydonna** [comment] 2016-12-01 22:38
@peder I filed https://github.com/Azure/Azure-Functions/issues/88 for the port configuration feature request.

**Comment by peder** [comment] 2016-12-01 22:39
Thanks for filing the feature request. I'm on Windows 10 Enterprise, without the Anniversary Update. I don't know if we have any group policies around UAC, anti-virus, etc. type of conflicts that might be the real issue here.

**Comment by lindydonna** [comment] 2016-12-16 00:35
@peder If you run the CLI and use a different port, do you get the same error?  I think the problem is likely something having to do with the Windows config, but @ahmelsayed will know for sure. I'll follow up soon.

**Comment by peder** [comment] 2016-12-16 14:40
I thought I had replied to this two weeks back, sorry for the late reply. Yes! Using the CLI and changing the port worked great, running as an admin and using the default port in Visual Studio also worked just fine.

**Comment by jsiegmund** [comment] 2016-12-21 10:02
I'm seeing kind of the same thing. Cannot run functions from either visual studio or CLI with the error that port 7071 is already in use. Running as administrator does not make a difference. When I run "func host start -p 7073" for instance, the CLI works fine. I have no clue what would be running on port 7071 otherwise, I tried http://localhost:7071 but that doesn't return anything. Is there a way to check?

**Comment by lindydonna** [comment] 2016-12-21 20:58
@jsiegmund and @peder Thanks for the update--I'm pretty sure it's the root cause is this bug I just opened: https://github.com/Azure/azure-webjobs-sdk-script/issues/1067

I'm going to close this issue in favor of the other one.

**Closed by lindydonna** 2016-12-21 20:58 UTC
Labels: CLI
