### ISSUE TITLE
Running functions via "Test /Run" fails intermittently

### ISSUE THREAD

**Issue by jbeeko** [Azure/Azure-Functions#1812] opened 2021-01-03 22:18 UTC
We have several functions that run without error when invoked via TimerTrigger. But fails intermittently when invoked using the 'Test/Run' feature on the Azure function port. 

The error message is always the same: 

```
Connected!
2021-01-03T21:57:02  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2021-01-03T21:57:13.451 [Information] Running organization IntegrityChecks
2021-01-03T21:57:21.735 [Error] Executed 'jobs-FullIntegrityCheck' (Failed, Id=9e3b2df1-95ca-4a61-bdaf-99cacf50e8f0, Duration=23008ms)[A]Microsoft.FSharp.Collections.FSharpList`1[Transactive.Seymour.Domain.SharedTypes.PaymentType] cannot be cast to [B]Microsoft.FSharp.Collections.FSharpList`1[Transactive.Seymour.Domain.SharedTypes.PaymentType]. Type A originates from 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'D:\home\site\wwwroot\bin\FSharp.Core.dll'. Type B originates from 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'D:\home\site\wwwroot\bin\FSharp.Core.dll'.
2021-01-03T21:59:02  No new trace in the past 1 min(s).
2021-01-03T22:00:02  No new trace in the past 2 min(s).
```

Initially this looks very similar to cases where a binding redirect may be needed. But on inspection the two types that can't be cast between are identical in all regards. And as mentioned it works outside the port.

**Comment by v-anvari** [comment] 2021-02-04 11:39
Hi @jbeeko , We need to investigate further to know the cause. We would like to have the piece of code that you are using in order to repro the project. Please share the repro steps as well.

**Comment by v-anvari** [comment] 2021-05-31 11:29
Hi @jbeeko, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue

**Closed by v-anvari** 2021-05-31 11:30 UTC
